[[packaging.container-images.dockerfiles]]
= Dockerfiles

虽然只需在 `Dockerfile` 中添加几行代码就可以将 Spring Boot uber jar 转换为 Docker 镜像，但使用 xref:packaging/container-images/efficient-images.adoc#packaging.container-images.efficient-images.layering[分层功能] 将产生一个优化的镜像。当你创建一个包含层索引文件的 jar 时，`spring-boot-jarmode-tools` jar 将作为依赖项添加到你的 jar 中。有了 classpath 上的这个 jar，你可以以一种特殊模式启动你的应用程序，该模式允许引导代码运行与你的应用程序完全不同的东西，例如，提取层的东西。

以下是如何使用 `tools` jar 模式启动你的 jar：

[source,shell]
----
$ java -Djarmode=tools -jar my-app.jar
----
这将提供以下输出：

[subs="verbatim"]
----
Usage:
  java -Djarmode=tools -jar my-app.jar

Available commands:
  extract      Extract the contents from the jar
  list-layers  List layers from the jar that can be extracted
  help         Help about any command
----
The `extract` 命令可用于轻松地将应用程序拆分为多个层，以便添加到 `Dockerfile`。
以下是一个使用 `jarmode` 的 `Dockerfile` 示例。

[source,dockerfile]
----
include::reference:partial$dockerfile[]
# Start the application jar - this is not the uber jar used by the builder
# This jar only contains application code and references to the extracted jar files
# This layout is efficient to start up and AOT cache (and CDS) friendly
ENTRYPOINT ["java", "-jar", "application.jar"]
----
假设上述 `Dockerfile` 位于当前目录中，则可以使用 `docker build .` 构建 Docker 镜像，或者可选地指定应用程序 jar 的路径，如下例所示：

[source,shell]
----
$ docker build --build-arg JAR_FILE=path/to/myapp.jar .
----
这是一个多阶段 `Dockerfile`。
构建阶段提取稍后需要的目录。
每个 `COPY` 命令都与 jarmode 提取的层相关。

当然，也可以在不使用 `jarmode` 的情况下编写 `Dockerfile`。
你可以使用 `unzip` 和 `mv` 的某种组合将内容移动到正确的层，但 `jarmode` 简化了这一点。
此外，由 `jarmode` 创建的布局开箱即用，对 AOT 缓存（和 CDS）友好。


[[packaging.container-images.dockerfiles.aot-cache]]
== AOT 缓存

如果你使用的是 Java 25 或更高版本，并且希望额外启用 xref:reference:packaging/aot-cache.adoc#packaging.aot-cache.aot-cache[AOT 缓存]，可以使用此 `Dockerfile`：
[source,dockerfile]
----
include::reference:partial$dockerfile[]

# Execute the AOT cache training run
RUN java -XX:AOTCacheOutput=app.aot -Dspring.context.exit=onRefresh -jar application.jar

# Start the application jar with AOT cache enabled - this is not the uber jar used by the builder
# This jar only contains application code and references to the extracted jar files
# This layout is efficient to start up and AOT cache friendly
ENTRYPOINT ["java", "-XX:AOTCache=app.aot", "-jar", "application.jar"]
----
这与上述 `Dockerfile` 基本相同。
作为最后步骤，它通过执行训练运行来创建 AOT 缓存文件，并将 AOT 缓存参数传递给 `java -jar`。


[[packaging.container-images.dockerfiles.cds]]
== CDS

注意：如果你使用的是 Java 24 或更高版本，请使用 AOT 缓存代替 CDS。

如果你想额外启用 xref:reference:packaging/aot-cache.adoc#packaging.aot-cache.cds[CDS]，你可以使用这个 `Dockerfile`：
[source,dockerfile]
----
include::reference:partial$dockerfile[]

# Execute the CDS training run
RUN java -XX:ArchiveClassesAtExit=application.jsa -Dspring.context.exit=onRefresh -jar application.jar

# Start the application jar with CDS enabled - this is not the uber jar used by the builder
# This jar only contains application code and references to the extracted jar files
# This layout is efficient to start up and CDS friendly
ENTRYPOINT ["java", "-XX:SharedArchiveFile=application.jsa", "-jar", "application.jar"]
----
这与上面的 `Dockerfile` 基本相同。
作为最后步骤，它通过执行训练运行创建 CDS 存档，并将 CDS 参数传递给 `java -jar`。

注意：如果您使用的是 Java 25 或更高版本，我们建议使用 AOT 缓存而不是 CDS。
