[[appendix.executable-jar.jarfile-class]]
= Spring Boot 的“`NestedJarFile`”类

用于支持加载嵌套 jar 的核心类是 javadoc:org.springframework.boot.loader.jar.NestedJarFile[]。
它允许你从嵌套的子 jar 数据中加载 jar 内容。
首次加载时，每个 javadoc:java.util.jar.JarEntry[] 的位置会被映射到外部 jar 的物理文件偏移量，如下例所示：

[source]
----
myapp.jar
+-------------------+-------------------------+
| /BOOT-INF/classes | /BOOT-INF/lib/mylib.jar |
|+-----------------+||+-----------+----------+|
||     A.class      |||  B.class  |  C.class ||
|+-----------------+||+-----------+----------+|
+-------------------+-------------------------+
 ^                    ^           ^
 0063                 3452        3980
----
前面的示例展示了 `A.class` 如何在 `/BOOT-INF/classes` 中的 `myapp.jar` 的 `0063` 位置被找到。
来自嵌套 jar 的 `B.class` 实际上可以在 `myapp.jar` 的 `3452` 位置找到，而 `C.class` 位于 `3980` 位置。

有了这些信息，我们可以通过定位到外部 jar 的适当部分来加载特定的嵌套条目。
我们不需要解压归档文件，也不需要将所有条目数据读入内存。


[[appendix.executable-jar.jarfile-class.compatibility]]
== 与标准 Java "`JarFile`" 的兼容性

Spring Boot Loader 力求与现有代码和库保持兼容。
javadoc:org.springframework.boot.loader.jar.NestedJarFile[] 继承自 javadoc:java.util.jar.JarFile[]，应可作为直接替换使用。

支持形式为 `jar:nested:/path/myjar.jar/!BOOT-INF/lib/mylib.jar!/B.class` 的嵌套 JAR URL，并打开一个与 javadoc:java.net.JarURLConnection[] 兼容的连接。
这些可以与 Java 的 javadoc:java.net.URLClassLoader[] 一起使用。
