site:
  title: Spring Boot 中文文档
  url: http://localhost:8080
  start_page: boot::index.adoc

content:
  edit_url: false
  sources:
  - url: .
    branches: HEAD
    start_paths:
    - versions/*/content/boot

asciidoc:
  extensions:
  - ./extensions/javadoc-inline-macro.cjs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: build/site

runtime:
  log:
    failure_level: fatal
