site:
  title: Spring Boot 中文文档
  url: http://localhost:8080
  start_page: boot::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: content/boot

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: build/site

runtime:
  log:
    failure_level: error
