[[build-tool-plugins.other-build-systems]]
= 支持其他构建系统

如果你想使用 Maven、Gradle 或 Ant 以外的构建工具，你可能需要开发自己的插件。
可执行 jar 需要遵循特定格式，并且某些条目必须以未压缩的形式写入（详情请参见附录中的 xref:specification:/executable-jar/index.adoc[可执行 jar 格式] 部分）。

Spring Boot Maven 和 Gradle 插件都使用 `spring-boot-loader-tools` 来实际生成 jar。
如果需要，你可以直接使用这个库。


[[build-tool-plugins.other-build-systems.repackaging-archives]]
== 重新打包归档

要重新打包现有归档，使其成为自包含的可执行归档，请使用 javadoc:org.springframework.boot.loader.tools.Repackager[]。
javadoc:org.springframework.boot.loader.tools.Repackager[] 类接受一个构造函数参数，该参数引用现有的 jar 或 war 归档。
使用两个可用的 `repackage()` 方法之一来替换原始文件或写入新目标。
在运行重新打包器之前，还可以在其上配置各种设置。


[[build-tool-plugins.other-build-systems.nested-libraries]]
== 嵌套库

重新打包归档时，可以使用 javadoc:org.springframework.boot.loader.tools.Libraries[] 接口包含对依赖文件的引用。
我们在此不提供任何 javadoc:org.springframework.boot.loader.tools.Libraries[] 的具体实现，因为它们通常是特定于构建系统的。

如果你的归档已经包含库，你可以使用 javadoc:org.springframework.boot.loader.tools.Libraries#NONE[]。


[[build-tool-plugins.other-build-systems.finding-main-class]]
== 查找主类

如果你没有使用 `Repackager.setMainClass()` 指定主类，重新打包器将使用 https://asm.ow2.io/[ASM] 读取类文件，并尝试查找具有 `public static void main(String[] args)` 方法的合适类。
如果找到多个候选类，则会抛出异常。


[[build-tool-plugins.other-build-systems.example-repackage-implementation]]
== 示例重新打包实现

以下示例展示了一个典型的重新打包实现：

[source,java]
----
import java.io.File;
import java.io.IOException;
import java.util.List;

import org.springframework.boot.loader.tools.Library;
import org.springframework.boot.loader.tools.LibraryCallback;
import org.springframework.boot.loader.tools.LibraryScope;
import org.springframework.boot.loader.tools.Repackager;

public class MyBuildTool {

	public void build() throws IOException {
		File sourceJarFile = /**/ null;
		Repackager repackager = new Repackager(sourceJarFile);
		repackager.setBackupSource(false);
		repackager.repackage(this::getLibraries);
	}

	private void getLibraries(LibraryCallback callback) throws IOException {
		// Build system specific implementation, callback for each dependency
		for (File nestedJar : getCompileScopeJars()) {
			callback.library(new Library(nestedJar, LibraryScope.COMPILE));
		}
		// ...
	}

	private List<File> getCompileScopeJars() {
		return /**/ null;
	}

}
----
