= 打包可执行归档

该插件可以创建包含应用程序所有依赖项的可执行归档（jar 文件和 war 文件），然后可以通过 `java -jar` 运行。

[[packaging-executable.jars]]
== 打包可执行 JAR

可以使用 `bootJar` 任务构建可执行 JAR。
当应用 `java` 插件时，该任务会自动创建，并且是 {apiref-gradle-plugin-boot-jar}[`BootJar`] 的一个实例。
`assemble` 任务会自动配置为依赖于 `bootJar` 任务，因此运行 `assemble`（或 `build`）也会运行 `bootJar` 任务。

[[packaging-executable.wars]]
== 打包可执行 WAR

可以使用 `bootWar` 任务构建可执行 WAR。
当应用 `war` 插件时，该任务会自动创建，并且是 {apiref-gradle-plugin-boot-war}[`BootWar`] 的一个实例。
`assemble` 任务会自动配置为依赖于 `bootWar` 任务，因此运行 `assemble`（或 `build`）也会运行 `bootWar` 任务。

[[packaging-executable.wars.deployable]]
=== 打包可执行且可部署的 WAR

可以打包一个 war 文件，使其既可以通过 `java -jar` 执行，也可以部署到外部容器。
为此，应将嵌入式 Servlet 容器运行时添加到 `providedRuntime` 配置中，例如：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/war-container-dependency.gradle[tags=dependencies]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/war-container-dependency.gradle.kts[tags=dependencies]
----
======

这确保了运行时 jar 包被打包在 war 文件的 `WEB-INF/lib-provided` 目录中，从而不会与外部容器自身的类冲突。

注意：`providedRuntime` 优于 Gradle 的 `compileOnly` 配置，因为除其他限制外，`compileOnly` 依赖项不在测试 classpath 上，因此任何基于 Web 的集成测试都会失败。


[[packaging-executable.and-plain-archives]]
== 打包可执行归档和普通归档

默认情况下，当配置 `bootJar` 或 `bootWar` 任务时，`jar` 或 `war` 任务被配置为使用 `plain` 作为其归档分类器的约定。
这确保了 `bootJar` 和 `jar` 或 `bootWar` 和 `war` 具有不同的输出位置，从而允许同时构建可执行归档和普通归档。

如果您希望可执行归档（而不是普通归档）使用分类器，请按以下示例为 `jar` 和 `bootJar` 任务配置分类器：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-and-jar-classifiers.gradle[tags=classifiers]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-and-jar-classifiers.gradle.kts[tags=classifiers]
----
======

或者，如果您希望完全不构建普通归档文件，可以禁用其任务，如下面的 `jar` 任务示例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/only-boot-jar.gradle[tags=disable-jar]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/only-boot-jar.gradle.kts[tags=disable-jar]
----
======

WARNING: 创建 native images 时，不要禁用 `jar` 任务。
详情请参见 https://github.com/spring-projects/spring-boot/issues/33238[#33238]。



[[packaging-executable.configuring]]
== 配置可执行归档的打包

{apiref-gradle-plugin-boot-jar}[`BootJar`] 和 {apiref-gradle-plugin-boot-war}[`BootWar`] 任务分别是 Gradle 的 `Jar` 和 `War` 任务的子类。
因此，打包 jar 或 war 时可用的所有标准配置选项，在打包可执行 jar 或 war 时同样可用。
此外，还提供了许多特定于可执行 jar 和 war 的配置选项。



[[packaging-executable.configuring.main-class]]
=== 配置主类

默认情况下，可执行归档的主类将通过在主源集输出中查找带有 `public static void main(String[])` 方法的类来自动配置。

也可以使用任务的 `mainClass` 属性显式配置主类：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-main-class.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-main-class.gradle.kts[tags=main-class]
----
======

或者，可以使用 Spring Boot DSL 的 `mainClass` 属性在项目范围内配置主类名：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/spring-boot-dsl-main-class.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/spring-boot-dsl-main-class.gradle.kts[tags=main-class]
----
======

如果已应用 {url-gradle-docs-application-plugin}[`application` 插件]，则必须配置其 `mainClass` 属性，并且可以用于相同目的：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/application-plugin-main-class.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/application-plugin-main-class.gradle.kts[tags=main-class]
----
======

最后，可以在任务的 manifest 上配置 `Start-Class` 属性：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-manifest-main-class.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-manifest-main-class.gradle.kts[tags=main-class]
----
======

注意：如果主类是用 Kotlin 编写的，则应使用生成的 Java 类的名称。
默认情况下，这是 Kotlin 类的名称加上 `Kt` 后缀。
例如，`ExampleApplication` 变为 `ExampleApplicationKt`。
如果使用 `@JvmName` 定义了其他名称，则应使用该名称。


[[packaging-executable.configuring.including-development-only-dependencies]]
=== 包含仅开发依赖项

默认情况下，在 `developmentOnly` 配置中声明的所有依赖项都将从可执行 jar 或 war 中排除。

如果希望将 `developmentOnly` 配置中声明的依赖项包含在归档文件中，请配置其任务的 classpath 以包含该配置，如下面的 `bootWar` 任务示例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-war-include-devtools.gradle[tags=include-devtools]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-war-include-devtools.gradle.kts[tags=include-devtools]
----
======

[[packaging-executable.configuring.unpacking]]
=== 配置需要解压的库

大多数库在嵌套于可执行归档中时可以直接使用，但某些库可能会出现问题。
例如，JRuby 包含其自身的嵌套 jar 支持，该支持假设 `jruby-complete.jar` 始终直接存在于文件系统上。

为了处理任何有问题的库，可以将可执行归档配置为在运行时将特定的嵌套 jar 解压到临时目录。
可以使用 Ant 风格的模式来标识需要解压的库，这些模式与源 jar 文件的绝对路径匹配：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-requires-unpack.gradle[tags=requires-unpack]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-requires-unpack.gradle.kts[tags=requires-unpack]
----
======

为了获得更多控制，也可以使用闭包。
闭包接收一个 `FileTreeElement` 并应返回一个 `boolean`，指示是否需要解包。


[[packaging-executable.configuring.properties-launcher]]
=== 使用 PropertiesLauncher

要使用 `PropertiesLauncher` 启动可执行 jar 或 war，请配置任务的清单以设置 `Main-Class` 属性：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-war-properties-launcher.gradle[tags=properties-launcher]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-war-properties-launcher.gradle.kts[tags=properties-launcher]
----
======



[[packaging-executable.configuring.layered-archives]]
=== 打包分层 Jar 或 War

默认情况下，`bootJar` 任务构建的归档文件中，应用程序的类和依赖分别位于 `BOOT-INF/classes` 和 `BOOT-INF/lib` 中。
类似地，`bootWar` 构建的归档文件中，应用程序的类位于 `WEB-INF/classes`，依赖位于 `WEB-INF/lib` 和 `WEB-INF/lib-provided` 中。
对于需要从 jar 内容构建 Docker 镜像的情况，进一步分离这些目录以便它们可以写入不同的层是很有用的。

分层 jar 使用与常规 boot 打包 jar 相同的布局，但包含一个额外的元数据文件来描述每一层。

默认情况下，定义了以下层：

* `dependencies`：用于版本不包含 `SNAPSHOT` 的任何非项目依赖。
* `spring-boot-loader`：用于 jar 加载器类。
* `snapshot-dependencies`：用于版本包含 `SNAPSHOT` 的任何非项目依赖。
* `application`：用于项目依赖、应用程序类和资源。

层的顺序很重要，因为它决定了当应用程序部分发生变化时，先前层被缓存的可能性。
默认顺序是 `dependencies`、`spring-boot-loader`、`snapshot-dependencies`、`application`。
最不可能变化的内容应首先添加，然后是更可能变化的层。

要禁用此功能，可以按以下方式操作：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-layered-disabled.gradle[tags=layered]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-layered-disabled.gradle.kts[tags=layered]
----
======
当创建分层 jar 或 war 时，`spring-boot-jarmode-tools` jar 将作为依赖项添加到您的归档中。将此 jar 放在 classpath 上，您可以在特殊模式下启动应用程序，该模式允许引导代码运行与应用程序完全不同的内容，例如，提取层的内容。如果您希望排除此依赖项，可以通过以下方式实现：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-layered-exclude-tools.gradle[tags=layered]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-layered-exclude-tools.gradle.kts[tags=layered]
----
======

[[packaging-executable.configuring.layered-archives.configuration]]
==== 自定义层配置

根据你的应用程序，你可能希望调整层的创建方式并添加新的层。

可以通过配置来描述如何将 jar 或 war 拆分为层，以及这些层的顺序。
以下示例展示了如何显式定义上述默认顺序：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-layered-custom.gradle[tags=layered]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-jar-layered-custom.gradle.kts[tags=layered]
----
======

`layered` DSL 由三部分组成：

* `application` 闭包定义了应用类和资源应如何分层。
* `dependencies` 闭包定义了依赖应如何分层。
* `layerOrder` 方法定义了层的写入顺序。

在 `intoLayer` 和 `application` 部分中，使用嵌套的 `dependencies` 闭包来为某个层声明内容。
这些闭包按照定义的顺序从上到下求值。
未被较早的 `intoLayer` 闭包声明的任何内容仍可供后续闭包考虑。

`intoLayer` 闭包通过嵌套的 `include` 和 `exclude` 调用来声明内容。
`application` 闭包使用 Ant 风格路径匹配来处理包含/排除参数。
`dependencies` 部分使用 `group:artifact[:version]` 模式。
它还提供了 `includeProjectDependencies()` 和 `excludeProjectDependencies()` 方法，可用于包含或排除项目依赖。

如果没有进行 `include` 调用，则所有内容（未被较早闭包声明的）都被视为包含。

如果没有进行 `exclude` 调用，则不应用任何排除。

查看上面示例中的 `dependencies` 闭包，我们可以看到第一个 `intoLayer` 会将所有项目依赖声明给 `application` 层。
下一个 `intoLayer` 会将所有 SNAPSHOT 依赖声明给 `snapshot-dependencies` 层。
第三个也是最后一个 `intoLayer` 会将剩余的任何内容（在本例中，既不是项目依赖也不是 SNAPSHOT 的依赖）声明给 `dependencies` 层。

`application` 闭包有类似的规则。
首先将 `org/springframework/boot/loader/**` 内容声明给 `spring-boot-loader` 层。
然后将剩余的任何类和资源声明给 `application` 层。

注意：`intoLayer` 闭包的添加顺序通常与层的写入顺序不同。
因此，必须始终调用 `layerOrder` 方法，并且 _必须_ 覆盖所有被 `intoLayer` 调用引用的层。
