= 使用 Gradle 运行你的应用程序

要运行你的应用程序而不先构建归档文件，请使用 `bootRun` 任务：

[source,shell]
----
$ ./gradlew bootRun
----
`bootRun` 任务是 {apiref-gradle-plugin-boot-run}[`BootRun`] 的实例，而 `BootRun` 是 `JavaExec` 的子类。
因此，所有用于在 Gradle 中执行 Java 进程的 {url-gradle-dsl}/org.gradle.api.tasks.JavaExec.html[常规配置选项] 都可用。
该任务会自动配置为使用 `main` source set 的 runtime classpath。

默认情况下，main class 会通过在 `main` source set 的输出中查找带有 `public static void main(String[])` 方法的类来自动配置。

也可以使用该任务的 `main` 属性显式配置 main class：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-main.gradle[tags=main]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-main.gradle.kts[tags=main]
----
======

或者，可以使用 Spring Boot DSL 的 `mainClass` 属性在项目范围内配置主类名：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/spring-boot-dsl-main-class-name.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/spring-boot-dsl-main-class-name.gradle.kts[tags=main-class]
----
======

默认情况下，`bootRun` 会配置 JVM 以优化其启动，从而在开发期间实现更快的启动速度。
可以通过使用 `optimizedLaunch` 属性来禁用此行为，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-disable-optimized-launch.gradle[tags=launch]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-disable-optimized-launch.gradle.kts[tags=launch]
----
======

如果已应用 {url-gradle-docs-application-plugin}[`application` 插件]，则必须配置其 `mainClass` 属性，并且可以用于相同目的：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/application-plugin-main-class-name.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/application-plugin-main-class-name.gradle.kts[tags=main-class]
----
======

[[running-your-application.passing-arguments]]
== 向应用程序传递参数

与所有 `JavaExec` 任务一样，使用 Gradle 4.9 或更高版本时，可以通过命令行使用 `--args='<arguments>'` 将参数传递给 `bootRun`。
例如，要运行应用程序并激活名为 `dev` 的 profile，可以使用以下命令：

[source,shell]
----
$ ./gradlew bootRun --args='--spring.profiles.active=dev'
----
有关详细信息，请参阅 {url-gradle-javadoc}/org/gradle/api/tasks/JavaExec.html#setArgsString(java.lang.String)[`JavaExec.setArgsString` 的 javadoc]。

[[running-your-application.passing-system-properties]]
== 向应用程序传递系统属性

由于 `bootRun` 是一个标准的 `JavaExec` 任务，因此可以通过在构建脚本中指定系统属性来将其传递给应用程序的 JVM。
要使系统属性的值可配置，请使用 {url-gradle-dsl}/org.gradle.api.Project.html#N14FE1[项目属性] 设置其值。
要使项目属性可选，请使用 `findProperty` 引用它。
这样做还可以使用 `?:` Elvis 运算符提供默认值，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-system-property.gradle[tags=system-property]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-system-property.gradle.kts[tags=system-property]
----
前面的示例将 `com.example.property` 系统属性设置为 `example` 项目属性的值。
如果 `example` 项目属性未设置，则系统属性的值将为 `default`。

Gradle 允许以多种方式设置项目属性，包括在命令行中使用 `-P` 标志，如下例所示：

[source,bash,indent=0,subs="verbatim,attributes"]
----
$ ./gradlew bootRun -Pexample=custom
----
前面的示例将 `example` 项目属性的值设置为 `custom`。
`bootRun` 将使用该值作为 `com.example.property` 系统属性的值。

[[running-your-application.reloading-resources]]
== 重新加载资源

如果 devtools 已添加到项目中，它将自动监视应用程序的 classpath 的更改。
请注意，修改后的文件需要重新编译，以便 classpath 更新，从而触发 devtools 的重新加载。
有关使用 devtools 的更多详细信息，请参阅 xref:reference:using/devtools.adoc#using.devtools.restart[参考文档的这一部分]。

或者，您可以配置 `bootRun`，以便从源位置加载应用程序的静态资源：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-source-resources.gradle[tags=source-resources]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-source-resources.gradle.kts[tags=source-resources]
----
这使得它们在实时应用程序中可重新加载，这在开发时可能很有帮助。

[[running-your-application.using-a-test-main-class]]
== 使用测试主类

除了 `bootRun` 之外，还注册了一个 `bootTestRun` 任务。
与 `bootRun` 类似，`bootTestRun` 是 `BootRun` 的一个实例，但它被配置为使用测试源集输出中找到的主类，而不是主源集。
它还使用测试源集的运行时 classpath，而不是主源集的运行时 classpath。
由于 `bootTestRun` 是 `BootRun` 的一个实例，上述为 `bootRun` 描述的所有配置选项也可以与 `bootTestRun` 一起使用。
