[[integration-tests]]
= 运行集成测试

虽然你可以非常容易地从测试（或测试套件）本身启动 Spring Boot 应用程序，但可能更希望在构建本身中处理这一点。
为了确保 Spring Boot 应用程序的生命周期在集成测试前后得到妥善管理，你可以使用 `start` 和 `stop` 目标，如下例所示：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$integration-tests/pom.xml[tags=integration-tests]
----
这样的设置现在可以使用 https://maven.apache.org/surefire/maven-failsafe-plugin[failsafe-plugin] 按预期运行集成测试。

注意：应用程序在单独的进程中启动，并使用 JMX 与应用程序通信。
默认情况下，插件使用端口 `9001`。
如果需要配置 JMX 端口，请参阅 xref:integration-tests.adoc#integration-tests.examples.jmx-port[专用示例]。

您还可以配置更高级的设置，在设置了特定属性时跳过集成测试，请参阅 xref:integration-tests.adoc#integration-tests.examples.skip[专用示例]。


[[integration-tests.no-starter-parent]]
== 在不使用 Spring Boot 父 POM 的情况下使用 Failsafe

Spring Boot 的父 POM `spring-boot-starter-parent` 将 Failsafe 的 `<classesDirectory>` 配置为 `${project.build.outputDirectory}`。
如果没有此配置（该配置使 Failsafe 使用编译后的类而不是重新打包的 jar），Failsafe 将无法加载应用程序的类。
如果您不使用父 POM，则应以相同的方式配置 Failsafe，如下例所示：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$integration-tests/failsafe-pom.xml[tags=failsafe]
----
include::partial$goals/start.adoc[leveloffset=+1]

include::partial$goals/stop.adoc[leveloffset=+1]



[[integration-tests.examples]]
== 示例



[[integration-tests.examples.random-port]]
=== 用于集成测试的随机端口

Spring Boot 测试集成的一个优秀特性是它可以为 Web 应用程序分配一个空闲端口。
当使用插件的 `start` 目标时，Spring Boot 应用程序会单独启动，这使得将实际端口传递给集成测试本身变得困难。

下面的示例展示了如何使用 https://www.mojohaus.org/build-helper-maven-plugin[Build Helper Maven Plugin] 实现相同的特性：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$integration-tests/random-port-pom.xml[tags=random-port]
----
现在，您可以在任何集成测试中检索 `test.server.port` 系统属性，以创建到服务器的正确 `URL`。

[[integration-tests.examples.jmx-port]]
=== 自定义 JMX 端口

`jmxPort` 属性允许自定义插件用于与 Spring Boot 应用程序通信的端口。

以下示例展示了如何在 `9001` 已被占用时自定义端口：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$integration-tests/customize-jmx-port-pom.xml[tags=customize-jmx-port]
----
提示：如果需要配置 JMX 端口，请确保像上面那样在全局配置中进行配置，以便两个目标共享该端口。

[[integration-tests.examples.skip]]
=== 跳过集成测试

`skip` 属性允许完全跳过 Spring Boot maven 插件的执行。

以下示例展示了如何通过命令行属性跳过集成测试，同时仍然确保 `repackage` 目标运行：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$integration-tests/skip-integration-tests-pom.xml[tags=skip-integration-tests]
----
默认情况下，集成测试会运行，但此设置允许你通过命令行轻松禁用它们，如下所示：

[source,shell]
----
$ mvn verify -Dskip.it=true
----
