= 使用 Maven 运行你的应用程序

该插件包含一个 run 目标，可用于从命令行启动你的应用程序，如下例所示：

[source,shell]
----
$ mvn spring-boot:run
----
可以使用 `arguments` 参数指定应用程序参数，更多详情请参见 xref:run.adoc#run.examples.using-application-arguments[使用应用程序参数]。

应用程序在分叉进程中执行，在命令行上设置属性不会影响应用程序。
如果需要指定某些 JVM 参数（例如用于调试目的），可以使用 `jvmArguments` 参数，更多详情请参见 xref:run.adoc#run.examples.debug[调试应用程序]。
此外，还明确支持 xref:run.adoc#run.examples.system-properties[系统属性] 和 xref:run.adoc#run.examples.environment-variables[环境变量]。

由于启用 profile 非常常见，因此有专门的 `profiles` 属性，它为 `-Dspring-boot.run.jvmArguments="-Dspring.profiles.active=dev"` 提供了快捷方式，请参见 xref:run.adoc#run.examples.specify-active-profiles[指定活动的 profiles]。

Spring Boot `devtools` 是一个模块，旨在改善开发 Spring Boot 应用程序时的开发体验。
要启用它，只需将以下依赖项添加到项目中：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$running/devtools-pom.xml[tags=devtools]
----
当 `devtools` 运行时，它会检测到你重新编译应用程序时的更改，并自动刷新应用程序。这不仅适用于资源，也适用于代码。它还提供了一个 LiveReload 服务器，以便在发生更改时自动触发浏览器刷新。

Devtools 也可以配置为仅在静态资源发生更改时刷新浏览器（并忽略代码中的任何更改）。只需在项目中包含以下属性：

[source,properties]
----
spring.devtools.remote.restart.enabled=false
----
在 `devtools` 之前，该插件默认支持资源的热刷新，但现在已禁用，转而采用上述解决方案。
你可以随时通过配置项目来恢复此功能：

[source,xml,subs="verbatim,attributes"]
----
include::example$running/hot-refresh-pom.xml[tags=hot-refresh]
----
当 `addResources` 启用时，任何 `src/main/resources` 目录都会在运行应用程序时被添加到应用程序 classpath 中，并且 classes 输出中发现的任何重复项都会被移除。
这允许资源的热刷新，在开发 Web 应用程序时非常有用。
例如，你可以处理 HTML、CSS 或 JavaScript 文件，并立即看到更改，而无需重新编译应用程序。
这也是一种让前端开发人员无需下载和安装 Java IDE 即可工作的有用方式。

注意：使用此功能的副作用是构建时的资源过滤将不起作用。

为了与 `repackage` 目标保持一致，`run` 目标构建 classpath 的方式是，插件配置中排除的任何依赖也会从 classpath 中排除。
更多详情，请参见 xref:packaging.adoc#packaging.examples.exclude-dependency[专用示例]。

有时运行应用程序的测试变体很有用。
例如，如果你想 xref:reference:features/dev-services.adoc#features.dev-services.testcontainers.at-development-time[在开发时使用 Testcontainers] 或使用一些测试桩。
为此，请使用 `test-run` 目标，它具有与 `run` 相同的许多功能和配置选项。

include::partial$goals/run.adoc[leveloffset=+1]

include::partial$goals/test-run.adoc[leveloffset=+1]


[[run.examples]]
== 示例


[[run.examples.debug]]
=== 调试应用程序

`run` 和 `test-run` 目标在分叉进程中运行你的应用程序。
如果需要调试，应添加必要的 JVM 参数以启用远程调试。
以下配置会挂起进程，直到调试器在端口 5005 上连接：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$running/debug-pom.xml[tags=debug]
----
这些参数也可以在命令行中指定：

[source,shell]
----
$ mvn spring-boot:run -Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
----
=== 使用系统属性

可以使用 `systemPropertyVariables` 属性指定系统属性。
以下示例将 `property1` 设置为 `test`，将 `property2` 设置为 42：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$running/system-properties-pom.xml[tags=system-properties]
----
如果值为空或未定义（即 `<my-property/`>），则系统属性将被设置为空字符串作为值。
Maven 会修剪在 pom 中指定的值，因此无法通过此机制指定需要以空格开头或结尾的系统属性：请考虑使用 `jvmArguments` 代替。

任何字符串类型的 Maven 变量都可以作为系统属性传递。
任何尝试传递其他 Maven 变量类型（例如 `List` 或 `URL` 变量）都会导致变量表达式被原样传递（不进行求值）。

`jvmArguments` 参数优先于通过上述机制定义的系统属性。
在以下示例中，`property1` 的值为 `overridden`：

[source,shell]
----
$ mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dproperty1=overridden"
----
[[run.examples.environment-variables]]
=== 使用环境变量

可以使用 `environmentVariables` 属性指定环境变量。
以下示例设置了 'ENV1'、'ENV2'、'ENV3'、'ENV4' 环境变量：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$running/environment-variables-pom.xml[tags=environment-variables]
----
如果值为空或未定义（即 `<MY_ENV/`>），则环境变量将被设置为空字符串作为值。
Maven 会修剪在 pom 中指定的值，因此无法指定需要以空格开头或结尾的环境变量。

任何字符串类型的 Maven 变量都可以作为系统属性传递。
任何尝试传递其他 Maven 变量类型（例如 `List` 或 `URL` 变量）都会导致变量表达式被原样传递（不经过求值）。

以这种方式定义的环境变量优先于现有值。


[[run.examples.using-application-arguments]]
=== 使用应用程序参数

可以使用 `arguments` 属性指定应用程序参数。
以下示例设置两个参数：`property1` 和 `property2=42`：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$running/application-arguments-pom.xml[tags=application-arguments]
----
在命令行中，参数与 `jvmArguments` 一样用空格分隔。
如果参数包含空格，请确保将其引起来。
在以下示例中，有两个参数可用：`property1` 和 `property2=Hello World`：

[source,shell]
----
$ mvn spring-boot:run -Dspring-boot.run.arguments="property1 'property2=Hello World'"
----
=== 指定激活的 Profile

可以使用 `profiles` 参数指定特定应用程序要使用的激活 profiles。

以下配置启用了 `local` 和 `dev` profiles：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$running/active-profiles-pom.xml[tags=active-profiles]
----
要启用的 profiles 也可以在命令行上指定，请确保用逗号分隔它们，如下例所示：

[source,shell]
----
$ mvn spring-boot:run -Dspring-boot.run.profiles=local,dev
----
