= 提供手动提示

为了改善用户体验并进一步帮助用户配置特定属性，您可以提供额外的元数据，这些元数据可以：

* 描述属性的潜在值列表。
* 关联一个提供者，为属性附加一个明确的语义，以便工具可以根据项目上下文发现潜在值列表。


== 值提示

每个提示的 `name` 属性指向属性的 `name`。
在 xref:configuration-metadata/format.adoc[前面展示的初始示例]中，我们为 `spring.jpa.hibernate.ddl-auto` 属性提供了五个值：`none`、`validate`、`update`、`create` 和 `create-drop`。
每个值也可以有描述。

如果您的属性是 javadoc:java.util.Map[] 类型，您可以为键和值提供提示（但不能为映射本身提供提示）。
特殊的 `.keys` 和 `.values` 后缀必须分别指向键和值。

假设一个 `my.contexts` 将魔法 javadoc:java.lang.String[] 值映射到整数，如下例所示：

include-code::MyProperties[]

魔法值（在此示例中）是 `sample1` 和 `sample2`。
为了为键提供额外的内容辅助，您可以将以下 JSON 添加到 xref:configuration-metadata/annotation-processor.adoc#appendix.configuration-metadata.annotation-processor.adding-additional-metadata[模块的手动元数据]中：

[source,json]
----
{"hints": [
	{
		"name": "my.contexts.keys",
		"values": [
			{
				"value": "sample1"
			},
			{
				"value": "sample2"
			}
		]
	}
]}
----
注意：也可以为 xref:configuration-metadata/annotation-processor.adoc#appendix.configuration-metadata.annotation-processor.automatic-metadata-generation.source[外部类型] 添加提示，并且只要使用该类型就会应用这些提示。

提示：我们建议您对这两个值使用 javadoc:java.lang.Enum[]。
如果您的 IDE 支持，这无疑是实现自动补全最有效的方法。


[[appendix.configuration-metadata.manual-hints.value-providers]]
== 值提供者

提供者是一种将语义附加到属性上的强大方式。
在本节中，我们定义了可用于您自己提示的官方提供者。
但是，您喜欢的 IDE 可能实现了其中一些，也可能一个都没有实现。
此外，它最终可能会提供自己的提供者。

注意：由于这是一项新功能，IDE 供应商必须跟上其工作方式。
采用时间自然有所不同。

下表总结了支持的提供者列表：

[cols="2,4"]
|===
| 名称 | 描述

| `any`
| 允许提供任何附加值。

| `class-reference`
| 自动补全项目中可用的类。
  通常由 `target` 参数指定的基类约束。

| `handle-as`
| 将属性视为由强制 `target` 参数定义的类型来定义。

| `logger-name`
| 自动补全有效的日志器名称和 xref:reference:features/logging.adoc#features.logging.log-groups[日志器组]。
  通常，当前项目中可用的包名和类名以及已定义的组都可以自动补全。

| `spring-bean-reference`
| 自动补全当前项目中可用的 bean 名称。
  通常由 `target` 参数指定的基类约束。

| `spring-profile-name`
| 自动补全项目中可用的 Spring profile 名称。
|===

提示：对于给定的属性，只能有一个提供者处于活动状态，但如果多个提供者能够以某种方式管理该属性，您可以指定多个提供者。
确保将最强大的提供者放在第一位，因为 IDE 必须使用 JSON 部分中它能够处理的第一个提供者。
如果不支持给定属性的提供者，则也不会提供特殊的内容辅助。


[[appendix.configuration-metadata.manual-hints.value-providers.any]]
=== Any

特殊的 **any** 提供者值允许提供任何附加值。
如果支持，应基于属性类型应用常规值验证。

如果您有一个值列表，并且任何额外的值仍应被视为有效，则通常使用此提供者。

以下示例为 `system.state` 提供 `on` 和 `off` 作为自动补全值：

[source,json]
----
{"hints": [
	{
		"name": "system.state",
		"values": [
			{
				"value": "on"
			},
			{
				"value": "off"
			}
		],
		"providers": [
			{
				"name": "any"
			}
		]
	}
]}
----
请注意，在前面的示例中，任何其他值也是允许的。

[[appendix.configuration-metadata.manual-hints.value-providers.class-reference]]
=== 类引用

**class-reference** 提供者自动补全项目中可用的类。
该提供者支持以下参数：

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| `target`
| javadoc:java.lang.String[] (`Class`)
| _无_
| 所选值应可赋值给的类的完全限定名。
  通常用于过滤掉非候选类。
  请注意，此信息可以由类型本身通过公开具有适当上界的类来提供。

| `concrete`
| `boolean`
| true
| 指定是否仅将具体类视为有效候选。
|===

以下元数据片段对应于标准的 `server.servlet.jsp.class-name` 属性，该属性定义要使用的类名必须是 javadoc:jakarta.servlet.http.HttpServlet[]：

[source,json]
----
{"hints": [
	{
		"name": "server.servlet.jsp.class-name",
		"providers": [
			{
				"name": "class-reference",
				"parameters": {
					"target": "jakarta.servlet.http.HttpServlet"
				}
			}
		]
	}
]}
----
=== 处理为

**handle-as** 提供者允许你将属性的类型替换为更高级的类型。
这通常发生在属性具有 javadoc:java.lang.String[] 类型时，因为你不想让你的配置类依赖于可能不在 classpath 上的类。
该提供者支持以下参数：

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| **`target`**
| javadoc:java.lang.String[] (`Class`)
| _无_
| 要考虑用于属性的类型的完全限定名。
  此参数是必需的。
|===

可以使用以下类型：

* 任何 javadoc:java.lang.Enum[]：列出属性的可能值。
  （我们建议使用 javadoc:java.lang.Enum[] 类型定义属性，因为 IDE 自动补全值不需要进一步的提示）
* javadoc:java.nio.charset.Charset[]：支持字符集/编码值的自动补全（例如 `UTF-8`）
* javadoc:java.util.Locale[]：区域设置的自动补全（例如 `en_US`）
* javadoc:org.springframework.util.MimeType[]：支持内容类型值的自动补全（例如 `text/plain`）
* javadoc:org.springframework.core.io.Resource[]：支持 Spring 的 Resource 抽象自动补全，以引用文件系统或 classpath 上的文件（例如 `classpath:/sample.properties`）

提示：如果可以提供多个值，请使用 javadoc:java.util.Collection[] 或 _Array_ 类型来告知 IDE。

以下元数据片段对应于标准的 `spring.liquibase.change-log` 属性，该属性定义了要使用的 changelog 的路径。
它实际上在内部用作 javadoc:org.springframework.core.io.Resource[]，但不能这样暴露，因为我们需要保留原始字符串值以传递给 Liquibase API。

[source,json]
----
{"hints": [
	{
		"name": "spring.liquibase.change-log",
		"providers": [
			{
				"name": "handle-as",
				"parameters": {
					"target": "org.springframework.core.io.Resource"
				}
			}
		]
	}
]}
----
=== 日志器名称

**logger-name** 提供程序自动补全有效的日志器名称和 xref:reference:features/logging.adoc#features.logging.log-groups[日志器组]。
通常，当前项目中可用的包名和类名可以被自动补全。
如果启用了组（默认）并且在配置中识别出自定义日志器组，则应提供针对它的自动补全。
特定框架可能还支持额外的魔法日志器名称。

此提供程序支持以下参数：

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| `group`
| `boolean`
| `true`
| 指定是否应考虑已知的组。
|===

由于日志器名称可以是任意名称，此提供程序应允许任何值，但可以高亮项目中 classpath 中不可用的有效包名和类名。

以下元数据片段对应于标准的 `logging.level` 属性。
键是 _日志器名称_，值对应于标准日志级别或任何自定义级别。
由于 Spring Boot 开箱即用地定义了几个日志器组，因此为这些组添加了专用的值提示。

[source,json]
----
{"hints": [
	{
		"name": "logging.level.keys",
		"values": [
			{
				"value": "root",
				"description": "Root logger used to assign the default logging level."
			},
			{
				"value": "sql",
				"description": "SQL logging group including Hibernate SQL logger."
			},
			{
				"value": "web",
				"description": "Web logging group including codecs."
			}
		],
		"providers": [
			{
				"name": "logger-name"
			}
		]
	},
	{
		"name": "logging.level.values",
		"values": [
			{
				"value": "trace"
			},
			{
				"value": "debug"
			},
			{
				"value": "info"
			},
			{
				"value": "warn"
			},
			{
				"value": "error"
			},
			{
				"value": "fatal"
			},
			{
				"value": "off"
			}

		],
		"providers": [
			{
				"name": "any"
			}
		]
	}
]}
----

=== Spring Bean 引用

**spring-bean-reference** 提供者会自动补全当前项目配置中定义的 beans。
该提供者支持以下参数：

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| `target`
| javadoc:java.lang.String[] (`Class`)
| _无_
| 候选 bean 类应可赋值给的全限定类名。
  通常用于过滤掉非候选的 beans。
|===

以下元数据片段对应于标准的 `spring.jmx.server` 属性，该属性定义了要使用的 javadoc:javax.management.MBeanServer[] bean 的名称：

[source,json]
----
{"hints": [
	{
		"name": "spring.jmx.server",
		"providers": [
			{
				"name": "spring-bean-reference",
				"parameters": {
					"target": "javax.management.MBeanServer"
				}
			}
		]
	}
]}
----
NOTE: 绑定器不知道元数据。
如果你提供了该提示，你仍然需要通过 javadoc:org.springframework.context.ApplicationContext[] 将 bean 名称转换为实际的 Bean 引用。

[[appendix.configuration-metadata.manual-hints.value-providers.spring-profile-name]]
=== Spring Profile Name

**spring-profile-name** 提供程序会自动补全当前项目配置中定义的 Spring profiles。

以下元数据片段对应于标准的 `spring.profiles.active` 属性，该属性定义了要启用的 Spring profile 的名称：

[source,json]
----
{"hints": [
	{
		"name": "spring.profiles.active",
		"providers": [
			{
				"name": "spring-profile-name"
			}
		]
	}
]}
----
