= Spring Session

Spring Boot 为多种数据存储提供 {url-spring-session-site}[Spring Session] auto-configuration。
对于每种数据存储，都提供了特定的 Spring Boot starter。

在构建 Servlet Web 应用程序时，以下存储可以自动配置：

* Redis (`spring-boot-starter-session-data-redis`)
* JDBC (`spring-boot-starter-session-jdbc`)

Servlet 自动配置取代了使用 `@Enable*HttpSession` 的需求。

在构建响应式 Web 应用程序时，可以通过依赖 `spring-boot-starter-session-data-redis` 来自动配置 Redis 存储。
这取代了使用 `@EnableRedisWebSession` 的需求。

每种存储都有特定的附加设置。
例如，可以自定义 JDBC 存储的表名，如下例所示：

[configprops,yaml]
----
spring:
  session:
    jdbc:
      table-name: "SESSIONS"
----

要设置会话超时时间，可以使用 configprop:spring.session.timeout[] 属性。
如果该属性未在 Servlet Web 应用中设置，自动配置会回退到 configprop:server.servlet.session.timeout[] 的值。
要以编程方式提供超时时间，请定义一个 javadoc:org.springframework.boot.session.autoconfigure.SessionTimeout[] bean。

你可以通过 `@Enable*HttpSession`（Servlet）或 `@EnableRedisWebSession`（Reactive）来控制 Spring Session 的配置。
这将导致自动配置退出。
或者，直接依赖相关的 Spring Session 模块，而不是使用 Spring Boot 的 starter 之一来配置 Spring Session。
无论采用哪种方法，都可以使用 annotation 的属性（而非之前描述的配置属性）来配置 Spring Session。
