[[web.spring-hateoas]]
= Spring HATEOAS

如果你开发使用超媒体的 RESTful API，Spring Boot 会为 Spring HATEOAS 提供 auto-configuration，且适用于大多数应用程序。
该 auto-configuration 取代了使用 javadoc:org.springframework.hateoas.config.EnableHypermediaSupport[format=annotation] 的需要，并注册多个 bean 来帮助构建基于超媒体的应用程序，包括 javadoc:org.springframework.hateoas.client.LinkDiscoverers[]（用于客户端支持）以及 javadoc:tools.jackson.databind.json.JsonMapper[]，后者配置为能将响应正确编组为所需表示形式。
javadoc:tools.jackson.databind.json.JsonMapper[] 可通过设置各种 `spring.jackson.*` 属性进行自定义；如果存在 javadoc:org.springframework.boot.jackson.autoconfigure.JsonMapperBuilderCustomizer[] bean，也会使用这些 bean 进行自定义。

你可以通过使用 javadoc:org.springframework.hateoas.config.EnableHypermediaSupport[format=annotation] 来控制 Spring HATEOAS 的配置。
请注意，这样做会禁用前面描述的 javadoc:tools.jackson.databind.json.JsonMapper[] 自定义。

WARNING: `spring-boot-starter-hateoas` 专用于 Spring MVC，不应与 Spring WebFlux 组合使用。
要将 Spring HATEOAS 与 Spring WebFlux 一起使用，可以直接添加对 `org.springframework.hateoas:spring-hateoas` 的依赖，并同时使用 `spring-boot-starter-webflux`。

默认情况下，接受 `application/json` 的请求会收到 `application/hal+json` 响应。
要禁用此行为，请将 configprop:spring.hateoas.use-hal-as-default-json-media-type[] 设置为 `false`，并定义 javadoc:org.springframework.hateoas.config.HypermediaMappingInformation[] 或 javadoc:org.springframework.hateoas.mediatype.hal.HalConfiguration[]，以便根据应用程序及其客户端的需求配置 Spring HATEOAS。
