[[getting-started.system-requirements]]
= 系统要求

Spring Boot {version-spring-boot} 至少需要 https://www.java.com[Java 17]，并且兼容至 Java 26（含该版本）。
此外，还需要 {url-spring-framework-docs}/[Spring Framework {version-spring-framework}] 或更高版本。

对第三方项目的支持可能有额外的或更高的要求。
详情请参阅相应支持的文档。

以下构建工具提供了显式的构建支持：

|===
| 构建工具 | 版本

| Maven
| 3.6.3 或更高版本

| Gradle
| Gradle 8.x（8.14 或更高版本）和 9.x
|===



[[getting-started.system-requirements.servlet-containers]]
== Servlet 容器

Spring Boot 支持以下内嵌 Servlet 容器：

|===
| 名称 | Servlet 版本

| Tomcat 11.0.x
| 6.1

| Jetty 12.1.x
| 6.1

|===

您还可以将 Spring Boot 应用程序部署到任何兼容 Servlet 6.1+ 的容器中。



[[getting-started.system-requirements.graal]]
== GraalVM Native Images

Spring Boot 应用程序可以使用 GraalVM {version-graal} 或更高版本 xref:reference:packaging/native-image/introducing-graalvm-native-images.adoc[转换为 Native Image]。

可以使用 https://github.com/graalvm/native-build-tools[native build tools] Gradle/Maven 插件或 GraalVM 提供的 `native-image` 工具来创建镜像。
您还可以使用 https://github.com/paketo-buildpacks/native-image[native-image Paketo buildpack] 创建 native images。

支持以下版本：

|===
| 名称 | 版本

| GraalVM Community
| {version-graal}

| Native Build Tools
| {version-native-build-tools}
|===
