= 响应式 Web 应用程序

Spring Boot 通过为 Spring Webflux 提供 auto-configuration，简化了响应式 Web 应用程序的开发。


[[web.reactive.webflux]]
== "`Spring WebFlux Framework`"

Spring WebFlux 是 Spring Framework 5.0 中引入的新响应式 Web 框架。
与 Spring MVC 不同，它不需要 Servlet API，完全异步且非阻塞，并通过 https://projectreactor.io/[Reactor 项目] 实现了 https://www.reactive-streams.org/[Reactive Streams] 规范。

Spring WebFlux 有两种风格：函数式和基于 annotation 的。
基于 annotation 的风格与 Spring MVC 模型非常接近，如下例所示：

include-code::MyRestController[]

WebFlux 是 Spring Framework 的一部分，详细信息可在其 {url-spring-framework-docs}/web/webflux.html[参考文档] 中找到。

"`WebFlux.fn`"，即函数式变体，将路由配置与请求的实际处理分离，如下例所示：

include-code::MyRoutingConfiguration[]

include-code::MyUserHandler[]

"`WebFlux.fn`" 是 Spring Framework 的一部分，详细信息可在其 {url-spring-framework-docs}/web/webflux-functional.html[参考文档] 中找到。

提示：你可以定义任意数量的 javadoc:org.springframework.web.reactive.function.server.RouterFunction[] beans 来模块化路由器的定义。
如果需要应用优先级，可以对 Bean 进行排序。

要开始使用，请将 `spring-boot-starter-webflux` 模块添加到你的应用程序中。

注意：在应用程序中同时添加 `spring-boot-starter-web` 和 `spring-boot-starter-webflux` 模块会导致 Spring Boot 自动配置 Spring MVC，而不是 WebFlux。
选择这种行为是因为许多 Spring 开发者将 `spring-boot-starter-webflux` 添加到他们的 Spring MVC 应用程序中以使用响应式 javadoc:org.springframework.web.reactive.function.client.WebClient[]。
你仍然可以通过将所选应用程序类型设置为 `SpringApplication.setWebApplicationType(WebApplicationType.REACTIVE)` 来强制执行你的选择。


[[web.reactive.webflux.auto-configuration]]
=== Spring WebFlux 自动配置

Spring Boot 为 Spring WebFlux 提供了 auto-configuration，这些配置适用于大多数应用程序。

auto-configuration 在 Spring 的默认值之上添加了以下功能：

* 为 javadoc:org.springframework.http.codec.HttpMessageReader[] 和 javadoc:org.springframework.http.codec.HttpMessageWriter[] 实例配置编解码器（描述 xref:web/reactive.adoc#web.reactive.webflux.httpcodecs[本文档稍后部分]）。
* 支持提供静态资源，包括对 WebJars 的支持（描述 xref:web/servlet.adoc#web.servlet.spring-mvc.static-content[本文档稍后部分]）。

如果你想保留 Spring Boot WebFlux 功能并添加额外的 {url-spring-framework-docs}/web/webflux/config.html[WebFlux 配置]，你可以添加自己的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类，类型为 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[]，但 *不要* 使用 javadoc:org.springframework.web.reactive.config.EnableWebFlux[format=annotation]。

如果你想对自动配置的 javadoc:org.springframework.http.server.reactive.HttpHandler[] 添加额外的自定义，你可以定义类型为 javadoc:org.springframework.boot.webflux.autoconfigure.WebHttpHandlerBuilderCustomizer[] 的 beans，并使用它们来修改 javadoc:org.springframework.web.server.adapter.WebHttpHandlerBuilder[]。

如果你想完全控制 Spring WebFlux，你可以添加自己的 javadoc:org.springframework.context.annotation.Configuration[format=annotation]，并使用 javadoc:org.springframework.web.reactive.config.EnableWebFlux[format=annotation] 进行注解。


[[web.reactive.webflux.conversion-service]]
=== Spring WebFlux 转换服务

如果你想自定义 Spring WebFlux 使用的 javadoc:org.springframework.core.convert.ConversionService[]，你可以提供一个 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[] bean，并带有 `addFormatters` 方法。

也可以使用 `spring.webflux.format.*` 配置属性来自定义转换。
当未配置时，使用以下默认值：

|===
|属性 |`DateTimeFormatter` |格式

|configprop:spring.webflux.format.date[]
|`ofLocalizedDate(FormatStyle.SHORT)`
|`java.util.Date` 和 javadoc:java.time.LocalDate[]

|configprop:spring.webflux.format.time[]
|`ofLocalizedTime(FormatStyle.SHORT)`
|java.time 的 javadoc:java.time.LocalTime[] 和 javadoc:java.time.OffsetTime[]

|configprop:spring.webflux.format.date-time[]
|`ofLocalizedDateTime(FormatStyle.SHORT)`
|java.time 的 javadoc:java.time.LocalDateTime[]、javadoc:java.time.OffsetDateTime[] 和 javadoc:java.time.ZonedDateTime[]
|===


[[web.reactive.webflux.httpcodecs]]
=== 使用 HttpMessageReaders 和 HttpMessageWriters 的 HTTP 编解码器

Spring WebFlux 使用 javadoc:org.springframework.http.codec.HttpMessageReader[] 和 javadoc:org.springframework.http.codec.HttpMessageWriter[] 接口来转换 HTTP 请求和响应。
它们通过 javadoc:org.springframework.http.codec.CodecConfigurer[] 进行配置，通过查看你的 classpath 中可用的库来提供合理的默认值。

Spring Boot 为编解码器提供了专用的配置属性 `+spring.http.codecs.*+`。
它还通过使用 javadoc:org.springframework.boot.http.codec.CodecCustomizer[] 实例来应用进一步的自定义。
例如，`+spring.jackson.*+` 配置键应用于 Jackson 编解码器。

如果你需要添加或自定义编解码器，你可以创建一个自定义的 javadoc:org.springframework.boot.http.codec.CodecCustomizer[] 组件，如下例所示：

include-code::MyCodecsConfiguration[]

你还可以利用 xref:features/json.adoc#features.json.jackson.custom-serializers-and-deserializers[Boot 的自定义 JSON 序列化器和反序列化器]。


[[web.reactive.webflux.static-content]]
=== 静态内容

默认情况下，Spring Boot 从 classpath 中名为 `/static`（或 `/public` 或 `/resources` 或 `/META-INF/resources`）的目录提供静态内容。
它使用来自 Spring WebFlux 的 javadoc:org.springframework.web.reactive.resource.ResourceWebHandler[]，以便你可以通过添加自己的 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[] 并覆盖 `addResourceHandlers` 方法来修改该行为。

默认情况下，资源映射到 `+/**+`，但你可以通过设置 configprop:spring.webflux.static-path-pattern[] 属性来调整。
例如，将所有资源重新定位到 `/resources/**` 可以通过以下方式实现：

[configprops,yaml]
----
spring:
  webflux:
    static-path-pattern: "/resources/**"
----

您还可以通过使用 `spring.web.resources.static-locations` 来自定义静态资源位置。
这样做会用目录位置列表替换默认值。
如果这样做，默认欢迎页面的检测将切换到您的自定义位置。
因此，如果在启动时您的任何位置中存在 `index.html`，它将成为应用程序的主页。

除了前面列出的 "`standard`" 静态资源位置外，https://www.webjars.org/[Webjars 内容] 是一个特例。
默认情况下，路径在 `+/webjars/**+` 中的任何资源，如果以 Webjars 格式打包，则会从 jar 文件中提供。
该路径可以通过 configprop:spring.webflux.webjars-path-pattern[] 属性进行自定义。

提示：Spring WebFlux 应用程序并不严格依赖 Servlet API，因此它们不能作为 war 文件部署，也不使用 `src/main/webapp` 目录。


[[web.reactive.webflux.welcome-page]]
=== 欢迎页面

Spring Boot 支持静态和模板化的欢迎页面。
它首先在配置的静态内容位置中查找 `index.html` 文件。
如果未找到，则查找 `index` 模板。
如果找到其中任何一个，它将自动用作应用程序的欢迎页面。

这仅作为应用程序定义的实际索引路由的回退。
顺序由 javadoc:org.springframework.web.reactive.HandlerMapping[] beans 的顺序定义，默认顺序如下：

[cols="1,1"]
|===
|`org.springframework.web.reactive.function.server.support.RouterFunctionMapping`
|使用 javadoc:org.springframework.web.reactive.function.server.RouterFunction[] beans 声明的端点

|`org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping`
|在 javadoc:org.springframework.stereotype.Controller[format=annotation] beans 中声明的端点

|`RouterFunctionMapping` 用于欢迎页面
|欢迎页面支持
|===


[[web.reactive.webflux.template-engines]]
=== 模板引擎

除了 REST Web 服务，您还可以使用 Spring WebFlux 来提供动态 HTML 内容。
Spring WebFlux 支持多种模板技术，包括 Thymeleaf、FreeMarker 和 Mustache。

Spring Boot 包含对以下模板引擎的 auto-configuration 支持：

* https://freemarker.apache.org/docs/[FreeMarker]
* https://www.thymeleaf.org[Thymeleaf]
* https://mustache.github.io/[Mustache]

注意：并非所有 FreeMarker 功能都受 WebFlux 支持。
有关更多详细信息，请检查每个属性的描述。

当您使用默认配置使用这些模板引擎之一时，您的模板会自动从 `src/main/resources/templates` 中获取。


[[web.reactive.webflux.error-handling]]
=== 错误处理

Spring Boot 提供了一个 javadoc:org.springframework.web.server.WebExceptionHandler[]，以合理的方式处理所有错误。
它在处理顺序中的位置紧接在 WebFlux 提供的处理器之前，这些处理器被视为最后。
对于机器客户端，它生成一个 JSON 响应，其中包含错误详情、HTTP 状态和异常消息。
对于浏览器客户端，有一个 "`whitelabel`" 错误处理器，以 HTML 格式呈现相同的数据。
您还可以提供自己的 HTML 模板来显示错误（请参阅 xref:web/reactive.adoc#web.reactive.webflux.error-handling.error-pages[下一节]）。

在直接自定义 Spring Boot 中的错误处理之前，您可以利用 Spring WebFlux 中的 {url-spring-framework-docs}/web/webflux/ann-rest-exceptions.html[RFC 9457 Problem Details] 支持。
Spring WebFlux 可以生成带有 `application/problem+json` 媒体类型的自定义错误消息，例如：

[source,json]
----
{
	"type": "https://example.org/problems/unknown-project",
	"title": "Unknown project",
	"status": 404,
	"detail": "No project found for id 'spring-unknown'",
	"instance": "/projects/spring-unknown"
}
----
可以通过将 configprop:spring.webflux.problemdetails.enabled[] 设置为 `true` 来启用此支持。

自定义此功能的第一步通常是使用现有机制，但替换或增强错误内容。为此，你可以添加一个类型为 javadoc:org.springframework.boot.webflux.error.ErrorAttributes[] 的 bean。

要更改错误处理行为，你可以实现 javadoc:org.springframework.boot.webflux.error.ErrorWebExceptionHandler[] 并注册该类型的 bean 定义。由于 javadoc:org.springframework.boot.webflux.error.ErrorWebExceptionHandler[] 是相当底层的，Spring Boot 还提供了一个方便的 javadoc:org.springframework.boot.webflux.autoconfigure.error.AbstractErrorWebExceptionHandler[]，让你以 WebFlux 函数式方式处理错误，如下例所示：

include-code::MyErrorWebExceptionHandler[]

为了更全面的了解，你也可以直接继承 javadoc:org.springframework.boot.webflux.autoconfigure.error.DefaultErrorWebExceptionHandler[] 并重写特定方法。

在某些情况下，在控制器级别处理的错误不会被 Web 观测或 xref:actuator/metrics.adoc#actuator.metrics.supported.spring-webflux[metrics infrastructure] 记录。应用程序可以通过 {url-spring-framework-docs}/integration/observability.html#observability.http-server.reactive[在观测上下文中设置已处理的异常] 来确保此类异常被观测记录。


[[web.reactive.webflux.error-handling.error-pages]]
==== 自定义错误页面

如果你想为给定的状态码显示自定义 HTML 错误页面，可以添加从 `error/*` 解析的视图，例如通过将文件添加到 `/error` 目录。错误页面可以是静态 HTML（即添加到任何静态资源目录下），也可以使用模板构建。文件名应为确切的状态码、状态码系列掩码或 `error`（用于默认情况，如果没有其他匹配项）。请注意，默认错误视图的路径是 `error/error`，而在 Spring MVC 中，默认错误视图是 `error`。

例如，要将 `404` 映射到静态 HTML 文件，你的目录结构应如下所示：

[source]
----
src/
 +- main/
     +- java/
     |   + <source code>
     +- resources/
         +- public/
             +- error/
             |   +- 404.html
             +- <other public assets>
----
要使用 Mustache 模板映射所有 `5xx` 错误，你的目录结构如下：

[source]
----
src/
 +- main/
     +- java/
     |   + <source code>
     +- resources/
         +- templates/
             +- error/
             |   +- 5xx.mustache
             +- <other templates>
----
[[web.reactive.webflux.web-filters]]
=== Web 过滤器

Spring WebFlux 提供了一个 javadoc:org.springframework.web.server.WebFilter[] 接口，可以实现该接口来过滤 HTTP 请求-响应交换。
javadoc:org.springframework.web.server.WebFilter[] 在应用上下文中找到的 beans 将自动用于过滤每个交换。

当过滤器的顺序很重要时，它们可以实现 javadoc:org.springframework.core.Ordered[] 或使用 javadoc:org.springframework.core.annotation.Order[format=annotation] 进行注解。
Spring Boot auto-configuration 可能会为你配置 Web 过滤器。
当它这样做时，将使用下表中显示的顺序：

|===
| Web 过滤器 | 顺序

| javadoc:org.springframework.security.web.server.WebFilterChainProxy[] (Spring Security)
| `-100`

| javadoc:org.springframework.boot.webflux.actuate.web.exchanges.HttpExchangesWebFilter[]
| `Ordered.LOWEST_PRECEDENCE - 10`
|===

[[web.reactive.webflux.api-versioning]]
=== API 版本管理

Spring WebFlux 支持 API 版本管理，可用于随时间演变 HTTP API。
相同的 `@Controller` 路径可以多次映射以支持 API 的不同版本。

更多详情请参阅 {url-spring-framework-docs}/web/webflux/controller/ann-requestmapping.html#webflux-ann-requestmapping-version[Spring 框架的参考文档]。

添加映射后，你还需要配置 Spring WebFlux，以便它能够使用请求中发送的任何版本信息。
通常，版本作为 HTTP 标头、查询参数、媒体类型参数或路径的一部分发送。

要配置 Spring WebFlux，你可以使用 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[] bean 并覆盖 `configureApiVersioning(...)` 方法，或者使用属性。

例如，以下将使用 `X-Version` HTTP 标头获取版本信息，并在未发送标头时默认为 `1.0.0`。

[configprops,yaml]
----
spring:
  webflux:
    apiversion:
      default: 1.0.0
      use:
        header: X-Version
----
NOTE: 如果你的设置需要多种策略，例如请求头和查询参数，请考虑通过重写 `configureApiVersioning` 方法以编程方式声明顺序。

为了更完全的控制，你还可以定义 javadoc:org.springframework.web.reactive.accept.ApiVersionResolver[]、javadoc:org.springframework.web.accept.ApiVersionParser[] 和 javadoc:org.springframework.web.reactive.accept.ApiVersionDeprecationHandler[] beans，它们将被注入到自动配置的 Spring WebFlux 配置中。

TIP: 客户端也支持 API 版本管理，同时支持 `WebClient` 和 `RestClient`。
详情请参见 xref:io/rest-client.adoc#io.rest-client.apiversioning[]。


[[web.reactive.reactive-server]]
== 嵌入式响应式服务器支持

Spring Boot 支持以下嵌入式响应式 Web 服务器：Reactor Netty、Tomcat 和 Jetty。
大多数开发者使用适当的 starter 来获取完全配置的实例。
默认情况下，嵌入式服务器在端口 8080 上监听 HTTP 请求。


[[web.reactive.reactive-server.customizing]]
=== 自定义响应式服务器

可以通过使用 Spring javadoc:org.springframework.core.env.Environment[] 属性来配置常见的响应式 Web 服务器设置。
通常，你会在 `application.properties` 或 `application.yaml` 文件中定义这些属性。

常见的服务器设置包括：

* 网络设置：传入 HTTP 请求的监听端口（`server.port`）、绑定的接口地址（`server.address`）等。
* 错误管理：错误页面的位置（configprop:spring.web.error.path[]）等。
* xref:how-to:webserver.adoc#howto.webserver.configure-ssl[SSL]
* xref:how-to:webserver.adoc#howto.webserver.enable-response-compression[HTTP 压缩]

Spring Boot 尽可能暴露通用设置，但这并不总是可能的。
对于这些情况，专用的命名空间（如 `server.netty.*`）提供了特定于服务器的自定义。

TIP: 请参见 javadoc:org.springframework.boot.web.server.autoconfigure.ServerProperties[] 类以获取完整列表。


[[web.reactive.reactive-server.customizing.programmatic]]
==== 编程式自定义

如果需要以编程方式配置响应式 Web 服务器，可以注册一个实现 javadoc:org.springframework.boot.web.server.WebServerFactoryCustomizer[] 接口的 Spring bean。
javadoc:org.springframework.boot.web.server.WebServerFactoryCustomizer[] 提供对 javadoc:org.springframework.boot.web.server.reactive.ConfigurableReactiveWebServerFactory[] 的访问，其中包含许多自定义设置方法。
以下示例展示了以编程方式设置端口：

include-code::MyWebServerFactoryCustomizer[]

javadoc:org.springframework.boot.jetty.reactive.JettyReactiveWebServerFactory[]、javadoc:org.springframework.boot.reactor.netty.NettyReactiveWebServerFactory[] 和 javadoc:org.springframework.boot.tomcat.reactive.TomcatReactiveWebServerFactory[] 是 javadoc:org.springframework.boot.web.server.reactive.ConfigurableReactiveWebServerFactory[] 的专用变体，分别具有 Jetty、Reactor Netty 和 Tomcat 的额外自定义设置方法。
以下示例展示了如何自定义 javadoc:org.springframework.boot.reactor.netty.NettyReactiveWebServerFactory[]，它提供了对 Reactor Netty 特定配置选项的访问：

include-code::MyNettyWebServerFactoryCustomizer[]


[[web.reactive.reactive-server.customizing.direct]]
==== 直接自定义 ConfigurableReactiveWebServerFactory

对于需要从 javadoc:org.springframework.boot.web.server.reactive.ReactiveWebServerFactory[] 扩展的更高级用例，你可以自己暴露一个此类类型的 bean。

许多配置选项都提供了设置方法。
如果需要做一些更特殊的事情，还提供了几个受保护的“`hooks`”方法。
详情请参见 javadoc:org.springframework.boot.web.server.reactive.ConfigurableReactiveWebServerFactory[] API 文档。

NOTE: 自动配置的自定义器仍然会应用于你的自定义工厂，因此请谨慎使用该选项。


[[web.reactive.reactive-server-resources-configuration]]
== 响应式服务器资源配置

当自动配置 Reactor Netty 或 Jetty 服务器时，Spring Boot 将创建特定的 beans，为服务器实例提供 HTTP 资源：javadoc:org.springframework.http.client.ReactorResourceFactory[] 或 javadoc:org.springframework.http.client.reactive.JettyResourceFactory[]。

默认情况下，这些资源也会与 Reactor Netty 和 Jetty 客户端共享以获得最佳性能，前提是：

* 服务器和客户端使用相同的技术
* 客户端实例是使用 Spring Boot 自动配置的 javadoc:org.springframework.web.reactive.function.client.WebClient$Builder[] bean 构建的

开发者可以通过提供自定义的 javadoc:org.springframework.http.client.ReactorResourceFactory[] 或 javadoc:org.springframework.http.client.reactive.JettyResourceFactory[] bean 来覆盖 Jetty 和 Reactor Netty 的资源配置——这将同时应用于客户端和服务器。

你可以在 xref:io/rest-client.adoc#io.rest-client.webclient.runtime[] 部分了解更多关于客户端资源配置的信息。
