[[howto.traditional-deployment]]
= 传统部署

Spring Boot 既支持传统部署，也支持更现代的部署形式。
本节回答关于传统部署的常见问题。



[[howto.traditional-deployment.war]]
== 创建可部署的 War 文件

WARNING: 由于 Spring WebFlux 并不严格依赖 Servlet API，且应用默认部署在嵌入式 Reactor Netty 服务器上，因此 WebFlux 应用不支持 War 部署。

生成可部署 war 文件的第一步是提供一个 javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[] 的子类，并重写其 `configure` 方法。
这样做利用了 Spring Framework 的 Servlet 3.0 支持，并允许你在 Servlet 容器启动应用时进行配置。
通常，你应该更新应用的主类以继承 javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[]，如下例所示：

include-code::MyApplication[]

下一步是更新构建配置，使项目生成 war 文件而非 jar 文件。
如果你使用 Maven 和 `spring-boot-starter-parent`（它会为你配置 Maven 的 war 插件），你只需修改 `pom.xml` 将打包方式改为 war，如下所示：

[source,xml]
----
<packaging>war</packaging>
----

如果你使用 Gradle，需要修改 `build.gradle` 以将 war 插件应用于项目，如下所示：

[source,gradle]
----
apply plugin: 'war'
----

过程的最后一步是确保嵌入式 Servlet 容器不会干扰部署 war 文件的 Servlet 容器。

对于 Maven，你需要将嵌入式 Servlet 容器依赖标记为 `provided`。
例如：

[source,xml]
----
<dependencies>
	<!-- ... -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-tomcat</artifactId>
		<scope>provided</scope>
	</dependency>
	<!-- ... -->
</dependencies>
----

如果你使用 Gradle，则需要将运行时依赖项移至 `providedRuntime` 配置中。
例如：

[source,gradle]
----
dependencies {
	// ...
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat-runtime'
	// ...
}
----

TIP: `providedRuntime` 优于 Gradle 的 `compileOnly` 配置。
除其他限制外，`compileOnly` 依赖项不在测试 classpath 上，因此任何基于 Web 的集成测试都会失败。

如果你使用 Spring Boot xref:build-tool-plugin:index.adoc[]，将嵌入式 Servlet 容器依赖标记为 provided 会生成一个可执行的 war 文件，其中 provided 依赖被打包在 `lib-provided` 目录中。
这意味着，除了可以部署到 Servlet 容器外，你还可以通过命令行使用 `java -jar` 运行你的应用程序。



[[howto.traditional-deployment.convert-existing-application]]
== 将现有应用程序转换为 Spring Boot

要将现有的非 Web Spring 应用程序转换为 Spring Boot 应用程序，请替换创建 javadoc:org.springframework.context.ApplicationContext[] 的代码，改为调用 javadoc:org.springframework.boot.SpringApplication[] 或 javadoc:org.springframework.boot.builder.SpringApplicationBuilder[]。
Spring MVC Web 应用程序通常可以先创建一个可部署的 war 应用程序，然后再迁移到可执行的 war 或 jar。

要创建可部署的 war，请扩展 javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[]（例如，在一个名为 `Application` 的类中）并添加 Spring Boot javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 注解，使用类似以下示例的代码：

include-code::MyApplication[tag=!main]

请记住，无论你在 `sources` 中放什么，都只是一个 Spring javadoc:org.springframework.context.ApplicationContext[]。
通常，任何已经能工作的东西在这里也应该能工作。
可能有一些 bean 你可以在以后移除，让 Spring Boot 提供自己的默认值，但在那之前应该能让某些东西工作。

静态资源可以移动到 classpath 根目录下的 `/public`（或 `/static`、`/resources`、`/META-INF/resources`）。
`messages.properties` 也是如此（Spring Boot 会自动在 classpath 根目录下检测到它）。

Spring javadoc:org.springframework.web.servlet.DispatcherServlet[] 和 Spring Security 的常规使用应该不需要进一步更改。
如果你的应用程序有其他特性（例如，使用其他 Servlet 或 Filter），你可能需要向 `Application` 上下文添加一些配置，通过替换 `web.xml` 中的那些元素，如下所示：

* 类型为 javadoc:jakarta.servlet.Servlet[] 或 javadoc:org.springframework.boot.web.servlet.ServletRegistrationBean[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation] 将该 bean 安装到容器中，就像它是 `web.xml` 中的 `<servlet/>` 和 `<servlet-mapping/>`。
* 类型为 javadoc:jakarta.servlet.Filter[] 或 javadoc:org.springframework.boot.web.servlet.FilterRegistrationBean[] 的 javadoc:org.springframework.context.annotation.Bean[format=annotation] 行为类似（作为 `<filter/>` 和 `<filter-mapping/>`）。
* XML 文件中的 javadoc:org.springframework.context.ApplicationContext[] 可以通过在 `+Application+` 中添加 javadoc:org.springframework.context.annotation.ImportResource[format=annotation] 来引入。
  或者，如果已经大量使用注解配置，可以用几行 javadoc:org.springframework.context.annotation.Bean[format=annotation] 定义来重新创建。

一旦 war 文件正常工作，你可以通过向 `Application` 添加一个 `main` 方法使其可执行，如下例所示：

include-code::MyApplication[tag=main]

[NOTE]
====
如果你打算以 war 或可执行应用程序的方式启动你的应用程序，你需要在一个方法中共享构建器的自定义配置，该方法既可用于 javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[] 回调，也可用于 `main` 方法，类似于以下类：

include-code::both/MyApplication[]
====

应用程序可能属于多个类别：

* 没有 `web.xml` 的 Servlet 3.0+ 应用程序。
* 有 `web.xml` 的应用程序。
* 有上下文层次结构的应用程序。
* 没有上下文层次结构的应用程序。

所有这些都应该可以转换，但每种可能需要稍微不同的技术。

Servlet 3.0+ 应用程序如果已经使用 Spring Servlet 3.0+ 初始化器支持类，可能很容易转换。
通常，现有 javadoc:org.springframework.web.WebApplicationInitializer[] 中的所有代码都可以移入 javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[]。
如果你的现有应用程序有多个 javadoc:org.springframework.context.ApplicationContext[]（例如，如果它使用 javadoc:org.springframework.web.servlet.support.AbstractDispatcherServletInitializer[]），那么你可能可以将所有上下文源合并到一个 javadoc:org.springframework.boot.SpringApplication[] 中。
你可能遇到的主要复杂情况是合并不起作用，你需要维护上下文层次结构。
有关示例，请参阅 xref:application.adoc#howto.application.context-hierarchy[关于构建层次结构的条目]。
包含 Web 特定功能的现有父上下文通常需要拆分，以便所有 javadoc:org.springframework.web.context.ServletContextAware[] 组件都在子上下文中。

尚未是 Spring 的应用程序可能可以转换为 Spring Boot 应用程序，前面提到的指导可能会有所帮助。
但是，你仍然可能遇到问题。
在这种情况下，我们建议 https://stackoverflow.com/questions/tagged/spring-boot[在 Stack Overflow 上提问，标签为 `spring-boot`]。



[[howto.traditional-deployment.weblogic]]
== 将 WAR 部署到 WebLogic

要将 Spring Boot 应用程序部署到 WebLogic，你必须确保你的 Servlet 初始化器 *直接* 实现 javadoc:org.springframework.web.WebApplicationInitializer[]（即使你扩展了已经实现它的基类）。

WebLogic 的典型初始化器应类似于以下示例：

include-code::MyApplication[]

如果你使用 Logback，你还需要告诉 WebLogic 优先使用打包的版本，而不是服务器预装的版本。
你可以通过添加一个包含以下内容的 `WEB-INF/weblogic.xml` 文件来实现：

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<wls:weblogic-web-app
	xmlns:wls="http://xmlns.oracle.com/weblogic/weblogic-web-app"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
		https://java.sun.com/xml/ns/javaee/ejb-jar_3_0.xsd
		http://xmlns.oracle.com/weblogic/weblogic-web-app
		https://xmlns.oracle.com/weblogic/weblogic-web-app/1.4/weblogic-web-app.xsd">
	<wls:container-descriptor>
		<wls:prefer-application-packages>
			<wls:package-name>org.slf4j</wls:package-name>
		</wls:prefer-application-packages>
	</wls:container-descriptor>
</wls:weblogic-web-app>
----
