= 测试 Spring Boot 应用程序

一个 Spring Boot 应用程序是一个 Spring javadoc:org.springframework.context.ApplicationContext[]，因此除了通常对普通 Spring 上下文进行的测试外，无需做任何特别的事情。

注意：默认情况下，只有当你使用 javadoc:org.springframework.boot.SpringApplication[] 创建上下文时，Spring Boot 的外部属性、日志记录和其他特性才会被安装到上下文中。

Spring Boot 提供了一个 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] annotation，当你需要 Spring Boot 特性时，它可以作为标准 `spring-test` javadoc:org.springframework.test.context.ContextConfiguration[format=annotation] annotation 的替代方案。
annotation 通过 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[creating the javadoc:org.springframework.context.ApplicationContext[] used in your tests through javadoc:org.springframework.boot.SpringApplication[]] 工作。
除了 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 之外，还提供了许多其他 annotation 用于 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[testing more specific slices] 应用程序。

提示：如果你使用 JUnit 4，不要忘记同时将 `@RunWith(SpringRunner.class)` 添加到你的测试中，否则 annotation 将被忽略。
如果你使用 JUnit 6，则无需添加等效的 `@ExtendWith(SpringExtension.class)`，因为 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 和其他 `@...Test` annotation 已经带有该注解。

默认情况下，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 不会启动服务器。
你可以使用 `webEnvironment` 的 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 属性来进一步细化测试的运行方式：

* `MOCK`（默认）：加载一个 Web javadoc:org.springframework.context.ApplicationContext[] 并提供模拟 Web 环境。
使用此 annotation 时不会启动嵌入式服务器。
如果你的 classpath 上没有可用的 Web 环境，此模式会透明地回退到创建常规的非 Web javadoc:org.springframework.context.ApplicationContext[]。
它可以与 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-mock-environment[`@AutoConfigureMockMvc`, javadoc:org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient[format=annotation]] 或 javadoc:org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient[format=annotation] 结合使用，用于基于模拟的 Web 应用程序测试。
* `RANDOM_PORT`：加载一个 javadoc:org.springframework.boot.web.server.context.WebServerApplicationContext[] 并提供真实的 Web 环境。
嵌入式服务器启动并监听随机端口。
* `DEFINED_PORT`：加载一个 javadoc:org.springframework.boot.web.server.context.WebServerApplicationContext[] 并提供真实的 Web 环境。
嵌入式服务器启动并监听定义的端口（来自你的 `application.properties`）或默认端口 `8080`。
* `NONE`：通过使用 javadoc:org.springframework.boot.SpringApplication[] 加载一个 javadoc:org.springframework.context.ApplicationContext[]，但不提供 _任何_ Web 环境（模拟或其他）。

注意：如果你的测试是 javadoc:org.springframework.transaction.annotation.Transactional[format=annotation]，默认情况下它会在每个测试方法结束时回滚事务。
然而，由于使用此配置与 `RANDOM_PORT` 或 `DEFINED_PORT` 会隐式提供真实的 servlet 环境，HTTP 客户端和服务器在单独的线程中运行，因此也在单独的事务中运行。
在这种情况下，服务器上发起的任何事务都不会回滚。

注意：如果你的应用程序为管理服务器使用不同的端口，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 与 `webEnvironment = WebEnvironment.RANDOM_PORT` 还会在单独的随机端口上启动管理服务器。



[[testing.spring-boot-applications.detecting-web-app-type]]
== 检测 Web 应用程序类型

如果 Spring MVC 可用，则会配置一个常规的基于 MVC 的应用程序上下文。
如果你只有 Spring WebFlux，我们将检测到它并改为配置一个基于 WebFlux 的应用程序上下文。

如果两者都存在，Spring MVC 优先。
如果你想在这种情况下测试响应式 Web 应用程序，必须设置 configprop:spring.main.web-application-type[] 属性：

include-code::MyWebFluxTests[]



[[testing.spring-boot-applications.detecting-configuration]]
== 检测测试配置

如果你熟悉 Spring 测试框架，你可能习惯于使用 `@ContextConfiguration(classes=...)` 来指定要加载哪个 Spring javadoc:org.springframework.context.annotation.Configuration[format=annotation]。
或者，你可能经常在测试中使用嵌套的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类。

在测试 Spring Boot 应用程序时，这通常不是必需的。
当你没有显式定义主配置时，Spring Boot 的 `@*Test` annotation 会自动搜索你的主配置。

搜索算法从包含测试的包向上工作，直到找到带有 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 或 javadoc:org.springframework.boot.SpringBootConfiguration[format=annotation] 注解的类。
只要你以合理的方式 xref:using/structuring-your-code.adoc[structured your code]，通常就能找到你的主配置。

[NOTE]
====
如果你使用 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[test annotation to test a more specific slice of your application]，应避免添加特定于 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.user-configuration-and-slicing[main method's application class] 某个区域的配置设置。

javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 的底层组件扫描配置定义了排除过滤器，用于确保切片按预期工作。
如果你在 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 注解的类上使用了显式的 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] 指令，请注意这些过滤器将被禁用。
如果你使用切片，应重新定义它们。
====

如果你想自定义主配置，可以使用嵌套的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 类。
与嵌套的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类（它将替代应用程序的主配置）不同，嵌套的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 类是在应用程序主配置之外额外使用的。

注意：Spring 的测试框架会在测试之间缓存应用程序上下文。
因此，只要你的测试共享相同的配置（无论它是如何发现的），加载上下文的潜在耗时过程只会发生一次。



[[testing.spring-boot-applications.using-main]]
== 使用测试配置的 main 方法

通常，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 发现的测试配置将是你的主 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]。
在大多数结构良好的应用程序中，此配置类还将包含用于启动应用程序的 `main` 方法。

例如，以下是一个典型 Spring Boot 应用程序的非常常见的代码模式：

include-code::typical/MyApplication[]

在上面的示例中，`main` 方法除了委托给 javadoc:org.springframework.boot.SpringApplication#run(java.lang.Class,java.lang.String...)[] 之外什么也不做。
然而，也可以有一个更复杂的 `main` 方法，在调用 javadoc:org.springframework.boot.SpringApplication#run(java.lang.Class,java.lang.String...)[] 之前应用自定义设置。

例如，以下是一个更改横幅模式并设置额外 profile 的应用程序：

include-code::custom/MyApplication[]

由于 `main` 方法中的自定义设置会影响生成的 javadoc:org.springframework.context.ApplicationContext[]，因此你可能也希望使用 `main` 方法来创建测试中使用的 javadoc:org.springframework.context.ApplicationContext[]。
默认情况下，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 不会调用你的 `main` 方法，而是直接使用该类本身来创建 javadoc:org.springframework.context.ApplicationContext[]。

如果你想更改此行为，可以将 `useMainMethod` 的 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 属性更改为 javadoc:org.springframework.boot.test.context.SpringBootTest$UseMainMethod#ALWAYS[] 或 javadoc:org.springframework.boot.test.context.SpringBootTest$UseMainMethod#WHEN_AVAILABLE[]。
当设置为 `ALWAYS` 时，如果找不到 `main` 方法，测试将失败。
当设置为 `WHEN_AVAILABLE` 时，如果 `main` 方法可用，则使用它；否则使用标准加载机制。

例如，以下测试将调用 `MyApplication` 的 `main` 方法来创建 javadoc:org.springframework.context.ApplicationContext[]。
如果 main 方法设置了额外的 profile，那么当 javadoc:org.springframework.context.ApplicationContext[] 启动时，这些设置将生效。

include-code::always/MyApplicationTests[]



[[testing.spring-boot-applications.excluding-configuration]]
== 排除测试配置

如果你的应用程序使用组件扫描（例如，如果你使用 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 或 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]），你可能会发现仅为特定测试创建的顶层配置类意外地被到处拾取。

正如我们 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[have seen earlier] 所述，javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 可以在测试的内部类上使用，以自定义主配置。
javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 也可以用在顶层类上。这样做表示该类不应被扫描拾取。
然后你可以在需要的地方显式导入该类，如下例所示：

include-code::MyTests[]

注意：如果你直接使用 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]（即不通过 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]），你需要向它注册 javadoc:org.springframework.boot.context.TypeExcludeFilter[]。
详情请参阅 javadoc:org.springframework.boot.context.TypeExcludeFilter[] API 文档。
NOTE: 导入的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 的处理时间早于内部类 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation]，并且导入的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 将在通过组件扫描发现的任何配置之前处理。
一般来说，这种顺序差异没有明显影响，但如果你依赖 bean 覆盖，则需要留意这一点。



[[testing.spring-boot-applications.using-application-arguments]]
== 使用应用程序参数

如果你的应用程序需要 xref:features/spring-application.adoc#features.spring-application.application-arguments[arguments]，你可以让 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 使用 `args` 属性注入它们。

include-code::MyApplicationArgumentTests[]



[[testing.spring-boot-applications.with-mock-environment]]
== 使用模拟环境进行测试

默认情况下，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 不会启动服务器，而是设置一个模拟环境来测试 Web endpoint。

使用 Spring MVC，我们可以通过 {url-spring-framework-docs}/testing/mockmvc.html[`MockMvc`] 查询 Web endpoint。
以下集成可用：

* 常规的 {url-spring-framework-docs}/testing/mockmvc/hamcrest.html[`MockMvc`]，它使用 Hamcrest。
* {url-spring-framework-docs}/testing/mockmvc/assertj.html[`MockMvcTester`]，它包装了 javadoc:org.springframework.test.web.servlet.MockMvc[] 并使用 AssertJ。
* {url-spring-framework-docs}/testing/resttestclient.html[`RestTestClient`]，其中 javadoc:org.springframework.test.web.servlet.MockMvc[] 作为服务器插入以处理请求。
* {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，其中 javadoc:org.springframework.test.web.servlet.MockMvc[] 作为服务器插入以处理请求。

以下示例展示了可用的集成：

include-code::MyMockMvcTests[]

TIP: 如果你只想关注 Web 层而不启动完整的 javadoc:org.springframework.context.ApplicationContext[]，请考虑 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.spring-mvc-tests[using javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] instead]。

对于 Spring WebFlux endpoint，你可以使用 {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，如下例所示：

include-code::MyMockWebTestClientTests[]

[TIP]
====
在模拟环境中测试通常比使用完整 servlet 容器运行更快。
然而，由于模拟发生在 Spring MVC 层，依赖于较低级别 servlet 容器行为的代码无法直接使用 MockMvc 进行测试。

例如，Spring Boot 的错误处理基于 servlet 容器提供的 "`error page`" 支持。
这意味着，虽然你可以测试 MVC 层按预期抛出和处理异常，但无法直接测试是否渲染了特定的 xref:web/servlet.adoc#web.servlet.spring-mvc.error-handling.error-pages[custom error page]。
如果你需要测试这些较低级别的问题，可以启动一个完全运行的服务器，如下一节所述。
====



[[testing.spring-boot-applications.with-running-server]]
== 使用运行中的服务器进行测试

如果你需要启动一个完全运行的服务器，我们建议使用随机端口。
如果你使用 `@SpringBootTest(webEnvironment=WebEnvironment.RANDOM_PORT)`，每次测试运行时都会随机选择一个可用端口。

javadoc:org.springframework.boot.test.web.server.LocalServerPort[format=annotation] annotation 可用于将 xref:how-to:webserver.adoc#howto.webserver.discover-port[inject the actual port used] 注入到你的测试中。

需要向启动的服务器发起 REST 调用的测试可以通过使用 javadoc:org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient[format=annotation] 注解测试类来自动装配 {url-spring-framework-docs}/testing/resttestclient.html[`RestTestClient`]。

配置的客户端将相对链接解析到运行中的服务器，并附带一个专用的 API 用于验证响应，如下例所示：

include-code::MyRandomPortRestTestClientTests[]

如果你更喜欢使用 AssertJ，可以从 javadoc:org.springframework.test.web.servlet.client.assertj.RestTestClientResponse[] 获得专用的断言，如下例所示：

include-code::MyRandomPortRestTestClientAssertJTests[]

如果你在 classpath 上有 `spring-webflux`，还可以通过使用 javadoc:org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient[format=annotation] 注解测试类来自动装配 {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]。

`WebTestClient` 提供了类似的 API，如下例所示：

include-code::MyRandomPortWebTestClientTests[]

TIP: javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 也可以与 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-mock-environment[mock environment] 一起使用，无需运行服务器，只需使用来自 `spring-boot-webflux-test` 的 javadoc:org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient[format=annotation] 注解你的测试类。

NOTE: 对于某些 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[sliced tests]，你可能需要使用 javadoc:org.springframework.boot.web.server.test.AutoConfigureWebServer[format=annotation] annotation 来自动配置嵌入式 Web 服务器。

`spring-boot-resttestclient` 模块还提供了 javadoc:org.springframework.boot.resttestclient.TestRestTemplate[] 功能：

include-code::MyRandomPortTestRestTemplateTests[]

要使用 `TestRestTemplate`，还需要依赖 `spring-boot-restclient`。
添加此依赖时需小心，因为它将为 `RestClient.Builder` 启用 auto-configuration。
如果你的主代码使用 `RestClient.Builder`，请声明 `spring-boot-restclient` 依赖，使其位于应用程序的主 classpath 上，而不仅仅在测试 classpath 上。



[[testing.spring-boot-applications.customizing-rest-test-client]]
== 自定义 RestTestClient

要自定义 javadoc:org.springframework.test.web.servlet.client.RestTestClient[] bean，请配置一个 javadoc:org.springframework.boot.resttestclient.autoconfigure.RestTestClientBuilderCustomizer[] bean。
任何此类 bean 都会与用于创建 javadoc:org.springframework.test.web.servlet.client.RestTestClient[] 的 javadoc:org.springframework.test.web.servlet.client.RestTestClient$Builder[] 一起被调用。



[[testing.spring-boot-applications.customizing-web-test-client]]
== 自定义 WebTestClient

要自定义 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] bean，请配置一个 javadoc:org.springframework.boot.webtestclient.autoconfigure.WebTestClientBuilderCustomizer[] bean。
任何此类 bean 都会与用于创建 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 的 javadoc:org.springframework.test.web.reactive.server.WebTestClient$Builder[] 一起被调用。



[[testing.spring-boot-applications.jmx]]
== 使用 JMX

由于测试上下文框架会缓存上下文，JMX 默认被禁用，以防止相同的组件注册到同一域。
如果此类测试需要访问 javadoc:javax.management.MBeanServer[]，请考虑也将其标记为脏：

include-code::MyJmxTests[]



[[testing.spring-boot-applications.observations]]
== 使用观测

如果你使用来自 `spring-boot-micrometer-tracing-test` 的 javadoc:org.springframework.boot.micrometer.tracing.test.autoconfigure.AutoConfigureTracing[format=annotation] 或来自 `spring-boot-micrometer-metrics-test` 的 javadoc:org.springframework.boot.micrometer.metrics.test.autoconfigure.AutoConfigureMetrics[format=annotation] 注解 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[a sliced test]，它会自动配置一个 javadoc:io.micrometer.observation.ObservationRegistry[]。



[[testing.spring-boot-applications.metrics]]
== 使用指标

无论你的 classpath 如何，使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 时，除内存支持外，仪表注册表不会自动配置。

如果你需要将指标导出到不同的后端作为集成测试的一部分，请使用 javadoc:org.springframework.boot.micrometer.metrics.test.autoconfigure.AutoConfigureMetrics[format=annotation] 注解它。

如果你使用 javadoc:org.springframework.boot.micrometer.metrics.test.autoconfigure.AutoConfigureMetrics[format=annotation] 注解 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[a sliced test]，它会自动配置一个内存中的 javadoc:io.micrometer.core.instrument.MeterRegistry[]。
在切片测试中，使用 javadoc:org.springframework.boot.micrometer.metrics.test.autoconfigure.AutoConfigureMetrics[format=annotation] annotation 不支持数据导出。



[[testing.spring-boot-applications.tracing]]
== 使用追踪

无论你的 classpath 如何，使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 时，报告数据的追踪组件不会自动配置。

如果你需要这些组件作为集成测试的一部分，请使用 javadoc:org.springframework.boot.micrometer.tracing.test.autoconfigure.AutoConfigureTracing[format=annotation] 注解测试。

如果你创建了自己的报告组件（例如自定义的 javadoc:io.opentelemetry.sdk.trace.export.SpanExporter[] 或 `brave.handler.SpanHandler`），并且不希望它们在测试中激活，可以使用 javadoc:org.springframework.boot.micrometer.tracing.autoconfigure.ConditionalOnEnabledTracingExport[format=annotation] annotation 来禁用它们。

如果你使用 javadoc:org.springframework.boot.micrometer.tracing.test.autoconfigure.AutoConfigureTracing[format=annotation] 注解 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[a sliced test]，它会自动配置一个无操作的 javadoc:io.micrometer.tracing.Tracer[]。
在切片测试中，使用 javadoc:org.springframework.boot.micrometer.tracing.test.autoconfigure.AutoConfigureTracing[format=annotation] annotation 不支持数据导出。



[[testing.spring-boot-applications.mocking-beans]]
== 模拟和监视 Bean

运行测试时，有时需要模拟应用程序上下文中的某些组件。
例如，你可能有一个对某些远程服务的封装，该服务在开发期间不可用。
当你想要模拟在真实环境中难以触发的故障时，模拟也很有用。

Spring 框架包含一个 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] annotation，可用于在你的 javadoc:org.springframework.context.ApplicationContext[] 中为 bean 定义 Mockito 模拟。
此外，javadoc:org.springframework.test.context.bean.override.mockito.MockitoSpyBean[format=annotation] 可用于定义 Mockito 间谍。\n在 {url-spring-framework-docs}/testing/annotations/integration-spring/annotation-mockitobean.html[Spring 框架文档] 中了解有关这些功能的更多信息。



[[testing.spring-boot-applications.autoconfigured-tests]]
== 自动配置的测试

Spring Boot 的 auto-configuration 系统对应用程序运行良好，但有时对测试来说可能有点过多。
通常，只加载测试应用程序 "`slice`" 所需的配置部分会有所帮助。
例如，你可能想测试 Spring MVC 控制器是否正确映射 URL，并且不希望在这些测试中涉及数据库调用；或者你可能想测试 JPA 实体，而在运行这些测试时对 Web 层不感兴趣。

当与 `spring-boot-test-autoconfigure` 结合使用时，Spring Boot 的 xref:reference:testing/test-modules.adoc[test modules] 包含许多 annotation，可用于自动配置此类“`slices`”。
每个的工作方式类似，提供一个 `@...Test` annotation 来加载 javadoc:org.springframework.context.ApplicationContext[] 以及一个或多个 `@AutoConfigure...` annotation，可用于自定义 auto-configuration 设置。

注意：每个切片将组件扫描限制为适当的组件，并加载非常有限的 auto-configuration 类集合。
如果需要排除其中一个，大多数 `@...Test` annotation 提供一个 `excludeAutoConfiguration` 属性。
或者，你可以使用 `@ImportAutoConfiguration#exclude`。

注意：在一个测试中通过使用多个 `@...Test` annotation 来包含多个“`slices`”是不支持的。
如果需要多个“`slices`”，请选择一个 `@...Test` annotation 并手动包含其他“`slices`”的 `@AutoConfigure...` annotation。

提示：也可以将 `@AutoConfigure...` annotation 与标准的 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] annotation 一起使用。
如果你对“`slicing`”你的应用程序不感兴趣，但想要一些自动配置的测试 bean，则可以使用这种组合。



[[testing.spring-boot-applications.json-tests]]
== 自动配置的 JSON 测试

要测试对象 JSON 序列化和反序列化是否按预期工作，可以使用 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] annotation，它来自 `spring-boot-test-autoconfigure` 模块。
javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 自动配置可用的受支持 JSON 映射器，可以是以下库之一：

* Jackson javadoc:tools.jackson.databind.json.JsonMapper[]，任何 javadoc:org.springframework.boot.jackson.JacksonComponent[format=annotation] bean 和任何 Jackson javadoc:tools.jackson.databind.JacksonModule[]
* Jackson 2（已弃用）javadoc:com.fasterxml.jackson.databind.ObjectMapper[]，任何 javadoc:org.springframework.boot.jackson2.JsonComponent[format=annotation] bean 和任何 Jackson javadoc:com.fasterxml.jackson.databind.Module[]
* `Gson`
* `Jsonb`

提示：由 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 启用的 auto-configuration 列表可以 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]。

如果需要配置 auto-configuration 的元素，可以使用 javadoc:org.springframework.boot.test.autoconfigure.json.AutoConfigureJsonTesters[format=annotation] annotation。

Spring Boot 包含基于 AssertJ 的辅助程序，可与 JSONAssert 和 JsonPath 库一起使用，以检查 JSON 是否符合预期。
javadoc:org.springframework.boot.test.json.JacksonTester[]、javadoc:org.springframework.boot.test.json.GsonTester[]、javadoc:org.springframework.boot.test.json.JsonbTester[] 和 javadoc:org.springframework.boot.test.json.BasicJsonTester[] 类可分别用于 Jackson、Gson、Jsonb 和字符串。
当使用 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 时，测试类上的任何辅助字段都可以 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation]。
以下示例显示了一个用于 Jackson 的测试类：

include-code::MyJsonTests[]

注意：JSON 辅助类也可以直接在标准单元测试中使用。
为此，如果你不使用 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation]，请在 javadoc:org.junit.jupiter.api.BeforeEach[format=annotation] 方法中调用辅助类的 `initFields` 方法。

如果你使用 Spring Boot 的基于 AssertJ 的辅助程序来断言给定 JSON 路径上的数值，则可能无法根据类型使用 `isEqualTo`。
相反，你可以使用 AssertJ 的 `satisfies` 来断言该值匹配给定条件。
例如，以下示例断言实际数值是一个浮点值，接近 `0.15`，偏移量为 `0.01`。

include-code::MyJsonAssertJTests[tag=*]



[[testing.spring-boot-applications.spring-mvc-tests]]
== 自动配置的 Spring MVC 测试

要测试 Spring MVC 控制器是否按预期工作，请使用 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] annotation，它来自 `spring-boot-webmvc-test` 模块。
javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 自动配置 Spring MVC 基础设施，并将扫描的 bean 限制为 javadoc:org.springframework.stereotype.Controller[format=annotation]、javadoc:org.springframework.web.bind.annotation.ControllerAdvice[format=annotation]、javadoc:org.springframework.boot.jackson.JacksonComponent[format=annotation]、javadoc:org.springframework.boot.jackson2.JsonComponent[format=annotation]（已弃用）、javadoc:org.springframework.core.convert.converter.Converter[]、javadoc:org.springframework.core.convert.converter.GenericConverter[]、javadoc:jakarta.servlet.Filter[]、javadoc:org.springframework.web.servlet.HandlerInterceptor[]、javadoc:org.springframework.web.servlet.config.annotation.WebMvcConfigurer[]、javadoc:org.springframework.boot.webmvc.autoconfigure.WebMvcRegistrations[] 和 javadoc:org.springframework.web.method.support.HandlerMethodArgumentResolver[]。
当使用 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] annotation 时，常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean 不会被扫描。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

提示：由 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 启用的 auto-configuration 设置列表可以 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]。

提示：如果需要注册额外的组件，例如 javadoc:tools.jackson.databind.JacksonModule[]，可以通过在测试中使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 来导入额外的配置类。

通常，javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 限于单个控制器，并与 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] 结合使用，为所需的协作者提供模拟实现。

javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 还自动配置 javadoc:org.springframework.test.web.servlet.MockMvc[]。
Mock MVC 提供了一种强大的方式，无需启动完整的 HTTP 服务器即可快速测试 MVC 控制器。
如果 AssertJ 可用，则 javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[] 提供的 AssertJ 支持也会自动配置。
如果你希望在测试中使用 javadoc:org.springframework.test.web.servlet.client.RestTestClient[]，请使用 javadoc:org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient[format=annotation] 注解你的测试类。
然后，使用 Mock MVC 基础设施的 `RestTestClient` 将被自动配置。

提示：你也可以在非 `@WebMvcTest`（例如 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation]）中通过使用 javadoc:org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc[format=annotation] 注解来自动配置 javadoc:org.springframework.test.web.servlet.MockMvc[] 和 javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[]。
以下示例使用 javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[]：

include-code::MyControllerTests[]

提示：如果需要配置 auto-configuration 的元素（例如，何时应用 servlet 过滤器），可以在 javadoc:org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc[format=annotation] annotation 中使用属性。

如果你使用 HtmlUnit 和 Selenium，auto-configuration 还提供 HtmlUnit javadoc:org.springframework.web.reactive.function.client.WebClient[] bean 和/或 Selenium javadoc:org.openqa.selenium.WebDriver[] bean。
以下示例使用 HtmlUnit：

include-code::MyHtmlUnitTests[]

注意：默认情况下，Spring Boot 将 javadoc:org.openqa.selenium.WebDriver[] bean 放在一个特殊的“`scope`”中，以确保驱动程序在每个测试后退出，并注入一个新实例。
如果你不希望这样，可以将 `@Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)` 添加到你的 javadoc:org.openqa.selenium.WebDriver[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 定义中。

WARNING：由 Spring Boot 创建的 `webDriver` 作用域将替换任何用户定义的相同名称的作用域。
如果你定义了自己的 `webDriver` 作用域，你可能会发现当你使用 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 时它停止工作。

如果你在 classpath 上使用了 Spring Security，javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 也会扫描 javadoc:org.springframework.security.config.annotation.web.WebSecurityConfigurer[] bean。
不必完全禁用此类测试的安全性，你可以使用 Spring Security 的测试支持。
有关如何使用 Spring Security 的 javadoc:org.springframework.test.web.servlet.MockMvc[] 支持的更多详细信息，请参见此 xref:how-to:testing.adoc#howto.testing.with-spring-security[] “`How-to Guides`”部分。

提示：有时编写 Spring MVC 测试是不够的；Spring Boot 可以帮助你运行 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-running-server[full end-to-end tests with an actual server]。



[[testing.spring-boot-applications.spring-webflux-tests]]
== 自动配置的 Spring WebFlux 测试

要测试 {url-spring-framework-docs}/web-reactive.html[Spring WebFlux] 控制器是否按预期工作，可以使用 javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] annotation，它来自 `spring-boot-webflux-test` 模块。
javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 自动配置 Spring WebFlux 基础设施，并将扫描的 bean 限制为 javadoc:org.springframework.stereotype.Controller[format=annotation]、javadoc:org.springframework.web.bind.annotation.ControllerAdvice[format=annotation]、javadoc:org.springframework.boot.jackson.JacksonComponent[format=annotation]、javadoc:org.springframework.boot.jackson2.JsonComponent[format=annotation]（已弃用）、javadoc:org.springframework.core.convert.converter.Converter[]、javadoc:org.springframework.core.convert.converter.GenericConverter[] 和 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[]。
当使用 javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] annotation 时，常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean 不会被扫描。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

提示：可以通过 xref:appendix:test-auto-configuration/index.adoc[found in the appendix] 查看 javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 启用了哪些 auto-configuration。

提示：如果需要注册额外的组件（例如 javadoc:tools.jackson.databind.JacksonModule[]），可以在测试中使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 导入额外的配置类。

通常，javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 仅限于单个控制器，并与 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] annotation 结合使用，为所需的协作者提供模拟实现。

javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 还会自动配置 {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，它提供了一种强大的方式来快速测试 WebFlux 控制器，而无需启动完整的 HTTP 服务器。

提示：你也可以在非 `@WebFluxTest`（例如 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation]）中通过使用 javadoc:org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient[format=annotation] 注解来自动配置 javadoc:org.springframework.test.web.reactive.server.WebTestClient[]。

以下示例展示了一个同时使用 javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 和 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 的类：

include-code::MyControllerTests[]

提示：此设置仅受 WebFlux 应用程序支持，因为目前在被模拟的 Web 应用程序中使用 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 仅适用于 WebFlux。

注意：javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 无法检测通过函数式 Web 框架注册的路由。
要在上下文中测试 javadoc:org.springframework.web.reactive.function.server.RouterFunction[] bean，请考虑通过使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 或使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 自行导入 javadoc:org.springframework.web.reactive.function.server.RouterFunction[]。

注意：javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 无法检测注册为 javadoc:org.springframework.context.annotation.Bean[format=annotation] 类型 javadoc:org.springframework.security.web.server.SecurityWebFilterChain[] 的自定义安全配置。
要将其包含在测试中，你需要通过使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 或使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 导入注册 bean 的配置。

提示：有时编写 Spring WebFlux 测试是不够的；Spring Boot 可以帮助你运行 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-running-server[full end-to-end tests with an actual server]。


[[testing.spring-boot-applications.spring-graphql-tests]]
== 自动配置的 Spring GraphQL 测试

Spring GraphQL 提供了一个专用的测试支持模块；你需要将其添加到项目中：

.Maven
[source,xml]
----
<dependencies>
	<dependency>
		<groupId>org.springframework.graphql</groupId>
		<artifactId>spring-graphql-test</artifactId>
		<scope>test</scope>
	</dependency>
	<!-- Unless already present in the compile scope -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-webflux</artifactId>
		<scope>test</scope>
	</dependency>
</dependencies>
----

.Gradle
[source,gradle]
----
dependencies {
	testImplementation("org.springframework.graphql:spring-graphql-test")
	// Unless already present in the implementation configuration
	testImplementation("org.springframework.boot:spring-boot-starter-webflux")
}
----

该测试模块提供了 {url-spring-graphql-docs}/testing.html#testing.graphqltester[GraphQlTester]。
测试器在测试中大量使用，因此请务必熟悉其用法。
有 javadoc:org.springframework.graphql.test.tester.GraphQlTester[] 种变体，Spring Boot 会根据测试类型自动配置它们：

* javadoc:org.springframework.graphql.test.tester.ExecutionGraphQlServiceTester[] 在服务端执行测试，无需客户端或传输层
* javadoc:org.springframework.graphql.test.tester.HttpGraphQlTester[] 使用连接到服务器的客户端执行测试，可以带或不带实时服务器

Spring Boot 帮助您使用 {url-spring-graphql-docs}/controllers.html[Spring GraphQL 控制器] 和来自 javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation] 模块的 annotation 进行测试。
`spring-boot-graphql-test` 自动配置 Spring GraphQL 基础设施，不涉及任何传输层或服务器。
这将扫描的 bean 限制为 javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation]、javadoc:org.springframework.stereotype.Controller[format=annotation]、javadoc:org.springframework.web.bind.annotation.ControllerAdvice[format=annotation]、javadoc:org.springframework.graphql.execution.RuntimeWiringConfigurer[]、javadoc:org.springframework.boot.jackson.JacksonComponent[]（已弃用）、javadoc:org.springframework.boot.jackson2.JsonComponent[format=annotation]、javadoc:org.springframework.core.convert.converter.Converter[]、javadoc:org.springframework.core.convert.converter.GenericConverter[]、javadoc:org.springframework.graphql.execution.DataFetcherExceptionResolver[] 和 javadoc:graphql.execution.instrumentation.Instrumentation[]。
使用 javadoc:org.springframework.boot.graphql.autoconfigure.GraphQlSourceBuilderCustomizer[] bean 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] annotation。
javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] bean。

提示：javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] 启用的 auto-configuration 列表可 javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation]。

通常，xref:appendix:test-auto-configuration/index.adoc[found in the appendix] 限于一组控制器，并与 javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation] annotation 结合使用，为所需的协作者提供模拟实现。

javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation]

include-code::GreetingControllerTests[] 测试是完整的集成测试，涉及整个应用程序。
可以通过使用来自 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 模块的 javadoc:org.springframework.graphql.test.tester.HttpGraphQlTester[] 注解测试类来添加 javadoc:org.springframework.boot.graphql.test.autoconfigure.tester.AutoConfigureHttpGraphQlTester[format=annotation] bean：

`spring-boot-graphql-test`

include-code::GraphQlIntegrationTests[] bean 使用集成测试的相关传输层。
当使用随机或指定端口时，测试器会针对实时服务器进行配置。
要将测试器绑定到 javadoc:org.springframework.graphql.test.tester.HttpGraphQlTester[]，请确保使用 `MockMvc` 注解测试类。


javadoc:org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc[format=annotation]
== 自动配置的 Data Cassandra 测试

您可以使用来自 [[testing.spring-boot-applications.autoconfigured-spring-data-cassandra]] 模块的 javadoc:org.springframework.boot.data.cassandra.test.autoconfigure.DataCassandraTest[format=annotation] 来测试 Data Cassandra 应用程序。
默认情况下，它会配置一个 `spring-boot-data-cassandra-test`，扫描 javadoc:org.springframework.data.cassandra.core.CassandraTemplate[] 类，并配置 Spring Data Cassandra 仓库。
使用 javadoc:org.springframework.data.cassandra.core.mapping.Table[format=annotation] bean 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] annotation。
javadoc:org.springframework.boot.data.cassandra.test.autoconfigure.DataCassandraTest[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] bean。
（有关将 Cassandra 与 Spring Boot 一起使用的更多信息，请参见 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation]。）

提示：xref:data/nosql.adoc#data.nosql.cassandra[] 启用的 auto-configuration 设置列表可 javadoc:org.springframework.boot.data.cassandra.test.autoconfigure.DataCassandraTest[format=annotation]。

以下示例展示了在 Spring Boot 中使用 Cassandra 测试的典型设置：

xref:appendix:test-auto-configuration/index.adoc[found in the appendix]


include-code::MyDataCassandraTests[]
== 自动配置的 Data Couchbase 测试

您可以使用来自 [[testing.spring-boot-applications.autoconfigured-spring-data-couchbase]] 模块的 javadoc:org.springframework.boot.data.couchbase.test.autoconfigure.DataCouchbaseTest[format=annotation] 来测试 Data Couchbase 应用程序。
默认情况下，它会配置一个 `spring-boot-data-couchbase-test` 或 javadoc:org.springframework.data.couchbase.core.CouchbaseTemplate[]，扫描 javadoc:org.springframework.data.couchbase.core.ReactiveCouchbaseTemplate[] 类，并配置 Spring Data Couchbase 仓库。
使用 javadoc:org.springframework.data.couchbase.core.mapping.Document[format=annotation] bean 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] annotation。
javadoc:org.springframework.boot.data.couchbase.test.autoconfigure.DataCouchbaseTest[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] bean。
（有关将 Couchbase 与 Spring Boot 一起使用的更多信息，请参见本章前面的 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation]。）

提示：xref:data/nosql.adoc#data.nosql.couchbase[] 启用的 auto-configuration 设置列表可 javadoc:org.springframework.boot.data.couchbase.test.autoconfigure.DataCouchbaseTest[format=annotation]。

以下示例展示了在 Spring Boot 中使用 Couchbase 测试的典型设置：

xref:appendix:test-auto-configuration/index.adoc[found in the appendix]


include-code::MyDataCouchbaseTests[]
== 自动配置的 Data Elasticsearch 测试

您可以使用来自 [[testing.spring-boot-applications.autoconfigured-spring-data-elasticsearch]] 模块的 javadoc:org.springframework.boot.data.elasticsearch.test.autoconfigure.DataElasticsearchTest[format=annotation] 来测试 Data Elasticsearch 应用程序。
默认情况下，它会配置一个 `spring-boot-data-elasticsearch-test`，扫描 javadoc:org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate[] 类，并配置 Spring Data Elasticsearch 仓库。
使用 javadoc:org.springframework.data.elasticsearch.annotations.Document[format=annotation] bean 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] annotation。
javadoc:org.springframework.boot.data.elasticsearch.test.autoconfigure.DataElasticsearchTest[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] bean。
（有关将 Elasticsearch 与 Spring Boot 一起使用的更多信息，请参见本章前面的 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation]。）

提示：xref:data/nosql.adoc#data.nosql.elasticsearch[] 启用的 auto-configuration 设置列表可 javadoc:org.springframework.boot.data.elasticsearch.test.autoconfigure.DataElasticsearchTest[format=annotation]。

以下示例展示了在 Spring Boot 中使用 Elasticsearch 测试的典型设置：

xref:appendix:test-auto-configuration/index.adoc[found in the appendix]


include-code::MyDataElasticsearchTests[]
== 自动配置的 Data JPA 测试

您可以使用来自 [[testing.spring-boot-applications.autoconfigured-spring-data-jpa]] 模块的 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] annotation 来测试 Data JPA 应用程序。
默认情况下，它会扫描 `spring-boot-data-jpa-test` 类并配置 Spring Data JPA 仓库。
如果 classpath 上有可用的嵌入式数据库，它也会配置一个。
默认情况下，通过将 javadoc:jakarta.persistence.Entity[format=annotation] 属性设置为 `spring.jpa.show-sql` 来记录 SQL 查询。
这可以通过 annotation 的 `true` 属性禁用。

使用 `showSql` bean 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] annotation。
javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] bean。

提示：javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] 启用的 auto-configuration 设置列表可 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation]。

默认情况下，Data JPA 测试是事务性的，并在每个测试结束时回滚。
有关更多详细信息，请参见 Spring 框架参考文档中的 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[相关章节]。
如果这不是您想要的，您可以按如下方式禁用测试或整个类的事务管理：

{url-spring-framework-docs}

Data JPA 测试还可以注入一个 include-code::MyNonTransactionalTests[] bean，它提供了标准 JPA javadoc:org.springframework.boot.jpa.test.autoconfigure.TestEntityManager[] 的替代方案，专门为测试设计。

提示：通过添加 javadoc:jakarta.persistence.EntityManager[]，javadoc:org.springframework.boot.jpa.test.autoconfigure.TestEntityManager[] 也可以自动配置到任何基于 Spring 的测试类中。
这样做时，请确保您的测试在事务中运行，例如通过在测试类或方法上添加 javadoc:org.springframework.boot.jpa.test.autoconfigure.AutoConfigureTestEntityManager[format=annotation]。

如果您需要，也可以使用 javadoc:org.springframework.transaction.annotation.Transactional[format=annotation]。
以下示例展示了 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] annotation 的使用：

include-code::withoutdb/MyRepositoryTests[]

内存嵌入式数据库通常非常适合测试，因为它们速度快且无需任何安装。
但是，如果你更倾向于针对真实数据库运行测试，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] annotation，如下例所示：

include-code::withdb/MyRepositoryTests[]



[[testing.spring-boot-applications.autoconfigured-jdbc]]
== 自动配置的 JDBC 测试

javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] 来自 `spring-boot-jdbc-test` 模块，类似于 javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation]，但适用于仅需要 javadoc:javax.sql.DataSource[] 且不使用 Spring Data JDBC 的测试。
默认情况下，它会配置一个内存嵌入式数据库和一个 javadoc:org.springframework.jdbc.core.JdbcTemplate[]。
使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] annotation 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

提示：javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] 启用的 auto-configuration 列表可以 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]。

默认情况下，JDBC 测试是事务性的，并在每个测试结束时回滚。
更多详情请参阅 Spring 框架参考文档中的 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[相关章节]。
如果这不是你想要的，你可以禁用测试或整个类的事务管理，如下所示：

include-code::MyTransactionalTests[]

如果你希望测试针对真实数据库运行，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] annotation，方式与 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 相同。
（参见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-spring-data-jpa[]。）



[[testing.spring-boot-applications.autoconfigured-spring-data-jdbc]]
== 自动配置的 Data JDBC 测试

javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation] 来自 `spring-boot-data-jdbc-test` 模块，类似于 javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation]，但适用于使用 Spring Data JDBC 仓库的测试。
默认情况下，它会配置一个内存嵌入式数据库、一个 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 和 Spring Data JDBC 仓库。
使用 javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation] annotation 时，仅扫描 javadoc:org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration[] 子类，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

提示：javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation] 启用的 auto-configuration 列表可以 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]。

默认情况下，Data JDBC 测试是事务性的，并在每个测试结束时回滚。
更多详情请参阅 Spring 框架参考文档中的 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[相关章节]。
如果这不是你想要的，你可以禁用测试或整个测试类的事务管理，如 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-jdbc[shown in the JDBC example] 所示。

如果你希望测试针对真实数据库运行，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] annotation，方式与 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 相同。
（参见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-spring-data-jpa[]。）



[[testing.spring-boot-applications.autoconfigured-spring-data-r2dbc]]
== 自动配置的 Data R2DBC 测试

javadoc:org.springframework.boot.data.r2dbc.test.autoconfigure.DataR2dbcTest[format=annotation] 来自 `spring-boot-data-r2dbc-test` 模块，类似于 javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation]，但适用于使用 Spring Data R2DBC 仓库的测试。
默认情况下，它会配置一个内存嵌入式数据库、一个 javadoc:org.springframework.data.r2dbc.core.R2dbcEntityTemplate[] 和 Spring Data R2DBC 仓库。
使用 javadoc:org.springframework.boot.data.r2dbc.test.autoconfigure.DataR2dbcTest[format=annotation] annotation 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

提示：javadoc:org.springframework.boot.data.r2dbc.test.autoconfigure.DataR2dbcTest[format=annotation] 启用的 auto-configuration 列表可以 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]。

默认情况下，Data R2DBC 测试不是事务性的。

如果你希望测试针对真实数据库运行，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] annotation，方式与 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 相同。
（参见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-spring-data-jpa[]。）



[[testing.spring-boot-applications.autoconfigured-jooq]]
== 自动配置的 jOOQ 测试

你可以使用来自 `spring-boot-jooq-test` 的 javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation]，方式与 javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] 类似，但用于 jOOQ 相关的测试。
由于 jOOQ 严重依赖于与数据库模式对应的 Java 模式，因此使用了现有的 javadoc:javax.sql.DataSource[]。
如果你想将其替换为内存数据库，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] 覆盖这些设置。
（有关在 Spring Boot 中使用 jOOQ 的更多信息，请参见 xref:data/sql.adoc#data.sql.jooq[]。）
使用 javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation] annotation 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

提示：javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation] 启用的 auto-configuration 列表可以 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]。

javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation] 配置一个 javadoc:org.jooq.DSLContext[]。
以下示例展示了 javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation] annotation 的使用：

include-code::MyJooqTests[]

默认情况下，jOOQ 测试是事务性的，并在每个测试结束时回滚。
如果这不是你想要的，你可以禁用测试或整个测试类的事务管理，如 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-jdbc[shown in the JDBC example] 所示。



[[testing.spring-boot-applications.autoconfigured-spring-data-mongodb]]
== 自动配置的 Data MongoDB 测试

你可以使用来自 `spring-boot-data-mongodb-test` 模块的 javadoc:org.springframework.boot.data.mongodb.test.autoconfigure.DataMongoTest[format=annotation] 来测试 MongoDB 应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.data.mongodb.core.MongoTemplate[]，扫描 javadoc:org.springframework.data.mongodb.core.mapping.Document[format=annotation] 类，并配置 Spring Data MongoDB 仓库。
使用 javadoc:org.springframework.boot.data.mongodb.test.autoconfigure.DataMongoTest[format=annotation] annotation 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（有关在 Spring Boot 中使用 MongoDB 的更多信息，请参见 xref:data/nosql.adoc#data.nosql.mongodb[]。）

提示：javadoc:org.springframework.boot.data.mongodb.test.autoconfigure.DataMongoTest[format=annotation] 启用的 auto-configuration 设置列表可以 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]。

以下类展示了 javadoc:org.springframework.boot.data.mongodb.test.autoconfigure.DataMongoTest[format=annotation] annotation 的使用：

include-code::MyDataMongoDbTests[]



[[testing.spring-boot-applications.autoconfigured-spring-data-neo4j]]
== 自动配置的 Data Neo4j 测试

你可以使用来自 `spring-boot-data-neo4j-test` 模块的 javadoc:org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest[format=annotation] 来测试 Neo4j 应用程序。
默认情况下，它会扫描 javadoc:org.springframework.data.neo4j.core.schema.Node[format=annotation] 类，并配置 Spring Data Neo4j 仓库。
使用 javadoc:org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest[format=annotation] annotation 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（有关在 Spring Boot 中使用 Neo4J 的更多信息，请参见 xref:data/nosql.adoc#data.nosql.neo4j[]。）
TIP: 通过 javadoc:org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest[format=annotation] 启用的 auto-configuration 设置列表可以在 xref:appendix:test-auto-configuration/index.adoc[found in the appendix] 中找到。

以下示例展示了在 Spring Boot 中使用 Neo4J 测试的典型设置：

include-code::propagation/MyDataNeo4jTests[]

默认情况下，Data Neo4j 测试是事务性的，并在每个测试结束时回滚。
更多详情请参阅 Spring 框架参考文档中的 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[相关章节]。
如果这不是你想要的，你可以为单个测试或整个类禁用事务管理，如下所示：

include-code::nopropagation/MyDataNeo4jTests[]

注意：响应式访问不支持事务性测试。
如果你使用这种风格，必须按照上述方式配置 javadoc:org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest[format=annotation] 测试。



[[testing.spring-boot-applications.autoconfigured-spring-data-redis]]
== 自动配置的 Data Redis 测试

你可以使用 javadoc:org.springframework.boot.data.redis.test.autoconfigure.DataRedisTest[format=annotation] 模块中的 `spring-boot-data-redis-test` 来测试 Data Redis 应用程序。
默认情况下，它会扫描 javadoc:org.springframework.data.redis.core.RedisHash[format=annotation] 类并配置 Spring Data Redis 仓库。
使用 javadoc:org.springframework.boot.data.redis.test.autoconfigure.DataRedisTest[format=annotation] annotation 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（有关在 Spring Boot 中使用 Redis 的更多信息，请参阅 xref:data/nosql.adoc#data.nosql.redis[]。）

提示：通过 javadoc:org.springframework.boot.data.redis.test.autoconfigure.DataRedisTest[format=annotation] 启用的 auto-configuration 设置列表可以在 xref:appendix:test-auto-configuration/index.adoc[found in the appendix] 中找到。

以下示例展示了 javadoc:org.springframework.boot.data.redis.test.autoconfigure.DataRedisTest[format=annotation] annotation 的使用：

include-code::MyDataRedisTests[]



[[testing.spring-boot-applications.autoconfigured-spring-data-ldap]]
== 自动配置的 Data LDAP 测试

你可以使用 javadoc:org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest[format=annotation] 来测试 Data LDAP 应用程序。
默认情况下，它会配置一个内存嵌入式 LDAP（如果可用），配置一个 javadoc:org.springframework.ldap.core.LdapTemplate[]，扫描 javadoc:org.springframework.ldap.odm.annotations.Entry[format=annotation] 类，并配置 Spring Data LDAP 仓库。
使用 javadoc:org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest[format=annotation] annotation 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
（有关在 Spring Boot 中使用 LDAP 的更多信息，请参阅 xref:data/nosql.adoc#data.nosql.ldap[]。）

提示：通过 javadoc:org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest[format=annotation] 启用的 auto-configuration 设置列表可以在 xref:appendix:test-auto-configuration/index.adoc[found in the appendix] 中找到。

以下示例展示了 javadoc:org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest[format=annotation] annotation 的使用：

include-code::inmemory/MyDataLdapTests[]

内存嵌入式 LDAP 通常适用于测试，因为它速度快且无需任何开发者安装。
但是，如果你更愿意针对真实的 LDAP 服务器运行测试，则应排除嵌入式 LDAP auto-configuration，如下例所示：

include-code::server/MyDataLdapTests[]



[[testing.spring-boot-applications.autoconfigured-rest-client]]
== 自动配置的 REST 客户端

你可以使用 javadoc:org.springframework.boot.restclient.test.autoconfigure.RestClientTest[format=annotation] 模块中的 `spring-boot-restclient-test` annotation 来测试 REST 客户端。
默认情况下，它会自动配置 Jackson、GSON 和 Jsonb 支持，配置一个 javadoc:org.springframework.boot.restclient.RestTemplateBuilder[] 和一个 javadoc:org.springframework.web.client.RestClient$Builder[]，并添加对 javadoc:org.springframework.test.web.client.MockRestServiceServer[] 的支持。
使用 javadoc:org.springframework.boot.restclient.test.autoconfigure.RestClientTest[format=annotation] annotation 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

提示：通过 javadoc:org.springframework.boot.restclient.test.autoconfigure.RestClientTest[format=annotation] 启用的 auto-configuration 设置列表可以在 xref:appendix:test-auto-configuration/index.adoc[found in the appendix] 中找到。

要测试的特定 bean 应通过 `value` 或 `components` 属性在 javadoc:org.springframework.boot.restclient.test.autoconfigure.RestClientTest[format=annotation] 中指定。

当在测试的 bean 中使用 javadoc:org.springframework.boot.restclient.RestTemplateBuilder[]，并且在构建 javadoc:org.springframework.web.client.RestTemplate[] 时调用了 `RestTemplateBuilder.rootUri(String rootUri)`，则应在 javadoc:org.springframework.test.web.client.MockRestServiceServer[] 期望中省略根 URI，如下例所示：

include-code::MyRestTemplateServiceTests[]

当在测试的 bean 中使用 javadoc:org.springframework.web.client.RestClient$Builder[]，或者使用 javadoc:org.springframework.boot.restclient.RestTemplateBuilder[] 但未调用 `rootUri(String rootURI)` 时，必须在 javadoc:org.springframework.test.web.client.MockRestServiceServer[] 期望中使用完整 URI，如下例所示：

include-code::MyRestClientServiceTests[]



[[testing.spring-boot-applications.autoconfigured-web-client]]
== 自动配置的 Web 客户端

你可以使用 javadoc:org.springframework.boot.webclient.test.autoconfigure.WebClientTest[format=annotation] 模块中的 `spring-boot-webclient-test` annotation 来测试使用 `WebClient` 的代码。
默认情况下，它会自动配置 Jackson、GSON 和 Jsonb 支持，并配置一个 javadoc:org.springframework.web.reactive.function.client.WebClient$Builder[]。
使用 javadoc:org.springframework.boot.webclient.test.autoconfigure.WebClientTest[format=annotation] annotation 时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] bean。

提示：通过 javadoc:org.springframework.boot.webclient.test.autoconfigure.WebClientTest[format=annotation] 启用的 auto-configuration 设置列表可以在 xref:appendix:test-auto-configuration/index.adoc[found in the appendix] 中找到。

要测试的特定 bean 应通过 `value` 或 `components` 属性在 javadoc:org.springframework.boot.webclient.test.autoconfigure.WebClientTest[format=annotation] 中指定。



[[testing.spring-boot-applications.autoconfigured-spring-restdocs]]
== 自动配置的 Spring REST Docs 测试

你可以使用 `spring-boot-restdocs-` 模块中的 javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] annotation 来在测试中使用 {url-spring-restdocs-site}[Spring REST Docs] 与 Mock MVC 或 WebTestClient。
它消除了在 Spring REST Docs 中对 JUnit 扩展的需求。

javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 可用于覆盖默认输出目录（如果你使用 Maven，则为 `target/generated-snippets`；如果你使用 Gradle，则为 `build/generated-snippets`）。
它还可用于配置任何文档化 URI 中出现的主机、方案和端口。



[[testing.spring-boot-applications.autoconfigured-spring-restdocs.with-mock-mvc]]
=== 使用 Mock MVC 的自动配置 Spring REST Docs 测试

javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 自定义 javadoc:org.springframework.test.web.servlet.MockMvc[] bean 以在测试基于 Servlet 的 Web 应用程序时使用 Spring REST Docs。
你可以通过 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 注入它，并在测试中像通常使用 Mock MVC 和 Spring REST Docs 一样使用它，如下例所示：

include-code::hamcrest/MyUserDocumentationTests[]

如果你更喜欢使用 AssertJ 集成，javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[] 也可用，如下例所示：

include-code::assertj/MyUserDocumentationTests[]

两者在后台重用相同的 javadoc:org.springframework.test.web.servlet.MockMvc[] 实例，因此对其的任何配置都适用于两者。

如果你需要对 Spring REST Docs 配置进行比 javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 属性提供的更多控制，可以使用 javadoc:org.springframework.boot.restdocs.test.autoconfigure.RestDocsMockMvcConfigurationCustomizer[] bean，如下例所示：

include-code::MyRestDocsConfiguration[]

如果你想利用 Spring REST Docs 对参数化输出目录的支持，可以创建一个 javadoc:org.springframework.restdocs.mockmvc.RestDocumentationResultHandler[] bean。
auto-configuration 使用此结果处理器调用 `alwaysDo`，从而使每个 javadoc:org.springframework.test.web.servlet.MockMvc[] 调用自动生成默认片段。
以下示例展示了 javadoc:org.springframework.restdocs.mockmvc.RestDocumentationResultHandler[] 的定义：

include-code::MyResultHandlerConfiguration[]



[[testing.spring-boot-applications.autoconfigured-spring-restdocs.with-web-test-client]]
=== 使用 WebTestClient 的自动配置 Spring REST Docs 测试

javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 也可以与 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 一起用于测试响应式 Web 应用程序。
你可以通过 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 注入它，并在测试中像通常使用 javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 和 Spring REST Docs 一样使用它，如下例所示：

include-code::MyUsersDocumentationTests[]
如果您需要比 javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 属性提供的对 Spring REST Docs 配置更多的控制，您可以使用 javadoc:org.springframework.boot.restdocs.test.autoconfigure.RestDocsWebTestClientConfigurationCustomizer[] bean，如下例所示：

include-code::MyRestDocsConfiguration[]

如果您想利用 Spring REST Docs 对参数化输出目录的支持，您可以使用 javadoc:org.springframework.boot.webtestclient.autoconfigure.WebTestClientBuilderCustomizer[] 为每个实体交换结果配置一个消费者。
以下示例展示了这样一个 javadoc:org.springframework.boot.webtestclient.autoconfigure.WebTestClientBuilderCustomizer[] 的定义：

include-code::MyWebTestClientBuilderCustomizerConfiguration[]



[[testing.spring-boot-applications.autoconfigured-webservices]]
== 自动配置的 Spring Web Services 测试



[[testing.spring-boot-applications.autoconfigured-webservices.client]]
=== 自动配置的 Spring Web Services 客户端测试

您可以使用 javadoc:org.springframework.boot.webservices.test.autoconfigure.client.WebServiceClientTest[format=annotation] 模块中的 `spring-boot-webservices-test` 来测试使用 Spring Web Services 项目调用 Web 服务的应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.ws.test.client.MockWebServiceServer[] bean，并自动定制您的 javadoc:org.springframework.boot.webservices.client.WebServiceTemplateBuilder[]。
（有关在 Spring Boot 中使用 Web Services 的更多信息，请参见 xref:io/webservices.adoc[]。）


提示：由 javadoc:org.springframework.boot.webservices.test.autoconfigure.client.WebServiceClientTest[format=annotation] 启用的 auto-configuration 设置列表可以 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]。

以下示例展示了 javadoc:org.springframework.boot.webservices.test.autoconfigure.client.WebServiceClientTest[format=annotation] annotation 的使用：

include-code::MyWebServiceClientTests[]



[[testing.spring-boot-applications.autoconfigured-webservices.server]]
=== 自动配置的 Spring Web Services 服务器测试

您可以使用 javadoc:org.springframework.boot.webservices.test.autoconfigure.server.WebServiceServerTest[format=annotation] 模块中的 `spring-boot-webservices-test` 来测试使用 Spring Web Services 项目实现 Web 服务的应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.ws.test.server.MockWebServiceClient[] bean，可用于调用您的 Web 服务 endpoint。
（有关在 Spring Boot 中使用 Web Services 的更多信息，请参见 xref:io/webservices.adoc[]。）


提示：由 javadoc:org.springframework.boot.webservices.test.autoconfigure.server.WebServiceServerTest[format=annotation] 启用的 auto-configuration 设置列表可以 xref:appendix:test-auto-configuration/index.adoc[found in the appendix]。

以下示例展示了 javadoc:org.springframework.boot.webservices.test.autoconfigure.server.WebServiceServerTest[format=annotation] annotation 的使用：

include-code::MyWebServiceServerTests[]



[[testing.spring-boot-applications.additional-autoconfiguration-and-slicing]]
== 额外的自动配置和切片

每个切片提供一个或多个 `@AutoConfigure...` annotation，这些 annotation 定义了应作为切片一部分包含的 auto-configuration。
可以通过创建自定义 `@AutoConfigure...` annotation 或向测试添加 javadoc:org.springframework.boot.autoconfigure.ImportAutoConfiguration[format=annotation] 来逐个测试地添加额外的 auto-configuration，如下例所示：

include-code::MyJdbcTests[]

注意：确保不要使用常规的 javadoc:org.springframework.context.annotation.Import[format=annotation] annotation 来导入 auto-configuration，因为它们由 Spring Boot 以特定方式处理。

或者，可以通过在存储在 `META-INF/spring` 中的文件中注册它们来为任何切片 annotation 的使用添加额外的 auto-configuration，如下例所示：

.META-INF/spring/org.springframework.boot.jdbc.test.autoconfigure.JdbcTest.imports
[source]
----
com.example.IntegrationAutoConfiguration
----

在此示例中，`+com.example.IntegrationAutoConfiguration+` 在每个标注了 javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] 的测试上启用。

提示：你可以在该文件中使用带有 `#` 的注释。

提示：只要切片或 `@AutoConfigure...` annotation 被 javadoc:org.springframework.boot.autoconfigure.ImportAutoConfiguration[format=annotation] 元注解，就可以通过这种方式自定义。



[[testing.spring-boot-applications.user-configuration-and-slicing]]
== 用户配置与切片

如果你以合理的方式 xref:using/structuring-your-code.adoc[structure your code]，你的 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 类将 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[used by default] 作为测试的配置。

因此，重要的是不要将特定于某个功能区域的配置设置散布到应用程序的主类中。

假设你正在使用 Spring Data MongoDB，你依赖其 auto-configuration，并且已启用审计。
你可以按如下方式定义你的 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]：

include-code::MyApplication[]

由于此类是测试的源配置，任何切片测试实际上都会尝试启用 Mongo 审计，这绝对不是你想要做的。
推荐的方法是将该特定区域的配置移动到与应用程序同级别的单独 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类中，如下例所示：

include-code::MyMongoConfiguration[]

注意：根据应用程序的复杂性，你可以为自定义配置使用单个 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类，或者每个领域区域使用一个类。
后一种方法允许你在必要时通过 javadoc:org.springframework.context.annotation.Import[format=annotation] annotation 在某个测试中启用它。
有关何时可能想要为切片测试启用特定 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类的更多详细信息，请参阅 xref:how-to:testing.adoc#howto.testing.slice-tests[this how-to section]。

测试切片会排除 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类的扫描。
例如，对于 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation]，以下配置不会将给定的 javadoc:org.springframework.web.servlet.config.annotation.WebMvcConfigurer[] bean 包含在测试切片加载的应用程序上下文中：

include-code::MyWebConfiguration[]

然而，下面的配置将导致自定义 javadoc:org.springframework.web.servlet.config.annotation.WebMvcConfigurer[] 被测试切片加载。

include-code::MyWebMvcConfigurer[]

另一个混淆来源是 classpath 扫描。
假设你以合理的方式组织了代码，但需要扫描一个额外的包。
你的应用程序可能类似于以下代码：

include-code::scan/MyApplication[]

这样做实际上会覆盖默认的组件扫描指令，其副作用是无论你选择哪个切片，都会扫描这两个包。
例如，javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 似乎会突然扫描应用程序的组件和用户配置。
同样，将自定义指令移动到单独的类是解决此问题的好方法。

提示：如果这对你来说不可行，你可以在测试层次结构中的某处创建一个 javadoc:org.springframework.boot.SpringBootConfiguration[format=annotation]，以便替代使用。
或者，你可以为测试指定一个源，这会禁用查找默认源的行为。



[[testing.spring-boot-applications.spock]]
== 使用 Spock 测试 Spring Boot 应用程序

Spock 2.4 或更高版本可用于测试 Spring Boot 应用程序。
为此，请将 Spock 的 `spock-spring` 模块的 `-groovy-5.0` 版本依赖项添加到应用程序的构建中。
`spock-spring` 将 Spring 的测试框架集成到 Spock 中。
更多详细信息，请参阅 https://spockframework.org/spock/docs/2.4/modules.html#spring-module[the documentation for Spock's Spring module]。
