= 与 Actuator 集成

[[integrating-with-actuator.build-info]]
== 生成构建信息

Spring Boot Actuator 的 `info` 端点会在存在 `META-INF/build-info.properties` 文件时自动发布有关构建的信息。
提供了一个 {apiref-gradle-plugin-boot-build-info}[`BuildInfo`] 任务来生成此文件。
使用该任务最简单的方式是通过插件的 DSL：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$integrating-with-actuator/build-info-basic.gradle[tags=build-info]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$integrating-with-actuator/build-info-basic.gradle.kts[tags=build-info]
----
======

这将配置一个名为 `bootBuildInfo` 的 {apiref-gradle-plugin-boot-build-info}[`BuildInfo`] 任务。
该任务的目标目录为 `build/bootBuildInfo`，文件名为 `META-INF/build-info.properties`。
如果主源集存在，其资源将被配置为使用 `bootBuildInfo` 任务的输出作为源目录。

默认情况下，生成的构建信息来源于项目：

|===
| 属性 | 默认值

| `build.artifact`
| `bootJar` 或 `bootWar` 任务的基本名称

| `build.group`
| 项目所属组

| `build.name`
| 项目名称

| `build.version`
| 项目版本

| `build.time`
| 项目构建时的时间

|===

可以使用 DSL 自定义这些属性：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$integrating-with-actuator/build-info-custom-values.gradle[tags=custom-values]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$integrating-with-actuator/build-info-custom-values.gradle.kts[tags=custom-values]
----
======

要从生成的构建信息中排除任何默认属性，请将其名称添加到 excludes 中。
例如，`time` 属性可以按如下方式排除：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$integrating-with-actuator/build-info-exclude-time.gradle[tags=exclude-time]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$integrating-with-actuator/build-info-exclude-time.gradle.kts[tags=exclude-time]
----
======

`build.time` 的默认值是项目构建的瞬间。
这带来的一个副作用是，该任务永远不会是最新的。
因此，构建将花费更长时间，因为更多任务（包括项目的测试）必须被执行。
另一个副作用是任务的输出将始终变化，因此构建将无法真正可重现。
如果你更看重构建性能或可重现性而非 `build.time` 属性的准确性，请像前面的示例那样排除 `time` 属性。

还可以向构建信息中添加其他属性：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$integrating-with-actuator/build-info-additional.gradle[tags=additional]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$integrating-with-actuator/build-info-additional.gradle.kts[tags=additional]
----
======

附加属性的值可以通过使用 `Provider` 进行惰性计算。
