[[howto.native-image.developing-your-first-application]]
= 开发你的第一个 GraalVM 原生应用

构建 Spring Boot 原生镜像应用主要有两种方式：

* 使用 Spring Boot 对 xref:reference:packaging/container-images/cloud-native-buildpacks.adoc[Cloud Native Buildpacks 的支持]，配合 https://paketo.io/docs/reference/java-native-image-reference/[Paketo Java Native Image buildpack] 生成包含原生可执行文件的轻量级容器。
* 使用 GraalVM Native Build Tools 生成原生可执行文件。

提示：启动一个新的原生 Spring Boot 项目最简单的方法是访问 https://start.spring.io[start.spring.io]，添加 `GraalVM Native Support` 依赖并生成项目。
包含的 `HELP.md` 文件将提供入门提示。



[[howto.native-image.developing-your-first-application.sample-application]]
== 示例应用

我们需要一个示例应用来创建原生镜像。
就我们的目的而言，xref:tutorial:first-application/index.adoc[] 部分中介绍的简单 "Hello World!" Web 应用就足够了。

回顾一下，我们的主应用代码如下：

include-code::MyApplication[]

此应用使用 Spring MVC 和嵌入式 Tomcat，这两者都经过测试并验证可与 GraalVM 原生镜像一起使用。



[[howto.native-image.developing-your-first-application.buildpacks]]
== 使用 Buildpacks 构建原生镜像

Spring Boot 支持使用 Cloud Native Buildpacks (CNB) 集成（通过 Maven 和 Gradle）以及 https://paketo.io/docs/reference/java-native-image-reference/[Paketo Java Native Image buildpack] 构建包含原生可执行文件的 Docker 镜像。
这意味着你只需输入一条命令，即可快速在本地运行的 Docker 守护进程中获取一个合理的镜像。
生成的镜像不包含 JVM，而是静态编译的原生镜像。
这导致镜像更小。

注意：用于镜像的 CNB builder 是 `paketobuildpacks/builder-noble-java-tiny:latest`。
它的体积小，攻击面减少。它不包含 shell，并且包含一组精简的系统库。
如果你需要在生成的镜像中使用更多工具，可以使用 `paketobuildpacks/ubuntu-noble-run:latest` 作为 *run* 镜像。

注意：你必须使用至少 JDK 25 构建应用，因为 Buildpacks 使用的 GraalVM native-image 版本与编译所用的 Java 版本相同。



[[howto.native-image.developing-your-first-application.buildpacks.system-requirements]]
=== 系统要求

应安装 Docker。更多详情请参见 https://docs.docker.com/installation/#installation[Get Docker]。
如果你在 Linux 上，请 https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user[配置它以允许非 root 用户]。

注意：你可以运行 `docker run hello-world`（不带 `sudo`）来检查 Docker 守护进程是否可按预期访问。
更多详情请查看 xref:maven-plugin:build-image.adoc#build-image.docker-daemon[Maven] 或 xref:gradle-plugin:packaging-oci-image.adoc#build-image.docker-daemon[Gradle] Spring Boot 插件文档。

提示：在 macOS 上，建议将分配给 Docker 的内存增加到至少 `8GB`，并可能添加更多 CPU。
更多详情请参见此 https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container/44533437#44533437[Stack Overflow 答案]。
在 Microsoft Windows 上，请确保启用 https://docs.docker.com/docker-for-windows/wsl/[Docker WSL 2 后端] 以获得更好的性能。



[[howto.native-image.developing-your-first-application.buildpacks.maven]]
=== 使用 Maven

要使用 Maven 构建原生镜像容器，应确保你的 `pom.xml` 文件使用了 `spring-boot-starter-parent` 和 `org.graalvm.buildtools:native-maven-plugin`。
你应该有一个如下所示的 `<parent>` 部分：

[source,xml,subs="verbatim,attributes"]
----
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>{version-spring-boot}</version>
</parent>
----

此外，你需要在 `<build> <plugins>` 部分添加以下内容：

[source,xml,subs="verbatim,attributes"]
----
<plugin>
	<groupId>org.graalvm.buildtools</groupId>
	<artifactId>native-maven-plugin</artifactId>
</plugin>
----

`spring-boot-starter-parent` 声明了一个 `native` profile，该 profile 配置了创建原生镜像所需执行的步骤。你可以通过命令行中的 `-P` 标志来激活 profile。

提示：如果你不想使用 `spring-boot-starter-parent`，则需要为 Spring Boot 插件的 `process-aot` 目标和 Native Build Tools 插件的 `add-reachability-metadata` 目标配置执行步骤。

要构建镜像，你可以激活 `native` profile 并运行 `spring-boot:build-image` 目标：

[source,shell]
----
$ mvn -Pnative spring-boot:build-image
----



[[howto.native-image.developing-your-first-application.buildpacks.gradle]]
=== 使用 Gradle

当应用 GraalVM Native Image 插件时，Spring Boot Gradle 插件会自动配置 AOT 任务。
你应该检查 Gradle 构建是否包含一个 `plugins` 块，其中包含 `org.graalvm.buildtools.native`。

只要应用了 `org.graalvm.buildtools.native` 插件，`bootBuildImage` 任务就会生成一个 native image 而不是 JVM 镜像。
你可以使用以下命令运行该任务：

[source,shell]
----
$ gradle bootBuildImage
----



[[howto.native-image.developing-your-first-application.buildpacks.running]]
=== 运行示例

一旦你运行了适当的构建命令，应该会有一个 Docker 镜像可用。
你可以使用 `docker run` 启动你的应用程序：

[source,shell]
----
$ docker run --rm -p 8080:8080 docker.io/library/myproject:0.0.1-SNAPSHOT
----

您应该会看到类似于以下的输出：

[source,shell]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v{version-spring-boot})
....... . . .
....... . . . (日志输出在此)
....... . . .
........ Started MyApplication in 0.08 seconds (进程运行了 0.095 秒)
----

注意：启动时间因机器而异，但应该比在 JVM 上运行的 Spring Boot 应用程序快得多。

如果你在浏览器中打开 `http://localhost:8080`，应该会看到以下输出：

[source]
----
Hello World!
----

要优雅地退出应用程序，请按 `ctrl-c`。



[[howto.native-image.developing-your-first-application.native-build-tools]]
== 使用 Native Build Tools 构建原生镜像

如果你想直接生成原生可执行文件而不使用 Docker，可以使用 GraalVM Native Build Tools。
Native Build Tools 是 GraalVM 为 Maven 和 Gradle 提供的插件。
你可以使用它们执行各种 GraalVM 任务，包括生成原生镜像。



[[howto.native-image.developing-your-first-application.native-build-tools.prerequisites]]
=== 前提条件

要使用 Native Build Tools 构建原生镜像，你需要在机器上安装 GraalVM 发行版。
你可以从 {url-download-liberica-nik}[Liberica Native Image Kit 页面] 手动下载，或者使用像 SDKMAN! 这样的下载管理器。



[[howto.native-image.developing-your-first-application.native-build-tools.prerequisites.linux-macos]]
==== Linux 和 macOS

要在 macOS 或 Linux 上安装原生镜像编译器，我们推荐使用 SDKMAN!。
从 https://sdkman.io 获取 SDKMAN!，并使用以下命令安装 Liberica GraalVM 发行版：

[source,shell,subs="verbatim,attributes"]
----
$ sdk install java 25.r25-nik
$ sdk use java 25.r25-nik
----

通过检查 `java -version` 的输出，验证是否已配置正确的版本：

[source,shell,subs="verbatim,attributes"]
----
$ java -version
openjdk version "25" 2025-09-16 LTS
OpenJDK Runtime Environment Liberica-NIK-25.0.0-1 (build 25+37-LTS)
OpenJDK 64-Bit Server VM Liberica-NIK-25.0.0-1 (build 25+37-LTS, mixed mode, sharing)
----



[[howto.native-image.developing-your-first-application.native-build-tools.prerequisites.windows]]
==== Windows

在 Windows 上，按照 https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311[这些说明] 安装 https://www.graalvm.org/downloads/[GraalVM] 或 {url-download-liberica-nik}[Liberica Native Image Kit] 版本 {version-graal}，以及 Visual Studio Build Tools 和 Windows SDK。
由于 https://docs.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/command-line-string-limitation[Windows 相关的命令行最大长度限制]，请确保使用 x64 Native Tools 命令提示符而不是常规的 Windows 命令行来运行 Maven 或 Gradle 插件。



[[howto.native-image.developing-your-first-application.native-build-tools.maven]]
=== 使用 Maven

与 xref:native-image/developing-your-first-application.adoc#howto.native-image.developing-your-first-application.buildpacks.maven[buildpacks 支持] 类似，你需要确保使用 `spring-boot-starter-parent` 以继承 `native` profile，并且使用了 `org.graalvm.buildtools:native-maven-plugin` 插件。

激活 `native` profile 后，你可以调用 `native:compile` 目标来触发 `native-image` 编译：

[source,shell]
----
$ mvn -Pnative native:compile
----

原生镜像可执行文件可以在 `target` 目录中找到。



[[howto.native-image.developing-your-first-application.native-build-tools.gradle]]
=== 使用 Gradle

当 Native Build Tools Gradle 插件应用于你的项目时，Spring Boot Gradle 插件将自动触发 Spring AOT 引擎。
任务依赖关系会自动配置，因此你可以直接运行标准的 `nativeCompile` 任务来生成原生镜像：

[source,shell]
----
$ gradle nativeCompile
----

原生镜像可执行文件可以在 `build/native/nativeCompile` 目录中找到。



[[howto.native-image.developing-your-first-application.native-build-tools.running]]
=== 运行示例

此时，你的应用程序应该可以工作了。现在，你可以直接运行它来启动应用程序：

[tabs]
======
Maven::
+
[source,shell]
----
$ target/myproject
----
Gradle::
+
[source,shell]
----
$ build/native/nativeCompile/myproject
----
======

您应该会看到类似如下的输出：

[source,shell,subs="verbatim,attributes"]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v{version-spring-boot})
....... . . .
....... . . . (日志输出在此)
....... . . .
........ Started MyApplication in 0.08 seconds (进程运行了 0.095 秒)
----

注意：启动时间因机器而异，但应该比在 JVM 上运行的 Spring Boot 应用程序快得多。

如果你在浏览器中打开 `http://localhost:8080`，应该会看到以下输出：

[source]
----
Hello World!
----

要优雅地退出应用程序，请按 `ctrl-c`。
