= 测试 Spring Boot 应用程序

一个 Spring Boot 应用程序就是一个 Spring 应用程序上下文，因此除了通常对普通 Spring 上下文所做的测试之外，无需做任何特别的事情来测试它。

注意：只有当你使用 javadoc:org.springframework.boot.SpringApplication[] 创建上下文时，外部属性、日志记录和 Spring Boot 的其他特性才会默认安装在上下文中。

Spring Boot 提供了一个 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 注解，当你需要 Spring Boot 特性时，它可以作为标准 `spring-test` javadoc:org.springframework.test.context.ContextConfiguration[format=annotation] 测试注解的替代方案。该注解通过 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[创建测试中使用的 javadoc:org.springframework.context.ApplicationContext[]] 来工作。除了 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 之外，还提供了许多其他注解用于 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[测试应用程序的更特定切片]。

提示：如果你使用 JUnit 4，不要忘记同时将 `@RunWith(SpringRunner.class)` 添加到你的测试中，否则该注解将被忽略。如果你使用 JUnit 6，则无需添加等效的 `@ExtendWith(SpringExtension.class)`，因为 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 和其他 `@...Test` 注解已经用其注解。

默认情况下，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 不会启动服务器。你可以使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 的 `webEnvironment` 属性来进一步细化测试的运行方式：

* `MOCK`（默认）：加载一个 Web javadoc:org.springframework.context.ApplicationContext[] 并提供模拟 Web 环境。使用此注解时不会启动嵌入式服务器。如果你的 classpath 上没有可用的 Web 环境，此模式会透明地回退到创建常规的非 Web javadoc:org.springframework.context.ApplicationContext[]。它可以与 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-mock-environment[`@AutoConfigureMockMvc`、javadoc:org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient[format=annotation] 或 javadoc:org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient[format=annotation]] 结合使用，用于基于模拟的 Web 应用程序测试。
* `RANDOM_PORT`：加载一个 javadoc:org.springframework.boot.web.server.context.WebServerApplicationContext[] 并提供真实的 Web 环境。嵌入式服务器启动并监听随机端口。
* `DEFINED_PORT`：加载一个 javadoc:org.springframework.boot.web.server.context.WebServerApplicationContext[] 并提供真实的 Web 环境。嵌入式服务器启动并监听定义的端口（来自你的 `application.properties`）或默认端口 `8080`。
* `NONE`：通过 javadoc:org.springframework.boot.SpringApplication[] 加载一个 javadoc:org.springframework.context.ApplicationContext[]，但不提供任何 Web 环境（模拟或其他）。

注意：如果你的测试是 javadoc:org.springframework.transaction.annotation.Transactional[format=annotation]，默认情况下它会在每个测试方法结束时回滚事务。但是，由于使用此设置与 `RANDOM_PORT` 或 `DEFINED_PORT` 会隐式提供真实的 Servlet 环境，HTTP 客户端和服务器在不同的线程中运行，因此也在不同的事务中运行。在这种情况下，服务器上发起的任何事务都不会回滚。

注意：如果应用程序为管理服务器使用不同的端口，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 与 `webEnvironment = WebEnvironment.RANDOM_PORT` 也会在单独的随机端口上启动管理服务器。



[[testing.spring-boot-applications.detecting-web-app-type]]
== 检测 Web 应用程序类型

如果 Spring MVC 可用，则会配置一个常规的基于 MVC 的应用程序上下文。如果你只有 Spring WebFlux，我们将检测到它并改为配置一个基于 WebFlux 的应用程序上下文。

如果两者都存在，Spring MVC 优先。在这种情况下，如果你想测试响应式 Web 应用程序，必须设置 configprop:spring.main.web-application-type[] 属性：

[source,java]
----
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest(properties = "spring.main.web-application-type=reactive")
class MyWebFluxTests {

	// ...

}
----



[[testing.spring-boot-applications.detecting-configuration]]
== 检测测试配置

如果你熟悉 Spring 测试框架，你可能习惯于使用 `@ContextConfiguration(classes=...)` 来指定要加载哪个 Spring javadoc:org.springframework.context.annotation.Configuration[format=annotation]。或者，你可能经常在测试中使用嵌套的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类。

在测试 Spring Boot 应用程序时，这通常不是必需的。当你没有显式定义一个主配置时，Spring Boot 的 `@*Test` 注解会自动搜索你的主配置。

搜索算法从包含测试的包向上工作，直到找到一个用 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 或 javadoc:org.springframework.boot.SpringBootConfiguration[format=annotation] 注解的类。只要你 xref:using/structuring-your-code.adoc[以合理的方式组织代码]，通常就能找到你的主配置。

[NOTE]
====
如果你使用 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[测试注解来测试应用程序的更特定切片]，则应避免在 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.user-configuration-and-slicing[主方法的应用程序类] 上添加特定于某个区域的配置设置。

javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 的底层组件扫描配置定义了排除过滤器，用于确保切片按预期工作。如果你在 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 注解的类上使用了显式的 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] 指令，请注意这些过滤器将被禁用。如果你使用切片，则应重新定义它们。
====

如果你想自定义主配置，可以使用嵌套的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 类。与嵌套的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类（将替代应用程序的主配置）不同，嵌套的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 类是在应用程序主配置之外额外使用的。

注意：Spring Boot 的测试框架会在测试之间缓存应用程序上下文。因此，只要你的测试共享相同的配置（无论它是如何发现的），加载上下文的潜在耗时过程只会发生一次。



[[testing.spring-boot-applications.using-main]]
== 使用测试配置主方法

通常，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 发现的测试配置将是你的主 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]。在大多数结构良好的应用程序中，此配置类还将包含用于启动应用程序的 `main` 方法。

例如，以下是一个典型的 Spring Boot 应用程序非常常见的代码模式：

[source,java]
----
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyApplication {

	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}

}
----

在上面的示例中，`main` 方法除了委托给 javadoc:org.springframework.boot.SpringApplication#run(java.lang.Class,java.lang.String...)[] 之外什么也不做。但是，也可以有一个更复杂的 `main` 方法，在调用 javadoc:org.springframework.boot.SpringApplication#run(java.lang.Class,java.lang.String...)[] 之前应用自定义设置。

例如，以下是一个更改横幅模式并设置其他 profiles 的应用程序：

[source,java]
----
import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyApplication {

	public static void main(String[] args) {
		SpringApplication application = new SpringApplication(MyApplication.class);
		application.setBannerMode(Banner.Mode.OFF);
		application.setAdditionalProfiles("myprofile");
		application.run(args);
	}

}
----

由于 `main` 方法中的自定义设置会影响生成的 javadoc:org.springframework.context.ApplicationContext[]，因此你可能也希望使用 `main` 方法来创建测试中使用的 javadoc:org.springframework.context.ApplicationContext[]。默认情况下，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 不会调用你的 `main` 方法，而是直接使用该类本身来创建 javadoc:org.springframework.context.ApplicationContext[]。

如果你想更改此行为，可以将 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 的 `useMainMethod` 属性更改为 javadoc:org.springframework.boot.test.context.SpringBootTest$UseMainMethod#ALWAYS[] 或 javadoc:org.springframework.boot.test.context.SpringBootTest$UseMainMethod#WHEN_AVAILABLE[]。当设置为 `ALWAYS` 时，如果找不到 `main` 方法，测试将失败。当设置为 `WHEN_AVAILABLE` 时，如果 `main` 方法可用，则使用它，否则使用标准加载机制。

例如，以下测试将调用 `MyApplication` 的 `main` 方法来创建 javadoc:org.springframework.context.ApplicationContext[]。如果主方法设置了其他 profiles，则这些设置将在 javadoc:org.springframework.context.ApplicationContext[] 启动时生效。

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.UseMainMethod;

@SpringBootTest(useMainMethod = UseMainMethod.ALWAYS)
class MyApplicationTests {

	@Test
	void exampleTest() {
		// ...
	}

}
----



[[testing.spring-boot-applications.excluding-configuration]]
== 排除测试配置

如果你的应用程序使用组件扫描（例如，如果你使用 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 或 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]），你可能会发现仅为特定测试创建的顶级配置类意外地被到处拾取。

正如我们 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[之前所见]，javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 可用于测试的内部类来自定义主配置。javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 也可以用于顶级类。这样做表示该类不应被扫描拾取。然后你可以在需要的地方显式导入该类，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;

@SpringBootTest
@Import(MyTestsConfiguration.class)
class MyTests {

	@Test
	void exampleTest() {
		// ...
	}

}
----

注意：如果你直接使用 javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]（即不通过 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]），则需要向其注册 javadoc:org.springframework.boot.context.TypeExcludeFilter[]。有关详细信息，请参阅 javadoc:org.springframework.boot.context.TypeExcludeFilter[] API 文档。
注意：导入的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 的处理顺序早于内部类 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation]，并且导入的 javadoc:org.springframework.boot.test.context.TestConfiguration[format=annotation] 将在通过组件扫描发现的任何配置之前处理。
一般来说，这种顺序差异没有明显影响，但如果你依赖 bean 覆盖，则需要留意这一点。



[[testing.spring-boot-applications.using-application-arguments]]
== 使用应用程序参数

如果你的应用程序期望 xref:features/spring-application.adoc#features.spring-application.application-arguments[参数]，你可以让 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 通过 `args` 属性注入它们。

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.test.context.SpringBootTest;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(args = "--app.test=one")
class MyApplicationArgumentTests {

	@Test
	void applicationArgumentsPopulated(@Autowired ApplicationArguments args) {
		assertThat(args.getOptionNames()).containsOnly("app.test");
		assertThat(args.getOptionValues("app.test")).containsOnly("one");
	}

}
----



[[testing.spring-boot-applications.with-mock-environment]]
== 使用模拟环境进行测试

默认情况下，javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 不会启动服务器，而是设置一个模拟环境来测试 Web 端点。

使用 Spring MVC，我们可以通过 {url-spring-framework-docs}/testing/mockmvc.html[`MockMvc`] 查询我们的 Web 端点。
以下集成可用：

* 常规的 {url-spring-framework-docs}/testing/mockmvc/hamcrest.html[`MockMvc`]，它使用 Hamcrest。
* {url-spring-framework-docs}/testing/mockmvc/assertj.html[`MockMvcTester`]，它包装了 javadoc:org.springframework.test.web.servlet.MockMvc[] 并使用 AssertJ。
* {url-spring-framework-docs}/testing/resttestclient.html[`RestTestClient`]，其中 javadoc:org.springframework.test.web.servlet.MockMvc[] 作为服务器插入以处理请求。
* {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，其中 javadoc:org.springframework.test.web.servlet.MockMvc[] 作为服务器插入以处理请求。

以下示例展示了可用的集成：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient;
import org.springframework.test.web.reactive.server.WebTestClient;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.assertj.MockMvcTester;
import org.springframework.test.web.servlet.client.RestTestClient;
import org.springframework.test.web.servlet.client.RestTestClient.ResponseSpec;
import org.springframework.test.web.servlet.client.assertj.RestTestClientResponse;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@AutoConfigureRestTestClient
@AutoConfigureWebTestClient
class MyMockMvcTests {

	@Test
	void testWithMockMvc(@Autowired MockMvc mvc) throws Exception {
		// @formatter:off
		mvc.perform(get("/"))
				.andExpect(status().isOk())
				.andExpect(content().string("Hello World"));
		// @formatter:on
	}

	@Test // If AssertJ is on the classpath, you can use MockMvcTester
	void testWithMockMvcTester(@Autowired MockMvcTester mvc) {
		// @formatter:off
		assertThat(mvc.get().uri("/"))
				.hasStatusOk()
				.hasBodyTextEqualTo("Hello World");
		// @formatter:on
	}

	@Test
	void testWithRestTestClient(@Autowired RestTestClient restClient) {
		// @formatter:off
		restClient
				.get().uri("/")
				.exchange()
				.expectStatus().isOk()
				.expectBody(String.class).isEqualTo("Hello World");
		// @formatter:on
	}

	@Test // If you prefer AssertJ, dedicated assertions are available
	void testWithRestTestClientAssertJ(@Autowired RestTestClient restClient) {
		// @formatter:off
		ResponseSpec spec = restClient.get().uri("/").exchange();
		RestTestClientResponse response = RestTestClientResponse.from(spec);
		assertThat(response).hasStatusOk()
				.bodyText().isEqualTo("Hello World");
		// @formatter:on
	}

	@Test // If Spring WebFlux is on the classpath
	void testWithWebTestClient(@Autowired WebTestClient webClient) {
		// @formatter:off
		webClient
				.get().uri("/")
				.exchange()
				.expectStatus().isOk()
				.expectBody(String.class).isEqualTo("Hello World");
		// @formatter:on
	}

}
----

提示：如果你只想关注 Web 层而不启动完整的 javadoc:org.springframework.context.ApplicationContext[]，请考虑 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.spring-mvc-tests[改用 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation]]。

使用 Spring WebFlux 端点，你可以使用 {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient;
import org.springframework.test.web.reactive.server.WebTestClient;

@SpringBootTest
@AutoConfigureWebTestClient
class MyMockWebTestClientTests {

	@Test
	void exampleTest(@Autowired WebTestClient webClient) {
		// @formatter:off
		webClient
			.get().uri("/")
			.exchange()
			.expectStatus().isOk()
			.expectBody(String.class).isEqualTo("Hello World");
		// @formatter:on
	}

}
----

[TIP]
====
在模拟环境中测试通常比使用完整 servlet 容器运行更快。
然而，由于模拟发生在 Spring MVC 层，依赖于较低级别 servlet 容器行为的代码无法直接使用 MockMvc 进行测试。

例如，Spring Boot 的错误处理基于 servlet 容器提供的 "`error page`" 支持。
这意味着，虽然你可以测试 MVC 层按预期抛出和处理异常，但无法直接测试是否渲染了特定的 xref:web/servlet.adoc#web.servlet.spring-mvc.error-handling.error-pages[自定义错误页面]。
如果你需要测试这些较低级别的问题，可以启动一个完全运行的服务器，如下一节所述。
====



[[testing.spring-boot-applications.with-running-server]]
== 使用运行中的服务器进行测试

如果你需要启动一个完全运行的服务器，我们建议使用随机端口。
如果你使用 `@SpringBootTest(webEnvironment=WebEnvironment.RANDOM_PORT)`，每次测试运行时都会随机选择一个可用端口。

javadoc:org.springframework.boot.test.web.server.LocalServerPort[format=annotation] 注解可用于 xref:how-to:webserver.adoc#howto.webserver.discover-port[注入实际使用的端口] 到你的测试中。

需要向已启动的服务器发起 REST 调用的测试可以通过使用 javadoc:org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient[format=annotation] 注解测试类来自动装配 {url-spring-framework-docs}/testing/resttestclient.html[`RestTestClient`]。

配置的客户端将相对链接解析到运行中的服务器，并带有用于验证响应的专用 API，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.test.web.servlet.client.RestTestClient;

@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@AutoConfigureRestTestClient
class MyRandomPortRestTestClientTests {

	@Test
	void exampleTest(@Autowired RestTestClient restClient) {
		// @formatter:off
		restClient
			.get().uri("/")
			.exchange()
			.expectStatus().isOk()
			.expectBody(String.class).isEqualTo("Hello World");
		// @formatter:on
	}

}
----

如果你更喜欢使用 AssertJ，可以从 javadoc:org.springframework.test.web.servlet.client.assertj.RestTestClientResponse[] 获得专用断言，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.test.web.servlet.client.RestTestClient;
import org.springframework.test.web.servlet.client.RestTestClient.ResponseSpec;
import org.springframework.test.web.servlet.client.assertj.RestTestClientResponse;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@AutoConfigureRestTestClient
class MyRandomPortRestTestClientAssertJTests {

	@Test
	void exampleTest(@Autowired RestTestClient restClient) {
		// @formatter:off
		ResponseSpec spec = restClient.get().uri("/").exchange();
		RestTestClientResponse response = RestTestClientResponse.from(spec);
		assertThat(response).hasStatusOk().bodyText().isEqualTo("Hello World");
		// @formatter:on
	}

}
----

如果你在 classpath 上有 `spring-webflux`，还可以通过使用 javadoc:org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient[format=annotation] 注解测试类来自动装配 {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]。

`WebTestClient` 提供了类似的 API，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient;
import org.springframework.test.web.reactive.server.WebTestClient;

@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@AutoConfigureWebTestClient
class MyRandomPortWebTestClientTests {

	@Test
	void exampleTest(@Autowired WebTestClient webClient) {
		// @formatter:off
		webClient
			.get().uri("/")
			.exchange()
			.expectStatus().isOk()
			.expectBody(String.class).isEqualTo("Hello World");
		// @formatter:on
	}

}
----

提示：javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 也可以与 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-mock-environment[模拟环境] 一起使用，无需运行服务器，只需使用 `spring-boot-webflux-test` 中的 javadoc:org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient[format=annotation] 注解测试类即可。

注意：对于某些 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[切片测试]，你可能需要使用 javadoc:org.springframework.boot.web.server.test.AutoConfigureWebServer[format=annotation] 注解来自动配置嵌入式 Web 服务器。

`spring-boot-resttestclient` 模块还提供了 javadoc:org.springframework.boot.resttestclient.TestRestTemplate[] 功能：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.TestRestTemplate;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureTestRestTemplate;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@AutoConfigureTestRestTemplate
class MyRandomPortTestRestTemplateTests {

	@Test
	void exampleTest(@Autowired TestRestTemplate restTemplate) {
		String body = restTemplate.getForObject("/", String.class);
		assertThat(body).isEqualTo("Hello World");
	}

}
----

要使用 `TestRestTemplate`，还需要依赖 `spring-boot-restclient`。
添加此依赖时需小心，因为它将为 `RestClient.Builder` 启用自动配置。
如果你的主代码使用 `RestClient.Builder`，请声明 `spring-boot-restclient` 依赖，使其位于应用程序的主 classpath 上，而不仅仅是测试 classpath 上。



[[testing.spring-boot-applications.customizing-rest-test-client]]
== 自定义 RestTestClient

要自定义 javadoc:org.springframework.test.web.servlet.client.RestTestClient[] bean，请配置一个 javadoc:org.springframework.boot.resttestclient.autoconfigure.RestTestClientBuilderCustomizer[] bean。
任何此类 beans 都会与用于创建 javadoc:org.springframework.test.web.servlet.client.RestTestClient[] 的 javadoc:org.springframework.test.web.servlet.client.RestTestClient$Builder[] 一起被调用。



[[testing.spring-boot-applications.customizing-web-test-client]]
== 自定义 WebTestClient

要自定义 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] bean，请配置一个 javadoc:org.springframework.boot.webtestclient.autoconfigure.WebTestClientBuilderCustomizer[] bean。
任何此类 beans 都会与用于创建 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 的 javadoc:org.springframework.test.web.reactive.server.WebTestClient$Builder[] 一起被调用。



[[testing.spring-boot-applications.jmx]]
== 使用 JMX

由于测试上下文框架会缓存上下文，JMX 默认被禁用，以防止相同的组件注册到同一域。
如果此类测试需要访问 javadoc:javax.management.MBeanServer[]，请考虑也将其标记为脏：

[source,java]
----
import javax.management.MBeanServer;

import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(properties = "spring.jmx.enabled=true")
@DirtiesContext
class MyJmxTests {

	@Autowired
	private MBeanServer mBeanServer;

	@Test
	void exampleTest() {
		assertThat(this.mBeanServer.getDomains()).contains("java.lang");
		// ...
	}

}
----



[[testing.spring-boot-applications.observations]]
== 使用 Observations

如果你使用 `spring-boot-micrometer-tracing-test` 中的 javadoc:org.springframework.boot.micrometer.tracing.test.autoconfigure.AutoConfigureTracing[format=annotation] 或 `spring-boot-micrometer-metrics-test` 中的 javadoc:org.springframework.boot.micrometer.metrics.test.autoconfigure.AutoConfigureMetrics[format=annotation] 注解 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[切片测试]，它会自动配置一个 javadoc:io.micrometer.observation.ObservationRegistry[]。



[[testing.spring-boot-applications.metrics]]
== 使用 Metrics

无论你的 classpath 是什么，使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 时，除内存支持外，meter registries 不会自动配置。

如果你需要在集成测试中将指标导出到不同的后端，请使用 javadoc:org.springframework.boot.micrometer.metrics.test.autoconfigure.AutoConfigureMetrics[format=annotation] 注解它。

如果你使用 javadoc:org.springframework.boot.micrometer.metrics.test.autoconfigure.AutoConfigureMetrics[format=annotation] 注解 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[切片测试]，它会自动配置一个内存中的 javadoc:io.micrometer.core.instrument.MeterRegistry[]。
切片测试中不支持使用 javadoc:org.springframework.boot.micrometer.metrics.test.autoconfigure.AutoConfigureMetrics[format=annotation] 注解导出数据。



[[testing.spring-boot-applications.tracing]]
== 使用 Tracing

无论你的 classpath 是什么，使用 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 时，报告数据的 tracing 组件不会自动配置。

如果你需要这些组件作为集成测试的一部分，请使用 javadoc:org.springframework.boot.micrometer.tracing.test.autoconfigure.AutoConfigureTracing[format=annotation] 注解测试。

如果你创建了自己的报告组件（例如自定义 javadoc:io.opentelemetry.sdk.trace.export.SpanExporter[] 或 `brave.handler.SpanHandler`），并且不希望它们在测试中处于活动状态，可以使用 javadoc:org.springframework.boot.micrometer.tracing.autoconfigure.ConditionalOnEnabledTracingExport[format=annotation] 注解来禁用它们。

如果你使用 javadoc:org.springframework.boot.micrometer.tracing.test.autoconfigure.AutoConfigureTracing[format=annotation] 注解 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-tests[切片测试]，它会自动配置一个无操作的 javadoc:io.micrometer.tracing.Tracer[]。
切片测试中不支持使用 javadoc:org.springframework.boot.micrometer.tracing.test.autoconfigure.AutoConfigureTracing[format=annotation] 注解导出数据。



[[testing.spring-boot-applications.mocking-beans]]
== Mock 和 Spy Bean

在运行测试时，有时需要模拟应用程序上下文中的某些组件。
例如，你可能有一个封装了某些在开发期间不可用的远程服务的门面。
当你想要模拟在真实环境中难以触发的故障时，Mocking 也很有用。

Spring 框架包含一个 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] 注解，可用于在你的 javadoc:org.springframework.context.ApplicationContext[] 内为 bean 定义 Mockito mock。
此外，javadoc:org.springframework.test.context.bean.override.mockito.MockitoSpyBean[format=annotation] 可用于定义 Mockito spy。\n在 {url-spring-framework-docs}/testing/annotations/integration-spring/annotation-mockitobean.html[Spring 框架文档] 中了解有关这些功能的更多信息。



[[testing.spring-boot-applications.autoconfigured-tests]]
== 自动配置的测试

Spring Boot 的自动配置系统适用于应用程序，但有时对于测试来说可能有点过多。
通常，只加载测试应用程序 "`slice`" 所需的配置部分会有所帮助。
例如，你可能想测试 Spring MVC 控制器是否正确映射 URL，并且不希望在这些测试中涉及数据库调用；或者你可能想测试 JPA 实体，而在运行这些测试时对 Web 层不感兴趣。

当与 `spring-boot-test-autoconfigure` 结合使用时，Spring Boot 的 xref:reference:testing/test-modules.adoc[测试模块] 包含许多注解，可用于自动配置此类“`slices`”。每个模块的工作方式类似，提供一个 `@...Test` 注解，用于加载 javadoc:org.springframework.context.ApplicationContext[] 以及一个或多个 `@AutoConfigure...` 注解，可用于自定义自动配置设置。

注意：每个切片将组件扫描限制为适当的组件，并加载非常有限的自动配置类集。如果需要排除其中一个，大多数 `@...Test` 注解提供 `excludeAutoConfiguration` 属性。或者，你可以使用 `@ImportAutoConfiguration#exclude`。

注意：不支持通过在一个测试中使用多个 `@...Test` 注解来包含多个“`slices`”。如果需要多个“`slices`”，请选择一个 `@...Test` 注解，并手动包含其他“`slices`”的 `@AutoConfigure...` 注解。

提示：也可以将 `@AutoConfigure...` 注解与标准的 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 注解一起使用。如果你对“`slicing`”你的应用程序不感兴趣，但想要一些自动配置的测试 beans，则可以使用这种组合。



[[testing.spring-boot-applications.json-tests]]
== 自动配置的 JSON 测试

要测试对象 JSON 序列化和反序列化是否按预期工作，你可以使用 `spring-boot-test-autoconfigure` 模块中的 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 注解。javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 自动配置可用的受支持 JSON 映射器，可以是以下库之一：

* Jackson javadoc:tools.jackson.databind.json.JsonMapper[]，任何 javadoc:org.springframework.boot.jackson.JacksonComponent[format=annotation] beans 和任何 Jackson javadoc:tools.jackson.databind.JacksonModule[]
* Jackson 2（已弃用）javadoc:com.fasterxml.jackson.databind.ObjectMapper[]，任何 javadoc:org.springframework.boot.jackson2.JsonComponent[format=annotation] beans 和任何 Jackson javadoc:com.fasterxml.jackson.databind.Module[]
* `Gson`
* `Jsonb`

提示：由 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 启用的自动配置列表可以在附录中找到。

如果需要配置自动配置的元素，可以使用 javadoc:org.springframework.boot.test.autoconfigure.json.AutoConfigureJsonTesters[format=annotation] 注解。

Spring Boot 包含基于 AssertJ 的辅助类，这些类与 JSONAssert 和 JsonPath 库一起使用，以检查 JSON 是否符合预期。javadoc:org.springframework.boot.test.json.JacksonTester[]、javadoc:org.springframework.boot.test.json.GsonTester[]、javadoc:org.springframework.boot.test.json.JsonbTester[] 和 javadoc:org.springframework.boot.test.json.BasicJsonTester[] 类分别用于 Jackson、Gson、Jsonb 和字符串。当使用 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation] 时，测试类上的任何辅助字段都可以 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation]。以下示例显示了一个用于 Jackson 的测试类：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.json.JsonTest;
import org.springframework.boot.test.json.JacksonTester;

import static org.assertj.core.api.Assertions.assertThat;

@JsonTest
class MyJsonTests {

	@Autowired
	private JacksonTester<VehicleDetails> json;

	@Test
	void serialize() throws Exception {
		VehicleDetails details = new VehicleDetails("Honda", "Civic");
		// Assert against a `.json` file in the same package as the test
		assertThat(this.json.write(details)).isEqualToJson("expected.json");
		// Or use JSON path based assertions
		assertThat(this.json.write(details)).hasJsonPathStringValue("@.make");
		assertThat(this.json.write(details)).extractingJsonPathStringValue("@.make").isEqualTo("Honda");
	}

	@Test
	void deserialize() throws Exception {
		String content = "{\"make\":\"Ford\",\"model\":\"Focus\"}";
		assertThat(this.json.parse(content)).isEqualTo(new VehicleDetails("Ford", "Focus"));
		assertThat(this.json.parseObject(content).getMake()).isEqualTo("Ford");
	}

}
----

注意：JSON 辅助类也可以直接在标准单元测试中使用。为此，如果你不使用 javadoc:org.springframework.boot.test.autoconfigure.json.JsonTest[format=annotation]，请在 javadoc:org.junit.jupiter.api.BeforeEach[format=annotation] 方法中调用辅助类的 `initFields` 方法。

如果你使用 Spring Boot 的基于 AssertJ 的辅助类来断言给定 JSON 路径上的数值，则可能无法根据类型使用 `isEqualTo`。相反，你可以使用 AssertJ 的 `satisfies` 来断言该值匹配给定条件。例如，以下示例断言实际数值是一个浮点值，接近 `0.15`，偏移量为 `0.01`。

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.json.JsonTest;
import org.springframework.boot.test.json.JacksonTester;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

@JsonTest
class MyJsonAssertJTests {

	@Autowired
	private JacksonTester<SomeObject> json;

	@Test
	void someTest() throws Exception {
		SomeObject value = new SomeObject(0.152f);
		assertThat(this.json.write(value)).extractingJsonPathNumberValue("@.test.numberValue")
			.satisfies((number) -> assertThat(number.floatValue()).isCloseTo(0.15f, within(0.01f)));
	}

}
----



[[testing.spring-boot-applications.spring-mvc-tests]]
== 自动配置的 Spring MVC 测试

要测试 Spring MVC 控制器是否按预期工作，请使用 `spring-boot-webmvc-test` 模块中的 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 注解。javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 自动配置 Spring MVC 基础设施，并将扫描的 beans 限制为 javadoc:org.springframework.stereotype.Controller[format=annotation]、javadoc:org.springframework.web.bind.annotation.ControllerAdvice[format=annotation]、javadoc:org.springframework.boot.jackson.JacksonComponent[format=annotation]、javadoc:org.springframework.boot.jackson2.JsonComponent[format=annotation]（已弃用）、javadoc:org.springframework.core.convert.converter.Converter[]、javadoc:org.springframework.core.convert.converter.GenericConverter[]、javadoc:jakarta.servlet.Filter[]、javadoc:org.springframework.web.servlet.HandlerInterceptor[]、javadoc:org.springframework.web.servlet.config.annotation.WebMvcConfigurer[]、javadoc:org.springframework.boot.webmvc.autoconfigure.WebMvcRegistrations[] 和 javadoc:org.springframework.web.method.support.HandlerMethodArgumentResolver[]。当使用 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

提示：由 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 启用的自动配置设置列表可以在附录中找到。

提示：如果需要注册额外的组件，例如 javadoc:tools.jackson.databind.JacksonModule[]，你可以通过在测试中使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 来导入额外的配置类。

通常，javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 限于单个控制器，并与 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] 结合使用，为所需的协作者提供模拟实现。

javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 还自动配置 javadoc:org.springframework.test.web.servlet.MockMvc[]。Mock MVC 提供了一种强大的方法，可以快速测试 MVC 控制器，而无需启动完整的 HTTP 服务器。如果 AssertJ 可用，javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[] 提供的 AssertJ 支持也会自动配置。如果你想在测试中使用 javadoc:org.springframework.test.web.servlet.client.RestTestClient[]，请使用 javadoc:org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient[format=annotation] 注释你的测试类。然后，将自动配置一个使用 Mock MVC 基础设施的 `RestTestClient`。

提示：你也可以通过使用 javadoc:org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc[format=annotation] 注释，在非 `@WebMvcTest`（例如 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation]）中自动配置 javadoc:org.springframework.test.web.servlet.MockMvc[] 和 javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[]。以下示例使用 javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[]：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.assertj.MockMvcTester;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.BDDMockito.given;

@WebMvcTest(UserVehicleController.class)
class MyControllerTests {

	@Autowired
	private MockMvcTester mvc;

	@MockitoBean
	private UserVehicleService userVehicleService;

	@Test
	void testExample() {
		// @formatter:off
		given(this.userVehicleService.getVehicleDetails("sboot"))
			.willReturn(new VehicleDetails("Honda", "Civic"));
		assertThat(this.mvc.get().uri("/sboot/vehicle").accept(MediaType.TEXT_PLAIN))
			.hasStatusOk()
			.hasBodyTextEqualTo("Honda Civic");
		// @formatter:on
	}

}
----

提示：如果需要配置自动配置的元素（例如，何时应用 servlet 过滤器），你可以在 javadoc:org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc[format=annotation] 注解中使用属性。

如果你使用 HtmlUnit 和 Selenium，自动配置还提供 HtmlUnit javadoc:org.springframework.web.reactive.function.client.WebClient[] bean 和/或 Selenium javadoc:org.openqa.selenium.WebDriver[] bean。以下示例使用 HtmlUnit：

[source,java]
----
import org.htmlunit.WebClient;
import org.htmlunit.html.HtmlPage;
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.BDDMockito.given;

@WebMvcTest(UserVehicleController.class)
class MyHtmlUnitTests {

	@Autowired
	private WebClient webClient;

	@MockitoBean
	private UserVehicleService userVehicleService;

	@Test
	void testExample() throws Exception {
		given(this.userVehicleService.getVehicleDetails("sboot")).willReturn(new VehicleDetails("Honda", "Civic"));
		HtmlPage page = this.webClient.getPage("/sboot/vehicle.html");
		assertThat(page.getBody().getTextContent()).isEqualTo("Honda Civic");
	}

}
----

注意：默认情况下，Spring Boot 将 javadoc:org.openqa.selenium.WebDriver[] beans 放在特殊的“`scope`”中，以确保驱动程序在每个测试后退出，并注入新实例。如果你不希望这样，可以将 `@Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)` 添加到你的 javadoc:org.openqa.selenium.WebDriver[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 定义中。

警告：Spring Boot 创建的 `webDriver` 作用域将替换任何用户定义的相同名称的作用域。如果你定义了自己的 `webDriver` 作用域，你可能会发现它在使用 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 时停止工作。

如果 Spring Security 在 classpath 上，javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation] 也会扫描 javadoc:org.springframework.security.config.annotation.web.WebSecurityConfigurer[] beans。你可以使用 Spring Security 的测试支持，而不是完全禁用此类测试的安全性。有关如何使用 Spring Security 的 javadoc:org.springframework.test.web.servlet.MockMvc[] 支持的更多详细信息，请参阅本 xref:how-to:testing.adoc#howto.testing.with-spring-security[]“`How-to Guides`”部分。

提示：有时编写 Spring MVC 测试是不够的；Spring Boot 可以帮助你运行 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-running-server[使用实际服务器的完整端到端测试]。



[[testing.spring-boot-applications.spring-webflux-tests]]
== 自动配置的 Spring WebFlux 测试

要测试 {url-spring-framework-docs}/web-reactive.html[Spring WebFlux] 控制器是否按预期工作，你可以使用 `spring-boot-webflux-test` 模块中的 javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 注解。javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 自动配置 Spring WebFlux 基础设施，并将扫描的 beans 限制为 javadoc:org.springframework.stereotype.Controller[format=annotation]、javadoc:org.springframework.web.bind.annotation.ControllerAdvice[format=annotation]、javadoc:org.springframework.boot.jackson.JacksonComponent[format=annotation]、javadoc:org.springframework.boot.jackson2.JsonComponent[format=annotation]（已弃用）、javadoc:org.springframework.core.convert.converter.Converter[]、javadoc:org.springframework.core.convert.converter.GenericConverter[] 和 javadoc:org.springframework.web.reactive.config.WebFluxConfigurer[]。当使用 javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

TIP: javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 启用的自动配置列表可 xref:appendix:test-auto-configuration/index.adoc[在附录中找到]。

TIP: 如果需要注册额外组件（例如 javadoc:tools.jackson.databind.JacksonModule[]），可以在测试中使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 导入其他配置类。

通常，javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 仅限于单个控制器，并与 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] 注解结合使用，为所需的协作者提供模拟实现。

javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 还会自动配置 {url-spring-framework-docs}/testing/webtestclient.html[`WebTestClient`]，它提供了一种无需启动完整 HTTP 服务器即可快速测试 WebFlux 控制器的强大方法。

TIP: 你也可以通过使用 javadoc:org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient[format=annotation] 注解，在非 `@WebFluxTest`（例如 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation]）中自动配置 javadoc:org.springframework.test.web.reactive.server.WebTestClient[]。

以下示例展示了一个同时使用 javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 和 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 的类：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webflux.test.autoconfigure.WebFluxTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.reactive.server.WebTestClient;

import static org.mockito.BDDMockito.given;

@WebFluxTest(UserVehicleController.class)
class MyControllerTests {

	@Autowired
	private WebTestClient webClient;

	@MockitoBean
	private UserVehicleService userVehicleService;

	@Test
	void testExample() {
		// @formatter:off
		given(this.userVehicleService.getVehicleDetails("sboot"))
			.willReturn(new VehicleDetails("Honda", "Civic"));
		this.webClient.get().uri("/sboot/vehicle").accept(MediaType.TEXT_PLAIN).exchange()
			.expectStatus().isOk()
			.expectBody(String.class).isEqualTo("Honda Civic");
		// @formatter:on
	}

}
----

TIP: 此设置仅受 WebFlux 应用程序支持，因为在模拟的 Web 应用程序中使用 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 目前仅适用于 WebFlux。

NOTE: javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 无法检测通过函数式 Web 框架注册的路由。
要测试上下文中的 javadoc:org.springframework.web.reactive.function.server.RouterFunction[] beans，请考虑使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 或 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 自行导入 javadoc:org.springframework.web.reactive.function.server.RouterFunction[]。

NOTE: javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 无法检测注册为 javadoc:org.springframework.context.annotation.Bean[format=annotation] 类型 javadoc:org.springframework.security.web.server.SecurityWebFilterChain[] 的自定义安全配置。
要将其包含在测试中，你需要使用 javadoc:org.springframework.context.annotation.Import[format=annotation] 或 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 导入注册 bean 的配置。

TIP: 有时编写 Spring WebFlux 测试是不够的；Spring Boot 可以帮助你运行 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.with-running-server[使用实际服务器的完整端到端测试]。


[[testing.spring-boot-applications.spring-graphql-tests]]
== 自动配置的 Spring GraphQL 测试

Spring GraphQL 提供了一个专用的测试支持模块；你需要将其添加到项目中：

.Maven
[source,xml]
----
<dependencies>
	<dependency>
		<groupId>org.springframework.graphql</groupId>
		<artifactId>spring-graphql-test</artifactId>
		<scope>test</scope>
	</dependency>
	<!-- Unless already present in the compile scope -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-webflux</artifactId>
		<scope>test</scope>
	</dependency>
</dependencies>
----

.Gradle
[source,gradle]
----
dependencies {
	testImplementation("org.springframework.graphql:spring-graphql-test")
	// Unless already present in the implementation configuration
	testImplementation("org.springframework.boot:spring-boot-starter-webflux")
}
----
该测试模块提供了 {url-spring-graphql-docs}/testing.html#testing.graphqltester[GraphQlTester]。
该测试器在测试中广泛使用，因此请务必熟悉其用法。
有 javadoc:org.springframework.graphql.test.tester.GraphQlTester[] 种变体，Spring Boot 会根据测试类型自动配置它们：

* javadoc:org.springframework.graphql.test.tester.ExecutionGraphQlServiceTester[] 在服务端执行测试，无需客户端或传输层
* javadoc:org.springframework.graphql.test.tester.HttpGraphQlTester[] 使用连接到服务器的客户端执行测试，无论是否有真实服务器

Spring Boot 帮助您使用 {url-spring-graphql-docs}/controllers.html[Spring GraphQL 控制器] 进行测试，它来自 javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation] 注解模块。
javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation] 自动配置 Spring GraphQL 基础设施，不涉及任何传输层或服务器。
这会将扫描的 beans 限制为 javadoc:org.springframework.stereotype.Controller[format=annotation]、javadoc:org.springframework.web.bind.annotation.ControllerAdvice[format=annotation]、javadoc:org.springframework.graphql.execution.RuntimeWiringConfigurer[]、javadoc:org.springframework.boot.jackson.JacksonComponent[]、javadoc:org.springframework.boot.jackson2.JsonComponent[format=annotation]（已弃用）、javadoc:org.springframework.core.convert.converter.Converter[]、javadoc:org.springframework.core.convert.converter.GenericConverter[]、javadoc:org.springframework.graphql.execution.DataFetcherExceptionResolver[]、javadoc:graphql.execution.instrumentation.Instrumentation[] 和 javadoc:org.springframework.boot.graphql.autoconfigure.GraphQlSourceBuilderCustomizer[]。
使用 javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

提示：javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation] 启用的自动配置列表可以 xref:appendix:test-auto-configuration/index.adoc[在附录中找到]。

通常，javadoc:org.springframework.boot.graphql.test.autoconfigure.GraphQlTest[format=annotation] 仅限于一组控制器，并与 javadoc:org.springframework.test.context.bean.override.mockito.MockitoBean[format=annotation] 注解结合使用，为所需的协作者提供模拟实现。

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.docs.web.graphql.runtimewiring.GreetingController;
import org.springframework.boot.graphql.test.autoconfigure.GraphQlTest;
import org.springframework.graphql.test.tester.GraphQlTester;

@GraphQlTest(GreetingController.class)
class GreetingControllerTests {

	@Autowired
	private GraphQlTester graphQlTester;

	@Test
	void shouldGreetWithSpecificName() {
		this.graphQlTester.document("{ greeting(name: \"Alice\") } ")
			.execute()
			.path("greeting")
			.entity(String.class)
			.isEqualTo("Hello, Alice!");
	}

	@Test
	void shouldGreetWithDefaultName() {
		this.graphQlTester.document("{ greeting } ")
			.execute()
			.path("greeting")
			.entity(String.class)
			.isEqualTo("Hello, Spring!");
	}

}
----

javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation] 测试是完整的集成测试，涉及整个应用程序。
可以通过使用来自 `spring-boot-graphql-test` 模块的 javadoc:org.springframework.boot.graphql.test.autoconfigure.tester.AutoConfigureHttpGraphQlTester[format=annotation] 注解测试类来添加 javadoc:org.springframework.graphql.test.tester.HttpGraphQlTester[] bean：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.graphql.test.autoconfigure.tester.AutoConfigureHttpGraphQlTester;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.graphql.test.tester.HttpGraphQlTester;

@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@AutoConfigureHttpGraphQlTester
class GraphQlIntegrationTests {

	@Test
	void shouldGreetWithSpecificName(@Autowired HttpGraphQlTester graphQlTester) {
		HttpGraphQlTester authenticatedTester = graphQlTester.mutate()
			.webTestClient((client) -> client.defaultHeaders((headers) -> headers.setBasicAuth("admin", "ilovespring")))
			.build();
		authenticatedTester.document("{ greeting(name: \"Alice\") } ")
			.execute()
			.path("greeting")
			.entity(String.class)
			.isEqualTo("Hello, Alice!");
	}

}
----

javadoc:org.springframework.graphql.test.tester.HttpGraphQlTester[] bean 使用集成测试的相关传输层。
当使用随机或指定端口时，测试器会针对真实服务器进行配置。
要将测试器绑定到 `MockMvc`，请确保使用 javadoc:org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc[format=annotation] 注解测试类。


[[testing.spring-boot-applications.autoconfigured-spring-data-cassandra]]
== 自动配置的 Data Cassandra 测试

您可以使用来自 `spring-boot-data-cassandra-test` 模块的 javadoc:org.springframework.boot.data.cassandra.test.autoconfigure.DataCassandraTest[format=annotation] 来测试 Data Cassandra 应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.data.cassandra.core.CassandraTemplate[]，扫描 javadoc:org.springframework.data.cassandra.core.mapping.Table[format=annotation] 类，并配置 Spring Data Cassandra 仓库。
使用 javadoc:org.springframework.boot.data.cassandra.test.autoconfigure.DataCassandraTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
（有关在 Spring Boot 中使用 Cassandra 的更多信息，请参见 xref:data/nosql.adoc#data.nosql.cassandra[]。）

提示：javadoc:org.springframework.boot.data.cassandra.test.autoconfigure.DataCassandraTest[format=annotation] 启用的自动配置设置列表可以 xref:appendix:test-auto-configuration/index.adoc[在附录中找到]。

以下示例展示了在 Spring Boot 中使用 Cassandra 测试的典型设置：

[source,java]
----
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.cassandra.test.autoconfigure.DataCassandraTest;

@DataCassandraTest
class MyDataCassandraTests {

	@Autowired
	@SuppressWarnings("unused")
	private SomeRepository repository;

}
----


[[testing.spring-boot-applications.autoconfigured-spring-data-couchbase]]
== 自动配置的 Data Couchbase 测试

您可以使用来自 `spring-boot-data-couchbase-test` 模块的 javadoc:org.springframework.boot.data.couchbase.test.autoconfigure.DataCouchbaseTest[format=annotation] 来测试 Data Couchbase 应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.data.couchbase.core.CouchbaseTemplate[] 或 javadoc:org.springframework.data.couchbase.core.ReactiveCouchbaseTemplate[]，扫描 javadoc:org.springframework.data.couchbase.core.mapping.Document[format=annotation] 类，并配置 Spring Data Couchbase 仓库。
使用 javadoc:org.springframework.boot.data.couchbase.test.autoconfigure.DataCouchbaseTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
（有关在 Spring Boot 中使用 Couchbase 的更多信息，请参见本章前面的 xref:data/nosql.adoc#data.nosql.couchbase[]。）

提示：javadoc:org.springframework.boot.data.couchbase.test.autoconfigure.DataCouchbaseTest[format=annotation] 启用的自动配置设置列表可以 xref:appendix:test-auto-configuration/index.adoc[在附录中找到]。

以下示例展示了在 Spring Boot 中使用 Couchbase 测试的典型设置：

[source,java]
----
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.couchbase.test.autoconfigure.DataCouchbaseTest;

@DataCouchbaseTest
class MyDataCouchbaseTests {

	@Autowired
	@SuppressWarnings("unused")
	private SomeRepository repository;

	// ...

}
----


[[testing.spring-boot-applications.autoconfigured-spring-data-elasticsearch]]
== 自动配置的 Data Elasticsearch 测试

您可以使用来自 `spring-boot-data-elasticsearch-test` 模块的 javadoc:org.springframework.boot.data.elasticsearch.test.autoconfigure.DataElasticsearchTest[format=annotation] 来测试 Data Elasticsearch 应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate[]，扫描 javadoc:org.springframework.data.elasticsearch.annotations.Document[format=annotation] 类，并配置 Spring Data Elasticsearch 仓库。
使用 javadoc:org.springframework.boot.data.elasticsearch.test.autoconfigure.DataElasticsearchTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
（有关在 Spring Boot 中使用 Elasticsearch 的更多信息，请参见本章前面的 xref:data/nosql.adoc#data.nosql.elasticsearch[]。）

提示：javadoc:org.springframework.boot.data.elasticsearch.test.autoconfigure.DataElasticsearchTest[format=annotation] 启用的自动配置设置列表可以 xref:appendix:test-auto-configuration/index.adoc[在附录中找到]。

以下示例展示了在 Spring Boot 中使用 Elasticsearch 测试的典型设置：

[source,java]
----
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.elasticsearch.test.autoconfigure.DataElasticsearchTest;

@DataElasticsearchTest
class MyDataElasticsearchTests {

	@Autowired
	@SuppressWarnings("unused")
	private SomeRepository repository;

	// ...

}
----


[[testing.spring-boot-applications.autoconfigured-spring-data-jpa]]
== 自动配置的 Data JPA 测试

您可以使用来自 `spring-boot-data-jpa-test` 模块的 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 注解来测试 Data JPA 应用程序。
默认情况下，它会扫描 javadoc:jakarta.persistence.Entity[format=annotation] 类并配置 Spring Data JPA 仓库。
如果 classpath 上有可用的嵌入式数据库，它也会配置一个。
默认情况下，通过将 `spring.jpa.show-sql` 属性设置为 `true` 来记录 SQL 查询。
这可以通过注解的 `showSql` 属性禁用。

使用 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

提示：javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 启用的自动配置设置列表可以 xref:appendix:test-auto-configuration/index.adoc[在附录中找到]。

默认情况下，Data JPA 测试是事务性的，并在每个测试结束时回滚。
有关更多详细信息，请参见 Spring 框架参考文档中的 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[相关章节]。
如果这不是您想要的，您可以按如下方式禁用测试或整个类的事务管理：

[source,java]
----
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@DataJpaTest
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class MyNonTransactionalTests {

	// ...

}
----

Data JPA 测试还可以注入一个 javadoc:org.springframework.boot.jpa.test.autoconfigure.TestEntityManager[] bean，它提供了标准 JPA javadoc:jakarta.persistence.EntityManager[] 的替代方案，专门为测试设计。

提示：javadoc:org.springframework.boot.jpa.test.autoconfigure.TestEntityManager[] 也可以通过添加 javadoc:org.springframework.boot.jpa.test.autoconfigure.AutoConfigureTestEntityManager[format=annotation] 自动配置到任何基于 Spring 的测试类中。
这样做时，请确保您的测试在事务中运行，例如通过在测试类或方法上添加 javadoc:org.springframework.transaction.annotation.Transactional[format=annotation]。

如果您需要，也可以使用 javadoc:org.springframework.jdbc.core.JdbcTemplate[]。
以下示例展示了 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 注解的使用：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jpa.test.autoconfigure.TestEntityManager;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
class MyRepositoryTests {

	@Autowired
	private TestEntityManager entityManager;

	@Autowired
	private UserRepository repository;

	@Test
	void testExample() {
		this.entityManager.persist(new User("sboot", "1234"));
		User user = this.repository.findByUsername("sboot");
		assertThat(user.getUsername()).isEqualTo("sboot");
		assertThat(user.getEmployeeNumber()).isEqualTo("1234");
	}

}
----

内存中的嵌入式数据库通常非常适合测试，因为它们速度快且无需任何安装。
但是，如果你更倾向于针对真实数据库运行测试，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] 注解，如下例所示：

[source,java]
----
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase.Replace;

@DataJpaTest
@AutoConfigureTestDatabase(replace = Replace.NONE)
class MyRepositoryTests {

	// ...

}
----



[[testing.spring-boot-applications.autoconfigured-jdbc]]
== 自动配置的 JDBC 测试

javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] 来自 `spring-boot-jdbc-test` 模块，类似于 javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation]，但适用于仅需要 javadoc:javax.sql.DataSource[] 且不使用 Spring Data JDBC 的测试。
默认情况下，它会配置一个内存中的嵌入式数据库和一个 javadoc:org.springframework.jdbc.core.JdbcTemplate[]。
使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

提示：javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中]找到。

默认情况下，JDBC 测试是事务性的，并在每个测试结束时回滚。
更多详情，请参阅 Spring 框架参考文档中的 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[相关章节]。
如果这不是你想要的，你可以禁用测试或整个类的事务管理，如下所示：

[source,java]
----
import org.springframework.boot.jdbc.test.autoconfigure.JdbcTest;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@JdbcTest
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class MyTransactionalTests {

}
----

如果你希望测试针对真实数据库运行，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] 注解，方式与 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 相同。
（参见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-spring-data-jpa[]。）



[[testing.spring-boot-applications.autoconfigured-spring-data-jdbc]]
== 自动配置的 Data JDBC 测试

javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation] 来自 `spring-boot-data-jdbc-test` 模块，类似于 javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation]，但适用于使用 Spring Data JDBC 仓库的测试。
默认情况下，它会配置一个内存中的嵌入式数据库、一个 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 和 Spring Data JDBC 仓库。
使用 javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation] 注解时，仅扫描 javadoc:org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration[] 子类，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

提示：javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中]找到。

默认情况下，Data JDBC 测试是事务性的，并在每个测试结束时回滚。
更多详情，请参阅 Spring 框架参考文档中的 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[相关章节]。
如果这不是你想要的，你可以禁用测试或整个测试类的事务管理，如 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-jdbc[JDBC 示例所示]。

如果你希望测试针对真实数据库运行，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] 注解，方式与 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 相同。
（参见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-spring-data-jpa[]。）



[[testing.spring-boot-applications.autoconfigured-spring-data-r2dbc]]
== 自动配置的 Data R2DBC 测试

javadoc:org.springframework.boot.data.r2dbc.test.autoconfigure.DataR2dbcTest[format=annotation] 来自 `spring-boot-data-r2dbc-test` 模块，类似于 javadoc:org.springframework.boot.data.jdbc.test.autoconfigure.DataJdbcTest[format=annotation]，但适用于使用 Spring Data R2DBC 仓库的测试。
默认情况下，它会配置一个内存中的嵌入式数据库、一个 javadoc:org.springframework.data.r2dbc.core.R2dbcEntityTemplate[] 和 Spring Data R2DBC 仓库。
使用 javadoc:org.springframework.boot.data.r2dbc.test.autoconfigure.DataR2dbcTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

提示：javadoc:org.springframework.boot.data.r2dbc.test.autoconfigure.DataR2dbcTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中]找到。

默认情况下，Data R2DBC 测试不是事务性的。

如果你希望测试针对真实数据库运行，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] 注解，方式与 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 相同。
（参见 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-spring-data-jpa[]。）



[[testing.spring-boot-applications.autoconfigured-jooq]]
== 自动配置的 jOOQ 测试

你可以使用来自 `spring-boot-jooq-test` 的 javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation]，方式与 javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] 类似，但用于 jOOQ 相关的测试。
由于 jOOQ 严重依赖于与数据库模式对应的 Java 模式，因此使用了现有的 javadoc:javax.sql.DataSource[]。
如果你想将其替换为内存数据库，可以使用 javadoc:org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase[format=annotation] 覆盖这些设置。
（有关在 Spring Boot 中使用 jOOQ 的更多信息，请参见 xref:data/sql.adoc#data.sql.jooq[]。）
使用 javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

提示：javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation] 启用的自动配置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中]找到。

javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation] 配置一个 javadoc:org.jooq.DSLContext[]。
以下示例展示了 javadoc:org.springframework.boot.jooq.test.autoconfigure.JooqTest[format=annotation] 注解的使用：

[source,java]
----
import org.jooq.DSLContext;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.jooq.test.autoconfigure.JooqTest;

@JooqTest
class MyJooqTests {

	@Autowired
	@SuppressWarnings("unused")
	private DSLContext dslContext;

	// ...

}
----

默认情况下，jOOQ 测试是事务性的，并在每个测试结束时回滚。
如果这不是你想要的，你可以禁用测试或整个测试类的事务管理，如 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.autoconfigured-jdbc[JDBC 示例所示]。



[[testing.spring-boot-applications.autoconfigured-spring-data-mongodb]]
== 自动配置的 Data MongoDB 测试

你可以使用来自 `spring-boot-data-mongodb-test` 模块的 javadoc:org.springframework.boot.data.mongodb.test.autoconfigure.DataMongoTest[format=annotation] 来测试 MongoDB 应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.data.mongodb.core.MongoTemplate[]，扫描 javadoc:org.springframework.data.mongodb.core.mapping.Document[format=annotation] 类，并配置 Spring Data MongoDB 仓库。
使用 javadoc:org.springframework.boot.data.mongodb.test.autoconfigure.DataMongoTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
（有关在 Spring Boot 中使用 MongoDB 的更多信息，请参见 xref:data/nosql.adoc#data.nosql.mongodb[]。）

提示：javadoc:org.springframework.boot.data.mongodb.test.autoconfigure.DataMongoTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中]找到。

以下类展示了 javadoc:org.springframework.boot.data.mongodb.test.autoconfigure.DataMongoTest[format=annotation] 注解的使用：

[source,java]
----
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.mongodb.test.autoconfigure.DataMongoTest;
import org.springframework.data.mongodb.core.MongoTemplate;

@DataMongoTest
class MyDataMongoDbTests {

	@Autowired
	@SuppressWarnings("unused")
	private MongoTemplate mongoTemplate;

	// ...

}
----



[[testing.spring-boot-applications.autoconfigured-spring-data-neo4j]]
== 自动配置的 Data Neo4j 测试

你可以使用来自 `spring-boot-data-neo4j-test` 模块的 javadoc:org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest[format=annotation] 来测试 Neo4j 应用程序。
默认情况下，它会扫描 javadoc:org.springframework.data.neo4j.core.schema.Node[format=annotation] 类，并配置 Spring Data Neo4j 仓库。
使用 javadoc:org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。
（有关在 Spring Boot 中使用 Neo4J 的更多信息，请参见 xref:data/nosql.adoc#data.nosql.neo4j[]。）

提示：javadoc:org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中]找到。

以下示例展示了在 Spring Boot 中使用 Neo4J 测试的典型设置：

[source,java]
----
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest;

@DataNeo4jTest
class MyDataNeo4jTests {

	@Autowired
	@SuppressWarnings("unused")
	private SomeRepository repository;

	// ...

}
----

默认情况下，Data Neo4j 测试是事务性的，并在每个测试结束时回滚。
详情请参见 Spring 框架参考文档中的 {url-spring-framework-docs}/testing/testcontext-framework/tx.html#testcontext-tx-enabling-transactions[相关章节]。
如果这不是您想要的，您可以按如下方式禁用测试或整个类的事务管理：

[source,java]
----
import org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@DataNeo4jTest
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class MyDataNeo4jTests {

}
----

注意：响应式访问不支持事务性测试。如果您使用这种风格，必须按上述方式配置 javadoc:org.springframework.boot.data.neo4j.test.autoconfigure.DataNeo4jTest[format=annotation] 测试。



[[testing.spring-boot-applications.autoconfigured-spring-data-redis]]
== 自动配置的 Data Redis 测试

您可以使用 `spring-boot-data-redis-test` 模块中的 javadoc:org.springframework.boot.data.redis.test.autoconfigure.DataRedisTest[format=annotation] 来测试 Data Redis 应用程序。默认情况下，它会扫描 javadoc:org.springframework.data.redis.core.RedisHash[format=annotation] 类并配置 Spring Data Redis 仓库。使用 javadoc:org.springframework.boot.data.redis.test.autoconfigure.DataRedisTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。（有关在 Spring Boot 中使用 Redis 的更多信息，请参见 xref:data/nosql.adoc#data.nosql.redis[]。）

提示：由 javadoc:org.springframework.boot.data.redis.test.autoconfigure.DataRedisTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中找到]。

以下示例展示了 javadoc:org.springframework.boot.data.redis.test.autoconfigure.DataRedisTest[format=annotation] 注解的使用：

[source,java]
----
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.redis.test.autoconfigure.DataRedisTest;

@DataRedisTest
class MyDataRedisTests {

	@Autowired
	@SuppressWarnings("unused")
	private SomeRepository repository;

	// ...

}
----



[[testing.spring-boot-applications.autoconfigured-spring-data-ldap]]
== 自动配置的 Data LDAP 测试

您可以使用 javadoc:org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest[format=annotation] 来测试 Data LDAP 应用程序。默认情况下，它会配置一个内存中的嵌入式 LDAP（如果可用），配置一个 javadoc:org.springframework.ldap.core.LdapTemplate[]，扫描 javadoc:org.springframework.ldap.odm.annotations.Entry[format=annotation] 类，并配置 Spring Data LDAP 仓库。使用 javadoc:org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。（有关在 Spring Boot 中使用 LDAP 的更多信息，请参见 xref:data/nosql.adoc#data.nosql.ldap[]。）

提示：由 javadoc:org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中找到]。

以下示例展示了 javadoc:org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest[format=annotation] 注解的使用：

[source,java]
----
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest;
import org.springframework.ldap.core.LdapTemplate;

@DataLdapTest
class MyDataLdapTests {

	@Autowired
	@SuppressWarnings("unused")
	private LdapTemplate ldapTemplate;

	// ...

}
----

内存中的嵌入式 LDAP 通常适用于测试，因为它速度快且无需开发者安装。但是，如果您更倾向于针对真实的 LDAP 服务器运行测试，则应排除嵌入式 LDAP 自动配置，如下例所示：

[source,java]
----
import org.springframework.boot.data.ldap.test.autoconfigure.DataLdapTest;
import org.springframework.boot.ldap.autoconfigure.embedded.EmbeddedLdapAutoConfiguration;

@DataLdapTest(excludeAutoConfiguration = EmbeddedLdapAutoConfiguration.class)
class MyDataLdapTests {

	// ...

}
----



[[testing.spring-boot-applications.autoconfigured-rest-client]]
== 自动配置的 REST 客户端

您可以使用 `spring-boot-restclient-test` 模块中的 javadoc:org.springframework.boot.restclient.test.autoconfigure.RestClientTest[format=annotation] 注解来测试 REST 客户端。默认情况下，它会自动配置 Jackson、GSON 和 Jsonb 支持，配置一个 javadoc:org.springframework.boot.restclient.RestTemplateBuilder[] 和一个 javadoc:org.springframework.web.client.RestClient$Builder[]，并添加对 javadoc:org.springframework.test.web.client.MockRestServiceServer[] 的支持。使用 javadoc:org.springframework.boot.restclient.test.autoconfigure.RestClientTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

提示：由 javadoc:org.springframework.boot.restclient.test.autoconfigure.RestClientTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中找到]。

您想要测试的特定 beans 应通过 javadoc:org.springframework.boot.restclient.test.autoconfigure.RestClientTest[format=annotation] 的 `value` 或 `components` 属性指定。

当在测试中的 beans 中使用 javadoc:org.springframework.boot.restclient.RestTemplateBuilder[]，并且在构建 javadoc:org.springframework.web.client.RestTemplate[] 时调用了 `RestTemplateBuilder.rootUri(String rootUri)`，则应在 javadoc:org.springframework.test.web.client.MockRestServiceServer[] 期望中省略根 URI，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.restclient.test.autoconfigure.RestClientTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.client.MockRestServiceServer;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.requestTo;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withSuccess;

@RestClientTest(org.springframework.boot.docs.testing.springbootapplications.autoconfiguredrestclient.RemoteVehicleDetailsService.class)
class MyRestTemplateServiceTests {

	@Autowired
	private RemoteVehicleDetailsService service;

	@Autowired
	private MockRestServiceServer server;

	@Test
	void getVehicleDetailsWhenResultIsSuccessShouldReturnDetails() {
		this.server.expect(requestTo("/greet/details")).andRespond(withSuccess("hello", MediaType.TEXT_PLAIN));
		String greeting = this.service.callRestService();
		assertThat(greeting).isEqualTo("hello");
	}

}
----

当在测试中的 beans 中使用 javadoc:org.springframework.web.client.RestClient$Builder[]，或者使用 javadoc:org.springframework.boot.restclient.RestTemplateBuilder[] 且未调用 `rootUri(String rootURI)` 时，必须在 javadoc:org.springframework.test.web.client.MockRestServiceServer[] 期望中使用完整 URI，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.restclient.test.autoconfigure.RestClientTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.client.MockRestServiceServer;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.requestTo;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withSuccess;

@RestClientTest(RemoteVehicleDetailsService.class)
class MyRestClientServiceTests {

	@Autowired
	private RemoteVehicleDetailsService service;

	@Autowired
	private MockRestServiceServer server;

	@Test
	void getVehicleDetailsWhenResultIsSuccessShouldReturnDetails() {
		this.server.expect(requestTo("https://example.com/greet/details"))
			.andRespond(withSuccess("hello", MediaType.TEXT_PLAIN));
		String greeting = this.service.callRestService();
		assertThat(greeting).isEqualTo("hello");
	}

}
----



[[testing.spring-boot-applications.autoconfigured-web-client]]
== 自动配置的 Web 客户端

您可以使用 `spring-boot-webclient-test` 模块中的 javadoc:org.springframework.boot.webclient.test.autoconfigure.WebClientTest[format=annotation] 注解来测试使用 `WebClient` 的代码。默认情况下，它会自动配置 Jackson、GSON 和 Jsonb 支持，并配置一个 javadoc:org.springframework.web.reactive.function.client.WebClient$Builder[]。使用 javadoc:org.springframework.boot.webclient.test.autoconfigure.WebClientTest[format=annotation] 注解时，不会扫描常规的 javadoc:org.springframework.stereotype.Component[format=annotation] 和 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。javadoc:org.springframework.boot.context.properties.EnableConfigurationProperties[format=annotation] 可用于包含 javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] beans。

提示：由 javadoc:org.springframework.boot.webclient.test.autoconfigure.WebClientTest[format=annotation] 启用的自动配置设置列表可在 xref:appendix:test-auto-configuration/index.adoc[附录中找到]。

您想要测试的特定 beans 应通过 javadoc:org.springframework.boot.webclient.test.autoconfigure.WebClientTest[format=annotation] 的 `value` 或 `components` 属性指定。



[[testing.spring-boot-applications.autoconfigured-spring-restdocs]]
== 自动配置的 Spring REST Docs 测试

您可以使用 `spring-boot-restdocs-` 模块中的 javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 注解在 Mock MVC 或 WebTestClient 测试中使用 {url-spring-restdocs-site}[Spring REST Docs]。它消除了在 Spring REST Docs 中使用 JUnit 扩展的需要。

javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 可用于覆盖默认输出目录（如果使用 Maven 则为 `target/generated-snippets`，如果使用 Gradle 则为 `build/generated-snippets`）。它还可用于配置任何文档化 URI 中出现的主机、方案和端口。



[[testing.spring-boot-applications.autoconfigured-spring-restdocs.with-mock-mvc]]
=== 使用 Mock MVC 的自动配置 Spring REST Docs 测试

javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 自定义 javadoc:org.springframework.test.web.servlet.MockMvc[] bean，以便在测试基于 Servlet 的 Web 应用程序时使用 Spring REST Docs。您可以通过 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 注入它，并在测试中像通常使用 Mock MVC 和 Spring REST Docs 一样使用它，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.assertj.MockMvcTester;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.document;

@WebMvcTest(UserController.class)
@AutoConfigureRestDocs
class MyUserDocumentationTests {

	@Autowired
	private MockMvcTester mvc;

	@Test
	void listUsers() {
		assertThat(this.mvc.get().uri("/users").accept(MediaType.TEXT_PLAIN)).hasStatusOk()
			.apply(document("list-users"));
	}

}
----

如果您更喜欢使用 AssertJ 集成，javadoc:org.springframework.test.web.servlet.assertj.MockMvcTester[] 也可用，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.assertj.MockMvcTester;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.document;

@WebMvcTest(UserController.class)
@AutoConfigureRestDocs
class MyUserDocumentationTests {

	@Autowired
	private MockMvcTester mvc;

	@Test
	void listUsers() {
		assertThat(this.mvc.get().uri("/users").accept(MediaType.TEXT_PLAIN)).hasStatusOk()
			.apply(document("list-users"));
	}

}
----

两者在后台重用相同的 javadoc:org.springframework.test.web.servlet.MockMvc[] 实例，因此对其的任何配置都适用于两者。

如果您需要对 Spring REST Docs 配置进行比 javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 属性提供的更多控制，可以使用 javadoc:org.springframework.boot.restdocs.test.autoconfigure.RestDocsMockMvcConfigurationCustomizer[] bean，如下例所示：

[source,java]
----
import org.springframework.boot.restdocs.test.autoconfigure.RestDocsMockMvcConfigurationCustomizer;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.restdocs.mockmvc.MockMvcRestDocumentationConfigurer;
import org.springframework.restdocs.templates.TemplateFormats;

@TestConfiguration(proxyBeanMethods = false)
public class MyRestDocsConfiguration implements RestDocsMockMvcConfigurationCustomizer {

	@Override
	public void customize(MockMvcRestDocumentationConfigurer configurer) {
		configurer.snippets().withTemplateFormat(TemplateFormats.markdown());
	}

}
----

如果您想利用 Spring REST Docs 对参数化输出目录的支持，可以创建一个 javadoc:org.springframework.restdocs.mockmvc.RestDocumentationResultHandler[] bean。自动配置使用此结果处理器调用 `alwaysDo`，从而使每次 javadoc:org.springframework.test.web.servlet.MockMvc[] 调用自动生成默认片段。以下示例展示了 javadoc:org.springframework.restdocs.mockmvc.RestDocumentationResultHandler[] 的定义：

[source,java]
----
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.restdocs.mockmvc.MockMvcRestDocumentation;
import org.springframework.restdocs.mockmvc.RestDocumentationResultHandler;

@TestConfiguration(proxyBeanMethods = false)
public class MyResultHandlerConfiguration {

	@Bean
	public RestDocumentationResultHandler restDocumentation() {
		return MockMvcRestDocumentation.document("{method-name}");
	}

}
----



[[testing.spring-boot-applications.autoconfigured-spring-restdocs.with-web-test-client]]
=== 使用 WebTestClient 的自动配置 Spring REST Docs 测试

javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 也可以与 javadoc:org.springframework.test.web.reactive.server.WebTestClient[] 一起用于测试响应式 Web 应用程序。您可以通过 javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation] 注入它，并在测试中像通常使用 javadoc:org.springframework.boot.webflux.test.autoconfigure.WebFluxTest[format=annotation] 和 Spring REST Docs 一样使用它，如下例所示：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs;
import org.springframework.boot.webflux.test.autoconfigure.WebFluxTest;
import org.springframework.test.web.reactive.server.WebTestClient;

import static org.springframework.restdocs.webtestclient.WebTestClientRestDocumentation.document;

@WebFluxTest
@AutoConfigureRestDocs
class MyUsersDocumentationTests {

	@Autowired
	private WebTestClient webTestClient;

	@Test
	void listUsers() {
		// @formatter:off
		this.webTestClient
			.get().uri("/")
		.exchange()
		.expectStatus()
			.isOk()
		.expectBody()
			.consumeWith(document("list-users"));
		// @formatter:on
	}

}
----

如果您需要对 Spring REST Docs 配置进行比 javadoc:org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs[format=annotation] 属性提供的更多控制，可以使用 javadoc:org.springframework.boot.restdocs.test.autoconfigure.RestDocsWebTestClientConfigurationCustomizer[] bean，如下例所示：

[source,java]
----
import org.springframework.boot.restdocs.test.autoconfigure.RestDocsWebTestClientConfigurationCustomizer;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.restdocs.webtestclient.WebTestClientRestDocumentationConfigurer;

@TestConfiguration(proxyBeanMethods = false)
public class MyRestDocsConfiguration implements RestDocsWebTestClientConfigurationCustomizer {

	@Override
	public void customize(WebTestClientRestDocumentationConfigurer configurer) {
		configurer.snippets().withEncoding("UTF-8");
	}

}
----
如果你想利用 Spring REST Docs 对参数化输出目录的支持，可以使用 javadoc:org.springframework.boot.webtestclient.autoconfigure.WebTestClientBuilderCustomizer[] 为每个实体交换结果配置一个消费者。
以下示例展示了这样一个 javadoc:org.springframework.boot.webtestclient.autoconfigure.WebTestClientBuilderCustomizer[] 的定义：

[source,java]
----
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.webtestclient.autoconfigure.WebTestClientBuilderCustomizer;
import org.springframework.context.annotation.Bean;

import static org.springframework.restdocs.webtestclient.WebTestClientRestDocumentation.document;

@TestConfiguration(proxyBeanMethods = false)
public class MyWebTestClientBuilderCustomizerConfiguration {

	@Bean
	public WebTestClientBuilderCustomizer restDocumentation() {
		return (builder) -> builder.entityExchangeResultConsumer(document("{method-name}"));
	}

}
----



[[testing.spring-boot-applications.autoconfigured-webservices]]
== 自动配置的 Spring Web Services 测试



[[testing.spring-boot-applications.autoconfigured-webservices.client]]
=== 自动配置的 Spring Web Services 客户端测试

你可以使用 javadoc:org.springframework.boot.webservices.test.autoconfigure.client.WebServiceClientTest[format=annotation]（来自 `spring-boot-webservices-test` 模块）来测试那些使用 Spring Web Services 项目调用 Web 服务的应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.ws.test.client.MockWebServiceServer[] bean，并自动定制你的 javadoc:org.springframework.boot.webservices.client.WebServiceTemplateBuilder[]。
（关于在 Spring Boot 中使用 Web Services 的更多信息，请参见 xref:io/webservices.adoc[]。）


提示：由 javadoc:org.springframework.boot.webservices.test.autoconfigure.client.WebServiceClientTest[format=annotation] 启用的自动配置设置列表可以 xref:appendix:test-auto-configuration/index.adoc[在附录中找到]。

以下示例展示了 javadoc:org.springframework.boot.webservices.test.autoconfigure.client.WebServiceClientTest[format=annotation] 注解的使用：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webservices.test.autoconfigure.client.WebServiceClientTest;
import org.springframework.ws.test.client.MockWebServiceServer;
import org.springframework.xml.transform.StringSource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.ws.test.client.RequestMatchers.payload;
import static org.springframework.ws.test.client.ResponseCreators.withPayload;

@WebServiceClientTest(SomeWebService.class)
class MyWebServiceClientTests {

	@Autowired
	private MockWebServiceServer server;

	@Autowired
	private SomeWebService someWebService;

	@Test
	void mockServerCall() {
		// @formatter:off
		this.server
			.expect(payload(new StringSource("<request/>")))
			.andRespond(withPayload(new StringSource("<response><status>200</status></response>")));
		assertThat(this.someWebService.test())
			.extracting(Response::getStatus)
			.isEqualTo(200);
		// @formatter:on
	}

}
----



[[testing.spring-boot-applications.autoconfigured-webservices.server]]
=== 自动配置的 Spring Web Services 服务器测试

你可以使用 javadoc:org.springframework.boot.webservices.test.autoconfigure.server.WebServiceServerTest[format=annotation]（来自 `spring-boot-webservices-test` 模块）来测试那些使用 Spring Web Services 项目实现 Web 服务的应用程序。
默认情况下，它会配置一个 javadoc:org.springframework.ws.test.server.MockWebServiceClient[] bean，可用于调用你的 Web 服务端点。
（关于在 Spring Boot 中使用 Web Services 的更多信息，请参见 xref:io/webservices.adoc[]。）


提示：由 javadoc:org.springframework.boot.webservices.test.autoconfigure.server.WebServiceServerTest[format=annotation] 启用的自动配置设置列表可以 xref:appendix:test-auto-configuration/index.adoc[在附录中找到]。

以下示例展示了 javadoc:org.springframework.boot.webservices.test.autoconfigure.server.WebServiceServerTest[format=annotation] 注解的使用：

[source,java]
----
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webservices.test.autoconfigure.server.WebServiceServerTest;
import org.springframework.ws.test.server.MockWebServiceClient;
import org.springframework.ws.test.server.RequestCreators;
import org.springframework.ws.test.server.ResponseMatchers;
import org.springframework.xml.transform.StringSource;

@WebServiceServerTest(ExampleEndpoint.class)
class MyWebServiceServerTests {

	@Autowired
	private MockWebServiceClient client;

	@Test
	void mockServerCall() {
		// @formatter:off
		this.client
			.sendRequest(RequestCreators.withPayload(new StringSource("<ExampleRequest/>")))
			.andExpect(ResponseMatchers.payload(new StringSource("<ExampleResponse>42</ExampleResponse>")));
		// @formatter:on
	}

}
----



[[testing.spring-boot-applications.additional-autoconfiguration-and-slicing]]
== 额外的自动配置与切片

每个切片提供一个或多个 `@AutoConfigure...` 注解，它们定义了作为切片一部分应包含的自动配置。
可以通过创建自定义的 `@AutoConfigure...` 注解或向测试添加 javadoc:org.springframework.boot.autoconfigure.ImportAutoConfiguration[format=annotation] 来逐个测试地添加额外的自动配置，如下例所示：

[source,java]
----
import org.springframework.boot.autoconfigure.ImportAutoConfiguration;
import org.springframework.boot.integration.autoconfigure.IntegrationAutoConfiguration;
import org.springframework.boot.jdbc.test.autoconfigure.JdbcTest;

@JdbcTest
@ImportAutoConfiguration(IntegrationAutoConfiguration.class)
class MyJdbcTests {

}
----

注意：确保不要使用常规的 javadoc:org.springframework.context.annotation.Import[format=annotation] 注解来导入自动配置，因为 Spring Boot 会以特定方式处理它们。

或者，可以通过在 `META-INF/spring` 中存储的文件中注册它们，为任何切片注解的使用添加额外的自动配置，如下例所示：

.META-INF/spring/org.springframework.boot.jdbc.test.autoconfigure.JdbcTest.imports
[source]
----
com.example.IntegrationAutoConfiguration
----
在这个例子中，`+com.example.IntegrationAutoConfiguration+` 在每个标注了 javadoc:org.springframework.boot.jdbc.test.autoconfigure.JdbcTest[format=annotation] 的测试上启用。

提示：你可以在此文件中使用带有 `#` 的注释。

提示：只要一个切片或 `@AutoConfigure...` 注解被 javadoc:org.springframework.boot.autoconfigure.ImportAutoConfiguration[format=annotation] 元注解，就可以通过这种方式自定义。



[[testing.spring-boot-applications.user-configuration-and-slicing]]
== 用户配置与切片

如果你以合理的方式 xref:using/structuring-your-code.adoc[组织代码]，你的 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 类会 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.detecting-configuration[默认被用作] 测试的配置。

那么，重要的是不要将特定于某个功能区域的配置设置散落在应用程序的主类中。

假设你正在使用 Spring Data MongoDB，你依赖其自动配置，并且启用了审计。
你可以如下定义你的 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]：

[source,java]
----
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.mongodb.config.EnableMongoAuditing;

@SpringBootApplication
@EnableMongoAuditing
public class MyApplication {

	// ...

}
----

由于这个类是测试的源配置，任何切片测试实际上都会尝试启用 Mongo 审计，这绝对不是你想要做的。
推荐的方法是将该特定区域的配置移动到一个单独的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类中，与你的应用程序处于同一级别，如下例所示：

[source,java]
----
import org.springframework.context.annotation.Configuration;
import org.springframework.data.mongodb.config.EnableMongoAuditing;

@Configuration(proxyBeanMethods = false)
@EnableMongoAuditing
public class MyMongoConfiguration {

	// ...

}
----

注意：根据应用程序的复杂性，你可能有一个单独的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类用于自定义，或者每个领域区域一个类。
后一种方法允许你在必要时通过 javadoc:org.springframework.context.annotation.Import[format=annotation] 注解在某个测试中启用它。
有关何时可能想要为切片测试启用特定 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类的更多细节，请参阅 xref:how-to:testing.adoc#howto.testing.slice-tests[这个操作指南部分]。

测试切片会排除 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类的扫描。
例如，对于 javadoc:org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest[format=annotation]，以下配置不会将给定的 javadoc:org.springframework.web.servlet.config.annotation.WebMvcConfigurer[] bean 包含在测试切片加载的应用程序上下文中：

[source,java]
----
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Configuration(proxyBeanMethods = false)
public class MyWebConfiguration {

	@Bean
	public WebMvcConfigurer testConfigurer() {
		return new WebMvcConfigurer() {
			// ...
		};
	}

}
----

然而，下面的配置会导致自定义的 javadoc:org.springframework.web.servlet.config.annotation.WebMvcConfigurer[] 被测试切片加载。

[source,java]
----
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Component
public class MyWebMvcConfigurer implements WebMvcConfigurer {

	// ...

}
----

另一个混淆来源是 classpath 扫描。
假设你以合理的方式组织了代码，但需要扫描一个额外的包。
你的应用程序可能类似于以下代码：

[source,java]
----
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan({ "com.example.app", "com.example.another" })
public class MyApplication {

	// ...

}
----

这样做实际上覆盖了默认的组件扫描指令，其副作用是无论你选择哪个切片，都会扫描这两个包。
例如，一个 javadoc:org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest[format=annotation] 似乎突然扫描了应用程序的组件和用户配置。
同样，将自定义指令移动到一个单独的类中是解决此问题的好方法。

提示：如果这对你来说不可行，你可以在测试的层次结构中创建一个 javadoc:org.springframework.boot.SpringBootConfiguration[format=annotation]，以便使用它来代替。
或者，你可以为测试指定一个源，这会禁用查找默认源的行为。



[[testing.spring-boot-applications.spock]]
== 使用 Spock 测试 Spring Boot 应用程序

Spock 2.4 或更高版本可用于测试 Spring Boot 应用程序。
为此，将 Spock 的 `spock-spring` 模块的 `-groovy-5.0` 版本依赖添加到应用程序的构建中。
`spock-spring` 将 Spring 的测试框架集成到 Spock 中。
有关更多细节，请参阅 https://spockframework.org/spock/docs/2.4/modules.html#spring-module[Spock 的 Spring 模块文档]。
