= SQL 数据库

{url-spring-framework-site}[Spring 框架] 为使用 SQL 数据库提供了广泛支持，从使用 javadoc:org.springframework.jdbc.core.simple.JdbcClient[] 或 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 的直接 JDBC 访问，到完整的“`object relational mapping`”技术（如 Hibernate）。
{url-spring-data-site}[Spring Data] 提供了额外的功能层次：直接从接口创建 javadoc:org.springframework.data.repository.Repository[] 实现，并使用约定从方法名生成查询。


[[data.sql.datasource]]
== 配置 DataSource

Java 的 javadoc:javax.sql.DataSource[] 接口提供了处理数据库连接的标准方法。
传统上，javadoc:javax.sql.DataSource[] 使用 `URL` 以及一些凭据来建立数据库连接。

提示：有关更高级的示例（通常是为了完全控制 DataSource 的配置），请参阅“`How-to Guides`”的 xref:how-to:data-access.adoc#howto.data-access.configure-custom-datasource[配置自定义 DataSource] 部分。


[[data.sql.datasource.embedded]]
=== 嵌入式数据库支持

使用内存嵌入式数据库来开发应用程序通常很方便。
显然，内存数据库不提供持久化存储。
你需要在应用程序启动时填充数据库，并准备好在应用程序结束时丢弃数据。

提示：“`How-to Guides`”部分包含 xref:how-to:data-initialization.adoc[关于如何初始化数据库的部分]。

Spring Boot 可以自动配置嵌入式 https://www.h2database.com[H2]、https://hsqldb.org/[HSQL] 和 https://db.apache.org/derby/[Derby]（已弃用）数据库。
你无需提供任何连接 URL。
你只需包含一个对你想要使用的嵌入式数据库的构建依赖。
如果 classpath 上有多个嵌入式数据库，请设置 configprop:spring.datasource.embedded-database-connection[] 配置属性来控制使用哪一个。
将该属性设置为 `none` 会禁用嵌入式数据库的自动配置。

[NOTE]
====
如果你在测试中使用此功能，你可能会注意到，无论你使用多少个应用程序上下文，整个测试套件都会重用同一个数据库。
如果你想确保每个上下文都有一个单独的嵌入式数据库，应将 `spring.datasource.generate-unique-name` 设置为 `true`。
====

例如，典型的 POM 依赖如下：

[source,xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
	<groupId>org.hsqldb</groupId>
	<artifactId>hsqldb</artifactId>
	<scope>runtime</scope>
</dependency>
----
NOTE: 你需要一个 `spring-jdbc` 依赖，以便嵌入式数据库能够被自动配置。
在此示例中，它通过 `spring-boot-starter-data-jpa` 被传递引入。

TIP: 如果出于某种原因，你确实为嵌入式数据库配置了连接 URL，请注意确保禁用数据库的自动关闭。
如果你使用 H2，应使用 `DB_CLOSE_ON_EXIT=FALSE` 来实现。
如果你使用 HSQLDB，应确保不使用 `shutdown=true`。
禁用数据库的自动关闭让 Spring Boot 控制何时关闭数据库，从而确保在不再需要访问数据库时关闭。


[[data.sql.datasource.production]]
=== 连接到生产数据库

生产数据库连接也可以通过使用连接池 javadoc:javax.sql.DataSource[] 进行自动配置。


[[data.sql.datasource.configuration]]
=== DataSource 配置

DataSource 配置由 `+spring.datasource.*+` 中的外部配置属性控制。
例如，你可以在 `application.properties` 中声明以下部分：

[configprops,yaml]
----
spring:
  datasource:
    url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
----
NOTE: 你至少应通过设置 configprop:spring.datasource.url[] 属性来指定 URL。
否则，Spring Boot 会尝试自动配置一个嵌入式数据库。

TIP: Spring Boot 可以从 URL 推断出大多数数据库的 JDBC 驱动类。
如果你需要指定特定的类，可以使用 configprop:spring.datasource.driver-class-name[] 属性。

NOTE: 要创建池化的 javadoc:javax.sql.DataSource[]，我们需要能够验证有效的 javadoc:java.sql.Driver[] 类是否可用，因此我们在执行任何操作之前会检查这一点。
换句话说，如果你设置了 `spring.datasource.driver-class-name=com.mysql.jdbc.Driver`，那么该类必须是可加载的。

有关更多支持的选项，请参阅 javadoc:org.springframework.boot.jdbc.autoconfigure.DataSourceProperties[] API 文档。
这些是无论 xref:data/sql.adoc#data.sql.datasource.connection-pool[实际实现] 如何都能工作的标准选项。
也可以使用它们各自的前缀（`+spring.datasource.hikari.*+`、`+spring.datasource.tomcat.*+`、`+spring.datasource.dbcp2.*+` 和 `+spring.datasource.oracleucp.*+`）来微调实现特定的设置。
有关更多详细信息，请参阅你使用的连接池实现的文档。

例如，如果你使用 {url-tomcat-docs}/jdbc-pool.html#Common_Attributes[Tomcat 连接池]，你可以自定义许多额外的设置，如下例所示：

[configprops,yaml]
----
spring:
  datasource:
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
----
这将设置连接池在无可用连接时等待10000毫秒后抛出异常，将最大连接数限制为50，并在从池中借用连接前验证连接。

[[data.sql.datasource.connection-pool]]
=== 支持的连接池

Spring Boot 使用以下算法选择具体实现：

. 我们优先选择 https://github.com/brettwooldridge/HikariCP[HikariCP]，因其性能和并发性。
如果 HikariCP 可用，我们总是选择它。
. 否则，如果 Tomcat 连接池 javadoc:javax.sql.DataSource[] 可用，则使用它。
. 否则，如果 https://commons.apache.org/proper/commons-dbcp/[Commons DBCP2] 可用，则使用它。
. 如果 HikariCP、Tomcat 和 DBCP2 均不可用，且 Oracle UCP 可用，则使用它。

注意：如果你使用 `spring-boot-starter-jdbc` 或 `spring-boot-starter-data-jpa` starters，你将自动获得 HikariCP 的依赖。

你可以完全绕过该算法，通过设置 configprop:spring.datasource.type[] 属性来指定要使用的连接池。
如果你的应用运行在 Tomcat 容器中，这一点尤其重要，因为默认提供了 `tomcat-jdbc`。

始终可以使用 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 手动配置额外的连接池。
如果你定义了自己的 javadoc:javax.sql.DataSource[] bean，则不会发生自动配置。
javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 支持以下连接池：

* HikariCP
* Tomcat 连接池 javadoc:javax.sql.DataSource[]
* Commons DBCP2
* Oracle UCP & `OracleDataSource`
* Spring 框架的 javadoc:org.springframework.jdbc.datasource.SimpleDriverDataSource[]
* H2 javadoc:org.h2.jdbcx.JdbcDataSource[]
* PostgreSQL javadoc:org.postgresql.ds.PGSimpleDataSource[]
* C3P0
* Vibur

[[data.sql.datasource.jndi]]
=== 连接到 JNDI DataSource

如果你将 Spring Boot 应用部署到应用服务器，你可能希望使用应用服务器的内置功能来配置和管理 DataSource，并通过 JNDI 访问它。

configprop:spring.datasource.jndi-name[] 属性可作为 configprop:spring.datasource.url[]、configprop:spring.datasource.username[] 和 configprop:spring.datasource.password[] 属性的替代，用于从特定 JNDI 位置访问 javadoc:javax.sql.DataSource[]。
例如，`application.properties` 中的以下部分展示了如何访问 JBoss AS 定义的 javadoc:javax.sql.DataSource[]：

[configprops,yaml]
----
spring:
  datasource:
    jndi-name: "java:jboss/datasources/customers"
----
[[data.sql.datasource.lazy-connection]]
=== 懒连接代理

当自动配置了池化的 `DataSource` 时，可以通过将 configprop:spring.datasource.connection-fetch[] 设置为 `lazy` 将其包装在一个代理中，该代理会尽可能晚地获取 JDBC 连接，如下例所示：

[configprops,yaml]
----
spring:
  datasource:
    connection-fetch: "lazy"
----
启用此功能后，仅在实际需要时才会从连接池中获取 JDBC 连接。
JDBC 事务控制可以在不获取连接池连接或与数据库通信的情况下进行；这将在首次创建 JDBC 语句时延迟执行。
要访问自动配置的目标 `DataSource`，请使用 `DataSource.unwrap`。

提示：如果你将目标 `DataSource` 包装在 `TransactionAwareDataSourceProxy` 中，请确保使用具有正顺序的 `BeanPostProcessor` 来执行此操作。

有关更多详细信息，请参阅 javadoc:org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy[]。



[[data.sql.jdbc-template]]
== 使用 JdbcTemplate

Spring 的 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 和 javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 类是自动配置的，你可以直接将它们自动装配到你自己的 beans 中，如下例所示：

[source,java]
----
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

	private final JdbcTemplate jdbcTemplate;

	public MyBean(JdbcTemplate jdbcTemplate) {
		this.jdbcTemplate = jdbcTemplate;
	}

	public void doSomething() {
		/* @chomp:line this.jdbcTemplate ... */ this.jdbcTemplate.execute("delete from customer");
	}

}
----

你可以通过使用 `spring.jdbc.template.*` 属性来自定义模板的某些属性，如下例所示：

[configprops,yaml]
----
spring:
  jdbc:
    template:
      max-rows: 500
----
如果需要调整 SQL 异常，你可以定义自己的 `SQLExceptionTranslator` bean，使其与自动配置的 `JdbcTemplate` 关联。

注意：javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 在后台复用了同一个 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 实例。
如果定义了多个 javadoc:org.springframework.jdbc.core.JdbcTemplate[] 且不存在主候选，则 javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 不会被自动配置。


[[data.sql.jdbc-client]]
== 使用 JdbcClient

Spring 的 javadoc:org.springframework.jdbc.core.simple.JdbcClient[] 会根据 javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate[] 的存在自动配置。
你也可以直接将其注入到自己的 beans 中，如下例所示：

[source,java]
----
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

	private final JdbcClient jdbcClient;

	public MyBean(JdbcClient jdbcClient) {
		this.jdbcClient = jdbcClient;
	}

	public void doSomething() {
		/* @chomp:line this.jdbcClient ... */ this.jdbcClient.sql("delete from customer").update();
	}

}
----

如果你依赖自动配置来创建底层的 javadoc:org.springframework.jdbc.core.JdbcTemplate[]，那么使用 `spring.jdbc.template.*` 属性进行的任何自定义也会在客户端中生效。


[[data.sql.jpa-and-spring-data]]
== JPA 和 Spring Data JPA

Java 持久化 API 是一种标准技术，允许你将对象“`map`”到关系数据库。
`spring-boot-starter-data-jpa` POM 提供了一种快速入门的方式。
它提供了以下关键依赖：

* Hibernate：最流行的 JPA 实现之一。
* Spring Data JPA：帮助你实现基于 JPA 的仓库。
* Spring ORM：来自 Spring 框架的核心 ORM 支持。

提示：我们不会深入介绍 JPA 或 {url-spring-data-site}[Spring Data] 的细节。
你可以跟随 https://spring.io 上的 https://spring.io/guides/gs/accessing-data-jpa/[使用 JPA 访问数据] 指南，并阅读 {url-spring-data-jpa-site}[Spring Data JPA] 和 https://hibernate.org/orm/documentation/[Hibernate] 参考文档。


[[data.sql.jpa-and-spring-data.entity-classes]]
=== 实体类

传统上，JPA “`Entity`” 类是在 `persistence.xml` 文件中指定的。
使用 Spring Boot，这个文件不是必需的，而是使用“`Entity Scanning`”。
默认情况下，会扫描 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包]。

任何带有 javadoc:jakarta.persistence.Entity[format=annotation]、javadoc:jakarta.persistence.Embeddable[format=annotation] 或 javadoc:jakarta.persistence.MappedSuperclass[format=annotation] 注解的类都会被考虑。
一个典型的实体类如下例所示：

[source,java]
----
import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

@Entity
public class City implements Serializable {

	@Id
	@GeneratedValue
	private Long id;

	@Column(nullable = false)
	private String name;

	@Column(nullable = false)
	private String state;

	// ... additional members, often include @OneToMany mappings

	protected City() {
		// no-args constructor required by JPA spec
		// this one is protected since it should not be used directly
	}

	public City(String name, String state) {
		this.name = name;
		this.state = state;
	}

	public String getName() {
		return this.name;
	}

	public String getState() {
		return this.state;
	}

	// ... etc

}
----

提示：你可以通过使用 javadoc:org.springframework.boot.persistence.autoconfigure.EntityScan[format=annotation] 注解来自定义实体扫描位置。
请参阅“`How-to Guides`”中的 xref:how-to:data-access.adoc#howto.data-access.separate-entity-definitions-from-spring-configuration[将 @Entity 定义与 Spring 配置分离] 部分。


[[data.sql.jpa-and-spring-data.repositories]]
=== Spring Data JPA 仓库

{url-spring-data-jpa-site}[Spring Data JPA] 仓库是你可以定义用于访问数据的接口。
JPA 查询会根据你的方法名自动创建。
例如，一个 `CityRepository` 接口可能声明一个 `findAllByState(String state)` 方法来查找给定州的所有城市。

对于更复杂的查询，你可以使用 Spring Data 的 javadoc:org.springframework.data.jpa.repository.Query[] 注解注解你的方法。

Spring Data 仓库通常继承自 javadoc:org.springframework.data.repository.Repository[] 或 javadoc:org.springframework.data.repository.CrudRepository[] 接口。
如果你使用自动配置，则会搜索 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 中的仓库。

提示：你可以使用 javadoc:org.springframework.data.jpa.repository.config.EnableJpaRepositories[format=annotation] 自定义查找仓库的位置。

以下示例展示了一个典型的 Spring Data 仓库接口定义：

[source,java]
----
import org.springframework.boot.docs.data.sql.jpaandspringdata.entityclasses.City;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.Repository;

public interface CityRepository extends Repository<City, Long> {

	Page<City> findAll(Pageable pageable);

	City findByNameAndStateAllIgnoringCase(String name, String state);

}
----

Spring Data JPA 仓库支持三种不同的引导模式：默认、延迟和惰性。
要启用延迟或惰性引导，请将 configprop:spring.data.jpa.repositories.bootstrap-mode[] 属性分别设置为 `deferred` 或 `lazy`。
当使用延迟或惰性引导时，自动配置的 javadoc:org.springframework.boot.jpa.EntityManagerFactoryBuilder[] 将使用上下文的 javadoc:org.springframework.core.task.AsyncTaskExecutor[]（如果有）作为引导执行器。
如果存在多个，则使用名为 `applicationTaskExecutor` 的那个。

[NOTE]
====
当使用延迟或惰性引导时，请确保在应用程序上下文引导阶段之后才访问 JPA 基础设施。
你可以使用 javadoc:org.springframework.beans.factory.SmartInitializingSingleton[] 来调用任何需要 JPA 基础设施的初始化。
对于作为 Spring beans 创建的 JPA 组件（如转换器），请使用 javadoc:org.springframework.beans.factory.ObjectProvider[] 来延迟依赖项的解析（如果有）。
====

提示：我们只是浅尝辄止地介绍了 Spring Data JPA。
有关完整细节，请参阅 {url-spring-data-jpa-docs}[Spring Data JPA 参考文档]。


[[data.sql.jpa-and-spring-data.envers-repositories]]
=== Spring Data Envers 仓库

如果 {url-spring-data-envers-site}[Spring Data Envers] 可用，JPA 仓库会自动配置以支持典型的 Envers 查询。

要使用 Spring Data Envers，请确保你的仓库继承自 javadoc:org.springframework.data.repository.history.RevisionRepository[]，如下例所示：

[source,java]
----
import org.springframework.boot.docs.data.sql.jpaandspringdata.entityclasses.Country;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.Repository;
import org.springframework.data.repository.history.RevisionRepository;

public interface CountryRepository extends RevisionRepository<Country, Long, Integer>, Repository<Country, Long> {

	Page<Country> findAll(Pageable pageable);

}
----

注意：更多细节，请查看 {url-spring-data-jpa-docs}/envers.html[Spring Data Envers 参考文档]。


[[data.sql.jpa-and-spring-data.creating-and-dropping]]
=== 创建和删除 JPA 数据库

默认情况下，JPA 数据库*仅*在你使用嵌入式数据库（即 H2、HSQL 或 Derby（已弃用））时自动创建。
你可以通过使用 `+spring.jpa.*+` 属性显式配置 JPA 设置。
例如，要创建和删除表，你可以将以下行添加到你的 `application.properties`：

[configprops,yaml]
----
spring:
  jpa:
    hibernate.ddl-auto: "create-drop"
----
NOTE: Hibernate 自身内部用于此属性的名称（如果你碰巧记得更清楚）是 `hibernate.hbm2ddl.auto`。
你可以通过使用 `+spring.jpa.properties.*+` 来设置它以及其他 Hibernate 原生属性（前缀会在添加到实体管理器之前被去除）。
以下行展示了为 Hibernate 设置 JPA 属性的示例：

[configprops,yaml]
----
spring:
  jpa:
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
----
上一示例中的行将 `true` 作为 `hibernate.globally_quoted_identifiers` 属性的值传递给 Hibernate 实体管理器。

默认情况下，DDL 执行（或验证）会延迟到 javadoc:org.springframework.context.ApplicationContext[] 启动之后。


[[data.sql.jpa-and-spring-data.open-entity-manager-in-view]]
=== 在视图中开放 EntityManager

如果你正在运行一个 Web 应用程序，Spring Boot 默认会注册 javadoc:org.springframework.orm.jpa.support.OpenEntityManagerInViewInterceptor[] 以应用 "`Open EntityManager in View`" 模式，从而允许在 Web 视图中进行懒加载。
如果你不希望这种行为，应在 `application.properties` 中将 `spring.jpa.open-in-view` 设置为 `false`。


[[data.sql.jdbc]]
== Spring Data JDBC

Spring Data 包含对 JDBC 的 Repository 支持，并会自动为 javadoc:org.springframework.data.repository.CrudRepository[] 上的方法生成 SQL。
对于更高级的查询，提供了 javadoc:org.springframework.data.jdbc.repository.query.Query[format=annotation] 注解。

Spring Boot 会在 classpath 上存在必要依赖时自动配置 Spring Data 的 JDBC Repository。
可以通过在项目中添加一个对 `spring-boot-starter-data-jdbc` 的单一依赖来引入它们。
如有必要，你可以通过向应用程序添加 javadoc:org.springframework.data.jdbc.repository.config.EnableJdbcRepositories[format=annotation] 注解或 javadoc:org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration[] 子类来控制 Spring Data JDBC 的配置。

如果你将 Spring Data JDBC 与 xref:packaging/aot.adoc[提前处理]（针对 JVM 或 native image）一起使用，建议进行一些额外配置。
为了防止在 AOT 处理期间需要数据库连接，请定义一个适合应用程序数据库的 `JdbcDialect` bean。
例如，如果你使用 Postgres，请定义一个 `JdbcPostgresDialect` bean。

提示：有关 Spring Data JDBC 的完整详细信息，请参阅 {url-spring-data-jdbc-docs}[参考文档]。


[[data.sql.h2-web-console]]
== 使用 H2 的 Web 控制台

https://www.h2database.com[H2 数据库] 提供了一个 https://www.h2database.com/html/quickstart.html#h2_console[基于浏览器的控制台]，Spring Boot 可以为你自动配置。
当满足以下条件时，控制台会被自动配置：

* 你正在开发一个基于 Servlet 的 Web 应用程序。
* `org.springframework.boot:spring-boot-h2console` 位于 classpath 上。
* 你正在使用 xref:using/devtools.adoc[Spring Boot 的开发者工具]。

提示：如果你没有使用 Spring Boot 的开发者工具，但仍希望使用 H2 的控制台，可以将 configprop:spring.h2.console.enabled[] 属性设置为 `true`。

注意：H2 控制台仅用于开发期间，因此应确保在生产环境中 `spring.h2.console.enabled` 未设置为 `true`。


[[data.sql.h2-web-console.custom-path]]
=== 更改 H2 控制台的路径

默认情况下，控制台可通过 `/h2-console` 访问。
你可以使用 configprop:spring.h2.console.path[] 属性自定义控制台的路径。


[[data.sql.h2-web-console.spring-security]]
=== 在安全应用程序中访问 H2 控制台

H2 控制台使用框架，并且由于它仅用于开发，因此不实现 CSRF 保护措施。
如果你的应用程序使用 Spring Security，你需要配置它以：

* 禁用针对控制台请求的 CSRF 保护，
* 在来自控制台的响应上设置标头 `X-Frame-Options` 为 `SAMEORIGIN`。

有关 {url-spring-security-docs}/features/exploits/csrf.html[CSRF] 和标头 {url-spring-security-docs}/features/exploits/headers.html#headers-frame-options[X-Frame-Options] 的更多信息，请参阅 Spring Security 参考指南。

在简单设置中，可以使用类似以下的 javadoc:org.springframework.security.web.SecurityFilterChain[]：

[source,java]
----
import org.springframework.boot.security.autoconfigure.web.servlet.PathRequest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.security.config.Customizer;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configurers.CsrfConfigurer;
import org.springframework.security.config.annotation.web.configurers.HeadersConfigurer.FrameOptionsConfig;
import org.springframework.security.web.SecurityFilterChain;

@Profile("dev")
@Configuration(proxyBeanMethods = false)
public class DevProfileSecurityConfiguration {

	@Bean
	@Order(Ordered.HIGHEST_PRECEDENCE)
	SecurityFilterChain h2ConsoleSecurityFilterChain(HttpSecurity http) {
		http.securityMatcher(PathRequest.toH2Console());
		http.authorizeHttpRequests(yourCustomAuthorization());
		http.csrf(CsrfConfigurer::disable);
		http.headers((headers) -> headers.frameOptions(FrameOptionsConfig::sameOrigin));
		return http.build();
	}


}
----

警告：H2 控制台仅用于开发期间。
在生产环境中，禁用 CSRF 保护或允许网站使用框架可能会造成严重的安全风险。

提示：`PathRequest.toH2Console()` 在控制台路径已自定义时也会返回正确的请求匹配器。


[[data.sql.jooq]]
== 使用 jOOQ

jOOQ（面向对象的查询，https://www.jooq.org/[jOOQ]）是 https://www.datageekery.com/[Data Geekery] 的一款流行产品，它从你的数据库生成 Java 代码，并让你通过其流畅的 API 构建类型安全的 SQL 查询。
商业版和开源版都可以与 Spring Boot 一起使用。
jOOQ 需要 Java 21 或更高版本。


[[data.sql.jooq.codegen]]
=== 代码生成

为了使用 jOOQ 类型安全查询，你需要从数据库模式生成 Java 类。
你可以按照 {url-jooq-docs}/#jooq-in-7-steps-step3[jOOQ 用户手册] 中的说明进行操作。
如果你使用 `jooq-codegen-maven` 插件并且也使用了 `spring-boot-starter-parent` "`parent POM`"，你可以安全地省略插件的 `<version>` 标签。
你还可以使用 Spring Boot 定义的版本变量（例如 `h2.version`）来声明插件的数据库依赖。
以下示例展示了这一点：

[source,xml]
----
<plugin>
	<groupId>org.jooq</groupId>
	<artifactId>jooq-codegen-maven</artifactId>
	<executions>
		...
	</executions>
	<dependencies>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>${h2.version}</version>
		</dependency>
	</dependencies>
	<configuration>
		<jdbc>
			<driver>org.h2.Driver</driver>
			<url>jdbc:h2:~/yourdatabase</url>
		</jdbc>
		<generator>
			...
		</generator>
	</configuration>
</plugin>
----
=== 使用 DSLContext

jOOQ 提供的流式 API 通过 javadoc:org.jooq.DSLContext[] 接口启动。
Spring Boot 自动配置一个 javadoc:org.jooq.DSLContext[] 作为 Spring Bean，并将其连接到你的应用程序 javadoc:javax.sql.DataSource[]。
要使用 javadoc:org.jooq.DSLContext[]，你可以注入它，如下例所示：

[source,java]
----
import java.util.GregorianCalendar;
import java.util.List;

import org.jooq.DSLContext;

import org.springframework.stereotype.Component;

import static org.springframework.boot.docs.data.sql.jooq.dslcontext.Tables.AUTHOR;

@Component
public class MyBean {

	private final DSLContext create;

	public MyBean(DSLContext dslContext) {
		this.create = dslContext;
	}
----

TIP: jOOQ 手册倾向于使用名为 `create` 的变量来持有 javadoc:org.jooq.DSLContext[]。

然后你可以使用 javadoc:org.jooq.DSLContext[] 来构建查询，如下例所示：

[source,java]
----
	public List<GregorianCalendar> authorsBornAfter1980() {
		return this.create.selectFrom(AUTHOR)
			.where(AUTHOR.DATE_OF_BIRTH.greaterThan(new GregorianCalendar(1980, 0, 1)))
			.fetch(AUTHOR.DATE_OF_BIRTH);
	} // end::method[]

}
----


[[data.sql.jooq.sqldialect]]
=== jOOQ SQL 方言

除非 configprop:spring.jooq.sql-dialect[] 属性已配置，否则 Spring Boot 会为你的数据源确定要使用的 SQL 方言。
如果 Spring Boot 无法检测到方言，它将使用 `DEFAULT`。

NOTE: Spring Boot 只能自动配置 jOOQ 开源版本支持的方言。


[[data.sql.jooq.customizing]]
=== 自定义 jOOQ

更高级的自定义可以通过定义你自己的 javadoc:org.springframework.boot.jooq.autoconfigure.DefaultConfigurationCustomizer[] bean 来实现，该 Bean 将在创建 javadoc:org.jooq.Configuration[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 之前被调用。
这优先于自动配置应用的任何内容。

如果你想完全控制 jOOQ 配置，你也可以创建自己的 javadoc:org.jooq.Configuration[] javadoc:org.springframework.context.annotation.Bean[format=annotation]。


[[data.sql.r2dbc]]
== 使用 R2DBC

响应式关系数据库连接（https://r2dbc.io[R2DBC]）项目将响应式编程 API 引入关系数据库。
R2DBC 的 javadoc:io.r2dbc.spi.Connection[] 提供了一种使用非阻塞数据库连接的标准方法。
连接通过使用 javadoc:io.r2dbc.spi.ConnectionFactory[] 来提供，类似于 jdbc 中的 javadoc:javax.sql.DataSource[]。

javadoc:io.r2dbc.spi.ConnectionFactory[] 配置由 `+spring.r2dbc.*+` 中的外部配置属性控制。
例如，你可以在 `application.properties` 中声明以下部分：

[configprops,yaml]
----
spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost/test"
    username: "dbuser"
    password: "dbpass"
----
TIP: 你无需指定驱动类名，因为 Spring Boot 会通过 R2DBC 的 Connection Factory 发现机制获取驱动。

NOTE: 至少应提供 url。URL 中指定的信息优先于单个属性，即 `name`、`username`、`password` 和连接池选项。

TIP: “`How-to Guides`”部分包含 xref:how-to:data-initialization.adoc#howto.data-initialization.using-basic-sql-scripts[关于如何初始化数据库的章节]。

要自定义由 javadoc:io.r2dbc.spi.ConnectionFactory[] 创建的连接，即设置你不想（或无法）在中央数据库配置中配置的特定参数，你可以使用 javadoc:org.springframework.boot.r2dbc.autoconfigure.ConnectionFactoryOptionsBuilderCustomizer[] javadoc:org.springframework.context.annotation.Bean[format=annotation]。以下示例展示了如何手动覆盖数据库端口，同时其余选项从应用程序配置中获取：

[source,java]
----
import io.r2dbc.spi.ConnectionFactoryOptions;

import org.springframework.boot.r2dbc.autoconfigure.ConnectionFactoryOptionsBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyR2dbcConfiguration {

	@Bean
	public ConnectionFactoryOptionsBuilderCustomizer connectionFactoryPortCustomizer() {
		return (builder) -> builder.option(ConnectionFactoryOptions.PORT, 5432);
	}

}
----

以下示例展示了如何设置一些 PostgreSQL 连接选项：

[source,java]
----
import java.util.HashMap;
import java.util.Map;

import io.r2dbc.postgresql.PostgresqlConnectionFactoryProvider;

import org.springframework.boot.r2dbc.autoconfigure.ConnectionFactoryOptionsBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyPostgresR2dbcConfiguration {

	@Bean
	public ConnectionFactoryOptionsBuilderCustomizer postgresCustomizer() {
		Map<String, String> options = new HashMap<>();
		options.put("lock_timeout", "30s");
		options.put("statement_timeout", "60s");
		return (builder) -> builder.option(PostgresqlConnectionFactoryProvider.OPTIONS, options);
	}

}
----

当 javadoc:io.r2dbc.spi.ConnectionFactory[] bean 可用时，常规的 JDBC javadoc:javax.sql.DataSource[] 自动配置会退出。如果你想保留 JDBC javadoc:javax.sql.DataSource[] 自动配置，并且愿意在响应式应用中使用阻塞 JDBC API 的风险，可以在应用程序的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类上添加 `@Import(DataSourceAutoConfiguration.class)` 以重新启用它。

[[data.sql.r2dbc.embedded]]
=== 嵌入式数据库支持

与 xref:data/sql.adoc#data.sql.datasource.embedded[JDBC 支持]类似，Spring Boot 可以自动配置用于响应式使用的嵌入式数据库。你无需提供任何连接 URL。只需添加对要使用的嵌入式数据库的构建依赖，如下例所示：

[source,xml]
----
<dependency>
	<groupId>io.r2dbc</groupId>
	<artifactId>r2dbc-h2</artifactId>
	<scope>runtime</scope>
</dependency>
----
[NOTE]
====
如果你在测试中使用此功能，你可能会注意到，无论使用多少个应用上下文，整个测试套件都会重用同一个数据库。
如果你想确保每个上下文都有独立的嵌入式数据库，应将 `spring.r2dbc.generate-unique-name` 设置为 `true`。
====



[[data.sql.r2dbc.using-database-client]]
=== 使用 DatabaseClient

javadoc:org.springframework.r2dbc.core.DatabaseClient[] bean 是自动配置的，你可以直接将其注入到你自己的 beans 中，如下例所示：

[source,java]
----
import java.util.Map;

import reactor.core.publisher.Flux;

import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

	private final DatabaseClient databaseClient;

	public MyBean(DatabaseClient databaseClient) {
		this.databaseClient = databaseClient;
	}

	// @fold:on // ...
	public Flux<Map<String, Object>> someMethod() {
		return this.databaseClient.sql("select * from user").fetch().all();
	}
	// @fold:off

}
----



[[data.sql.r2dbc.repositories]]
=== Spring Data R2DBC 仓库

https://spring.io/projects/spring-data-r2dbc[Spring Data R2DBC] 仓库是你定义用于访问数据的接口。
查询会根据你的方法名自动创建。
例如，一个 `CityRepository` 接口可能声明一个 `findAllByState(String state)` 方法来查找给定州的所有城市。

对于更复杂的查询，你可以使用 Spring Data 的 javadoc:org.springframework.data.r2dbc.repository.Query[format=annotation] 注解注解你的方法。

Spring Data 仓库通常继承自 javadoc:org.springframework.data.repository.Repository[] 或 javadoc:org.springframework.data.repository.CrudRepository[] 接口。
如果你使用自动配置，则会搜索 xref:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 中的仓库。

以下示例展示了一个典型的 Spring Data 仓库接口定义：

[source,java]
----
import reactor.core.publisher.Mono;

import org.springframework.data.repository.Repository;

public interface CityRepository extends Repository<City, Long> {

	Mono<City> findByNameAndStateAllIgnoringCase(String name, String state);

}
----

提示：我们只是浅尝辄止地介绍了 Spring Data R2DBC。有关完整详情，请参阅 {url-spring-data-r2dbc-docs}[Spring Data R2DBC 参考文档]。
