[[messaging.amqp]]
= AMQP

AMQP 是一种面向消息中间件的平台中立、线级协议。
Spring AMQP 项目将核心 Spring 概念应用于基于 AMQP 的消息传递解决方案的开发。
Spring Boot 提供了多种通过 RabbitMQ 使用 AMQP 的便利，包括 `spring-boot-starter-amqp` starter。

[[messaging.amqp.rabbitmq]]
== RabbitMQ 支持

https://www.rabbitmq.com/[RabbitMQ] 是一个基于 AMQP 协议的轻量级、可靠、可扩展且可移植的消息代理。
Spring 使用 RabbitMQ 通过 AMQP 协议进行通信。

RabbitMQ 配置由 `+spring.rabbitmq.*+` 中的外部配置属性控制。
例如，您可以在 `application.properties` 中声明以下部分：

[configprops,yaml]
----
spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "secret"
----

或者，你可以使用 `addresses` 属性配置相同的连接：

[configprops,yaml]
----
spring:
  rabbitmq:
    addresses: "amqp://admin:secret@localhost"
----

注意：以这种方式指定地址时，`host` 和 `port` 属性将被忽略。
如果地址使用 `amqps` 协议，则会自动启用 SSL 支持。

有关更多支持的基于属性的配置选项，请参阅 javadoc:org.springframework.boot.amqp.autoconfigure.RabbitProperties[]。
要配置由 Spring AMQP 使用的 RabbitMQ javadoc:com.rabbitmq.client.ConnectionFactory[] 的更低级别细节，请定义一个 javadoc:org.springframework.boot.amqp.autoconfigure.ConnectionFactoryCustomizer[] bean。

如果上下文中存在 javadoc:org.springframework.amqp.rabbit.connection.ConnectionNameStrategy[] bean，它将自动用于命名由自动配置的 javadoc:org.springframework.amqp.rabbit.connection.CachingConnectionFactory[] 创建的连接。

要对 javadoc:org.springframework.amqp.rabbit.core.RabbitTemplate[] 进行应用范围的附加定制，请使用 javadoc:org.springframework.boot.amqp.autoconfigure.RabbitTemplateCustomizer[] bean。

提示：有关更多详细信息，请参阅 https://spring.io/blog/2010/06/14/understanding-amqp-the-protocol-used-by-rabbitmq/[理解 AMQP，RabbitMQ 使用的协议]。


[[messaging.amqp.sending]]
== 发送消息

Spring 的 javadoc:org.springframework.amqp.core.AmqpTemplate[] 和 javadoc:org.springframework.amqp.core.AmqpAdmin[] 是自动配置的，您可以直接将它们注入到自己的 bean 中，如下例所示：

[source,java]
----
import org.springframework.amqp.core.AmqpAdmin;
import org.springframework.amqp.core.AmqpTemplate;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

	private final AmqpAdmin amqpAdmin;

	private final AmqpTemplate amqpTemplate;

	public MyBean(AmqpAdmin amqpAdmin, AmqpTemplate amqpTemplate) {
		this.amqpAdmin = amqpAdmin;
		this.amqpTemplate = amqpTemplate;
	}

	// @fold:on // ...
	public void someMethod() {
		this.amqpAdmin.getQueueInfo("someQueue");
	}

	public void someOtherMethod() {
		this.amqpTemplate.convertAndSend("hello");
	}
	// @fold:off

}
----

注意：javadoc:org.springframework.amqp.rabbit.core.RabbitMessagingTemplate[] 可以以类似的方式注入。
如果定义了 javadoc:org.springframework.amqp.support.converter.MessageConverter[] bean，它将自动关联到自动配置的 javadoc:org.springframework.amqp.core.AmqpTemplate[]。

如有必要，任何定义为 bean 的 javadoc:org.springframework.amqp.core.Queue[] 将自动用于在 RabbitMQ 实例上声明相应的队列。

要重试操作，您可以在 javadoc:org.springframework.amqp.core.AmqpTemplate[] 上启用重试（例如，在代理连接丢失的情况下）：

[configprops,yaml]
----
spring:
  rabbitmq:
    template:
      retry:
        enabled: true
        initial-interval: "2s"
----

默认情况下，重试是禁用的。
你也可以通过声明一个 javadoc:org.springframework.boot.amqp.autoconfigure.RabbitTemplateRetrySettingsCustomizer[] bean 以编程方式自定义 javadoc:org.springframework.core.retry.RetryTemplate[]。

如果你需要创建更多的 javadoc:org.springframework.amqp.rabbit.core.RabbitTemplate[] 实例，或者想要覆盖默认设置，Spring Boot 提供了一个 javadoc:org.springframework.boot.amqp.autoconfigure.RabbitTemplateConfigurer[] bean，你可以用它来初始化一个 javadoc:org.springframework.amqp.rabbit.core.RabbitTemplate[]，使其具有与自动配置使用的工厂相同的设置。

如果上下文中存在一个类型为 javadoc:org.springframework.amqp.rabbit.support.micrometer.RabbitTemplateObservationConvention[] 的 bean，它将自动配置到 javadoc:org.springframework.amqp.rabbit.core.RabbitTemplate[] 上。


[[messaging.amqp.sending-stream]]
== 向流发送消息

要向特定流发送消息，请指定流的名称，如下例所示：

[configprops,yaml]
----
spring:
  rabbitmq:
    stream:
      name: "my-stream"
----

如果定义了 javadoc:org.springframework.amqp.support.converter.MessageConverter[]、javadoc:org.springframework.rabbit.stream.support.converter.StreamMessageConverter[]、javadoc:org.springframework.rabbit.stream.producer.ProducerCustomizer[] 或 javadoc:org.springframework.rabbit.stream.micrometer.RabbitStreamTemplateObservationConvention[] bean，它会自动关联到自动配置的 javadoc:org.springframework.rabbit.stream.producer.RabbitStreamTemplate[]。

如果需要创建更多 javadoc:org.springframework.rabbit.stream.producer.RabbitStreamTemplate[] 实例，或者想要覆盖默认配置，Spring Boot 提供了一个 javadoc:org.springframework.boot.amqp.autoconfigure.RabbitStreamTemplateConfigurer[] bean，你可以用它来初始化一个 javadoc:org.springframework.rabbit.stream.producer.RabbitStreamTemplate[]，其设置与自动配置使用的工厂相同。



[[messaging.amqp.sending-stream.ssl]]
=== SSL

要对 RabbitMQ Streams 使用 SSL，请将 configprop:spring.rabbitmq.stream.ssl.enabled[] 设置为 `true`，或设置 configprop:spring.rabbitmq.stream.ssl.bundle[] 以配置 xref:features/ssl.adoc#features.ssl.bundles[SSL bundle] 使用。



[[messaging.amqp.receiving]]
== 接收消息

当 Rabbit 基础设施存在时，任何 bean 都可以使用 javadoc:org.springframework.amqp.rabbit.annotation.RabbitListener[format=annotation] 注解来创建一个监听器端点。
如果没有定义 javadoc:org.springframework.amqp.rabbit.listener.RabbitListenerContainerFactory[]，则会自动配置一个默认的 javadoc:org.springframework.amqp.rabbit.config.SimpleRabbitListenerContainerFactory[]，你可以使用 configprop:spring.rabbitmq.listener.type[] 属性切换到直接容器。
如果定义了 javadoc:org.springframework.amqp.support.converter.MessageConverter[]、javadoc:org.springframework.amqp.rabbit.retry.MessageRecoverer[] 或 javadoc:org.springframework.amqp.rabbit.support.micrometer.RabbitListenerObservationConvention[] bean，它会自动关联到默认工厂。

以下示例组件在 `someQueue` 队列上创建了一个监听器端点：

[source,java]
----
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

	@RabbitListener(queues = "someQueue")
	public void processMessage(String content) {
		// ...
	}

}
----

提示：有关更多详细信息，请参阅 javadoc:org.springframework.amqp.rabbit.annotation.EnableRabbit[format=annotation]。

如果需要创建更多 javadoc:org.springframework.amqp.rabbit.listener.RabbitListenerContainerFactory[] 实例，或者想要覆盖默认配置，Spring Boot 提供了 javadoc:org.springframework.boot.amqp.autoconfigure.SimpleRabbitListenerContainerFactoryConfigurer[] 和 javadoc:org.springframework.boot.amqp.autoconfigure.DirectRabbitListenerContainerFactoryConfigurer[]，你可以用它们来初始化 javadoc:org.springframework.amqp.rabbit.config.SimpleRabbitListenerContainerFactory[] 和 javadoc:org.springframework.amqp.rabbit.config.DirectRabbitListenerContainerFactory[]，其设置与自动配置使用的工厂相同。

提示：选择哪种容器类型并不重要。这两个 bean 由自动配置暴露。

例如，以下配置类暴露了另一个使用特定 javadoc:org.springframework.amqp.support.converter.MessageConverter[] 的工厂：

[source,java]
----
import org.springframework.amqp.rabbit.config.SimpleRabbitListenerContainerFactory;
import org.springframework.amqp.rabbit.connection.ConnectionFactory;
import org.springframework.boot.amqp.autoconfigure.SimpleRabbitListenerContainerFactoryConfigurer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyRabbitConfiguration {

	@Bean
	public SimpleRabbitListenerContainerFactory myFactory(SimpleRabbitListenerContainerFactoryConfigurer configurer) {
		SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory();
		ConnectionFactory connectionFactory = getCustomConnectionFactory();
		configurer.configure(factory, connectionFactory);
		factory.setMessageConverter(new MyMessageConverter());
		return factory;
	}

	private ConnectionFactory getCustomConnectionFactory() {
		return /**/ null;
	}

}
----

然后你可以在任何 javadoc:org.springframework.amqp.rabbit.annotation.RabbitListener[format=annotation] 注解的方法中使用该工厂，如下所示：

[source,java]
----
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

	@RabbitListener(queues = "someQueue", containerFactory = "myFactory")
	public void processMessage(String content) {
		// ...
	}

}
----

你可以启用重试来处理监听器抛出异常的情况。默认情况下，使用 javadoc:org.springframework.amqp.rabbit.retry.RejectAndDontRequeueRecoverer[]，但你可以定义自己的 javadoc:org.springframework.amqp.rabbit.retry.MessageRecoverer[]。当重试耗尽时，消息会被拒绝，并根据代理的配置丢弃或路由到死信交换机。默认情况下，重试是禁用的。你还可以通过声明 javadoc:org.springframework.boot.amqp.autoconfigure.RabbitListenerRetrySettingsCustomizer[] bean 以编程方式自定义 javadoc:org.springframework.core.retry.RetryPolicy[]。

重要：默认情况下，如果重试被禁用且监听器抛出异常，投递会无限重试。你可以通过两种方式修改此行为：将 `defaultRequeueRejected` 属性设置为 `false`，以便尝试零次重新投递；或者抛出 javadoc:org.springframework.amqp.AmqpRejectAndDontRequeueException[] 以表示应拒绝该消息。后者是启用重试且达到最大投递尝试次数时使用的机制。
