[[messaging.spring-integration]]
= Spring Integration

Spring Boot 为使用 {url-spring-integration-site}[Spring Integration] 提供了若干便利，包括 `spring-boot-starter-integration` starter。
Spring Integration 提供了消息传递的抽象，以及 HTTP、TCP 等其他传输方式。
如果 Spring Integration 在 classpath 上，它会通过 javadoc:org.springframework.integration.config.EnableIntegration[format=annotation] 注解进行初始化。

Spring Integration 的轮询逻辑依赖于 xref:features/task-execution-and-scheduling.adoc[自动配置的 javadoc:org.springframework.scheduling.TaskScheduler[]]。
默认的 javadoc:org.springframework.integration.scheduling.PollerMetadata[]（每秒轮询无限数量的消息）可以通过 `spring.integration.poller.*` 配置属性进行自定义。

Spring Boot 还配置了一些由额外 Spring Integration 模块触发启用的特性。
如果 `spring-integration-jmx` 也在 classpath 上，消息处理统计信息将通过 JMX 发布。
如果 `spring-integration-jdbc` 可用，可以在启动时创建默认数据库模式，如下行所示：

[configprops,yaml]
----
spring:
  integration:
    jdbc:
      initialize-schema: "always"
----

如果 `spring-integration-rsocket` 可用，开发者可以使用 `spring.rsocket.server.*` 属性配置一个 RSocket 服务器，并让它使用 javadoc:org.springframework.integration.rsocket.IntegrationRSocketEndpoint[] 或 javadoc:org.springframework.integration.rsocket.outbound.RSocketOutboundGateway[] 组件来处理传入的 RSocket 消息。
此基础设施可以处理 Spring Integration RSocket 通道适配器和 javadoc:org.springframework.messaging.handler.annotation.MessageMapping[format=annotation] 处理器（前提是配置了 `spring.integration.rsocket.server.message-mapping-enabled`）。

Spring Boot 还可以使用配置属性自动配置一个 javadoc:org.springframework.integration.rsocket.ClientRSocketConnector[]：

[configprops,yaml]
----
# 通过 TCP 连接到 RSocket 服务器
spring:
  integration:
    rsocket:
      client:
        host: "example.org"
        port: 9898
----

[configprops,yaml]
----
# 通过 WebSocket 连接到 RSocket 服务器
spring:
  integration:
    rsocket:
      client:
        uri: "ws://example.org"
----

更多详情，请参见 {code-spring-boot-integration-src}/autoconfigure/IntegrationAutoConfiguration.java[`IntegrationAutoConfiguration`] 和 javadoc:org.springframework.boot.integration.autoconfigure.IntegrationProperties[] 类。
