[[upgrading]]
= 升级 Spring Boot

关于如何从 Spring Boot 的早期版本进行升级的说明可在项目的 {url-github-wiki}[wiki] 中找到。
请按照 {url-github-wiki}#release-notes[发行说明] 部分中的链接，找到您要升级到的版本。

升级说明始终是发行说明中的第一项。
如果您跳过了多个版本，请务必同时查看您跳过的那些版本的发行说明。


[[upgrading.from-1x]]
== 从 1.x 升级

如果您是从 Spring Boot 的 `1.x` 版本升级，请查看项目 wiki 上的 {url-github-wiki}/Spring-Boot-2.0-Migration-Guide[迁移指南]，其中提供了升级到 Spring Boot 2.x 的详细说明。
同时查看 {url-github-wiki}#release-notes[发行说明]，了解每个版本中“`新增与值得关注`”的特性列表。



[[upgrading.from-2x]]
== 从 2.x 升级

如果您是从 Spring Boot 的 `2.x` 版本升级，请查看项目 wiki 上的 {url-github-wiki}/Spring-Boot-3.0-Migration-Guide[迁移指南]，其中提供了详细的升级说明。
同时查看 {url-github-wiki}#release-notes[发行说明]，了解每个版本中“`新增与值得关注`”的特性列表。



[[upgrading.from-3x]]
== 从 3.x 升级

如果您是从 Spring Boot 的 `3.x` 版本升级，请查看项目 wiki 上的 {url-github-wiki}/Spring-Boot-4.0-Migration-Guide[迁移指南]，其中提供了详细的升级说明。
同时查看 {url-github-wiki}#release-notes[发行说明]，了解每个版本中“`新增与值得关注`”的特性列表。



[[upgrading.to-feature]]
== 升级到新的特性版本

当升级到新的特性版本时，一些属性可能已被重命名或移除。
Spring Boot 提供了一种方式来分析您的应用程序环境并在启动时打印诊断信息，同时还能在运行时为您临时迁移属性。
要启用此功能，请在项目中添加以下依赖：

[source,xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-properties-migrator</artifactId>
	<scope>runtime</scope>
</dependency>
----

WARNING: 在环境后期添加的属性（例如使用 javadoc:org.springframework.context.annotation.PropertySource[format=annotation] 时）将不会被考虑。

NOTE: 迁移完成后，请务必从项目依赖中移除此模块。



[[upgrading.cli]]
== 升级 Spring Boot CLI

要升级现有的 CLI 安装，请使用相应的包管理器命令（例如 `brew upgrade`）。
如果您手动安装了 CLI，请遵循 xref:installing.adoc#getting-started.installing.cli.manual-installation[标准说明]，并记得更新您的 `PATH` 环境变量以移除任何旧引用。
