= Apache Pulsar 支持

https://pulsar.apache.org/[Apache Pulsar] 通过提供 auto-configuration 的 {url-spring-pulsar-site}[Spring for Apache Pulsar] 项目来获得支持。

当 `org.springframework.pulsar:spring-pulsar` 位于 classpath 上时，Spring Boot 将自动配置并注册用于 Apache Pulsar 组件的 Spring。

有一个 `spring-boot-starter-pulsar` starter 可以方便地收集用于使用的依赖项。


[[messaging.pulsar.connecting]]
== 连接到 Pulsar

当你使用 Pulsar starter 时，Spring Boot 将自动配置并注册一个 javadoc:org.apache.pulsar.client.api.PulsarClient[] bean。

默认情况下，应用程序尝试连接到位于 `pulsar://localhost:6650` 的本地 Pulsar 实例。
可以通过设置 configprop:spring.pulsar.client.service-url[] 属性为不同的值来调整。

注意：该值必须是有效的 https://pulsar.apache.org/docs/client-libraries-java/#connection-urls[Pulsar 协议] URL。

你可以通过指定任何以 `spring.pulsar.client.*` 为前缀的应用程序属性来配置客户端。

如果你需要对配置进行更多控制，可以考虑注册一个或多个 javadoc:org.springframework.pulsar.core.PulsarClientBuilderCustomizer[] bean。


[[messaging.pulsar.connecting.auth]]
=== 认证

要连接到需要认证的 Pulsar 集群，你需要通过设置 `pluginClassName` 以及插件所需的任何参数来指定要使用的认证插件。
你可以将参数设置为参数名称到参数值的映射。
以下示例展示了如何配置 `AuthenticationOAuth2` 插件。

[configprops,yaml]
----
spring:
  pulsar:
    client:
      authentication:
        plugin-class-name: org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
        param:
          issuerUrl: https://auth.server.cloud/
          privateKey: file:///Users/some-key.json
          audience: urn:sn:acme:dev:my-instance
----

[NOTE]
====
你需要确保在 `+spring.pulsar.client.authentication.param.*+` 下定义的名称与你的认证插件期望的名称完全匹配（通常是驼峰命名）。
Spring Boot 不会对这些条目进行任何形式的宽松绑定。

例如，如果你想为 `AuthenticationOAuth2` 认证插件配置颁发者 URL，你必须使用 `+spring.pulsar.client.authentication.param.issuerUrl+`。
如果你使用其他形式，例如 `issuerurl` 或 `issuer-url`，该设置将不会应用到插件。

这种缺乏宽松绑定的情况也使得使用环境变量进行认证参数设置变得困难，因为在转换过程中会丢失大小写敏感性。
如果你对环境变量使用这些参数，那么你需要遵循 Spring for Apache Pulsar 参考文档中的 {url-spring-pulsar-docs}/reference/pulsar/pulsar-client.html#client-authentication-env-vars[这些步骤] 才能使其正常工作。
====



[[messaging.pulsar.connecting.ssl]]
=== SSL

默认情况下，Pulsar 客户端以明文方式与 Pulsar 服务通信。
你可以按照 Spring for Apache Pulsar 参考文档中的 {url-spring-pulsar-docs}/reference/pulsar/pulsar-client.html#tls-encryption[这些步骤] 来启用 TLS 加密。

有关客户端和认证的完整详细信息，请参阅 Spring for Apache Pulsar 的 {url-spring-pulsar-docs}/reference/pulsar/pulsar-client.html[参考文档]。



[[messaging.pulsar.admin]]
== 连接到 Pulsar 管理

Spring for Apache Pulsar 的 javadoc:org.springframework.pulsar.core.PulsarAdministration[] 客户端也会自动配置。

默认情况下，应用程序尝试连接到本地 Pulsar 实例，地址为 `\http://localhost:8080`。
可以通过将 configprop:spring.pulsar.admin.service-url[] 属性设置为 `(http|https)://<host>:<port>` 形式的不同值来调整。

如果你需要对配置进行更多控制，请考虑注册一个或多个 javadoc:org.springframework.pulsar.core.PulsarAdminBuilderCustomizer[] bean。



[[messaging.pulsar.admin.auth]]
=== 认证

当访问需要认证的 Pulsar 集群时，管理客户端需要与常规 Pulsar 客户端相同的安全配置。
你可以使用前面提到的 xref:messaging/pulsar.adoc#messaging.pulsar.connecting.auth[authentication configuration]，只需将 `spring.pulsar.client.authentication` 替换为 `spring.pulsar.admin.authentication`。

提示：要在启动时创建主题，请添加一个类型为 javadoc:org.springframework.pulsar.core.PulsarTopic[] 的 bean。
如果主题已存在，则 bean 将被忽略。



[[messaging.pulsar.sending]]
== 发送消息

Spring 的 javadoc:org.springframework.pulsar.core.PulsarTemplate[] 是自动配置的，你可以使用它发送消息，如下例所示：

[source,java]
----
import org.springframework.pulsar.core.PulsarTemplate;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

	private final PulsarTemplate<String> pulsarTemplate;

	public MyBean(PulsarTemplate<String> pulsarTemplate) {
		this.pulsarTemplate = pulsarTemplate;
	}

	public void someMethod() {
		this.pulsarTemplate.send("someTopic", "Hello");
	}

}
----

javadoc:org.springframework.pulsar.core.PulsarTemplate[] 依赖于 javadoc:org.springframework.pulsar.core.PulsarProducerFactory[] 来创建底层的 Pulsar 生产者。
Spring Boot auto-configuration 也提供了这个生产者工厂，默认情况下它会缓存创建的生产者。
你可以通过指定任何以 `spring.pulsar.producer.\*` 和 `spring.pulsar.producer.cache.*` 为前缀的应用程序属性来配置生产者工厂和缓存设置。

如果你需要对生产者工厂配置进行更多控制，请考虑注册一个或多个 javadoc:org.springframework.pulsar.core.ProducerBuilderCustomizer[] bean。
这些自定义器会应用于所有创建的生产者。
你也可以在发送消息时传入一个 javadoc:org.springframework.pulsar.core.ProducerBuilderCustomizer[]，以仅影响当前生产者。

如果你需要对发送的消息进行更多控制，可以在发送消息时传入一个 javadoc:org.springframework.pulsar.core.TypedMessageBuilderCustomizer[]。



[[messaging.pulsar.receiving]]
== 接收消息

当 Apache Pulsar 基础设施存在时，任何 bean 都可以使用 javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation] 注解来创建一个监听器 endpoint。
以下组件在 `someTopic` 主题上创建了一个监听器 endpoint：

[source,java]
----
import org.springframework.pulsar.annotation.PulsarListener;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

	@PulsarListener(topics = "someTopic")
	public void processMessage(String content) {
		// ...
	}

}
----

Spring Boot auto-configuration 提供了 javadoc:org.springframework.pulsar.annotation.PulsarListener[] 所需的所有组件，例如 javadoc:org.springframework.pulsar.config.PulsarListenerContainerFactory[] 以及用于构造底层 Pulsar 消费者的消费者工厂。
你可以通过指定任何以 `spring.pulsar.listener.\*` 和 `spring.pulsar.consumer.*` 为前缀的应用程序属性来配置这些组件。

如果你需要对消费者工厂的配置进行更多控制，请考虑注册一个或多个 javadoc:org.springframework.pulsar.core.ConsumerBuilderCustomizer[] bean。
这些自定义器会应用于工厂创建的所有消费者，因此也应用于所有 javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation] 实例。
你也可以通过设置 javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation] annotation 的 `consumerCustomizer` 属性来自定义单个监听器。

如果你需要对实际容器工厂配置进行更多控制，请考虑注册一个或多个 `PulsarContainerFactoryCustomizer<ConcurrentPulsarListenerContainerFactory<?>>` bean。



[[messaging.pulsar.reading]]
== 读取消息

Pulsar 读取器接口使应用程序能够手动管理游标。
当你使用读取器连接到主题时，需要指定读取器在连接主题时从哪条消息开始读取。

当 Apache Pulsar 基础设施存在时，任何 bean 都可以使用 javadoc:org.springframework.pulsar.annotation.PulsarReader[format=annotation] 注解来通过读取器消费消息。
以下组件创建了一个读取器 endpoint，从 `someTopic` 主题的开头开始读取消息：

[source,java]
----
import org.springframework.pulsar.annotation.PulsarReader;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

	@PulsarReader(topics = "someTopic", startMessageId = "earliest")
	public void processMessage(String content) {
		// ...
	}

}
----

javadoc:org.springframework.pulsar.annotation.PulsarReader[format=annotation] 依赖于 javadoc:org.springframework.pulsar.core.PulsarReaderFactory[] 来创建底层的 Pulsar 读取器。
Spring Boot auto-configuration 提供了这个读取器工厂，可以通过设置任何以 `spring.pulsar.reader.*` 为前缀的应用程序属性来自定义。

如果你需要对读取器工厂的配置进行更多控制，请考虑注册一个或多个 javadoc:org.springframework.pulsar.core.ReaderBuilderCustomizer[] bean。
这些自定义器会应用于工厂创建的所有读取器，因此也应用于所有 javadoc:org.springframework.pulsar.annotation.PulsarReader[format=annotation] 实例。
你也可以通过设置 javadoc:org.springframework.pulsar.annotation.PulsarReader[format=annotation] annotation 的 `readerCustomizer` 属性来自定义单个监听器。

如果你需要对实际容器工厂配置进行更多控制，请考虑注册一个或多个 `PulsarContainerFactoryCustomizer<DefaultPulsarReaderContainerFactory<?>>` bean。

提示：有关上述任何组件的更多详细信息以及发现其他可用功能，请参阅 Spring for Apache Pulsar 的 {url-spring-pulsar-docs}[参考文档]。



[[messaging.pulsar.transactions]]
== 事务支持

Spring for Apache Pulsar 在使用 javadoc:org.springframework.pulsar.core.PulsarTemplate[] 和 javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation] 时支持事务。

将 configprop:spring.pulsar.transaction.enabled[] 属性设置为 `true` 将会：

* 配置一个 javadoc:org.springframework.pulsar.transaction.PulsarTransactionManager[] bean
* 为 javadoc:org.springframework.pulsar.core.PulsarTemplate[] 启用事务支持
* 为 javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation] 方法启用事务支持

javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation] 的 `transactional` 属性可用于微调何时在监听器中使用事务。

为了对 Spring for Apache Pulsar 事务功能进行更多控制，你应该定义自己的 javadoc:org.springframework.pulsar.core.PulsarTemplate[] 和/或 javadoc:org.springframework.pulsar.config.ConcurrentPulsarListenerContainerFactory[] bean。
如果默认自动配置的 javadoc:org.springframework.pulsar.transaction.PulsarTransactionManager[] 不合适，你也可以定义一个 javadoc:org.springframework.pulsar.transaction.PulsarAwareTransactionManager[] bean。



[[messaging.pulsar.additional-properties]]
== 其他 Pulsar 属性

auto-configuration 支持的属性显示在附录的 xref:appendix:application-properties/index.adoc#appendix.application-properties.integration[Integration Properties] 部分。
请注意，这些属性（连字符形式或驼峰形式）大部分直接映射到 Apache Pulsar 配置属性。
详细信息请参阅 Apache Pulsar 文档。

只有 Pulsar 支持的属性子集可以直接通过 javadoc:org.springframework.boot.pulsar.autoconfigure.PulsarProperties[] 类获得。
如果你希望通过额外的不直接支持的属性来调整自动配置的组件，可以使用每个上述组件支持的自定义器。
