[[features.kotlin]]
= Kotlin 支持

https://kotlinlang.org[Kotlin] 是一种面向 JVM（及其他平台）的静态类型语言，能够编写简洁优雅的代码，同时提供与现有 Java 库的 {url-kotlin-docs}/java-interop.html[互操作性]。

Spring Boot 通过利用 Spring 框架、Spring Data 和 Reactor 等其他 Spring 项目中的支持来提供 Kotlin 支持。
更多信息请参阅 {url-spring-framework-docs}/languages/kotlin.html[Spring 框架 Kotlin 支持文档]。

开始使用 Spring Boot 和 Kotlin 的最简单方法是遵循 https://spring.io/guides/tutorials/spring-boot-kotlin/[这份综合教程]。
你可以通过 https://start.spring.io/#!language=kotlin[start.spring.io] 创建新的 Kotlin 项目。
如果需要支持，欢迎加入 https://slack.kotlinlang.org/[Kotlin Slack] 的 #spring 频道，或在 https://stackoverflow.com/questions/tagged/spring+kotlin[Stack Overflow] 上使用 `spring` 和 `kotlin` 标签提问。



[[features.kotlin.requirements]]
== 要求

Spring Boot 至少需要 Kotlin 2.2.x，并通过依赖管理管理合适的 Kotlin 版本。
要使用 Kotlin，`org.jetbrains.kotlin:kotlin-stdlib` 和 `org.jetbrains.kotlin:kotlin-reflect` 必须存在于 classpath 中。

Kotlin 2.2.x 引入了 https://kotlinlang.org/docs/whatsnew22.html#new-defaulting-rules-for-use-site-annotation-targets[用于将注解传播到参数、字段和属性的新默认规则]。
为了避免相关警告并使用可能在即将到来的版本中成为 Kotlin 默认行为的行为，建议配置 `-Xannotation-default-target=param-property` 编译器标志。

由于 https://discuss.kotlinlang.org/t/classes-final-by-default/166[Kotlin 类默认是 final 的]，你可能希望配置 {url-kotlin-docs}/compiler-plugins.html#spring-support[kotlin-spring] 插件，以自动打开 Spring 注解的类，使其能够被代理。

https://github.com/FasterXML/jackson-module-kotlin[Jackson 的 Kotlin 模块] 用于在 Kotlin 中序列化/反序列化 JSON 数据。
当在 classpath 中发现时，它会自动注册。

提示：如果在 https://start.spring.io/#!language=kotlin[start.spring.io] 上引导 Kotlin 项目，这些依赖和插件默认提供。



[[features.kotlin.null-safety]]
== 空安全

Kotlin 的关键特性之一是 {url-kotlin-docs}/null-safety.html[空安全]。
它在编译时处理 `null` 值，而不是将问题推迟到运行时并遇到 javadoc:java.lang.NullPointerException[]。
这有助于消除常见的错误来源，而无需付出像 javadoc:java.util.Optional[] 这样的包装器代价。
Kotlin 还允许使用可空值的函数式构造，如 https://www.baeldung.com/kotlin-null-safety[Kotlin 空安全综合指南] 所述。

尽管 Java 不允许在其类型系统中表达空安全，但大多数 Spring 项目通过 https://jspecify.dev/[JSpecify] 注解提供 {url-spring-framework-docs}/core/null-safety.html[空安全]。

从 Kotlin 2.1 开始，Kotlin 强制对来自 `org.jspecify.annotations` 包的空性注解进行严格处理。



[[features.kotlin.api]]
== Kotlin API



[[features.kotlin.api.run-application]]
=== runApplication

Spring Boot 提供了一种惯用的方式来运行应用程序，使用 `runApplication<MyApplication>(*args)`，如下例所示：

[source,kotlin]
----
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class MyApplication

fun main(args: Array<String>) {
	runApplication<MyApplication>(*args)
}
----

这是 `SpringApplication.run(MyApplication::class.java, *args)` 的直接替代品。它还允许自定义应用程序，如下例所示：

[source,kotlin]
----
runApplication<MyApplication>(*args) {
	setBannerMode(OFF)
}
----



[[features.kotlin.api.extensions]]
=== 扩展

Kotlin {url-kotlin-docs}/extensions.html[扩展] 提供了向现有类添加额外功能的能力。
Spring Boot Kotlin API 利用这些扩展为现有 API 添加了新的 Kotlin 特定便利。

提供了 javadoc:org.springframework.boot.resttestclient.TestRestTemplate[] 扩展，类似于 Spring Framework 为 javadoc:org.springframework.web.client.RestOperations[] 提供的扩展。
除此之外，这些扩展还使得利用 Kotlin 的具体化类型参数成为可能。



[[features.kotlin.dependency-management]]
== 依赖管理

为了避免在 classpath 上混合不同版本的 Kotlin 依赖，Spring Boot 导入了 Kotlin BOM。

使用 Maven 时，可以通过设置 `kotlin.version` 属性来自定义 Kotlin 版本，并为 `kotlin-maven-plugin` 提供了插件管理。
使用 Gradle 时，Spring Boot 插件会自动将 `kotlin.version` 与 Kotlin 插件的版本对齐。

Spring Boot 还通过导入 Kotlin Coroutines BOM 来管理 Coroutines 依赖的版本。
可以通过设置 `kotlin-coroutines.version` 属性来自定义版本。

提示：如果在 https://start.spring.io/#!language=kotlin[start.spring.io] 上引导一个至少包含一个响应式依赖的 Kotlin 项目，则默认提供 `org.jetbrains.kotlinx:kotlinx-coroutines-reactor` 依赖。



[[features.kotlin.configuration-properties]]
== @ConfigurationProperties
javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation] 与 xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.constructor-binding[构造函数绑定] 结合使用时，支持具有不可变 `val` 属性的数据类，如下例所示：

[source,kotlin]
----
@ConfigurationProperties("example.kotlin")
data class KotlinExampleProperties(
		val name: String,
		val description: String,
		val myService: MyService
) {

	data class MyService(
			val apiToken: String,
			val uri: URI
	)
}
----

由于与 Java 互操作性的限制，对值类的支持有限。
特别是，依赖值类的默认值在配置属性绑定时将无法正常工作。
在这种情况下，应改用数据类。

提示：要使用注解处理器生成 xref:specification:configuration-metadata/annotation-processor.adoc[你自己的元数据]，应使用 `spring-boot-configuration-processor` 依赖项配置 {url-kotlin-docs}/kapt.html[`kapt`]。
请注意，由于 kapt 提供的模型存在限制，某些功能（如检测默认值或已弃用的项）无法正常工作。



[[features.kotlin.testing]]
== 测试

虽然可以使用 JUnit 4 测试 Kotlin 代码，但默认提供 JUnit 6，并且推荐使用。
JUnit 6 允许测试类实例化一次，并用于该类的所有测试。
这使得可以在非静态方法上使用 javadoc:org.junit.jupiter.api.BeforeAll[format=annotation] 和 javadoc:org.junit.jupiter.api.AfterAll[format=annotation] 注解，这非常适合 Kotlin。

要模拟 Kotlin 类，推荐使用 https://mockk.io/[MockK]。
如果你需要与 Mockito 特定的 xref:testing/spring-boot-applications.adoc#testing.spring-boot-applications.mocking-beans[`@MockitoBean` 和 javadoc:org.springframework.test.context.bean.override.mockito.MockitoSpyBean[format=annotation] 注解] 等效的 `MockK`，可以使用 https://github.com/Ninja-Squad/springmockk[SpringMockK]，它提供了类似的 `@MockkBean` 和 `@SpykBean` 注解。



[[features.kotlin.resources]]
== 资源



[[features.kotlin.resources.further-reading]]
=== 延伸阅读

* {url-kotlin-docs}[Kotlin 语言参考]
* https://kotlinlang.slack.com/[Kotlin Slack]（设有专门的 #spring 频道）
* https://stackoverflow.com/questions/tagged/spring+kotlin[Stack Overflow 上带有 `spring` 和 `kotlin` 标签的问题]
* https://try.kotlinlang.org/[在浏览器中尝试 Kotlin]
* https://blog.jetbrains.com/kotlin/[Kotlin 博客]
* https://kotlin.link/[Awesome Kotlin]
* https://spring.io/guides/tutorials/spring-boot-kotlin/[教程：使用 Spring Boot 和 Kotlin 构建 Web 应用程序]
* https://spring.io/blog/2016/02/15/developing-spring-boot-applications-with-kotlin[使用 Kotlin 开发 Spring Boot 应用程序]
* https://spring.io/blog/2016/03/20/a-geospatial-messenger-with-kotlin-spring-boot-and-postgresql[使用 Kotlin、Spring Boot 和 PostgreSQL 的地理空间信使]
* https://spring.io/blog/2017/01/04/introducing-kotlin-support-in-spring-framework-5-0[Spring Framework 5.0 中引入 Kotlin 支持]
* https://spring.io/blog/2017/08/01/spring-framework-5-kotlin-apis-the-functional-way[Spring Framework 5 Kotlin API：函数式方式]



[[features.kotlin.resources.examples]]
=== 示例

* https://github.com/sdeleuze/spring-boot-kotlin-demo[spring-boot-kotlin-demo]：常规 Spring Boot + Spring Data JPA 项目
* https://github.com/mixitconf/mixit[mixit]：Spring Boot 2 + WebFlux + Reactive Spring Data MongoDB
* https://github.com/sdeleuze/spring-kotlin-fullstack[spring-kotlin-fullstack]：WebFlux Kotlin 全栈示例，前端使用 Kotlin2js 而非 JavaScript 或 TypeScript
* https://github.com/spring-petclinic/spring-petclinic-kotlin[spring-petclinic-kotlin]：Spring PetClinic 示例应用程序的 Kotlin 版本
* https://github.com/sdeleuze/spring-kotlin-deepdive[spring-kotlin-deepdive]：从 Boot 1.0 + Java 逐步迁移到 Boot 2.0 + Kotlin
* https://github.com/sdeleuze/spring-boot-coroutines-demo[spring-boot-coroutines-demo]：协程示例项目
