= SSL

Spring Boot 提供了配置 SSL 信任材料的能力，这些材料可应用于多种类型的连接，以支持安全通信。前缀为 `spring.ssl.bundle` 的配置属性可用于指定命名的信任材料集及其相关信息。

[[features.ssl.jks]]
== 使用 Java KeyStore 文件配置 SSL

前缀为 `spring.ssl.bundle.jks` 的配置属性可用于配置使用 Java `keytool` 工具创建并存储在 JKS 或 PKCS12 格式的 Java KeyStore 文件中的信任材料包。每个包都有一个用户提供的名称，可用于引用该包。

当用于保护嵌入式 Web 服务器时，`keystore` 通常配置为包含证书和私钥的 Java KeyStore，如下例所示：

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          jks:
            mybundle:
              key:
                alias: "application"
              keystore:
                location: "classpath:application.p12"
                password: "secret"
                type: "PKCS12"
----
当用于保护客户端连接时，`truststore` 通常配置一个包含服务器证书的 Java KeyStore，如下例所示：

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          jks:
            mybundle:
              truststore:
                location: "classpath:server.p12"
                password: "secret"
----
[TIP]
====
可以提供其 xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.conversion.base64[Base64 编码内容]，而不是文件的路径。
如果选择此选项，属性的值应以 `base64:` 开头。
====

有关支持的属性的完整集合，请参见 javadoc:org.springframework.boot.autoconfigure.ssl.JksSslBundleProperties[]。

注意：如果使用环境变量来配置捆绑包，则捆绑包的名称 xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.relaxed-binding.maps-from-environment-variables[始终转换为小写]。



[[features.ssl.pem]]
== 使用 PEM 编码证书配置 SSL

前缀为 `spring.ssl.bundle.pem` 的配置属性可用于配置 PEM 编码文本形式的信任材料捆绑包。
每个捆绑包都有一个用户提供的名称，可用于引用该捆绑包。

当用于保护嵌入式 Web 服务器时，`keystore` 通常配置有证书和私钥，如以下示例所示：

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            mybundle:
              keystore:
                certificate: "classpath:application.crt"
                private-key: "classpath:application.key"
----
当用于保护客户端连接时，`truststore`通常配置为使用服务器证书，如下例所示：

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            mybundle:
              truststore:
                certificate: "classpath:server.crt"
----
====
可以提供其 xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.conversion.base64[Base64 编码内容] 而不是文件位置。
如果选择此选项，属性的值应以 `base64:` 开头。

PEM 内容也可以直接用于 `certificate` 和 `private-key` 属性。
如果属性值包含 `BEGIN` 和 `END` 标记，则它们将被视为 PEM 内容而不是资源位置。

以下示例展示了如何定义信任库证书：

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            mybundle:
              truststore:
                certificate: |
                  -----BEGIN CERTIFICATE-----
                  MIID1zCCAr+gAwIBAgIUNM5QQv8IzVQsgSmmdPQNaqyzWs4wDQYJKoZIhvcNAQEL
                  BQAwezELMAkGA1UEBhMCWFgxEjAQBgNVBAgMCVN0YXRlTmFtZTERMA8GA1UEBwwI
                  ...
                  V0IJjcmYjEZbTvpjFKznvaFiOUv+8L7jHQ1/Yf+9c3C8gSjdUfv88m17pqYXd+Ds
                  HEmfmNNjht130UyjNCITmLVXyy5p35vWmdf95U3uEbJSnNVtXH8qRmN9oK9mUpDb
                  ngX6JBJI7fw7tXoqWSLHNiBODM88fUlQSho8
                  -----END CERTIFICATE-----
----
====

有关支持的属性的完整列表，请参见 javadoc:org.springframework.boot.autoconfigure.ssl.PemSslBundleProperties[]。

注意：如果使用环境变量配置捆绑包，则捆绑包的名称会 xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.relaxed-binding.maps-from-environment-variables[始终转换为小写]。



[[features.ssl.applying]]
== 应用 SSL 捆绑包

一旦使用属性配置完成，SSL 捆绑包就可以通过名称在配置属性中引用，用于 Spring Boot 自动配置的各种连接类型。
有关更多信息，请参见 xref:how-to:webserver.adoc#howto.webserver.configure-ssl[嵌入式 Web 服务器]、xref:data/index.adoc[数据技术]和 xref:io/rest-client.adoc[REST 客户端]等章节。



[[features.ssl.bundles]]
== 使用 SSL 捆绑包

Spring Boot 自动配置一个类型为 javadoc:org.springframework.boot.ssl.SslBundles[] 的 bean，该 bean 提供对使用 `spring.ssl.bundle` 属性配置的每个命名捆绑包的访问。

可以从自动配置的 javadoc:org.springframework.boot.ssl.SslBundles[] bean 中检索 javadoc:org.springframework.boot.ssl.SslBundle[]，并使用它来创建用于配置客户端库中 SSL 连接的对象。
javadoc:org.springframework.boot.ssl.SslBundle[] 提供了一种分层方法来获取这些 SSL 对象：

- `getStores()` 提供对密钥库和信任库 javadoc:java.security.KeyStore[] 实例以及任何所需密钥库密码的访问。
- `getManagers()` 提供对 javadoc:javax.net.ssl.KeyManagerFactory[] 和 javadoc:javax.net.ssl.TrustManagerFactory[] 实例以及它们创建的 javadoc:javax.net.ssl.KeyManager[] 和 javadoc:javax.net.ssl.TrustManager[] 数组的访问。
- `createSslContext()` 提供了一种便捷的方式来获取新的 javadoc:javax.net.ssl.SSLContext[] 实例。

此外，javadoc:org.springframework.boot.ssl.SslBundle[] 提供了有关正在使用的密钥、要使用的协议以及应应用于 SSL 引擎的任何选项的详细信息。

以下示例展示了如何检索 javadoc:org.springframework.boot.ssl.SslBundle[] 并使用它来创建 javadoc:javax.net.ssl.SSLContext[]：

[source,java]
----
import javax.net.ssl.SSLContext;

import org.springframework.boot.ssl.SslBundle;
import org.springframework.boot.ssl.SslBundles;
import org.springframework.stereotype.Component;

@Component
public class MyComponent {

	@SuppressWarnings("unused")
	public MyComponent(SslBundles sslBundles) {
		SslBundle sslBundle = sslBundles.getBundle("mybundle");
		SSLContext sslContext = sslBundle.createSslContext();
		// do something with the created sslContext
	}

}
----



[[features.ssl.reloading]]
== 重新加载 SSL 捆绑包

当密钥材料发生变化时，可以重新加载 SSL 捆绑包。
使用捆绑包的组件必须与可重新加载的 SSL 捆绑包兼容。
目前以下组件是兼容的：

* Tomcat Web 服务器
* Netty Web 服务器

要启用重新加载，您需要通过配置属性选择加入，如下例所示：

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            mybundle:
              reload-on-update: true
              keystore:
                certificate: "file:/some/directory/application.crt"
                private-key: "file:/some/directory/application.key"
----
然后，文件监视器会监视这些文件，如果它们发生变化，SSL 捆绑包将被重新加载。
这反过来会触发消费组件中的重新加载，例如 Tomcat 会在启用 SSL 的连接器中轮换证书。

您可以使用 configprop:spring.ssl.bundle.watch.file.quiet-period[] 属性配置文件监视器的静默期（以确保没有更多更改）。

[[features.ssl.reloading.lets-encrypt]]
=== 使用 Let's Encrypt 重新加载 SSL 捆绑包

如果您使用 https://letsencrypt.org/[Let's Encrypt] 颁发的证书，并由外部工具（如 https://certbot.eff.org/[Certbot]）续订，则可以配置 PEM 捆绑包以使用生成的文件并启用重新加载。
Certbot 通常将这些文件存储在 `/etc/letsencrypt/live/` 下以您的域名命名的目录中。
以下示例展示了如何为 `example.com` 配置 PEM 捆绑包：

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            webserver:
              reload-on-update: true
              keystore:
                certificate: "file:/etc/letsencrypt/live/example.com/fullchain.pem"
                private-key: "file:/etc/letsencrypt/live/example.com/privkey.pem"
    server:
      ssl:
        bundle: "webserver"
----
Spring Boot 不会请求或续订 Let's Encrypt 证书。
当 Certbot 或其他 ACME 客户端更新配置的文件时，SSL 捆绑包会重新加载。
兼容的消费者（例如 Tomcat 和 Netty Web 服务器）随后可以使用更新后的证书，而无需重新启动应用程序。

`/etc/letsencrypt/live` 中的文件通常是 `/etc/letsencrypt/archive` 中文件的符号链接。
文件监视器会跟踪符号链接，以便对目标文件的更新可以触发重新加载。
