= 日志记录

Spring Boot 在内部所有日志记录中使用 https://commons.apache.org/logging[Commons Logging]，但底层日志实现是开放的。
为 {apiref-openjdk}/java.logging/java/util/logging/package-summary.html[Java Util Logging]、https://logging.apache.org/log4j/2.x/[Log4j2] 和 https://logback.qos.ch/[Logback] 提供了默认配置。
每种情况下，日志记录器都预先配置为使用控制台输出，并可选择文件输出。

默认情况下，如果你使用 starters，则使用 Logback 进行日志记录。
还包含了适当的 Logback 路由，以确保使用 Java Util Logging、Commons Logging、Log4J 或 SLF4J 的依赖库都能正常工作。

提示：Java 有许多可用的日志框架。
如果上面的列表看起来令人困惑，请不要担心。
通常，你不需要更改日志依赖项，Spring Boot 的默认设置就能很好地工作。

提示：当你将应用程序部署到 servlet 容器或应用服务器时，使用 Java Util Logging API 执行的日志记录不会路由到应用程序的日志中。
这可以防止容器或部署到其中的其他应用程序执行的日志记录出现在你的应用程序日志中。

[[features.logging.log-format]]
== 日志格式

Spring Boot 的默认日志输出类似于以下示例：

[source]
----
include::ROOT:partial$logging/logging-format.txt[]
----
输出以下项目：

* 日期和时间：毫秒精度且易于排序。
* 日志级别：`ERROR`、`WARN`、`INFO`、`DEBUG` 或 `TRACE`。
* 进程 ID。
* 一个 `---` 分隔符，用于区分实际日志消息的开始。
* 应用名称：用方括号括起来（默认仅在设置了 configprop:spring.application.name[] 时记录）
* 应用组：用方括号括起来（默认仅在设置了 configprop:spring.application.group[] 时记录）
* 线程名称：用方括号括起来（控制台输出时可能被截断）。
* 关联 ID：如果启用了追踪（上面的示例中未显示）
* 日志记录器名称：通常是源类名（通常缩写）。
* 日志消息。

注意：Logback 没有 `FATAL` 级别。
它被映射到 `ERROR`。

提示：如果你有 configprop:spring.application.name[] 属性但不想记录它，可以将 configprop:logging.include-application-name[] 设置为 `false`。

提示：如果你有 configprop:spring.application.group[] 属性但不想记录它，可以将 configprop:logging.include-application-group[] 设置为 `false`。

提示：有关关联 ID 的更多详细信息，请 xref:reference:actuator/tracing.adoc#actuator.micrometer-tracing.logging[参阅此文档]。

[[features.logging.console-output]]
== 控制台输出

默认日志配置会在消息写入时将消息回显到控制台。
默认情况下，记录 `ERROR` 级别、`WARN` 级别和 `INFO` 级别的消息。
你也可以通过使用 `--debug` 标志启动应用程序来启用 "`debug`" 模式。

[source,shell]
----
$ java -jar myapp.jar --debug
----
NOTE: 你也可以在 `application.properties` 中指定 `debug=true`。

当启用调试模式时，会选择一些核心日志记录器（嵌入式容器、Hibernate 和 Spring Boot）输出更多信息。
启用调试模式 _不会_ 配置你的应用程序以 `DEBUG` 级别记录所有消息。

或者，你可以通过使用 `--trace` 标志（或在 `application.properties` 中使用 `trace=true`）启动应用程序来启用“`trace`”模式。
这样做会为一些核心日志记录器（嵌入式容器、Hibernate 模式生成以及整个 Spring 产品组合）启用跟踪日志记录。

如果你想禁用基于控制台的日志记录，可以将 configprop:logging.console.enabled[] 属性设置为 `false`。


[[features.logging.console-output.color-coded]]
=== 彩色编码输出

如果你的终端支持 ANSI，则会使用彩色输出来提高可读性。
你可以将 `spring.output.ansi.enabled` 设置为 javadoc:org.springframework.boot.ansi.AnsiOutput$Enabled[supported value] 以覆盖自动检测。

颜色编码通过使用 `%clr` 转换词进行配置。
在最简单的形式中，转换器根据日志级别对输出进行着色，如下例所示：

[source]
----
%clr(%5p)
----
下表描述了日志级别到颜色的映射：

|===
| 级别 | 颜色

| `FATAL`
| 红色

| `ERROR`
| 红色

| `WARN`
| 黄色

| `INFO`
| 绿色

| `DEBUG`
| 绿色

| `TRACE`
| 绿色
|===

或者，您可以通过将颜色和样式作为选项提供给转换来指定应使用的颜色和样式。
例如，要使文本变为黄色和粗体，请使用以下设置：

[source]
----
%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){yellow,bold}
----
支持以下文本颜色：

* `black`
* `blue`
* `bright_black`
* `bright_blue`
* `bright_cyan`
* `bright_green`
* `bright_magenta`
* `bright_red`
* `bright_white`
* `bright_yellow`
* `cyan`
* `green`
* `magenta`
* `red`
* `white`
* `yellow`

支持以下背景颜色：

* `bg_black`
* `bg_blue`
* `bg_bright_black`
* `bg_bright_blue`
* `bg_bright_cyan`
* `bg_bright_green`
* `bg_bright_magenta`
* `bg_bright_red`
* `bg_bright_white`
* `bg_bright_yellow`
* `bg_cyan`
* `bg_green`
* `bg_magenta`
* `bg_red`
* `bg_white`
* `bg_yellow`

支持以下样式：

* `bold`
* `faint`
* `italic`
* `normal`
* `reverse`
* `underline`


[[features.logging.file-output]]
== 文件输出

默认情况下，Spring Boot 仅记录到控制台，不写入日志文件。
如果希望在控制台输出之外写入日志文件，需要设置 configprop:logging.file.name[] 或 configprop:logging.file.path[] 属性（例如，在 `application.properties` 中）。
如果同时设置了这两个属性，则 `logging.file.path` 被忽略，仅使用 `logging.file.name`。

下表展示了 `logging.*` 属性如何组合使用：

.日志属性
[cols="1,1,4"]
|===
| configprop:logging.file.name[] | configprop:logging.file.path[] | 描述

| _(无)_
| _(无)_
| 仅控制台日志。

| 特定文件（例如 `my.log`）
| _(无)_
| 写入 `logging.file.name` 指定的位置。
  该位置可以是绝对路径或相对于当前目录的路径。

| _(无)_
| 特定目录（例如 `/var/log`）
| 将 `spring.log` 写入 `logging.file.path` 指定的目录。
  该目录可以是绝对路径或相对于当前目录的路径。

| 特定文件
| 特定目录
| 写入 `logging.file.name` 指定的位置，并忽略 `logging.file.path`。
  该位置可以是绝对路径或相对于当前目录的路径。
|===

当日志文件达到 10 MB 时进行轮转，并且与控制台输出一样，默认记录 `ERROR`、`WARN` 和 `INFO` 级别的消息。
注意，Log4J2 需要设置 `logging.file.path` 才能使用此类配置。

提示：日志属性与实际日志基础设施无关。
因此，特定配置键（例如 Logback 的 `logback.configurationFile`）不由 Spring Boot 管理。


[[features.logging.file-rotation]]
== 文件轮转

如果使用 Logback 或 Log4J2，可以通过 `application.properties` 或 `application.yaml` 文件微调日志轮转设置。
对于所有其他日志系统，需要直接自行配置轮转设置。

Logback 支持以下轮转策略属性：

|===
| 名称 | 描述

| configprop:logging.logback.rollingpolicy.file-name-pattern[]
| 用于创建日志归档的文件名模式。

| configprop:logging.logback.rollingpolicy.clean-history-on-start[]
| 是否在应用程序启动时清理日志归档。

| configprop:logging.logback.rollingpolicy.max-file-size[]
| 日志文件归档前的最大大小。

| configprop:logging.logback.rollingpolicy.total-size-cap[]
| 日志归档在被删除前可占用的最大空间。

| configprop:logging.logback.rollingpolicy.max-history[]
| 保留的归档日志文件最大数量（默认为 7）。
|===

如果使用 Log4j2，则提供以下轮转策略属性：

|===
| 名称 | 描述

| configprop:logging.log4j2.rollingpolicy.file-name-pattern[]
| 用于创建日志归档的文件名模式。

| configprop:logging.log4j2.rollingpolicy.max-file-size[]
| 日志文件归档前的最大大小（默认为 10MB）。

| configprop:logging.log4j2.rollingpolicy.max-history[]
| 保留的归档日志文件最大数量（默认为 7）。

| configprop:logging.log4j2.rollingpolicy.strategy[]
| 轮转策略（默认为 'size'）。

| configprop:logging.log4j2.rollingpolicy.cron[]
| 当策略为 'cron' 时的 Cron 表达式（默认为每天午夜）。

| configprop:logging.log4j2.rollingpolicy.time-interval[]
| 当策略为 'time' 或 'size-and-time' 时基于时间的触发间隔（默认为 1）。

| configprop:logging.log4j2.rollingpolicy.time-modulate[]
| 当策略基于时间时，是否将下一次轮转时间对齐到间隔的起始点（默认为 `false`）。

|===


[[features.logging.log-levels]]
== 日志级别

所有支持的日志系统都可以在 Spring javadoc:org.springframework.core.env.Environment[] 中设置日志级别（例如，在 `application.properties` 中），使用 `+logging.level.<logger-name>=<level>+`，其中 `level` 是 TRACE、DEBUG、INFO、WARN、ERROR、FATAL 或 OFF 之一。
`root` 日志记录器可以通过 `logging.level.root` 进行配置。

以下示例展示了 `application.properties` 中可能的日志设置：

[configprops,yaml]
----
logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"
----
也可以使用环境变量设置日志级别。
例如，`LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG` 会将 `org.springframework.web` 设置为 `DEBUG`。

注意：上述方法仅适用于包级别的日志配置。
由于宽松绑定 xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.relaxed-binding.maps-from-environment-variables[始终将环境变量转换为小写]，因此无法通过这种方式为单个类配置日志。
如果需要为某个类配置日志，可以使用 xref:features/external-config.adoc#features.external-config.application-json[`SPRING_APPLICATION_JSON` 变量]。

[[features.logging.log-groups]]
== 日志组

将相关的日志记录器分组以便同时配置它们通常很有用。
例如，您可能经常更改 _所有_ Tomcat 相关日志记录器的日志级别，但不容易记住顶层包。

为帮助解决此问题，Spring Boot 允许您在 Spring javadoc:org.springframework.core.env.Environment[] 中定义日志组。
例如，以下是如何通过将 "`tomcat`" 组添加到您的 `application.properties` 中来定义它：

[configprops,yaml]
----
logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
----
定义后，您可以通过一行代码更改组中所有日志记录器的级别：

[configprops,yaml]
----
logging:
  level:
    tomcat: "trace"
----
Spring Boot 包含以下预定义的日志组，可直接使用：

[cols="1,4"]
|===
| 名称 | 日志器

| web
| `org.springframework.core.codec`, `org.springframework.http`, `org.springframework.web`, `org.springframework.boot.actuate.endpoint.web`, `org.springframework.boot.web.servlet.ServletContextInitializerBeans`

| sql
| `org.springframework.jdbc.core`, `org.hibernate.SQL`, javadoc:org.jooq.tools.LoggerListener[]
|===


[[features.logging.shutdown-hook]]
== 使用日志关闭钩子

为了在应用程序终止时释放日志资源，提供了一个关闭钩子，当 JVM 退出时将触发日志系统清理。
除非你的应用程序部署为 war 文件，否则此关闭钩子会自动注册。
如果你的应用程序具有复杂的上下文层次结构，关闭钩子可能无法满足你的需求。
如果确实如此，请禁用关闭钩子，并直接研究底层日志系统提供的选项。
例如，Logback 提供了 https://logback.qos.ch/manual/loggingSeparation.html[上下文选择器]，允许每个 Logger 在其自己的上下文中创建。
你可以使用 configprop:logging.register-shutdown-hook[] 属性来禁用关闭钩子。
将其设置为 `false` 将禁用注册。
你可以在 `application.properties` 或 `application.yaml` 文件中设置该属性：

[configprops,yaml]
----
logging:
  register-shutdown-hook: false
----
== 自定义日志配置

可以通过在 classpath 上包含相应的库来激活各种日志系统，并通过在 classpath 的根目录或由以下 Spring javadoc:org.springframework.core.env.Environment[] 属性指定的位置提供合适的配置文件来进一步自定义：configprop:logging.config[]。

你可以通过使用 `org.springframework.boot.logging.LoggingSystem` 系统属性强制 Spring Boot 使用特定的日志系统。该值应为 javadoc:org.springframework.boot.logging.LoggingSystem[] 实现的全限定类名。你也可以通过使用值 `none` 完全禁用 Spring Boot 的日志配置。

注意：由于日志初始化是在 javadoc:org.springframework.context.ApplicationContext[] 创建 *之前* 进行的，因此无法从 Spring javadoc:org.springframework.context.annotation.Configuration[format=annotation] 文件中的 javadoc:org.springframework.context.annotation.PropertySources[format=annotation] 控制日志。更改日志系统或完全禁用的唯一方法是通过系统属性。

根据你的日志系统，会加载以下文件：

|===
| 日志系统 | 自定义

| Logback
| `logback-spring.xml`, `logback-spring.groovy`, `logback.xml` 或 `logback.groovy`

| Log4j2
| `log4j2-spring.xml` 或 `log4j2.xml`

| JDK (Java Util Logging)
| `logging.properties`
|===

注意：在可能的情况下，我们建议你使用日志配置的 `-spring` 变体（例如，`logback-spring.xml` 而不是 `logback.xml`）。如果使用标准配置位置，Spring 无法完全控制日志初始化。

警告：Java Util Logging 存在已知的类加载问题，在从 '可执行 jar' 运行时会导致问题。如果可能，我们建议你在从 '可执行 jar' 运行时避免使用它。

为了帮助自定义，一些其他属性从 Spring javadoc:org.springframework.core.env.Environment[] 转移到系统属性。这允许这些属性被日志系统配置使用。例如，在 `application.properties` 或 `LOGGING_FILE_NAME` 中设置 `logging.file.name` 作为环境变量将导致设置 `LOG_FILE` 系统属性。转移的属性如下表所述：

|===
| Spring 环境 | 系统属性 | 注释

| configprop:logging.exception-conversion-word[]
| `LOG_EXCEPTION_CONVERSION_WORD`
| 记录异常时使用的转换词。

| configprop:logging.file.name[]
| `LOG_FILE`
| 如果定义，则在默认日志配置中使用。

| configprop:logging.file.path[]
| `LOG_PATH`
| 如果定义，则在默认日志配置中使用。

| configprop:logging.pattern.console[]
| `CONSOLE_LOG_PATTERN`
| 在控制台（stdout）上使用的日志模式。

| configprop:logging.pattern.dateformat[]
| `LOG_DATEFORMAT_PATTERN`
| 日志日期格式的附加器模式。

| configprop:logging.charset.console[]
| `CONSOLE_LOG_CHARSET`
| 用于控制台日志记录的字符集。

| configprop:logging.threshold.console[]
| `CONSOLE_LOG_THRESHOLD`
| 用于控制台日志记录的日志级别阈值。

| configprop:logging.pattern.file[]
| `FILE_LOG_PATTERN`
| 在文件中使用的日志模式（如果启用了 `LOG_FILE`）。

| configprop:logging.charset.file[]
| `FILE_LOG_CHARSET`
| 用于文件日志记录的字符集（如果启用了 `LOG_FILE`）。

| configprop:logging.threshold.file[]
| `FILE_LOG_THRESHOLD`
| 用于文件日志记录的日志级别阈值。

| configprop:logging.pattern.level[]
| `LOG_LEVEL_PATTERN`
| 渲染日志级别时使用的格式（默认 `%5p`）。

| configprop:logging.structured.format.console[]
| `CONSOLE_LOG_STRUCTURED_FORMAT`
| 用于控制台日志记录的结构化日志格式。

| configprop:logging.structured.format.file[]
| `FILE_LOG_STRUCTURED_FORMAT`
| 用于文件日志记录的结构化日志格式。

| `PID`
| `PID`
| 当前进程 ID（如果可能则发现，并且当尚未定义为操作系统环境变量时）。
|===

如果你使用 Logback，以下属性也会被转移：

|===
| Spring 环境 | 系统属性 | 注释

| configprop:logging.logback.rollingpolicy.file-name-pattern[]
| `LOGBACK_ROLLINGPOLICY_FILE_NAME_PATTERN`
| 滚动日志文件名的模式（默认 `$\{LOG_FILE}.%d\{yyyy-MM-dd}.%i.gz`）。

| configprop:logging.logback.rollingpolicy.clean-history-on-start[]
| `LOGBACK_ROLLINGPOLICY_CLEAN_HISTORY_ON_START`
| 是否在启动时清理归档日志文件。

| configprop:logging.logback.rollingpolicy.max-file-size[]
| `LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE`
| 最大日志文件大小。

| configprop:logging.logback.rollingpolicy.total-size-cap[]
| `LOGBACK_ROLLINGPOLICY_TOTAL_SIZE_CAP`
| 要保留的日志备份总大小。

| configprop:logging.logback.rollingpolicy.max-history[]
| `LOGBACK_ROLLINGPOLICY_MAX_HISTORY`
| 要保留的最大归档日志文件数。
|===

所有支持的日志系统在解析其配置文件时都可以查阅系统属性。请参阅 `spring-boot.jar` 中的默认配置以获取示例：

* {code-spring-boot}/core/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml[Logback]
* {code-spring-boot}/core/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2.xml[Log4j 2]
* {code-spring-boot}/core/spring-boot/src/main/resources/org/springframework/boot/logging/java/logging-file.properties[Java Util logging]

[TIP]
====
如果你想在日志属性中使用占位符，应使用 xref:features/external-config.adoc#features.external-config.files.property-placeholders[Spring Boot 的语法] 而不是底层框架的语法。值得注意的是，如果你使用 Logback，应使用 `:` 作为属性名称与其默认值之间的分隔符，而不是使用 `:-`。
====

[TIP]
====
你可以通过仅覆盖 `LOG_LEVEL_PATTERN`（或使用 Logback 时的 `logging.pattern.level`）来将 MDC 和其他临时内容添加到日志行中。例如，如果你使用 `logging.pattern.level=user:%X\{user} %5p`，则默认日志格式包含“user”的 MDC 条目（如果存在），如下例所示。

[source]
----
2019-08-30 12:30:04.031 user:someone INFO 22174 --- [  nio-8080-exec-0] demo.Controller
Handling authenticated request
----
====

[[structured-logging]]
== 结构化日志

结构化日志是一种将日志输出以定义良好、通常机器可读的格式写入的技术。
Spring Boot 支持结构化日志，并内置支持以下 JSON 格式：

* xref:#features.logging.structured.ecs[Elastic Common Schema (ECS)]
* xref:#features.logging.structured.gelf[Graylog Extended Log Format (GELF)]
* xref:#features.logging.structured.logstash[Logstash]

要启用结构化日志，请将属性 configprop:logging.structured.format.console[]（用于控制台输出）或 configprop:logging.structured.format.file[]（用于文件输出）设置为您要使用的格式的 ID。

如果您使用 xref:#features.logging.custom-log-configuration[自定义日志配置]，请更新您的配置以遵守 `CONSOLE_LOG_STRUCTURED_FORMAT` 和 `FILE_LOG_STRUCTURED_FORMAT` 系统属性。
以 `CONSOLE_LOG_STRUCTURED_FORMAT` 为例：
[tabs]
======
Logback::
+
[source,xml]
----
<!-- replace your encoder with StructuredLogEncoder -->
<encoder class="org.springframework.boot.logging.logback.StructuredLogEncoder">
	<format>${CONSOLE_LOG_STRUCTURED_FORMAT}</format>
	<charset>${CONSOLE_LOG_CHARSET}</charset>
</encoder>
----
+
您也可以参考 Spring Boot 中包含的默认配置：
+
* {code-spring-boot}/core/spring-boot/src/main/resources/org/springframework/boot/logging/logback/structured-console-appender.xml[Logback 结构化控制台附加器]
* {code-spring-boot}/core/spring-boot/src/main/resources/org/springframework/boot/logging/logback/structured-file-appender.xml[Logback 结构化文件附加器]
Log4j2::
+
[source,xml]
----
<!-- replace your PatternLayout with StructuredLogLayout -->
<StructuredLogLayout format="${sys:CONSOLE_LOG_STRUCTURED_FORMAT}" charset="${sys:CONSOLE_LOG_CHARSET}"/>
----
+
您也可以参考 Spring Boot 中包含的默认配置：
+
* {code-spring-boot}/core/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2.xml[Log4j2 控制台附加器]
* {code-spring-boot}/core/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2-file.xml[Log4j2 控制台和文件附加器]
======


[[features.logging.structured.ecs]]
=== Elastic Common Schema

https://www.elastic.co/guide/en/ecs/8.11/ecs-reference.html[Elastic Common Schema] 是一种基于 JSON 的日志格式。

要启用 Elastic Common Schema 日志格式，请将相应的 `format` 属性设置为 `ecs`：

[configprops,yaml]
----
logging:
  structured:
    format:
      console: ecs
      file: ecs
----
一条日志行看起来像这样：

[source,json]
----
{"@timestamp":"2024-01-01T10:15:00.067462556Z","log":{"level":"INFO","logger":"org.example.Application"},"process":{"pid":39599,"thread":{"name":"main"}},"service":{"name":"simple"},"message":"No active profile set, falling back to 1 default profile: \"default\"","ecs":{"version":"8.11"}}
----
此格式还会将 MDC 中包含的每个键值对添加到 JSON 对象中。
您也可以使用 https://www.slf4j.org/manual.html#fluent[SLF4J 流式日志 API] 通过 https://www.slf4j.org/apidocs/org/slf4j/spi/LoggingEventBuilder.html#addKeyValue(java.lang.String,java.lang.Object)[addKeyValue] 方法将键值对添加到记录的 JSON 对象中。

`service` 值可以使用 `logging.structured.ecs.service` 属性进行自定义：

[configprops,yaml]
----
logging:
  structured:
    ecs:
      service:
        name: MyService
        version: 1.0
        environment: Production
        node-name: Primary
----
NOTE: configprop:logging.structured.ecs.service.name[] 如果未指定，将默认为 configprop:spring.application.name[]。

NOTE: configprop:logging.structured.ecs.service.version[] 如果未指定，将默认为 configprop:spring.application.version[]。


[[features.logging.structured.gelf]]
=== GELF

https://go2docs.graylog.org/current/getting_in_log_data/gelf.html[GELF] 是一种基于 JSON 的日志格式，用于 Graylog 日志分析平台。

要启用 GELF，请将相应的 `format` 属性设置为 `gelf`：

[configprops,yaml]
----
logging:
  structured:
    format:
      console: gelf
      file: gelf
----
日志行看起来像这样：

[source,json]
----
{"version":"1.1","short_message":"No active profile set, falling back to 1 default profile: \"default\"","timestamp":1725958035.857,"level":6,"_level_name":"INFO","_process_pid":47649,"_process_thread_name":"main","_log_logger":"org.example.Application"}
----
这种格式还会将 MDC 中包含的每个键值对添加到 JSON 对象中。
你也可以使用 https://www.slf4j.org/manual.html#fluent[SLF4J 流式日志 API] 通过 https://www.slf4j.org/apidocs/org/slf4j/spi/LoggingEventBuilder.html#addKeyValue(java.lang.String,java.lang.Object)[addKeyValue] 方法向记录的 JSON 对象添加键值对。

可以使用 `logging.structured.gelf` 属性自定义多个字段：

[configprops,yaml]
----
logging:
  structured:
    gelf:
      host: MyService
      service:
        version: 1.0
----
注意：configprop:logging.structured.gelf.host[] 如果未指定，将默认为 configprop:spring.application.name[]。

注意：configprop:logging.structured.gelf.service.version[] 如果未指定，将默认为 configprop:spring.application.version[]。


[[features.logging.structured.logstash]]
=== Logstash JSON 格式

https://github.com/logfellow/logstash-logback-encoder?tab=readme-ov-file#standard-fields[Logstash JSON 格式] 是一种基于 JSON 的日志格式。

要启用 Logstash JSON 日志格式，请将相应的 `format` 属性设置为 `logstash`：

[configprops,yaml]
----
logging:
  structured:
    format:
      console: logstash
      file: logstash
----
日志行看起来像这样：

[source,json]
----
{"@timestamp":"2024-01-01T10:15:00.111037681+02:00","@version":"1","message":"No active profile set, falling back to 1 default profile: \"default\"","logger_name":"org.example.Application","thread_name":"main","level":"INFO","level_value":20000}
----
这种格式还会将 MDC 中包含的每个键值对添加到 JSON 对象中。
你也可以使用 https://www.slf4j.org/manual.html#fluent[SLF4J 流式日志 API] 通过 https://www.slf4j.org/apidocs/org/slf4j/spi/LoggingEventBuilder.html#addKeyValue(java.lang.String,java.lang.Object)[addKeyValue] 方法向记录的 JSON 对象添加键值对。

如果你添加了 https://www.slf4j.org/api/org/slf4j/Marker.html[标记]，它们会以 `tags` 字符串数组的形式出现在 JSON 中。


[[features.logging.structured.customizing-json]]
=== 自定义结构化日志 JSON

Spring Boot 会尝试为结构化日志输出的 JSON 名称和值选择合理的默认值。
但有时，你可能需要根据自己的需求对 JSON 进行小幅调整。
例如，你可能希望更改某些名称以匹配日志采集系统的期望。
你也可能希望过滤掉某些成员，因为你觉得它们没有用。

以下属性允许你更改结构化日志 JSON 的写入方式：

|===
| 属性 | 描述

| configprop:logging.structured.json.include[] 和 configprop:logging.structured.json.exclude[]
| 过滤 JSON 中的特定路径

| configprop:logging.structured.json.rename[]
| 重命名 JSON 中的特定成员

| configprop:logging.structured.json.add[]
| 向 JSON 添加额外的成员
|===

例如，以下配置将排除 `log.level`，将 `process.id` 重命名为 `procid`，并添加一个固定的 `corpname` 字段：

[configprops,yaml]
----
logging:
  structured:
    json:
      exclude: log.level
      rename:
        process.id: procid
      add:
        corpname: mycorp
----
TIP: 对于更高级的自定义，你可以使用 javadoc:org.springframework.boot.logging.structured.StructuredLoggingJsonMembersCustomizer[] 接口。
你可以使用 configprop:logging.structured.json.customizer[] 属性引用一个或多个实现。
你也可以通过在 `META-INF/spring.factories` 文件中列出它们来声明实现。

[[features.logging.structured.customizing-stack-traces]]
=== 自定义结构化日志堆栈跟踪

每当记录带有异常的消息时，完整的堆栈跟踪会包含在 JSON 输出中。
这些信息量可能对你的日志摄取系统处理成本较高，因此你可能希望调整堆栈跟踪的打印方式。

为此，你可以使用以下一个或多个属性：

|===
| 属性 | 描述

| configprop:logging.structured.json.stacktrace.root[]
| 使用 `last` 将根项最后打印（与 Java 相同）或使用 `first` 将根项最先打印。

| configprop:logging.structured.json.stacktrace.max-length[]
| 应打印的最大长度

| configprop:logging.structured.json.stacktrace.max-throwable-depth[]
| 每个堆栈跟踪打印的最大帧数（包括公共帧和抑制帧）

| configprop:logging.structured.json.stacktrace.include-common-frames[]
| 是否包含或移除公共帧

| configprop:logging.structured.json.stacktrace.include-hashes[]
| 是否包含堆栈跟踪的哈希值
|===

例如，以下配置将使用根项最先的堆栈跟踪，限制其长度，并包含哈希值。

[configprops,yaml]
----
logging:
  structured:
    json:
      stacktrace:
        root: first
        max-length: 1024
        include-common-frames: true
        include-hashes: true
----
====
如果您需要完全控制堆栈跟踪打印，可以将 configprop:logging.structured.json.stacktrace.printer[] 设置为某个 javadoc:org.springframework.boot.logging.StackTracePrinter[] 实现的名称。
您也可以将其设置为 `logging-system`，以强制使用常规日志系统的堆栈跟踪输出。

您的 `StackTracePrinter` 实现还可以包含一个接受 javadoc:org.springframework.boot.logging.StandardStackTracePrinter[] 的构造函数参数，以便对从属性创建的堆栈跟踪打印机进行进一步的自定义。
====



[[features.logging.structured.other-formats]]
=== 支持其他结构化日志格式

Spring Boot 中的结构化日志支持是可扩展的，允许您定义自己的自定义格式。
为此，请实现 javadoc:org.springframework.boot.logging.structured.StructuredLogFormatter[] 接口。使用 Logback 时，泛型类型参数必须为 javadoc:ch.qos.logback.classic.spi.ILoggingEvent[]；使用 Log4j2 时，必须为 javadoc:org.apache.logging.log4j.core.LogEvent[]（这意味着您的实现与特定的日志系统绑定）。
然后，您的实现会随日志事件被调用，并返回要记录的 javadoc:java.lang.String[]，如下例所示：

[source,java]
----
import ch.qos.logback.classic.spi.ILoggingEvent;

import org.springframework.boot.logging.structured.StructuredLogFormatter;

class MyCustomFormat implements StructuredLogFormatter<ILoggingEvent> {

	@Override
	public String format(ILoggingEvent event) {
		return "time=" + event.getInstant() + " level=" + event.getLevel() + " message=" + event.getMessage() + "\n";
	}

}
----

如示例所示，您可以返回任何格式，不一定是 JSON。

要启用您的自定义格式，请将属性 configprop:logging.structured.format.console[] 或 configprop:logging.structured.format.file[] 设置为您的实现的完全限定类名。

您的实现可以使用一些构造函数参数，这些参数会自动注入。
更多详细信息，请参阅 javadoc:org.springframework.boot.logging.structured.StructuredLogFormatter[] 的 JavaDoc。



[[features.logging.logback-extensions]]
== Logback 扩展

Spring Boot 包含许多 Logback 扩展，可帮助进行高级配置。
您可以在 `logback-spring.xml` 配置文件中使用这些扩展。

注意：由于标准的 `logback.xml` 配置文件加载过早，您无法在其中使用扩展。
您需要使用 `logback-spring.xml` 或定义 configprop:logging.config[] 属性。

警告：这些扩展不能与 Logback 的 https://logback.qos.ch/manual/configuration.html#autoScan[配置扫描]一起使用。
如果尝试这样做，对配置文件进行更改会导致记录类似于以下之一的错误：

[source]
----
ERROR in ch.qos.logback.core.joran.spi.Interpreter@4:71 - no applicable action for [springProperty], current ElementPath is [[configuration][springProperty]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@4:71 - no applicable action for [springProfile], current ElementPath is [[configuration][springProfile]]
----
=== 特定于 Profile 的配置

`<springProfile>` 标签允许您根据活动的 Spring profiles 有选择地包含或排除配置部分。
Profile 部分在 `<configuration>` 元素内的任何位置都受支持。
使用 `name` 属性指定哪个 profile 接受该配置。
`<springProfile>` 标签可以包含一个 profile 名称（例如 `staging`）或一个 profile 表达式。
profile 表达式允许表达更复杂的 profile 逻辑，例如 `production & (eu-central | eu-west)`。
有关更多详细信息，请查看 {url-spring-framework-docs}/core/beans/environment.html#beans-definition-profiles-java[Spring 框架参考指南]。
以下列表显示了三个示例 profiles：

[source,xml]
----
<springProfile name="staging">
	<!-- configuration to be enabled when the "staging" profile is active -->
</springProfile>

<springProfile name="dev | staging">
	<!-- configuration to be enabled when the "dev" or "staging" profiles are active -->
</springProfile>

<springProfile name="!production">
	<!-- configuration to be enabled when the "production" profile is not active -->
</springProfile>
----
=== 环境属性

`<springProperty>` 标签允许你从 Spring javadoc:org.springframework.core.env.Environment[] 中暴露属性，以供 Logback 使用。
如果你想在 Logback 配置中访问 `application.properties` 文件中的值，这样做会很有用。
该标签的工作方式与 Logback 标准的 `<property>` 标签类似。
不过，它不是指定直接的 `value`，而是指定属性的 `source`（来自 javadoc:org.springframework.core.env.Environment[]）。
如果你需要将属性存储在 `local` 作用域之外的其他地方，可以使用 `scope` 属性。
如果你需要一个回退值（以防属性未在 javadoc:org.springframework.core.env.Environment[] 中设置），可以使用 `defaultValue` 属性。
以下示例展示了如何暴露属性以供 Logback 使用：

[source,xml]
----
<springProperty scope="context" name="fluentHost" source="myapp.fluentd.host"
		defaultValue="localhost"/>
<appender name="FLUENT" class="ch.qos.logback.more.appenders.DataFluentAppender">
	<remoteHost>${fluentHost}</remoteHost>
	...
</appender>
----
NOTE: `source` 必须使用短横线命名法（例如 `my.property-name`）。
但是，可以通过宽松规则将属性添加到 javadoc:org.springframework.core.env.Environment[]。


[[features.logging.log4j2-extensions]]
== Log4j2 扩展

Spring Boot 包含许多 Log4j2 的扩展，有助于高级配置。
你可以在任何 `log4j2-spring.xml` 配置文件中使用这些扩展。

NOTE: 由于标准的 `log4j2.xml` 配置文件加载过早，你无法在其中使用扩展。
你需要使用 `log4j2-spring.xml` 或定义 configprop:logging.config[] 属性。

NOTE: 这些扩展取代了 Log4J 提供的 https://logging.apache.org/log4j/2.x/log4j-spring-boot.html[Spring Boot 支持]。
你应该确保在构建中不包含 `org.apache.logging.log4j:log4j-spring-boot` 模块。


[[features.logging.log4j2-extensions.profile-specific]]
=== 特定 Profile 配置

`<SpringProfile>` 标签允许你根据激活的 Spring profiles 选择性地包含或排除配置部分。
Profile 部分在 `<Configuration>` 元素内的任何位置都受支持。
使用 `name` 属性指定哪个 profile 接受该配置。
`<SpringProfile>` 标签可以包含 profile 名称（例如 `staging`）或 profile 表达式。
profile 表达式允许表达更复杂的 profile 逻辑，例如 `production & (eu-central | eu-west)`。
更多详情请查阅 {url-spring-framework-docs}/core/beans/environment.html#beans-definition-profiles-java[Spring 框架参考指南]。
以下列表展示了三个示例 profiles：

[source,xml]
----
<SpringProfile name="staging">
	<!-- configuration to be enabled when the "staging" profile is active -->
</SpringProfile>

<SpringProfile name="dev | staging">
	<!-- configuration to be enabled when the "dev" or "staging" profiles are active -->
</SpringProfile>

<SpringProfile name="!production">
	<!-- configuration to be enabled when the "production" profile is not active -->
</SpringProfile>
----
=== 环境属性查找

如果你想在 Log4j2 配置中引用 Spring javadoc:org.springframework.core.env.Environment[] 中的属性，可以使用 `spring:` 前缀的 https://logging.apache.org/log4j/2.x/manual/lookups.html[查找]。
这样做在你想要从 `application.properties` 文件中访问值到 Log4j2 配置中时非常有用。

以下示例展示了如何设置名为 `applicationName` 和 `applicationGroup` 的 Log4j2 属性，这些属性从 Spring javadoc:org.springframework.core.env.Environment[] 中读取 `spring.application.name` 和 `spring.application.group`：

[source,xml]
----
<Properties>
	<Property name="applicationName">${spring:spring.application.name}</Property>
	<Property name="applicationGroup">${spring:spring.application.group}</Property>
</Properties>
----
NOTE: 查找键应以 kebab 形式指定（例如 `my.property-name`）。

[[features.logging.log4j2-extensions.environment-property-source]]
=== Log4j2 系统属性

Log4j2 支持许多 https://logging.apache.org/log4j/2.x/manual/systemproperties.html[系统属性]，可用于配置各种项目。
例如，`log4j2.skipJansi` 系统属性可用于配置 javadoc:org.apache.logging.log4j.core.appender.ConsoleAppender[] 是否尝试在 Windows 上使用 https://github.com/fusesource/jansi[Jansi] 输出流。

所有在 Log4j2 初始化后加载的系统属性都可以从 Spring javadoc:org.springframework.core.env.Environment[] 获取。
例如，您可以将 `log4j2.skipJansi=false` 添加到 `application.properties` 文件中，以使 javadoc:org.apache.logging.log4j.core.appender.ConsoleAppender[] 在 Windows 上使用 Jansi。

NOTE: Spring javadoc:org.springframework.core.env.Environment[] 仅在系统属性和操作系统环境变量不包含正在加载的值时才被考虑。

WARNING: 在 Log4j2 初始化早期加载的系统属性不能引用 Spring javadoc:org.springframework.core.env.Environment[]。
例如，Log4j2 用于选择默认 Log4j2 实现的属性在 Spring 环境可用之前就被使用了。
