= Cloud Foundry 支持

Spring Boot 的 `spring-boot-cloudfoundry` 模块（属于 `spring-boot-starter-cloudfoundry` 的一部分）包含额外的支持，当您部署到兼容的 Cloud Foundry 实例时，该支持会被激活。
`/cloudfoundryapplication` 路径为所有 javadoc:org.springframework.boot.actuate.endpoint.annotation.Endpoint[format=annotation] beans 提供了一条替代的安全路由。

扩展支持允许 Cloud Foundry 管理 UI（例如可用于查看已部署应用程序的 Web 应用程序）通过 Spring Boot actuator 信息进行增强。
例如，应用程序状态页面可以包含完整的健康信息，而不是典型的“`running`”或“`stopped`”状态。

注意：`/cloudfoundryapplication` 路径对普通用户不可直接访问。
要使用端点，您必须在请求中传递有效的 UAA 令牌。


[[actuator.cloud-foundry.disable]]
== 禁用扩展的 Cloud Foundry Actuator 支持

如果您想完全禁用 `/cloudfoundryapplication` 端点，可以将以下设置添加到您的 `application.properties` 文件中：

[configprops,yaml]
----
management:
  cloudfoundry:
    enabled: false
----
[[actuator.cloud-foundry.ssl]]
== Cloud Foundry 自签名证书

默认情况下，`/cloudfoundryapplication` 端点的安全验证会对各种 Cloud Foundry 服务进行 SSL 调用。
如果你的 Cloud Foundry UAA 或 Cloud Controller 服务使用自签名证书，则需要设置以下属性：

[configprops,yaml]
----
management:
  cloudfoundry:
    skip-ssl-validation: true
----
[[actuator.cloud-foundry.custom-context-path]]
== 自定义上下文路径

如果服务器的上下文路径被配置为 `/` 以外的任何值，Cloud Foundry 端点将无法在应用程序的根路径下访问。
例如，如果 `server.servlet.context-path=/app`，Cloud Foundry 端点可在 `/app/cloudfoundryapplication/*` 访问。

如果你希望 Cloud Foundry 端点始终在 `/cloudfoundryapplication/*` 可用，无论服务器的上下文路径如何，你需要在应用程序中显式配置。
配置因使用的 Web 服务器而异。
对于 Tomcat，你可以添加以下配置：

[source,java]
----
import java.io.IOException;
import java.util.Collections;

import jakarta.servlet.GenericServlet;
import jakarta.servlet.Servlet;
import jakarta.servlet.ServletContainerInitializer;
import jakarta.servlet.ServletContext;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import org.apache.catalina.Host;
import org.apache.catalina.core.StandardContext;
import org.apache.catalina.startup.Tomcat;

import org.springframework.boot.tomcat.servlet.TomcatServletWebServerFactory;
import org.springframework.boot.web.servlet.ServletContextInitializer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyCloudFoundryConfiguration {

	@Bean
	public TomcatServletWebServerFactory servletWebServerFactory() {
		return new TomcatServletWebServerFactory() {

			@Override
			protected void prepareContext(Host host, ServletContextInitializer[] initializers, TempDirs tempDirs) {
				super.prepareContext(host, initializers, tempDirs);
				StandardContext child = new StandardContext();
				child.addLifecycleListener(new Tomcat.FixContextListener());
				child.setPath("/cloudfoundryapplication");
				ServletContainerInitializer initializer = getServletContextInitializer(getContextPath());
				child.addServletContainerInitializer(initializer, Collections.emptySet());
				child.setCrossContext(true);
				host.addChild(child);
			}

		};
	}

	private ServletContainerInitializer getServletContextInitializer(String contextPath) {
		return (classes, context) -> {
			Servlet servlet = new GenericServlet() {

				@Override
				public void service(ServletRequest req, ServletResponse res) throws ServletException, IOException {
					ServletContext context = req.getServletContext().getContext(contextPath);
					context.getRequestDispatcher("/cloudfoundryapplication").forward(req, res);
				}

			};
			context.addServlet("cloudfoundry", servlet).addMapping("/*");
		};
	}

}
----

如果你使用基于 Webflux 的应用程序，可以使用以下配置：

[source,java]
----
import java.util.Map;

import reactor.core.publisher.Mono;

import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.boot.webflux.autoconfigure.WebFluxProperties;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.server.reactive.ContextPathCompositeHandler;
import org.springframework.http.server.reactive.HttpHandler;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.http.server.reactive.ServerHttpResponse;
import org.springframework.web.server.adapter.WebHttpHandlerBuilder;

@Configuration(proxyBeanMethods = false)
@EnableConfigurationProperties(WebFluxProperties.class)
public class MyReactiveCloudFoundryConfiguration {

	@Bean
	public HttpHandler httpHandler(ApplicationContext applicationContext, WebFluxProperties properties) {
		HttpHandler httpHandler = WebHttpHandlerBuilder.applicationContext(applicationContext).build();
		return new CloudFoundryHttpHandler(properties.getBasePath(), httpHandler);
	}

	private static final class CloudFoundryHttpHandler implements HttpHandler {

		private final HttpHandler delegate;

		private final ContextPathCompositeHandler contextPathDelegate;

		private CloudFoundryHttpHandler(String basePath, HttpHandler delegate) {
			this.delegate = delegate;
			this.contextPathDelegate = new ContextPathCompositeHandler(Map.of(basePath, delegate));
		}

		@Override
		public Mono<Void> handle(ServerHttpRequest request, ServerHttpResponse response) {
			// Remove underlying context path first (e.g. Servlet container)
			String path = request.getPath().pathWithinApplication().value();
			if (path.startsWith("/cloudfoundryapplication")) {
				return this.delegate.handle(request, response);
			}
			else {
				return this.contextPathDelegate.handle(request, response);
			}
		}

	}

}
----
