[[actuator.loggers]]
= 日志器

Spring Boot Actuator 支持在运行时查看和配置应用程序的日志级别。
您可以查看整个列表或单个日志器的配置，该配置由显式配置的日志级别以及日志框架赋予它的有效日志级别组成。
这些级别可以是以下之一：

* `TRACE`
* `DEBUG`
* `INFO`
* `WARN`
* `ERROR`
* `FATAL`
* `OFF`
* `null`

`null` 表示没有显式配置。



[[actuator.loggers.configure]]
== 配置日志器

要配置给定的日志器，请向资源的 URI 发送 `POST` 请求，并附带部分实体，如下例所示：

[source,json]
----
{
	"configuredLevel": "DEBUG"
}
----

TIP: 要“重置”日志记录器的特定级别（并使用默认配置），可以将 `null` 作为 `configuredLevel` 的值传递。



[[actuator.loggers.opentelemetry]]
== OpenTelemetry
默认情况下，通过 OpenTelemetry 进行日志记录并未配置。
您必须提供 OpenTelemetry 日志端点的位置来配置它：

[configprops,yaml]
----
management:
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: "https://otlp.example.com:4318/v1/logs"
----

`management.opentelemetry.logging.export.*` 配置属性可用于配置 javadoc:io.opentelemetry.sdk.logs.export.BatchLogRecordProcessor[]。
例如，将导出间隔改为 15 秒：

[configprops,yaml]
----
management:
  opentelemetry:
    logging:
      export:
        schedule-delay: "15s"
----

`management.opentelemetry.logging.limits.*` 配置属性可用于配置日志记录限制。
例如，将每条日志记录的属性数量限制为 64 个，并将最大属性值长度限制为 256 个字符：

[configprops,yaml]
----
management:
  opentelemetry:
    logging:
      limits:
        max-attributes: 64
        max-attribute-value-length: 256
----

如果需要完全控制，可以注册一个自定义的 javadoc:io.opentelemetry.sdk.logs.LogLimits[] bean。

注意：OpenTelemetry Logback appender 和 Log4j appender 不属于 Spring Boot。
更多详情，请参见 https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-appender-1.0/library[OpenTelemetry Logback appender] 或 https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library[OpenTelemetry Log4j2 appender]，它们位于 https://github.com/open-telemetry/opentelemetry-java-instrumentation[OpenTelemetry Java instrumentation GitHub 仓库] 中。

提示：你需要在 `logback-spring.xml` 或 `log4j2-spring.xml` 配置中配置 appender，才能使 OpenTelemetry 日志记录正常工作。

Logback 和 Log4j 的 `OpenTelemetryAppender` 都需要访问 javadoc:io.opentelemetry.api.OpenTelemetry[] 实例才能正常运行。
该实例必须在应用程序启动时通过编程方式设置，可以像这样完成：

[source,java]
----
import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.stereotype.Component;

@Component
class OpenTelemetryAppenderInitializer implements InitializingBean {

	private final OpenTelemetry openTelemetry;

	OpenTelemetryAppenderInitializer(OpenTelemetry openTelemetry) {
		this.openTelemetry = openTelemetry;
	}

	@Override
	public void afterPropertiesSet() {
		OpenTelemetryAppender.install(this.openTelemetry);
	}

}
----
