= 通过 HTTP 进行监控和管理

如果你正在开发一个 Web 应用程序，Spring Boot Actuator 会自动配置所有已启用的端点以通过 HTTP 暴露。
默认约定是使用端点的 `id`，并以 `/actuator` 作为 URL 路径的前缀。
例如，`health` 被暴露为 `/actuator/health`。

提示：Actuator 原生支持 Spring MVC、Spring WebFlux 和 Jersey。
如果同时存在 Jersey 和 Spring MVC，则使用 Spring MVC。

注意：Jackson 是必需的依赖项，以便获得 xref:api:rest/actuator/index.adoc[API 文档] 中所述的正确 JSON 响应。
对于 Spring MVC 和 Spring WebFlux，应使用 Jackson 3。
Jersey 尚未提供 Jackson 3 模块，因此你需要使用 Jackson 2。


[[actuator.monitoring.customizing-management-server-context-path]]
== 自定义管理端点路径

有时，自定义管理端点的前缀很有用。
例如，你的应用程序可能已经将 `/actuator` 用于其他目的。
你可以使用 configprop:management.endpoints.web.base-path[] 属性来更改管理端点的前缀，如下例所示：

[configprops,yaml]
----
management:
  endpoints:
    web:
      base-path: "/manage"
----
前面的 `application.properties` 示例将端点从 `/actuator/\{id}` 更改为 `/manage/\{id}`（例如，`/manage/info`）。

注意：除非管理端口已配置为 xref:actuator/monitoring.adoc#actuator.monitoring.customizing-management-server-port[通过不同的 HTTP 端口暴露端点]，否则 `management.endpoints.web.base-path` 相对于 `server.servlet.context-path`（对于 Servlet Web 应用程序）或 `spring.webflux.base-path`（对于响应式 Web 应用程序）。
如果配置了 `management.server.port`，则 `management.endpoints.web.base-path` 相对于 `management.server.base-path`。

如果要将端点映射到不同的路径，可以使用 configprop:management.endpoints.web.path-mapping[] 属性。

以下示例将 `/actuator/health` 重新映射到 `/healthcheck`：

[configprops,yaml]
----
management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "healthcheck"
----
== 自定义管理服务器端口

对于基于云的部署，使用默认 HTTP 端口暴露管理端点是一个明智的选择。
但是，如果您的应用程序在您自己的数据中心内运行，您可能更倾向于使用不同的 HTTP 端口暴露端点。

您可以设置 configprop:management.server.port[] 属性来更改 HTTP 端口，如下例所示：

[configprops,yaml]
----
management:
  server:
    port: 8081
----
NOTE: 在 Cloud Foundry 上，默认情况下，应用程序仅通过端口 8080 接收 HTTP 和 TCP 路由的请求。
如果要在 Cloud Foundry 上使用自定义管理端口，则需要显式设置应用程序的路由，以将流量转发到自定义端口。

[[actuator.monitoring.management-specific-ssl]]
== 配置管理专用 SSL

当配置为使用自定义端口时，还可以通过使用各种 `management.server.ssl.*` 属性来为管理服务器配置其自己的 SSL。
例如，这样做可以让管理服务器通过 HTTP 可用，而主应用程序使用 HTTPS，如下面的属性设置所示：

[configprops,yaml]
----
server:
  port: 8443
  ssl:
    enabled: true
    key-store: "classpath:store.jks"
    key-password: "secret"
management:
  server:
    port: 8080
    ssl:
      enabled: false
----
或者，主服务器和管理服务器都可以使用 SSL，但使用不同的密钥库，如下所示：

[configprops,yaml]
----
server:
  port: 8443
  ssl:
    enabled: true
    key-store: "classpath:main.jks"
    key-password: "secret"
management:
  server:
    port: 8080
    ssl:
      enabled: true
      key-store: "classpath:management.jks"
      key-password: "secret"
----
[[actuator.monitoring.customizing-management-server-address]]
== 自定义管理服务器地址

您可以通过设置 configprop:management.server.address[] 属性来自定义管理端点可用的地址。
如果您只想在内部或面向运维的网络中监听，或者只监听来自 `localhost` 的连接，这样做会很有用。

注意：仅当端口与主服务器端口不同时，您才能在不同的地址上监听。

以下 `application.properties` 示例不允许远程管理连接：

[configprops,yaml]
----
management:
  server:
    port: 8081
    address: "127.0.0.1"
----
== 禁用 HTTP 端点

如果您不想通过 HTTP 暴露端点，可以将管理端口设置为 `-1`，如下例所示：

[configprops,yaml]
----
management:
  server:
    port: -1
----
您也可以通过使用 configprop:management.endpoints.web.exposure.exclude[] 属性来实现这一点，如下例所示：

[configprops,yaml]
----
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
----
