[[using.devtools]]
= 开发者工具

Spring Boot 包含一组额外的工具，可以让应用程序开发体验更加愉快。
`spring-boot-devtools` 模块可以包含在任何项目中，以提供额外的开发时特性。
要包含 devtools 支持，请将模块依赖添加到您的构建中，如下面的 Maven 和 Gradle 清单所示：

.Maven
[source,xml]
----
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-devtools</artifactId>
		<optional>true</optional>
	</dependency>
</dependencies>
----

.Gradle
[source,gradle]
----
dependencies {
	developmentOnly("org.springframework.boot:spring-boot-devtools")
}
----
CAUTION: Devtools 可能导致类加载问题，尤其是在多模块项目中。
xref:using/devtools.adoc#using.devtools.diagnosing-classloading-issues[] 解释了如何诊断和解决这些问题。

NOTE: 当运行完全打包的应用程序时，开发者工具会自动禁用。
如果您的应用程序是从 `java -jar` 启动的，或者是从特殊的类加载器启动的，则它被视为 "`production application`"。
您可以通过使用 `spring.devtools.restart.enabled` 系统属性来控制此行为。
要启用 devtools，无论用于启动应用程序的类加载器如何，请设置 `-Dspring.devtools.restart.enabled=true` 系统属性。
这不应在生产环境中进行，因为运行 devtools 存在安全风险。
要禁用 devtools，请排除依赖项或设置 `-Dspring.devtools.restart.enabled=false` 系统属性。

TIP: 在 Maven 中将依赖项标记为可选，或在 Gradle 中使用 `developmentOnly` 配置（如上所示），可防止 devtools 被传递性地应用于使用您项目的其他模块。

TIP: 默认情况下，重新打包的归档文件不包含 devtools。
如果您想使用 xref:using/devtools.adoc#using.devtools.remote-applications[某个远程 devtools 功能]，则需要包含它。
使用 Maven 插件时，通过将 `includeOptional` 属性设置为 `true` 来选择可选依赖项。
您还需要将 `excludeDevtools` 属性设置为 `false`。
使用 Gradle 插件时，xref:gradle-plugin:packaging.adoc#packaging-executable.configuring.including-development-only-dependencies[配置任务的 classpath 以包含 `developmentOnly` 配置]。



[[using.devtools.diagnosing-classloading-issues]]
== 诊断类加载问题

如 xref:#using.devtools.restart.restart-vs-reload[] 部分所述，重启功能是通过使用两个类加载器实现的。
对于大多数应用程序，这种方法效果良好。
然而，它有时会导致类加载问题，尤其是在多模块项目中。

要诊断类加载问题是否确实由 devtools 及其两个类加载器引起，xref:using/devtools.adoc#using.devtools.restart.disable[尝试禁用重启]。
如果这解决了您的问题，xref:using/devtools.adoc#using.devtools.restart.customizing-the-classload[自定义重启类加载器] 以包含整个项目。



[[using.devtools.property-defaults]]
== 属性默认值

Spring Boot 支持的多个库使用缓存来提高性能。
例如，xref:web/servlet.adoc#web.servlet.spring-mvc.template-engines[模板引擎] 缓存编译后的模板以避免重复解析模板文件。
此外，Spring MVC 在提供静态资源时可以向响应添加 HTTP 缓存头。

虽然缓存在生产环境中非常有益，但在开发过程中可能适得其反，阻止您看到刚刚在应用程序中所做的更改。
因此，spring-boot-devtools 默认禁用缓存选项。

缓存选项通常通过 `application.properties` 文件中的设置进行配置。
例如，Thymeleaf 提供了 configprop:spring.thymeleaf.cache[] 属性。

同样适用于跟踪概率，默认设置为 100% 可能不会记录用于测试的所有跟踪。

无需手动设置这些属性，`spring-boot-devtools` 模块会自动应用合理的开发时配置。

下表列出了所有应用的属性：

include::ROOT:partial$propertydefaults/devtools-property-defaults.adoc[]

NOTE: 如果您不希望应用属性默认值，可以在 `application.properties` 中将 configprop:spring.devtools.add-properties[] 设置为 `false`。

因为在开发 Spring MVC 和 Spring WebFlux 应用程序时需要更多关于 Web 请求的信息，开发者工具建议您为 `web` 日志组启用 `DEBUG` 日志记录。
这将为您提供有关传入请求、处理它的处理器、响应结果以及其他详细信息。
如果您希望记录所有请求详细信息（包括潜在的敏感信息），可以打开 configprop:spring.mvc.log-request-details[] 或 configprop:spring.http.codecs.log-request-details[] 配置属性。



[[using.devtools.restart]]
== 自动重启

使用 `spring-boot-devtools` 的应用程序每当 classpath 上的文件发生变化时都会自动重启。
在 IDE 中工作时，这是一个有用的功能，因为它为代码更改提供了非常快速的反馈循环。
默认情况下，监视 classpath 上指向目录的任何条目以进行更改。
请注意，某些资源（如静态资源和视图模板）xref:using/devtools.adoc#using.devtools.restart.excluding-resources[不需要重启应用程序]。

.触发重启
****
由于 DevTools 监视 classpath 资源，触发重启的唯一方法是更新 classpath。
无论您使用的是 IDE 还是构建插件，修改后的文件必须重新编译才能触发重启。
导致 classpath 更新的方式取决于您使用的工具：

* 在 Eclipse 中，保存修改后的文件会导致 classpath 更新并触发重启。
* 在 IntelliJ IDEA 中，构建项目（`Build +->+ Build Project`）具有相同的效果。
* 如果使用构建插件，运行 `mvn compile`（对于 Maven）或 `gradle build`（对于 Gradle）将触发重启。
****

NOTE: 如果使用构建插件通过 Maven 或 Gradle 重启，则必须将 `forking` 设置为 `enabled`。
如果禁用分支，则不会创建 devtools 使用的隔离应用程序类加载器，重启将无法正常运行。

TIP: 如果您使用 JRebel，自动重启将被禁用，转而使用动态类重新加载。
其他 devtools 功能（如属性覆盖）仍可使用。

NOTE: DevTools 依赖应用程序上下文的关闭钩子在重启期间关闭它。
如果您禁用了关闭钩子（`SpringApplication.setRegisterShutdownHook(false)`），它将无法正常工作。

NOTE: DevTools 需要自定义 javadoc:org.springframework.context.ApplicationContext[] 使用的 javadoc:org.springframework.core.io.ResourceLoader[]。
如果您的应用程序已经提供了一个，它将被包装。
不支持直接覆盖 javadoc:org.springframework.context.ApplicationContext[] 上的 `getResource` 方法。

CAUTION: 使用 AspectJ 编织时不支持自动重启。

[[using.devtools.restart.restart-vs-reload]]
.重启与重新加载
****
Spring Boot 提供的重启技术通过使用两个类加载器工作。
不会更改的类（例如，来自第三方 JAR 的类）被加载到 _基础_ 类加载器中。
您正在积极开发的类被加载到 _重启_ 类加载器中。
当应用程序重启时，_重启_ 类加载器被丢弃并创建一个新的。
这种方法意味着应用程序重启通常比 "`cold starts`" 快得多，因为 _基础_ 类加载器已经可用并已填充。

如果您发现重启对您的应用程序来说不够快，或者遇到类加载问题，可以考虑使用 ZeroTurnaround 的 https://jrebel.com/software/jrebel/[JRebel] 等重新加载技术。
这些技术通过在加载时重写类来使其更易于重新加载。
****



[[using.devtools.restart.logging-condition-delta]]
=== 记录条件评估的更改

默认情况下，每次应用程序重启时，都会记录显示条件评估差异的报告。
该报告显示当您进行更改（如添加或删除 beans 和设置配置属性）时应用程序的自动配置的变化。

要禁用报告的记录，请设置以下属性：

[configprops,yaml]
----
spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
----
[[using.devtools.restart.excluding-resources]]
=== 排除资源

某些资源在更改时不一定需要触发重启。
例如，Thymeleaf 模板可以就地编辑。
默认情况下，更改 `/META-INF/maven`、`/META-INF/resources`、`/resources`、`/static`、`/public` 或 `/templates` 中的资源不会触发重启，但会触发 xref:using/devtools.adoc#using.devtools.livereload[实时重载]。
如果你想自定义这些排除项，可以使用 configprop:spring.devtools.restart.exclude[] 属性。
例如，要仅排除 `/static` 和 `/public`，你可以设置以下属性：

[configprops,yaml]
----
spring:
  devtools:
    restart:
      exclude: "static/**,public/**"
----
提示：如果你想保留这些默认值并_添加_额外的排除项，请使用 configprop:spring.devtools.restart.additional-exclude[] 属性。

[[using.devtools.restart.watching-additional-paths]]
=== 监视额外路径

你可能希望在修改不在 classpath 上的文件时重启或重新加载应用程序。为此，请使用 configprop:spring.devtools.restart.additional-paths[] 属性配置要监视更改的额外路径。你可以使用 configprop:spring.devtools.restart.exclude[] 属性 xref:using/devtools.adoc#using.devtools.restart.excluding-resources[前面描述过] 来控制额外路径下的更改是触发完全重启还是 xref:using/devtools.adoc#using.devtools.livereload[实时重新加载]。

[[using.devtools.restart.disable]]
=== 禁用重启

如果你不想使用重启功能，可以通过 configprop:spring.devtools.restart.enabled[] 属性禁用它。在大多数情况下，你可以在 `application.properties` 中设置此属性（这样做仍会初始化重启类加载器，但不会监视文件更改）。

如果你需要_完全_禁用重启支持（例如，因为它与特定库不兼容），你需要在调用 `SpringApplication.run(...)` 之前将 configprop:spring.devtools.restart.enabled[] javadoc:java.lang.System[] 属性设置为 `false`，如下例所示：

[source,java]
----
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyApplication {

	public static void main(String[] args) {
		System.setProperty("spring.devtools.restart.enabled", "false");
		SpringApplication.run(MyApplication.class, args);
	}

}
----

[[using.devtools.restart.triggerfile]]
=== 使用触发文件

如果你使用的 IDE 会持续编译已更改的文件，你可能更希望在特定时间触发重启。为此，你可以使用一个“`trigger file`”，这是一个特殊文件，当你实际想要触发重启检查时必须修改它。

注意：对文件的任何更新都会触发检查，但仅当 Devtools 检测到有事情要做时才会实际重启。

要使用触发文件，请将 configprop:spring.devtools.restart.trigger-file[] 属性设置为触发文件的名称（不包括任何路径）。触发文件必须出现在你的 classpath 上的某个位置。

例如，如果你的项目具有以下结构：

[source]
----
src
+- main
   +- resources
      +- .reloadtrigger
----
那么你的 `trigger-file` 属性将是：

[configprops,yaml]
----
spring:
  devtools:
    restart:
      trigger-file: ".reloadtrigger"
----
现在，只有在 `src/main/resources/.reloadtrigger` 更新时才会发生重启。

提示：你可能希望将 `spring.devtools.restart.trigger-file` 设置为 xref:using/devtools.adoc#using.devtools.globalsettings[全局设置]，以便所有项目的行为方式相同。

某些 IDE 具有可以避免手动更新触发文件的功能。
https://spring.io/tools[Spring Tools for Eclipse] 和 https://www.jetbrains.com/idea/[IntelliJ IDEA (Ultimate Edition)] 都提供了此类支持。
使用 Spring Tools，你可以使用控制台视图中的“`reload`”按钮（只要你的 `trigger-file` 名为 `.reloadtrigger`）。
对于 IntelliJ IDEA，你可以按照 https://www.jetbrains.com/help/idea/spring-boot.html#application-update-policies[其文档中的说明] 进行操作。



[[using.devtools.restart.customizing-the-classload]]
=== 自定义重启类加载器
如前文 xref:#using.devtools.restart.restart-vs-reload[] 部分所述，重启功能是通过使用两个类加载器实现的。
如果这导致问题，你可以使用 `spring.devtools.restart.enabled` 系统属性来诊断问题，并且如果应用在关闭重启的情况下正常工作，则可能需要自定义每个类加载器加载的内容。

默认情况下，IDE 中任何打开的项目都使用“`restart`”类加载器加载，而任何常规的 `.jar` 文件都使用“`base`”类加载器加载。
如果你使用 `mvn spring-boot:run` 或 `gradle bootRun`，情况也是如此：包含你的 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 的项目使用“`restart`”类加载器加载，而其他所有内容使用“`base`”类加载器加载。
classpath 在启动应用时打印在控制台上，这有助于识别任何有问题的条目。
反射使用的类，尤其是注解，可能会在启动时被加载到父（固定）类加载器中，早于使用它们的应用类，这可能导致它们无法被应用中的 Spring 检测到。

你可以通过创建 `META-INF/spring-devtools.properties` 文件来指示 Spring Boot 使用不同的类加载器加载项目的部分内容。
`spring-devtools.properties` 文件可以包含以 `restart.exclude` 和 `restart.include` 为前缀的属性。
`include` 元素是应被提升到“`restart`”类加载器中的项，而 `exclude` 元素是应被下推到“`base`”类加载器中的项。
属性的值是一个正则表达式模式，应用于启动时传递给 JVM 的 classpath。
以下是一个示例，其中排除了某些本地类文件，并将一些额外的库包含在重启类加载器中：

[source,properties]
----
restart.exclude.companycommonlibs="/mycorp-common-[\\w\\d-\\.]/(build|bin|out|target)/"
restart.include.projectcommon="/mycorp-myproj-[\\w\\d-\\.]+\\.jar"
----
NOTE: 所有属性键必须唯一。
只要属性以 `restart.include.` 或 `restart.exclude.` 开头，即被视为有效。

TIP: 来自 classpath 的所有 `META-INF/spring-devtools.properties` 都会被加载。
你可以将文件打包到项目中，或打包到项目所依赖的库中。
系统属性不能使用，只能使用属性文件。


[[using.devtools.restart.limitations]]
=== 已知限制

重启功能对于通过标准 javadoc:java.io.ObjectInputStream[] 反序列化的对象效果不佳。
如果你需要反序列化数据，可能需要将 Spring 的 javadoc:org.springframework.core.ConfigurableObjectInputStream[] 与 `Thread.currentThread().getContextClassLoader()` 结合使用。

不幸的是，许多第三方库在反序列化时没有考虑上下文类加载器。
如果你发现此类问题，需要向原始作者请求修复。


[[using.devtools.livereload]]
== LiveReload

WARNING: 由于 LiveReload 的流行度和支持度下降，该功能自 Spring Boot 4.1.0 起已弃用，且无替代方案。

`spring-boot-devtools` 模块包含一个嵌入式 LiveReload 服务器，可用于在资源更改时触发浏览器刷新。
LiveReload 浏览器扩展可免费用于 Chrome、Firefox 和 Safari。
你可以通过在你选择的浏览器的市场或商店中搜索“LiveReload”来找到这些扩展。

如果你希望在应用程序运行时启动 LiveReload 服务器，可以将 configprop:spring.devtools.livereload.enabled[deprecated] 属性设置为 `true`。

NOTE: 一次只能运行一个 LiveReload 服务器。
在启动应用程序之前，请确保没有其他 LiveReload 服务器正在运行。
如果你从 IDE 启动多个应用程序，只有第一个支持 LiveReload。

WARNING: 要在文件更改时触发 LiveReload，必须启用 xref:using/devtools.adoc#using.devtools.restart[]。


[[using.devtools.globalsettings]]
== 全局设置

你可以通过将以下任一文件添加到 `$HOME/.config/spring-boot` 目录来配置全局 devtools 设置：

. `spring-boot-devtools.properties`
. `spring-boot-devtools.yaml`
. `spring-boot-devtools.yml`

添加到这些文件中的任何属性都将应用于你机器上使用 devtools 的 _所有_ Spring Boot 应用程序。
例如，要将重启配置为始终使用 xref:using/devtools.adoc#using.devtools.restart.triggerfile[触发文件]，你可以将以下属性添加到你的 `spring-boot-devtools` 文件中：

[configprops,yaml]
----
spring:
  devtools:
    restart:
      trigger-file: ".reloadtrigger"
----
默认情况下，`$HOME` 是用户的主目录。
要自定义此位置，请设置 `SPRING_DEVTOOLS_HOME` 环境变量或 `spring.devtools.home` 系统属性。

注意：如果在 `$HOME/.config/spring-boot` 中未找到 devtools 配置文件，则会搜索 `$HOME` 目录的根目录以查找 `.spring-boot-devtools.properties` 文件。
这允许您将 devtools 全局配置与运行在不支持 `$HOME/.config/spring-boot` 位置的旧版本 Spring Boot 上的应用程序共享。

[NOTE]
====
devtools 属性/yaml 文件中不支持 profile。

在 `.spring-boot-devtools.properties` 中激活的任何 profiles 不会影响 xref:features/external-config.adoc#features.external-config.files.profile-specific[profile 特定配置文件]的加载。
不支持特定于 profile 的文件名（形式为 `spring-boot-devtools-<profile>.properties`）以及 YAML 和 Properties 文件中的 `spring.config.activate.on-profile` 文档。
====



[[using.devtools.globalsettings.configuring-file-system-watcher]]
=== 配置文件系统监视器

javadoc:org.springframework.boot.devtools.filewatch.FileSystemWatcher[] 通过以一定时间间隔轮询类更改，然后等待预定义的静默期以确保没有更多更改来工作。
由于 Spring Boot 完全依赖 IDE 来编译文件并将文件复制到 Spring Boot 可以读取的位置，您可能会发现有时 devtools 重新启动应用程序时某些更改不会反映出来。
如果您经常遇到此类问题，请尝试将 `spring.devtools.restart.poll-interval` 和 `spring.devtools.restart.quiet-period` 参数增加到适合您开发环境的值：

[configprops,yaml]
----
spring:
  devtools:
    restart:
      poll-interval: "2s"
      quiet-period: "1s"
----
被监控的 classpath 目录现在每 2 秒轮询一次变更，并保持 1 秒的静默期以确保没有额外的类变更。

[[using.devtools.remote-applications]]
== 远程应用

Spring Boot 开发者工具不仅限于本地开发。在远程运行应用时，你也可以使用若干功能。远程支持是选择性加入的，因为启用它可能带来安全风险。它只应在受信任的网络中运行或通过 SSL 保护时启用。如果这两种选项都不可用，你不应使用 DevTools 的远程支持。切勿在生产部署中启用支持。

要启用它，你需要确保 `devtools` 包含在重新打包的归档中，如下所示：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<includeOptional>true</includeOptional>
				<excludeDevtools>false</excludeDevtools>
			</configuration>
		</plugin>
	</plugins>
</build>
----
NOTE: 可选依赖项默认不包含，这解释了为什么 `includeOptional` 也存在。

然后你需要设置 configprop:spring.devtools.remote.secret[] 属性。
与任何重要的密码或密钥一样，该值应唯一且强健，使其无法被猜测或暴力破解。

远程 devtools 支持分为两部分：一个接受连接的服务器端端点和一个在 IDE 中运行的客户端应用程序。
当设置 configprop:spring.devtools.remote.secret[] 属性时，服务器组件会自动启用。
客户端组件必须手动启动。

NOTE: 远程 devtools 不支持 Spring WebFlux 应用程序。


[[using.devtools.remote-applications.client]]
=== 运行远程客户端应用程序

远程客户端应用程序设计为从 IDE 内部运行。
你需要使用与你连接的远程项目相同的 classpath 运行 javadoc:org.springframework.boot.devtools.RemoteSpringApplication[]。
该应用程序的唯一必需参数是它连接的远程 URL。

例如，如果你使用 Eclipse 或 Spring Tools，并且有一个名为 `my-app` 的项目已部署到 Cloud Foundry，则应执行以下操作：

* 从 `Run` 菜单中选择 `Run Configurations...`。
* 创建一个新的 `Java Application` "`launch configuration`"。
* 浏览 `my-app` 项目。
* 使用 javadoc:org.springframework.boot.devtools.RemoteSpringApplication[] 作为主类。
* 将 `+++https://myapp.cfapps.io+++` 添加到 `Program arguments`（或任何你的远程 URL）。

一个正在运行的远程客户端可能类似于以下列表：

[source,subs="verbatim,attributes"]
----
include::ROOT:example$remote-spring-application.txt[]
----
NOTE: 因为远程客户端使用与真实应用相同的 classpath，所以它可以直接读取应用属性。
这就是 configprop:spring.devtools.remote.secret[] 属性被读取并传递给服务器进行身份验证的方式。

TIP: 始终建议使用 `https://` 作为连接协议，这样流量会被加密，密码无法被截获。

TIP: 如果需要使用代理访问远程应用，请配置 `spring.devtools.remote.proxy.host` 和 `spring.devtools.remote.proxy.port` 属性。


[[using.devtools.remote-applications.update]]
=== 远程更新

远程客户端以与 xref:using/devtools.adoc#using.devtools.restart[本地重启]相同的方式监视应用程序 classpath 的更改。
任何更新的资源都会被推送到远程应用，并且（如果需要）触发重启。
这在你迭代使用本地没有的云服务的功能时非常有用。
通常，远程更新和重启比完整的重建和部署周期快得多。

在较慢的开发环境中，静默期可能不够长，类的更改可能会分成多批。
在第一批类更改上传后，服务器会重启。
下一批无法发送到应用，因为服务器正在重启。

这通常表现为 javadoc:org.springframework.boot.devtools.RemoteSpringApplication[] 日志中关于无法上传某些类的警告，以及随后的重试。
但也可能导致应用代码不一致，并在第一批更改上传后无法重启。
如果你经常观察到此类问题，请尝试将 `spring.devtools.restart.poll-interval` 和 `spring.devtools.restart.quiet-period` 参数增加到适合你开发环境的值。
有关配置这些属性的信息，请参阅 xref:using/devtools.adoc#using.devtools.globalsettings.configuring-file-system-watcher[] 部分。

NOTE: 文件仅在远程客户端运行时被监视。
如果在启动远程客户端之前更改了文件，则不会将其推送到远程服务器。
