[[howto.aot-cache]]
= AOT 缓存
:page-aliases: class-data-sharing.adoc

本节包含有关在 Spring Boot 应用程序中使用 AOT 缓存的信息。
有关 Spring Boot 对 AOT 缓存支持的概述，请参见 xref:reference:packaging/aot-cache.adoc[]。



[[howto.aot-cache.buildpacks]]
== 使用 AOT 缓存和 Buildpacks 打包应用程序

Spring Boot 的 xref:reference:packaging/container-images/cloud-native-buildpacks.adoc[对 Cloud Native Buildpacks 的支持] 结合 https://paketo.io/docs/reference/java-reference[Paketo Java buildpack] 及其 https://paketo.io/docs/reference/java-reference/#spring-boot-applications[Spring Boot 支持] 可用于生成包含 AOT 缓存优化应用程序的 Docker 镜像。

要在生成的 Docker 镜像中启用 AOT 缓存，您必须使用 Java 25 或更高版本，并且在构建镜像时，如 xref:maven-plugin:build-image.adoc#build-image.examples.builder-configuration[Maven 插件] 和 xref:gradle-plugin:packaging-oci-image.adoc#build-image.examples.builder-configuration[Gradle 插件] 文档所述，应将 buildpack 环境变量 `BP_JVM_AOTCACHE_ENABLED` 设置为 `true`。
这将导致 buildpack 对应用程序进行一次训练运行，将 AOT 缓存保存到镜像中，并在启动应用程序时使用该 AOT 缓存。

Paketo Spring Boot Buildpack 的 https://github.com/paketo-buildpacks/spring-boot?tab=readme-ov-file#configuration[文档] 提供了有关其他可通过构建器环境变量启用的配置选项的信息，例如 `TRAINING_RUN_JAVA_TOOL_OPTIONS`，它允许覆盖默认的 `JAVA_TOOL_OPTIONS`，仅用于 AOT 缓存训练运行。



[[howto.aot-cache.dockerfiles]]
== 使用 AOT 缓存和 Dockerfiles 打包应用程序

如果您不想使用 Cloud Native Buildpacks，也可以将 AOT 缓存（或 CDS）与 `Dockerfile` 一起使用。
有关更多信息，请参见 xref:reference:packaging/container-images/dockerfiles.adoc#packaging.container-images.dockerfiles.aot-cache[Dockerfiles 参考文档]。



[[howto.aot-cache.training-run-configuration]]
== 防止训练运行期间与远程服务交互

在执行训练运行时，可能需要自定义 Spring Boot 应用程序配置，以防止在 Spring 生命周期启动之前可能发生的与远程服务的连接。
这通常可能发生在早期的数据库交互中，可以通过默认应用于您的应用程序（或专门针对训练运行）的相关配置来处理，以防止此类交互，请参见 https://github.com/spring-projects/spring-lifecycle-smoke-tests/blob/main/README.adoc#training-run-configuration[相关文档]。
