= 构建

Spring Boot 包含用于 Maven 和 Gradle 的构建插件。
本节回答关于这些插件的常见问题。


[[howto.build.generate-info]]
== 生成构建信息

Maven 插件和 Gradle 插件都允许生成包含项目坐标、名称和版本的构建信息。
这些插件还可以通过配置来添加额外的属性。
当存在这样的文件时，Spring Boot 会自动配置一个 javadoc:org.springframework.boot.info.BuildProperties[] bean。

要使用 Maven 生成构建信息，请为 `build-info` 目标添加一个执行，如下例所示：

[source,xml,subs="verbatim,attributes"]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<version>{version-spring-boot}</version>
			<executions>
				<execution>
					<goals>
						<goal>build-info</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
----
TIP: 有关更多详细信息，请参阅 xref:maven-plugin:build-info.adoc[Spring Boot Maven 插件文档]。

以下示例使用 Gradle 执行相同操作：

[source,gradle]
----
springBoot {
	buildInfo()
}
----
TIP: 更多详情请参阅 xref:gradle-plugin:integrating-with-actuator.adoc[Spring Boot Gradle 插件文档]。

[[howto.build.generate-git-info]]
== 生成 Git 信息

Maven 和 Gradle 都允许生成一个 `git.properties` 文件，其中包含项目构建时 `git` 源代码仓库的状态信息。

对于 Maven 用户，`spring-boot-starter-parent` POM 包含一个预配置的插件，用于生成 `git.properties` 文件。
要使用它，请将以下 {url-git-commit-id-maven-plugin}[`Git Commit Id Plugin`] 声明添加到您的 POM 中：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>io.github.git-commit-id</groupId>
			<artifactId>git-commit-id-maven-plugin</artifactId>
		</plugin>
	</plugins>
</build>
----
Gradle 用户可以通过使用 https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties[`gradle-git-properties`] 插件达到相同效果，如下例所示：

[source,gradle]
----
plugins {
	id "com.gorylenko.gradle-git-properties" version "2.4.1"
}
----
Maven 和 Gradle 插件都允许配置包含在 `git.properties` 中的属性。

TIP: `git.properties` 中的提交时间应匹配以下格式：`yyyy-MM-dd'T'HH:mm:ssZ`。
这是上面列出的两个插件的默认格式。
使用此格式可以将时间解析为 javadoc:java.util.Date[]；当它序列化为 JSON 时，其格式可由 Jackson 的日期序列化配置设置控制。


[[howto.build.generate-cyclonedx-sbom]]
== 生成 CycloneDX SBOM

Maven 和 Gradle 都允许在项目构建时生成 CycloneDX SBOM。

对于 Maven 用户，`spring-boot-starter-parent` POM 包含一个预配置的插件，用于生成 SBOM。
要使用它，请将以下 {url-cyclonedx-docs-maven-plugin}[`cyclonedx-maven-plugin`] 声明添加到你的 POM：

[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.cyclonedx</groupId>
            <artifactId>cyclonedx-maven-plugin</artifactId>
        </plugin>
    </plugins>
</build>
----
Gradle 用户可以通过使用 {url-cyclonedx-docs-gradle-plugin}[`cyclonedx-gradle-plugin`] 插件达到相同的结果，如下例所示：

[source,gradle]
----
plugins {
    id 'org.cyclonedx.bom' version '3.0.0'
}
----
== 自定义依赖版本

`spring-boot-dependencies` POM 管理常见依赖的版本。
Spring Boot 的 Maven 和 Gradle 插件允许通过构建属性自定义这些受管理的依赖版本。

WARNING: 每个 Spring Boot 版本都是针对这组特定的第三方依赖进行设计和测试的。
覆盖版本可能会导致兼容性问题。

要使用 Maven 覆盖依赖版本，请参阅 Maven 插件文档中的 xref:maven-plugin:using.adoc[]。

要使用 Gradle 覆盖依赖版本，请参阅 Gradle 插件文档中的 xref:gradle-plugin:managing-dependencies.adoc#managing-dependencies.dependency-management-plugin.customizing[]。

[[howto.build.create-an-executable-jar-with-maven]]
== 使用 Maven 创建可执行 JAR

`spring-boot-maven-plugin` 可用于创建可执行的 "`fat`" JAR。
如果您使用 `spring-boot-starter-parent` POM，可以声明该插件，您的 JAR 将按如下方式重新打包：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
	</plugins>
</build>
----
如果你不使用父 POM，你仍然可以使用该插件。
但是，你必须额外添加一个 `<executions>` 部分，如下所示：

[source,xml,subs="verbatim,attributes"]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<version>{version-spring-boot}</version>
			<executions>
				<execution>
					<goals>
						<goal>repackage</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
----
有关完整的使用细节，请参阅 xref:maven-plugin:packaging.adoc#packaging.repackage-goal[插件文档]。

[[howto.build.use-a-spring-boot-application-as-dependency]]
== 将 Spring Boot 应用程序用作依赖项

与 war 文件类似，Spring Boot 应用程序不打算用作依赖项。
如果你的应用程序包含希望与其他项目共享的类，推荐的方法是将这些代码移到一个单独的模块中。
然后，你的应用程序和其他项目可以依赖这个单独的模块。

如果你无法按照上述建议重新组织代码，则必须配置 Spring Boot 的 Maven 和 Gradle 插件，以生成一个适合用作依赖项的独立构件。
可执行归档不能用作依赖项，因为 xref:specification:executable-jar/nested-jars.adoc#appendix.executable-jar.nested-jars.jar-structure[可执行 jar 格式] 将应用程序类打包在 `BOOT-INF/classes` 中。
这意味着当可执行 jar 用作依赖项时，无法找到这些类。

要生成两个构件（一个可用作依赖项，另一个可执行），必须指定一个分类器。
此分类器应用于可执行归档的名称，而保留默认归档用作依赖项。

要在 Maven 中配置分类器为 `exec`，可以使用以下配置：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<classifier>exec</classifier>
			</configuration>
		</plugin>
	</plugins>
</build>
----
== 可执行 JAR 运行时提取特定库

可执行 JAR 中的大多数嵌套库在运行时无需解包。然而，某些库可能会出现问题。例如，JRuby 包含自己的嵌套 JAR 支持，它假设 `jruby-complete.jar` 始终作为文件直接可用。

为了解决任何有问题的库，你可以标记特定的嵌套 JAR，使其在可执行 JAR 首次运行时自动解包。这些嵌套 JAR 会被写入由 `java.io.tmpdir` 系统属性标识的临时目录下。

WARNING: 应注意确保操作系统配置得当，以免在应用程序仍在运行时删除已解包到临时目录的 JAR。

例如，要使用 Maven 插件标记 JRuby 进行解包，你可以添加以下配置：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<requiresUnpack>
					<dependency>
						<groupId>org.jruby</groupId>
						<artifactId>jruby-complete</artifactId>
					</dependency>
				</requiresUnpack>
			</configuration>
		</plugin>
	</plugins>
</build>
----
== 创建带排除项的非可执行 JAR

通常，如果你将可执行 jar 和非可执行 jar 作为两个独立的构建产物，可执行版本会包含库 jar 中不需要的额外配置文件。
例如，`application.yaml` 配置文件可能被排除在非可执行 JAR 之外。

在 Maven 中，可执行 jar 必须是主要工件，你可以为库添加一个带分类器的 jar，如下所示：

[source,xml]
----
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
		<plugin>
			<artifactId>maven-jar-plugin</artifactId>
			<executions>
				<execution>
					<id>lib</id>
					<phase>package</phase>
					<goals>
						<goal>jar</goal>
					</goals>
					<configuration>
						<classifier>lib</classifier>
						<excludes>
							<exclude>application.yaml</exclude>
						</excludes>
					</configuration>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
----
[[howto.build.remote-debug-maven]]
== 远程调试使用 Maven 启动的 Spring Boot 应用程序

要将远程调试器附加到使用 Maven 启动的 Spring Boot 应用程序，可以使用 xref:maven-plugin:index.adoc[Maven Plugin] 的 `jvmArguments` 属性。

更多详情请参见 xref:maven-plugin:run.adoc#run.examples.debug[此示例]。


[[howto.build.build-an-executable-archive-with-ant-without-using-spring-boot-antlib]]
== 在不使用 spring-boot-antlib 的情况下从 Ant 构建可执行归档

要使用 Ant 构建，你需要获取依赖、编译，然后创建 jar 或 war 归档。
要使其可执行，你可以使用 `spring-boot-antlib` 模块，或者按照以下说明操作：

. 如果你正在构建 jar，将应用程序的类和资源打包到嵌套的 `BOOT-INF/classes` 目录中。
  如果你正在构建 war，像往常一样将应用程序的类打包到嵌套的 `WEB-INF/classes` 目录中。
. 将运行时依赖添加到 jar 的嵌套 `BOOT-INF/lib` 目录或 war 的 `WEB-INF/lib` 目录中。
  记住 *不要* 压缩归档中的条目。
. 将 `provided`（嵌入式容器）依赖添加到 jar 的嵌套 `BOOT-INF/lib` 目录或 war 的 `WEB-INF/lib-provided` 目录中。
  记住 *不要* 压缩归档中的条目。
. 将 `spring-boot-loader` 类添加到归档的根目录（以便 `Main-Class` 可用）。
. 使用适当的启动器（例如 jar 文件的 javadoc:org.springframework.boot.loader.launch.JarLauncher[]）作为清单中的 `Main-Class` 属性，并指定它需要的其他属性作为清单条目——主要通过设置 `Start-Class` 属性。

以下示例展示了如何使用 Ant 构建可执行归档：

[source,xml]
----
<target name="build" depends="compile">
	<jar destfile="target/${ant.project.name}-${spring-boot.version}.jar" compress="false">
		<mappedresources>
			<fileset dir="target/classes" />
			<globmapper from="*" to="BOOT-INF/classes/*"/>
		</mappedresources>
		<mappedresources>
			<fileset dir="src/main/resources" erroronmissingdir="false"/>
			<globmapper from="*" to="BOOT-INF/classes/*"/>
		</mappedresources>
		<mappedresources>
			<fileset dir="${lib.dir}/runtime" />
			<globmapper from="*" to="BOOT-INF/lib/*"/>
		</mappedresources>
		<zipfileset src="${lib.dir}/loader/spring-boot-loader-jar-${spring-boot.version}.jar" />
		<manifest>
			<attribute name="Main-Class" value="org.springframework.boot.loader.launch.JarLauncher" />
			<attribute name="Start-Class" value="${start-class}" />
		</manifest>
	</jar>
</target>
----
