[[howto.data-access]]
= 数据访问

Spring Boot 包含许多用于处理数据源的 starters。
本节回答与此相关的常见问题。


[[howto.data-access.configure-custom-datasource]]
== 配置自定义 DataSource

要配置自己的 javadoc:javax.sql.DataSource[]，请在配置中定义一个该类型的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。
Spring Boot 在任何需要的地方重用你的 javadoc:javax.sql.DataSource[]，包括数据库初始化。
如果需要外部化某些设置，可以将 javadoc:javax.sql.DataSource[] 绑定到环境（参见 xref:reference:features/external-config.adoc#features.external-config.typesafe-configuration-properties.third-party-configuration[]）。

以下示例展示了如何在 bean 中定义数据源：

[source,java]
----
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyDataSourceConfiguration {

	@Bean
	@ConfigurationProperties("app.datasource")
	public SomeDataSource dataSource() {
		return new SomeDataSource();
	}

}
----

以下示例展示了如何通过设置属性来定义数据源：

[configprops%novalidate,yaml]
----
app:
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: "sa"
    pool-size: 30
----
假设 `SomeDataSource` 具有 URL、用户名和池大小的常规 JavaBean 属性，则在 javadoc:javax.sql.DataSource[] 对其他组件可用之前，这些设置会自动绑定。

Spring Boot 还提供了一个名为 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 的工具构建器类，可用于创建标准数据源之一（如果它在 classpath 上）。该构建器可以根据 classpath 上可用的内容检测要使用哪一个。它还会根据 JDBC URL 自动检测驱动程序。

以下示例展示了如何使用 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 创建数据源：

[source,java]
----
import javax.sql.DataSource;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.jdbc.DataSourceBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyDataSourceConfiguration {

	@Bean
	@ConfigurationProperties("app.datasource")
	public DataSource dataSource() {
		return DataSourceBuilder.create().build();
	}

}
----

要运行使用该 javadoc:javax.sql.DataSource[] 的应用程序，您只需要连接信息。也可以提供特定于池的设置。有关更多详细信息，请检查将在运行时使用的实现。

以下示例展示了如何通过设置属性来定义 JDBC 数据源：

[configprops%novalidate,yaml]
----
app:
  datasource:
    url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
    pool-size: 30
----
然而，由于该方法的 javadoc:javax.sql.DataSource[] 返回类型，存在一个问题。
这会隐藏连接池的实际类型，因此不会为您的自定义 javadoc:javax.sql.DataSource[] 生成配置属性元数据，IDE 中也不会有自动补全功能。
要解决此问题，请使用构建器的 `type(Class)` 方法指定要构建的 javadoc:javax.sql.DataSource[] 类型，并更新方法的返回类型。
例如，以下示例展示了如何使用 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 创建一个 javadoc:com.zaxxer.hikari.HikariDataSource[]：

[source,java]
----
import com.zaxxer.hikari.HikariDataSource;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.jdbc.DataSourceBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyDataSourceConfiguration {

	@Bean
	@ConfigurationProperties("app.datasource")
	public HikariDataSource dataSource() {
		return DataSourceBuilder.create().type(HikariDataSource.class).build();
	}

}
----

不幸的是，这个基本设置无法工作，因为 Hikari 没有 `url` 属性。
相反，它有一个 `jdbc-url` 属性，这意味着您必须按如下方式重写配置：

[configprops%novalidate,yaml]
----
app:
  datasource:
    jdbc-url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
    pool-size: 30
----
为了解决这个问题，请使用 javadoc:org.springframework.boot.jdbc.autoconfigure.DataSourceProperties[]，它将为你处理从 `url` 到 `jdbc-url` 的转换。
你可以使用任何 javadoc:org.springframework.boot.jdbc.autoconfigure.DataSourceProperties[] 对象的 `initializeDataSourceBuilder()` 方法，从其状态初始化一个 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[]。
你可以注入 Spring Boot 自动创建的 javadoc:org.springframework.boot.jdbc.autoconfigure.DataSourceProperties[]，但这会将你的配置分散在 `+spring.datasource.*+` 和 `+app.datasource.*+` 之间。
为了避免这种情况，请定义一个带有自定义配置属性前缀的自定义 javadoc:org.springframework.boot.jdbc.autoconfigure.DataSourceProperties[]，如下例所示：

[source,java]
----
import com.zaxxer.hikari.HikariDataSource;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.jdbc.autoconfigure.DataSourceProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;

@Configuration(proxyBeanMethods = false)
public class MyDataSourceConfiguration {

	@Bean
	@Primary
	@ConfigurationProperties("app.datasource")
	public DataSourceProperties dataSourceProperties() {
		return new DataSourceProperties();
	}

	@Bean
	@ConfigurationProperties("app.datasource.configuration")
	public HikariDataSource dataSource(DataSourceProperties properties) {
		return properties.initializeDataSourceBuilder().type(HikariDataSource.class).build();
	}

}
----

此设置等同于 Spring Boot 默认为你所做的，不同之处在于池的类型在代码中指定，其设置作为 `app.datasource.configuration.*` 属性暴露。
javadoc:org.springframework.boot.jdbc.autoconfigure.DataSourceProperties[] 负责从 `url` 到 `jdbc-url` 的转换，因此你可以按如下方式配置它：

[configprops%novalidate,yaml]
----
app:
  datasource:
    url: "jdbc:mysql://localhost/test"
    username: "dbuser"
    password: "dbpass"
    configuration:
      maximum-pool-size: 30
----
请注意，由于自定义配置在代码中指定应使用 Hikari，`app.datasource.type` 将不会生效。

如 xref:reference:data/sql.adoc#data.sql.datasource.connection-pool[] 所述，javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 支持多种不同的连接池。
要使用 Hikari 以外的连接池，请将其添加到 classpath，使用 `type(Class)` 方法指定要使用的连接池类，并更新 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法的返回类型以匹配。
这还将为您提供所选特定连接池的配置属性元数据。

提示：Spring Boot 会将 Hikari 特定的设置暴露给 `spring.datasource.hikari`。
此示例使用更通用的 `configuration` 子命名空间，因为该示例不支持多种数据源实现。

有关更多详细信息，请参阅 xref:reference:data/sql.adoc#data.sql.datasource[] 和 {code-spring-boot-jdbc-src}/autoconfigure/DataSourceAutoConfiguration.java[`DataSourceAutoConfiguration`] 类。


[[howto.data-access.configure-two-datasources]]
== 配置两个数据源

要定义额外的 javadoc:javax.sql.DataSource[]，可以使用与上一节类似的方法。
一个关键区别是，javadoc:javax.sql.DataSource[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 必须使用 `defaultCandidate=false` 声明。
这可以防止自动配置的 javadoc:javax.sql.DataSource[] 回退。

注意：{url-spring-framework-docs}/core/beans/dependencies/factory-autowire.html#beans-factory-autowire-candidate[Spring 框架参考文档] 更详细地描述了此功能。

为了允许在需要的地方注入额外的 javadoc:javax.sql.DataSource[]，还需要使用 javadoc:org.springframework.beans.factory.annotation.Qualifier[format=annotation] 对其进行注解，如下例所示：

[source,java]
----
import com.zaxxer.hikari.HikariDataSource;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.jdbc.DataSourceBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyAdditionalDataSourceConfiguration {

	@Qualifier("second")
	@Bean(defaultCandidate = false)
	@ConfigurationProperties("app.datasource")
	public HikariDataSource secondDataSource() {
		return DataSourceBuilder.create().type(HikariDataSource.class).build();
	}

}
----

要使用额外的 javadoc:javax.sql.DataSource[]，请使用相同的 javadoc:org.springframework.beans.factory.annotation.Qualifier[format=annotation] 注解注入点。

自动配置的和额外的数据源可以按如下方式配置：

[configprops%novalidate,yaml]
----
spring:
  datasource:
    url: "jdbc:mysql://localhost/first"
    username: "dbuser"
    password: "dbpass"
    configuration:
      maximum-pool-size: 30
app:
  datasource:
    url: "jdbc:mysql://localhost/second"
    username: "dbuser"
    password: "dbpass"
    max-total: 30
----
更高级的、特定于实现的自动配置 javadoc:javax.sql.DataSource[] 配置可通过 `spring.datasource.configuration.*` 属性获得。
您可以将相同的概念应用于额外的 javadoc:javax.sql.DataSource[]，如下例所示：

[source,java]
----
import com.zaxxer.hikari.HikariDataSource;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.jdbc.autoconfigure.DataSourceProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyCompleteAdditionalDataSourceConfiguration {

	@Qualifier("second")
	@Bean(defaultCandidate = false)
	@ConfigurationProperties("app.datasource")
	public DataSourceProperties secondDataSourceProperties() {
		return new DataSourceProperties();
	}

	@Qualifier("second")
	@Bean(defaultCandidate = false)
	@ConfigurationProperties("app.datasource.configuration")
	public HikariDataSource secondDataSource(@Qualifier("second") DataSourceProperties dataSourceProperties) {
		return dataSourceProperties.initializeDataSourceBuilder().type(HikariDataSource.class).build();
	}

}
----

前面的示例使用与 Spring Boot 在自动配置中相同的逻辑配置了额外的数据源。
请注意，`app.datasource.configuration.*` 属性提供了基于所选实现的高级设置。

与 xref:how-to:data-access.adoc#howto.data-access.configure-custom-datasource[配置单个自定义 javadoc:javax.sql.DataSource[]] 一样，一个或两个 javadoc:javax.sql.DataSource[] beans 的类型可以使用 `type(Class)` 方法在 javadoc:org.springframework.boot.jdbc.DataSourceBuilder[] 上进行自定义。
有关支持类型的详细信息，请参阅 xref:reference:data/sql.adoc#data.sql.datasource.connection-pool[]。


[[howto.data-access.spring-data-repositories]]
== 使用 Spring 数据仓库

Spring Data 可以创建各种风格的 javadoc:org.springframework.data.repository.Repository[] 接口的实现。
只要这些 javadoc:org.springframework.data.repository.Repository[] 实现包含在 xref:reference:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 中（通常是使用 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 或 javadoc:org.springframework.boot.autoconfigure.EnableAutoConfiguration[format=annotation] 注解的主应用程序类的包或其子包），Spring Boot 就会为您处理所有这些。

对于许多应用程序，您只需要将正确的 Spring Data 依赖项放在您的 classpath 上。
有一个用于 JPA 的 `spring-boot-starter-data-jpa`，一个用于 MongoDB 的 `spring-boot-starter-data-mongodb`，以及各种其他受支持技术的 starters。
要开始使用，请创建一些仓库接口来处理您的 javadoc:jakarta.persistence.Entity[format=annotation] 对象。

Spring Boot 通过扫描 xref:reference:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 来确定您的 javadoc:org.springframework.data.repository.Repository[] 实现的位置。
要获得更多控制，请使用来自 Spring Data 的 `@Enable…Repositories` annotations。

有关 Spring Data 的更多信息，请参阅 {url-spring-data-site}[Spring Data 项目页面]。


[[howto.data-access.separate-entity-definitions-from-spring-configuration]]
== 将 @Entity 定义与 Spring 配置分离

Spring Boot 通过扫描 xref:reference:using/auto-configuration.adoc#using.auto-configuration.packages[自动配置包] 来确定您的 javadoc:jakarta.persistence.Entity[format=annotation] 定义的位置。
要获得更多控制，请使用 javadoc:org.springframework.boot.persistence.autoconfigure.EntityScan[format=annotation] annotation，如下例所示：

[source,java]
----
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.persistence.autoconfigure.EntityScan;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
@EnableAutoConfiguration
@EntityScan(basePackageClasses = City.class)
public class MyApplication {

	// ...

}
----


[[howto.data-access.filter-scanned-entity-definitions]]
== 过滤扫描的 @Entity 定义

可以使用 javadoc:org.springframework.orm.jpa.persistenceunit.ManagedClassNameFilter[] bean 过滤 javadoc:jakarta.persistence.Entity[format=annotation] 定义。
这在测试中可能很有用，当只应考虑可用实体的子集时。
在以下示例中，仅包含来自 `com.example.app.customer` 包的实体：

[source,java]
----
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.orm.jpa.persistenceunit.ManagedClassNameFilter;

@Configuration(proxyBeanMethods = false)
public class MyEntityScanConfiguration {

	@Bean
	public ManagedClassNameFilter entityScanFilter() {
		return (className) -> className.startsWith("com.example.app.customer.");
	}

}
----


[[howto.data-access.jpa-properties]]
== 配置 JPA 属性

Spring Data JPA 已经提供了一些与供应商无关的配置选项（例如用于 SQL 日志记录的选项），而 Spring Boot 将这些选项以及 Hibernate 的一些其他选项作为外部配置属性公开。
其中一些会根据上下文自动检测，因此您不必设置它们。

`spring.jpa.hibernate.ddl-auto` 是一个特例，因为根据运行时条件，它有不同的默认值。
如果使用嵌入式数据库并且没有模式管理器（如 Liquibase 或 Flyway）处理 javadoc:javax.sql.DataSource[]，则默认为 `create-drop`。
在所有其他情况下，默认为 `none`。

要使用的方言由 JPA 提供程序检测。
如果您更愿意自己设置方言，请设置 configprop:spring.jpa.database-platform[] 属性。

最常见的设置选项如下例所示：

[configprops,yaml]
----
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: "com.example.MyPhysicalNamingStrategy"
    show-sql: true
----
此外，当创建本地 javadoc:jakarta.persistence.EntityManagerFactory[] 时，`+spring.jpa.properties.*+` 中的所有属性都会作为普通 JPA 属性传递（前缀被剥离）。

[WARNING]
====
你需要确保在 `+spring.jpa.properties.*+` 下定义的名称与你的 JPA 提供者所期望的名称完全匹配。
Spring Boot 不会对这些条目进行任何形式的宽松绑定。

例如，如果你想配置 Hibernate 的批量大小，你必须使用 `+spring.jpa.properties.hibernate.jdbc.batch_size+`。
如果你使用其他形式，例如 `batchSize` 或 `batch-size`，Hibernate 将不会应用该设置。
====

提示：如果你需要对 Hibernate 属性进行高级自定义，考虑注册一个 javadoc:org.springframework.boot.hibernate.autoconfigure.HibernatePropertiesCustomizer[] bean，它将在创建 javadoc:jakarta.persistence.EntityManagerFactory[] 之前被调用。
这优先于自动配置应用的任何设置。


[[howto.data-access.configure-hibernate-naming-strategy]]
== 配置 Hibernate 命名策略

Hibernate 使用 {url-hibernate-userguide}#naming[两种不同的命名策略] 将名称从对象模型映射到相应的数据库名称。
物理策略和隐式策略实现的全限定类名可以分别通过设置 `spring.jpa.hibernate.naming.physical-strategy` 和 `spring.jpa.hibernate.naming.implicit-strategy` 属性来配置。
或者，如果 javadoc:org.hibernate.boot.model.naming.ImplicitNamingStrategy[] 或 javadoc:org.hibernate.boot.model.naming.PhysicalNamingStrategy[] beans 在应用上下文中可用，Hibernate 将自动配置使用它们。

默认情况下，Spring Boot 使用 javadoc:org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy[] 配置物理命名策略。
使用此策略，所有点被下划线替换，驼峰命名也被下划线替换。
此外，默认情况下，所有表名都以小写生成。
例如，`TelephoneNumber` 实体被映射到 `telephone_number` 表。
如果你的模式需要混合大小写标识符，定义一个自定义的 javadoc:org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy[] bean，如下例所示：

[source,java]
----
import org.hibernate.boot.model.naming.Identifier;
import org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl;
import org.hibernate.engine.jdbc.env.spi.JdbcEnvironment;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyHibernateConfiguration {

	@Bean
	public PhysicalNamingStrategySnakeCaseImpl caseSensitivePhysicalNamingStrategy() {
		return new PhysicalNamingStrategySnakeCaseImpl() {

			@Override
			public Identifier toPhysicalColumnName(Identifier logicalName, JdbcEnvironment jdbcEnvironment) {
				return logicalName;
			}

		};
	}

}
----

如果你更喜欢使用 Hibernate 的默认值，设置以下属性：

[configprops,yaml]
----
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
----
或者，你可以配置以下 bean：

[source,java]
----
import org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
class MyHibernateConfiguration {

	@Bean
	PhysicalNamingStrategyStandardImpl caseSensitivePhysicalNamingStrategy() {
		return new PhysicalNamingStrategyStandardImpl();
	}

}
----

更多细节，请参阅 {code-spring-boot-hibernate-src}/autoconfigure/HibernateJpaAutoConfiguration.java[`HibernateJpaAutoConfiguration`] 和 {code-spring-boot-jpa-src}/autoconfigure/JpaBaseConfiguration.java[`JpaBaseConfiguration`]。



[[howto.data-access.configure-hibernate-second-level-caching]]
== 配置 Hibernate 二级缓存

Hibernate {url-hibernate-userguide}#caching[二级缓存] 可以针对一系列缓存提供者进行配置。
与其让 Hibernate 再次查找缓存提供者，不如尽可能提供上下文中已有的那个。

要通过 JCache 实现这一点，首先确保 `org.hibernate.orm:hibernate-jcache` 在 classpath 上可用。
然后，添加一个 javadoc:org.springframework.boot.hibernate.autoconfigure.HibernatePropertiesCustomizer[] bean，如下例所示：

[source,java]
----
import org.hibernate.cache.jcache.ConfigSettings;

import org.springframework.boot.hibernate.autoconfigure.HibernatePropertiesCustomizer;
import org.springframework.cache.jcache.JCacheCacheManager;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyHibernateSecondLevelCacheConfiguration {

	@Bean
	public HibernatePropertiesCustomizer hibernateSecondLevelCacheCustomizer(JCacheCacheManager cacheManager) {
		return (properties) -> properties.put(ConfigSettings.CACHE_MANAGER, cacheManager.getCacheManager());
	}

}
----

这个定制器将配置 Hibernate 使用与应用程序相同的 javadoc:org.springframework.cache.CacheManager[]。
也可以使用独立的 javadoc:org.springframework.cache.CacheManager[] 实例。
详情请参阅 {url-hibernate-userguide}#caching-provider-jcache[《Hibernate 用户指南》]。



[[howto.data-access.dependency-injection-in-hibernate-components]]
== 在 Hibernate 组件中使用依赖注入

默认情况下，Spring Boot 注册了一个使用 javadoc:org.springframework.beans.factory.BeanFactory[] 的 javadoc:org.hibernate.resource.beans.container.spi.BeanContainer[] 实现，以便转换器和实体监听器可以使用常规的依赖注入。

你可以通过注册一个移除或更改 `hibernate.resource.beans.container` 属性的 javadoc:org.springframework.boot.hibernate.autoconfigure.HibernatePropertiesCustomizer[] 来禁用或调整此行为。



[[howto.data-access.use-custom-entity-manager]]
== 使用自定义 EntityManagerFactory

要完全控制 javadoc:jakarta.persistence.EntityManagerFactory[] 的配置，你需要添加一个名为 '`entityManagerFactory`' 的 javadoc:org.springframework.context.annotation.Bean[format=annotation]。
Spring Boot 自动配置会在存在该类型的 bean 时关闭其实体管理器。

注意：当你自己为 javadoc:org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean[] 创建 bean 时，在创建自动配置的 javadoc:org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean[] 期间应用的任何定制都会丢失。
请确保使用自动配置的 javadoc:org.springframework.boot.jpa.EntityManagerFactoryBuilder[] 来保留 JPA 和供应商属性。
如果你依赖 `spring.jpa.*` 属性来配置命名策略或 DDL 模式等内容，这一点尤其重要。



[[howto.data-access.use-multiple-entity-managers]]
== 使用多个 EntityManagerFactory

如果你需要针对多个数据源使用 JPA，则每个数据源可能需要一个 javadoc:jakarta.persistence.EntityManagerFactory[]。
来自 Spring ORM 的 javadoc:org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean[] 允许你根据需要配置 javadoc:jakarta.persistence.EntityManagerFactory[]。
你还可以重用 javadoc:org.springframework.boot.jpa.autoconfigure.JpaProperties[] 来绑定第二个 javadoc:jakarta.persistence.EntityManagerFactory[] 的设置。
基于 xref:how-to:data-access.adoc#howto.data-access.configure-two-datasources[配置第二个 javadoc:javax.sql.DataSource[] 的示例]，可以定义第二个 javadoc:jakarta.persistence.EntityManagerFactory[]，如下例所示：

[source,java]
----
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Function;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.jpa.EntityManagerFactoryBuilder;
import org.springframework.boot.jpa.autoconfigure.JpaProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.orm.jpa.JpaVendorAdapter;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;

@Configuration(proxyBeanMethods = false)
public class MyAdditionalEntityManagerFactoryConfiguration {

	@Qualifier("second")
	@Bean(defaultCandidate = false)
	@ConfigurationProperties("app.jpa")
	public JpaProperties secondJpaProperties() {
		return new JpaProperties();
	}

	@Qualifier("second")
	@Bean(defaultCandidate = false)
	public LocalContainerEntityManagerFactoryBean secondEntityManagerFactory(@Qualifier("second") DataSource dataSource,
			@Qualifier("second") JpaProperties jpaProperties) {
		EntityManagerFactoryBuilder builder = createEntityManagerFactoryBuilder(jpaProperties);
		return builder.dataSource(dataSource).packages(Order.class).persistenceUnit("second").build();
	}

	private EntityManagerFactoryBuilder createEntityManagerFactoryBuilder(JpaProperties jpaProperties) {
		JpaVendorAdapter jpaVendorAdapter = createJpaVendorAdapter(jpaProperties);
		Function<DataSource, Map<String, ?>> jpaPropertiesFactory = (dataSource) -> createJpaProperties(dataSource,
				jpaProperties.getProperties());
		return new EntityManagerFactoryBuilder(jpaVendorAdapter, jpaPropertiesFactory, null);
	}

	private JpaVendorAdapter createJpaVendorAdapter(JpaProperties jpaProperties) {
		// ... map JPA properties as needed
		return new HibernateJpaVendorAdapter();
	}

	private Map<String, ?> createJpaProperties(DataSource dataSource, Map<String, ?> existingProperties) {
		Map<String, ?> jpaProperties = new LinkedHashMap<>(existingProperties);
		// ... map JPA properties that require the DataSource (e.g. DDL flags)
		return jpaProperties;
	}

}
----

上面的示例使用限定符为 `@Qualifier("second")` 的 javadoc:javax.sql.DataSource[] bean 创建了一个 javadoc:jakarta.persistence.EntityManagerFactory[]。
它扫描与 `Order` 位于同一包中的实体。
可以使用 `app.jpa` 命名空间映射额外的 JPA 属性。
使用 `@Bean(defaultCandidate=false)` 允许定义 `secondJpaProperties` 和 `secondEntityManagerFactory` beans，而不会干扰自动配置的同类型 beans。

注意：{url-spring-framework-docs}/core/beans/dependencies/factory-autowire.html#beans-factory-autowire-candidate[Spring Framework 参考文档] 更详细地描述了此功能。

你应该为任何需要 JPA 访问的额外数据源提供类似的配置。
为了完整起见，你还需要为每个 javadoc:jakarta.persistence.EntityManagerFactory[] 配置一个 javadoc:org.springframework.orm.jpa.JpaTransactionManager[]。
或者，你可以使用一个跨越两者的 JTA 事务管理器。

如果你使用 Spring Data，则需要相应地配置 javadoc:org.springframework.data.jpa.repository.config.EnableJpaRepositories[format=annotation]，如下例所示：

[source,java]
----
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@Configuration(proxyBeanMethods = false)
@EnableJpaRepositories(basePackageClasses = Order.class, entityManagerFactoryRef = "entityManagerFactory")
public class OrderConfiguration {

}
----

[source,java]
----
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@Configuration(proxyBeanMethods = false)
@EnableJpaRepositories(basePackageClasses = Customer.class, entityManagerFactoryRef = "secondEntityManagerFactory")
public class CustomerConfiguration {

}
----



[[howto.data-access.use-traditional-persistence-xml]]
== 使用传统的 persistence.xml 文件

默认情况下，Spring Boot 不会搜索或使用 `META-INF/persistence.xml`。
如果你更喜欢使用传统的 `persistence.xml`，你需要定义自己的类型为 javadoc:org.springframework.orm.jpa.LocalEntityManagerFactoryBean[]（ID 为 '`entityManagerFactory`'）的 javadoc:org.springframework.context.annotation.Bean[format=annotation]，并在其中设置持久化单元名称。

默认设置请参阅 {code-spring-boot-jpa-src}/autoconfigure/JpaBaseConfiguration.java[`JpaBaseConfiguration`]。



[[howto.data-access.use-spring-data-jpa-and-mongo-repositories]]
== 使用 Spring Data JPA 和 Mongo 仓库

Spring Data JPA 和 Spring Data Mongo 都可以自动为你创建 javadoc:org.springframework.data.repository.Repository[] 实现。
如果它们同时存在于 classpath 上，你可能需要做一些额外的配置来告诉 Spring Boot 要创建哪些仓库。
最明确的方法是使用标准的 Spring Data javadoc:org.springframework.data.jpa.repository.config.EnableJpaRepositories[format=annotation] 和 javadoc:org.springframework.data.mongodb.repository.config.EnableMongoRepositories[format=annotation] annotations，并提供你的 javadoc:org.springframework.data.repository.Repository[] 接口的位置。

还有一些标志（`+spring.data.*.repositories.enabled+` 和 `+spring.data.*.repositories.type+`）可用于在外部配置中打开和关闭自动配置的仓库。
例如，如果你想关闭 Mongo 仓库但仍使用自动配置的 javadoc:org.springframework.data.mongodb.core.MongoTemplate[]，这样做很有用。

其他自动配置的 Spring Data 仓库类型（Elasticsearch、Redis 等）也存在同样的障碍和特性。
要使用它们，请相应地更改 annotations 和标志的名称。



[[howto.data-access.customize-spring-data-web-support]]
== 自定义 Spring Data 的 Web 支持

Spring Data 提供了 Web 支持，简化了在 Web 应用程序中使用 Spring Data 仓库的操作。
Spring Boot 在 `spring.data.web` 命名空间中提供了用于自定义其配置的属性。
请注意，如果你使用 Spring Data REST，则必须改用 `spring.data.rest` 命名空间中的属性。



[[howto.data-access.exposing-spring-data-repositories-as-rest]]
== 将 Spring Data 仓库暴露为 REST 端点

Spring Data REST 可以将 javadoc:org.springframework.data.repository.Repository[] 实现作为 REST 端点暴露给你，
前提是 Spring MVC 已为应用程序启用。

Spring Boot 暴露了一组有用的属性（来自 `spring.data.rest` 命名空间），用于自定义 javadoc:org.springframework.data.rest.core.config.RepositoryRestConfiguration[]。
如果你需要提供额外的自定义，应使用 javadoc:org.springframework.data.rest.webmvc.config.RepositoryRestConfigurer[] bean。

注意：如果你没有为自定义 javadoc:org.springframework.data.rest.webmvc.config.RepositoryRestConfigurer[] 指定任何顺序，它将在 Spring Boot 内部使用的那个之后运行。
如果你需要指定顺序，请确保它大于 0。



[[howto.data-access.configure-a-component-that-is-used-by-jpa]]
== 配置 JPA 使用的组件

如果你想配置 JPA 使用的组件，则需要确保该组件在 JPA 之前初始化。
当组件是自动配置时，Spring Boot 会为你处理这一点。
例如，当 Flyway 自动配置时，Hibernate 被配置为依赖于 Flyway，以便 Flyway 有机会在 Hibernate 尝试使用数据库之前初始化数据库。

如果你自己配置组件，可以使用 javadoc:org.springframework.boot.jpa.autoconfigure.EntityManagerFactoryDependsOnPostProcessor[] 子类作为设置必要依赖的便捷方式。
例如，如果你使用 Hibernate Search 并将 Elasticsearch 作为其索引管理器，则任何 javadoc:jakarta.persistence.EntityManagerFactory[] beans 都必须配置为依赖于 `elasticsearchClient` bean，如下例所示：

[source,java]
----
import jakarta.persistence.EntityManagerFactory;

import org.springframework.boot.jpa.autoconfigure.EntityManagerFactoryDependsOnPostProcessor;
import org.springframework.stereotype.Component;

/**
 * {@link EntityManagerFactoryDependsOnPostProcessor} that ensures that
 * {@link EntityManagerFactory} beans depend on the {@code elasticsearchClient} bean.
 */
@Component
public class ElasticsearchEntityManagerFactoryDependsOnPostProcessor
		extends EntityManagerFactoryDependsOnPostProcessor {

	public ElasticsearchEntityManagerFactoryDependsOnPostProcessor() {
		super("elasticsearchClient");
	}

}
----



[[howto.data-access.configure-jooq-with-multiple-datasources]]
== 使用两个数据源配置 jOOQ

如果你需要使用多个数据源使用 jOOQ，则应为每个数据源创建自己的 javadoc:org.jooq.DSLContext[]。
更多细节，请参阅 {code-spring-boot-jooq-src}/autoconfigure/JooqAutoConfiguration.java[`JooqAutoConfiguration`]。

提示：特别是，javadoc:org.springframework.boot.jooq.autoconfigure.ExceptionTranslatorExecuteListener[] 和 javadoc:org.springframework.boot.jooq.autoconfigure.SpringTransactionProvider[] 可以重用，以提供与自动配置使用单个 javadoc:javax.sql.DataSource[] 类似的功能。
