= 热交换

Spring Boot 支持热交换。
本节回答有关其工作原理的问题。


[[howto.hotswapping.reload-static-content]]
== 重新加载静态内容

有几种热重载选项。
推荐的方法是使用 xref:reference:using/devtools.adoc[`spring-boot-devtools`]，因为它提供了额外的开发时功能，例如支持快速应用程序重启和 LiveReload，以及合理的开发时配置（例如模板缓存）。
Devtools 通过监视 classpath 的变化来工作。
这意味着静态资源更改必须“构建”才能使更改生效。
默认情况下，在 Eclipse 中保存更改时会自动发生这种情况。
在 IntelliJ IDEA 中，“Make Project”命令会触发必要的构建。
由于 xref:reference:using/devtools.adoc#using.devtools.restart.excluding-resources[默认重启排除]，静态资源的更改不会触发应用程序重启。
但是，它们会触发实时重新加载。

或者，在 IDE 中运行（尤其是在启用调试的情况下）是一种很好的开发方式（所有现代 IDE 都允许重新加载静态资源，并且通常也允许热交换 Java 类更改）。

最后，可以配置 xref:build-tool-plugin:index.adoc[Maven 和 Gradle 插件]（请参阅 `addResources` 属性）以支持从命令行运行并直接从源重新加载静态文件。
如果您使用更高级的工具编写代码，可以将其与外部 css/js 编译器进程一起使用。


[[howto.hotswapping.reload-templates]]
== 重新加载模板而不重启容器

Spring Boot 支持的大多数模板技术都包含一个禁用缓存的配置选项（本文档稍后描述）。
如果您使用 `spring-boot-devtools` 模块，这些属性在开发时会 xref:reference:using/devtools.adoc#using.devtools.property-defaults[自动配置]。


[[howto.hotswapping.reload-templates.thymeleaf]]
=== Thymeleaf 模板

如果您使用 Thymeleaf，请将 `spring.thymeleaf.cache` 设置为 `false`。
有关其他 Thymeleaf 自定义选项，请参阅 {code-spring-boot-thymeleaf-src}/autoconfigure/ThymeleafAutoConfiguration.java[`ThymeleafAutoConfiguration`]。


[[howto.hotswapping.reload-templates.freemarker]]
=== FreeMarker 模板

如果您使用 FreeMarker，请将 `spring.freemarker.cache` 设置为 `false`。
有关其他 FreeMarker 自定义选项，请参阅 {code-spring-boot-freemarker-src}/autoconfigure/FreeMarkerAutoConfiguration.java[`FreeMarkerAutoConfiguration`]。

注意：WebFlux 不支持 FreeMarker 的模板缓存。


[[howto.hotswapping.reload-templates.groovy]]
=== Groovy 模板

如果您使用 Groovy 模板，请将 `spring.groovy.template.cache` 设置为 `false`。
有关其他 Groovy 自定义选项，请参阅 {code-spring-boot-groovy-templates-src}/autoconfigure/GroovyTemplateAutoConfiguration.java[`GroovyTemplateAutoConfiguration`]。


[[howto.hotswapping.fast-application-restarts]]
== 快速应用程序重启

`spring-boot-devtools` 模块包含对自动应用程序重启的支持。
虽然不如 https://www.jrebel.com/products/jrebel[JRebel] 等技术快，但通常比“`cold start`”快得多。
在尝试本文档后面讨论的一些更复杂的重载选项之前，您可能应该先尝试一下。

有关更多详细信息，请参阅 xref:reference:using/devtools.adoc[] 部分。


[[howto.hotswapping.reload-java-classes-without-restarting]]
== 重新加载 Java 类而不重启容器

许多现代 IDE（Eclipse、IntelliJ IDEA 等）支持字节码的热交换。
因此，如果您所做的更改不影响类或方法签名，它应该会干净地重新加载，没有副作用。
