= Quartz Scheduler

Spring Boot 为使用 https://www.quartz-scheduler.org/[Quartz 调度器] 提供了若干便利，包括 `spring-boot-starter-quartz` starter。
如果 Quartz 可用，则会自动配置一个 javadoc:org.quartz.Scheduler[]（通过 javadoc:org.springframework.scheduling.quartz.SchedulerFactoryBean[] 抽象）。

以下类型的 bean 会被自动拾取并与 javadoc:org.quartz.Scheduler[] 关联：

* javadoc:org.quartz.JobDetail[]：定义特定的 Job。
  javadoc:org.quartz.JobDetail[] 实例可以使用 javadoc:org.quartz.JobBuilder[] API 构建。
* javadoc:org.quartz.Calendar[]。
* javadoc:org.quartz.Trigger[]：定义特定 job 何时触发。

默认情况下，使用内存中的 javadoc:org.quartz.spi.JobStore[]。
但是，如果应用程序中存在 javadoc:javax.sql.DataSource[] bean，并且 configprop:spring.quartz.job-store-type[] 属性已相应配置，则可以配置基于 JDBC 的存储，如下例所示：

[configprops,yaml]
----
spring:
  quartz:
    job-store-type: "jdbc"
----
使用 JDBC 存储时，可以在启动时初始化模式，如下例所示：

[configprops,yaml]
----
spring:
  quartz:
    jdbc:
      initialize-schema: "always"
----
WARNING: 默认情况下，数据库会使用 Quartz 库提供的标准脚本进行检测和初始化。
这些脚本会删除现有表，每次重启时删除所有触发器。
要使用自定义脚本，请设置 configprop:spring.quartz.jdbc.schema[] 属性。
某些标准脚本（例如用于 SQL Server、Azure SQL 和 Sybase 的脚本）未经修改无法使用。
在这种情况下，请复制脚本并根据脚本注释中的指示进行编辑，然后设置 configprop:spring.quartz.jdbc.schema[] 以使用自定义脚本。

要让 Quartz 使用不同于应用程序主 javadoc:javax.sql.DataSource[] 的 javadoc:javax.sql.DataSource[]，请声明一个 javadoc:javax.sql.DataSource[] bean，并使用 javadoc:org.springframework.boot.quartz.autoconfigure.QuartzDataSource[format=annotation] 注解其 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法。
这样做可以确保 Quartz 特定的 javadoc:javax.sql.DataSource[] 同时被 javadoc:org.springframework.scheduling.quartz.SchedulerFactoryBean[] 和模式初始化使用。
类似地，要让 Quartz 使用不同于应用程序主 javadoc:org.springframework.transaction.TransactionManager[] 的 javadoc:org.springframework.transaction.TransactionManager[]，请声明一个 javadoc:org.springframework.transaction.TransactionManager[] bean，并使用 javadoc:org.springframework.boot.quartz.autoconfigure.QuartzTransactionManager[format=annotation] 注解其 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法。

默认情况下，通过配置创建的作业不会覆盖已从持久化作业存储中读取的已注册作业。
要启用覆盖现有作业定义，请设置 configprop:spring.quartz.overwrite-existing-jobs[] 属性。

可以使用 `spring.quartz` 属性和 javadoc:org.springframework.boot.quartz.autoconfigure.SchedulerFactoryBeanCustomizer[] beans 自定义 Quartz Scheduler 配置，这些属性允许以编程方式进行 javadoc:org.springframework.scheduling.quartz.SchedulerFactoryBean[] 自定义。
可以使用 `spring.quartz.properties.*` 自定义高级 Quartz 配置属性。

NOTE: 特别是，javadoc:java.util.concurrent.Executor[] bean 不与调度器关联，因为 Quartz 提供了一种通过 `spring.quartz.properties` 配置调度器的方式。
如果需要自定义任务执行器，请考虑实现 javadoc:org.springframework.boot.quartz.autoconfigure.SchedulerFactoryBeanCustomizer[]。

作业可以定义 setter 来注入数据映射属性。
常规 beans 也可以类似方式注入，如下例所示：

include-code::MySampleJob[]
