= 缓存

Spring 框架为应用程序透明地添加缓存提供了支持。其核心是，抽象层将缓存应用于方法，从而根据缓存中的可用信息减少执行次数。缓存逻辑是透明应用的，不会对调用者造成任何干扰。更多详情，请参阅 Spring 框架参考文档的 {url-spring-framework-docs}/integration/cache.html[相关章节]。

只要通过 javadoc:org.springframework.cache.annotation.EnableCaching[format=annotation] 注解启用了缓存支持，Spring Boot 就会自动配置缓存基础设施。

提示：避免将 javadoc:org.springframework.cache.annotation.EnableCaching[format=annotation] 添加到主方法的应用程序类中。这样做会使缓存成为强制功能，包括 xref:io/caching.adoc#io.caching.testing[在运行测试套件时]。

要为服务的操作添加缓存，请将相应的注解添加到其方法中，如下例所示：

[source,java]
----
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Component;

@Component
public class MyMathService {

	@Cacheable("piDecimals")
	public int computePiDecimal(int precision) {
		/**/ return 0;
	}

}
----

此示例演示了在可能代价高昂的操作上使用缓存。在调用 `computePiDecimal` 之前，抽象层会在 `piDecimals` 缓存中查找与 `precision` 参数匹配的条目。如果找到条目，缓存中的内容会立即返回给调用者，并且不会调用该方法。否则，该方法会被调用，并在返回值之前更新缓存。

注意：你也可以透明地使用标准 JSR-107 (JCache) 注解（例如 javadoc:javax.cache.annotation.CacheResult[format=annotation]）。但是，我们强烈建议你不要混合使用 Spring Cache 和 JCache 注解。

如果你没有添加任何特定的缓存库，Spring Boot 会自动配置一个 xref:io/caching.adoc#io.caching.provider.simple[简单提供者]，它使用内存中的并发映射。当需要缓存时（例如前面示例中的 `piDecimals`），此提供者会为你创建它。简单提供者并不真正推荐用于生产环境，但它非常适合入门和确保你理解这些特性。当你决定使用哪个缓存提供者后，请务必阅读其文档，以了解如何配置应用程序使用的缓存。几乎所有提供者都要求你显式配置应用程序中使用的每个缓存。有些提供者提供了一种通过 configprop:spring.cache.cache-names[] 属性自定义默认缓存的方法。

提示：也可以透明地 {url-spring-framework-docs}/integration/cache/annotations.html#cache-annotations-put[更新] 或 {url-spring-framework-docs}/integration/cache/annotations.html#cache-annotations-evict[驱逐] 缓存中的数据。



[[io.caching.provider]]
== 支持的缓存提供者

缓存抽象并不提供实际的存储，而是依赖于由 javadoc:org.springframework.cache.Cache[] 和 javadoc:org.springframework.cache.CacheManager[] 接口实现的抽象。

如果你没有定义类型为 javadoc:org.springframework.cache.CacheManager[] 的 bean 或名为 `cacheResolver` 的 javadoc:org.springframework.cache.interceptor.CacheResolver[]（参见 javadoc:org.springframework.cache.annotation.CachingConfigurer[]），Spring Boot 会尝试按以下顺序检测提供者：

. xref:io/caching.adoc#io.caching.provider.generic[通用]
. xref:io/caching.adoc#io.caching.provider.jcache[JCache (JSR-107)]（EhCache 3、Hazelcast、Infinispan 等）
. xref:io/caching.adoc#io.caching.provider.hazelcast[Hazelcast]
. xref:io/caching.adoc#io.caching.provider.infinispan[Infinispan]
. xref:io/caching.adoc#io.caching.provider.couchbase[Couchbase]
. xref:io/caching.adoc#io.caching.provider.redis[Redis]
. xref:io/caching.adoc#io.caching.provider.caffeine[Caffeine]
. xref:io/caching.adoc#io.caching.provider.cache2k[Cache2k]
. xref:io/caching.adoc#io.caching.provider.simple[Simple]

提示：如果 javadoc:org.springframework.cache.CacheManager[] 由 Spring Boot 自动配置，可以通过设置 configprop:spring.cache.type[] 属性来 _强制_ 使用特定的缓存提供者。

提示：使用 `spring-boot-starter-cache` starter 可以快速添加基本的缓存依赖。starter 会引入 `spring-context-support`。如果你手动添加依赖，必须包含 `spring-context-support` 才能使用 JCache 或 Caffeine 支持。

如果 javadoc:org.springframework.cache.CacheManager[] 由 Spring Boot 自动配置，你可以通过暴露一个实现 javadoc:org.springframework.boot.cache.autoconfigure.CacheManagerCustomizer[] 接口的 bean 来在其完全初始化之前进一步调整其配置。以下示例设置了一个标志，表示 `null` 值不应传递到底层映射：

[source,java]
----
import org.springframework.boot.cache.autoconfigure.CacheManagerCustomizer;
import org.springframework.cache.concurrent.ConcurrentMapCacheManager;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyCacheManagerConfiguration {

	@Bean
	public CacheManagerCustomizer<ConcurrentMapCacheManager> cacheManagerCustomizer() {
		return (cacheManager) -> cacheManager.setAllowNullValues(false);
	}

}
----

注意：在前面的示例中，期望有一个自动配置的 javadoc:org.springframework.cache.concurrent.ConcurrentMapCacheManager[]。如果不是这种情况（要么你提供了自己的配置，要么自动配置了不同的缓存提供者），则根本不会调用自定义器。你可以拥有任意数量的自定义器，也可以使用 javadoc:org.springframework.core.annotation.Order[format=annotation] 或 javadoc:org.springframework.core.Ordered[] 对它们进行排序。



[[io.caching.provider.generic]]
=== 通用

如果上下文定义了 _至少_ 一个 javadoc:org.springframework.cache.Cache[] bean，则使用通用缓存。会创建一个包装所有该类型 beans 的 javadoc:org.springframework.cache.CacheManager[]。



[[io.caching.provider.jcache]]
=== JCache (JSR-107)

https://jcp.org/en/jsr/detail?id=107[JCache] 通过在 classpath 上存在 javadoc:javax.cache.spi.CachingProvider[] 来引导（即，classpath 上存在符合 JSR-107 的缓存库），并且 javadoc:org.springframework.cache.jcache.JCacheCacheManager[] 由 `spring-boot-starter-cache` starter 提供。有多种兼容库可用，Spring Boot 为 Ehcache 3、Hazelcast 和 Infinispan 提供了依赖管理。也可以添加任何其他兼容库。

可能会出现多个提供者的情况，此时必须显式指定提供者。即使 JSR-107 标准没有强制规定定义配置文件位置的标准化方式，Spring Boot 也会尽力通过实现细节来设置缓存，如下例所示：

[configprops,yaml]
----
    # Only necessary if more than one provider is present
	spring:
	  cache:
	    jcache:
	      provider: "com.example.MyCachingProvider"
	      config: "classpath:example.xml"
----
NOTE: 当缓存库同时提供原生实现和 JSR-107 支持时，Spring Boot 优先使用 JSR-107 支持，这样如果你切换到不同的 JSR-107 实现，也能使用相同的功能。

TIP: Spring Boot 有 xref:io/hazelcast.adoc[对 Hazelcast 的通用支持]。
如果单个 javadoc:com.hazelcast.core.HazelcastInstance[] 可用，它也会自动被用于 javadoc:javax.cache.CacheManager[]，除非指定了 configprop:spring.cache.jcache.config[] 属性。

有两种方式自定义底层 javadoc:javax.cache.CacheManager[]：

* 可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存。
如果定义了自定义的 javadoc:javax.cache.configuration.Configuration[] bean，则用它来自定义缓存。
* javadoc:org.springframework.boot.cache.autoconfigure.CacheManagerCustomizer[] beans 会通过 javadoc:javax.cache.CacheManager[] 的引用来调用，以实现完全自定义。

TIP: 如果定义了标准的 javadoc:javax.cache.CacheManager[] bean，它会自动被包装成抽象层期望的 javadoc:org.springframework.cache.CacheManager[] 实现。
不会对其应用进一步的自定义。



[[io.caching.provider.hazelcast]]
=== Hazelcast

Spring Boot 有 xref:io/hazelcast.adoc[对 Hazelcast 的通用支持]。
如果 javadoc:com.hazelcast.core.HazelcastInstance[] 已自动配置且 `com.hazelcast:hazelcast-spring` 在 classpath 上，它会自动被包装成 javadoc:org.springframework.cache.CacheManager[]。

NOTE: Hazelcast 可以用作 JCache 兼容的缓存，也可以用作 Spring javadoc:org.springframework.cache.CacheManager[] 兼容的缓存。
当设置 configprop:spring.cache.type[] 为 `hazelcast` 时，Spring Boot 将使用基于 javadoc:org.springframework.cache.CacheManager[] 的实现。
如果你想将 Hazelcast 用作 JCache 兼容的缓存，请将 configprop:spring.cache.type[] 设置为 `jcache`。
如果你有多个 JCache 兼容的缓存提供者并希望强制使用 Hazelcast，你必须 xref:io/caching.adoc#io.caching.provider.jcache[显式设置 JCache 提供者]。



[[io.caching.provider.infinispan]]
=== Infinispan

https://infinispan.org/[Infinispan] 没有默认的配置文件位置，因此必须显式指定。
否则，将使用默认的引导配置。

[configprops,yaml]
----
spring:
  cache:
    infinispan:
      config: "infinispan.xml"
----
可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存。
如果定义了自定义的 javadoc:org.infinispan.configuration.cache.ConfigurationBuilder[] bean，则用它来自定义缓存。

更多详情，请参见 https://infinispan.org/docs/stable/titles/spring/spring.html[文档]。

[[io.caching.provider.couchbase]]
=== Couchbase

如果 Spring Data Couchbase 可用且 Couchbase 已 xref:data/nosql.adoc#data.nosql.couchbase[配置]，则会自动配置一个 javadoc:org.springframework.data.couchbase.cache.CouchbaseCacheManager[]。
可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建额外的缓存，并可以使用 `spring.cache.couchbase.*` 属性配置缓存默认值。
例如，以下配置创建了 `cache1` 和 `cache2` 缓存，其条目 _过期时间_ 为 10 分钟：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    couchbase:
      expiration: "10m"
----

如果您需要对配置进行更精细的控制，可以考虑注册一个 javadoc:org.springframework.boot.cache.autoconfigure.CouchbaseCacheManagerBuilderCustomizer[] bean。
以下示例展示了一个自定义器，用于配置 `cache1` 和 `cache2` 的特定条目过期时间：

[source,java]
----
import java.time.Duration;

import org.springframework.boot.cache.autoconfigure.CouchbaseCacheManagerBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.couchbase.cache.CouchbaseCacheConfiguration;

@Configuration(proxyBeanMethods = false)
public class MyCouchbaseCacheManagerConfiguration {

	@Bean
	public CouchbaseCacheManagerBuilderCustomizer myCouchbaseCacheManagerBuilderCustomizer() {
		// @formatter:off
		return (builder) -> builder
				.withCacheConfiguration("cache1", CouchbaseCacheConfiguration
						.defaultCacheConfig().entryExpiry(Duration.ofSeconds(10)))
				.withCacheConfiguration("cache2", CouchbaseCacheConfiguration
						.defaultCacheConfig().entryExpiry(Duration.ofMinutes(1)));
		// @formatter:on

	}

}
----



[[io.caching.provider.redis]]
=== Redis

如果 https://redis.io/[Redis] 可用且已配置，则会自动配置一个 javadoc:org.springframework.data.redis.cache.RedisCacheManager[]。
可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建额外的缓存，并使用 `spring.cache.redis.*` 属性配置缓存默认值。
例如，以下配置创建了 `cache1` 和 `cache2` 缓存，其 _生存时间_ 为 10 分钟：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    redis:
      time-to-live: "10m"
----
NOTE: 默认情况下，会添加一个键前缀，这样，如果两个独立的缓存使用相同的键，Redis 就不会有重叠的键，也不会返回无效的值。
如果你创建自己的 javadoc:org.springframework.data.redis.cache.RedisCacheManager[]，我们强烈建议保持此设置启用。

TIP: 你可以通过添加自己的 javadoc:org.springframework.data.redis.cache.RedisCacheConfiguration[] javadoc:org.springframework.context.annotation.Bean[format=annotation] 来完全控制默认配置。
如果你需要自定义默认序列化策略，这会很有用。

如果你需要对配置进行更多控制，可以考虑注册一个 javadoc:org.springframework.boot.cache.autoconfigure.RedisCacheManagerBuilderCustomizer[] bean。
以下示例展示了一个自定义器，它为 `cache1` 和 `cache2` 配置了特定的生存时间：

[source,java]
----
import java.time.Duration;

import org.springframework.boot.cache.autoconfigure.RedisCacheManagerBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.redis.cache.RedisCacheConfiguration;

@Configuration(proxyBeanMethods = false)
public class MyRedisCacheManagerConfiguration {

	@Bean
	public RedisCacheManagerBuilderCustomizer myRedisCacheManagerBuilderCustomizer() {
		// @formatter:off
		return (builder) -> builder
				.withCacheConfiguration("cache1", RedisCacheConfiguration
						.defaultCacheConfig().entryTtl(Duration.ofSeconds(10)))
				.withCacheConfiguration("cache2", RedisCacheConfiguration
						.defaultCacheConfig().entryTtl(Duration.ofMinutes(1)));
		// @formatter:on

	}

}
----


[[io.caching.provider.caffeine]]
=== Caffeine

https://github.com/ben-manes/caffeine[Caffeine] 是 Guava 缓存的 Java 8 重写，取代了对 Guava 的支持。
如果 Caffeine 存在，则会自动配置一个 javadoc:org.springframework.cache.caffeine.CaffeineCacheManager[]（由 `spring-boot-starter-cache` starter 提供）。
可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存，并可以通过以下方式之一进行自定义（按指示的顺序）：

. 由 `spring.cache.caffeine.spec` 定义的缓存规范
. 定义了 javadoc:com.github.benmanes.caffeine.cache.CaffeineSpec[] bean
. 定义了 javadoc:com.github.benmanes.caffeine.cache.Caffeine[] bean

例如，以下配置创建了 `cache1` 和 `cache2` 缓存，最大大小为 500，生存时间为 10 分钟：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=600s"
----
如果定义了 javadoc:com.github.benmanes.caffeine.cache.CacheLoader[] bean，它会自动关联到 javadoc:org.springframework.cache.caffeine.CaffeineCacheManager[]。
由于 javadoc:com.github.benmanes.caffeine.cache.CacheLoader[] 将与缓存管理器管理的 _所有_ 缓存关联，因此必须将其定义为 `CacheLoader<Object, Object>`。
自动配置会忽略任何其他泛型类型。

[[io.caching.provider.cache2k]]
=== Cache2k

https://cache2k.org/[Cache2k] 是一个内存缓存。
如果存在 Cache2k Spring 集成，则会自动配置 `SpringCache2kCacheManager`。

可以通过设置 configprop:spring.cache.cache-names[] 属性在启动时创建缓存。
可以使用 javadoc:org.springframework.boot.cache.autoconfigure.Cache2kBuilderCustomizer[] bean 自定义缓存默认值。
以下示例展示了一个自定义器，它将缓存容量配置为 200 个条目，过期时间为 5 分钟：

[source,java]
----
import java.util.concurrent.TimeUnit;

import org.springframework.boot.cache.autoconfigure.Cache2kBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class MyCache2kDefaultsConfiguration {

	@Bean
	public Cache2kBuilderCustomizer myCache2kDefaultsCustomizer() {
		// @formatter:off
		return (builder) -> builder.entryCapacity(200)
				.expireAfterWrite(5, TimeUnit.MINUTES);
		// @formatter:on
	}

}
----

[[io.caching.provider.simple]]
=== Simple

如果找不到其他提供程序，则会配置一个使用 javadoc:java.util.concurrent.ConcurrentHashMap[] 作为缓存存储的简单实现。
如果应用程序中没有缓存库，这是默认配置。
默认情况下，缓存会根据需要创建，但你可以通过设置 `cache-names` 属性来限制可用缓存的列表。
例如，如果你只需要 `cache1` 和 `cache2` 缓存，请按如下方式设置 `cache-names` 属性：

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
----
如果这样做，并且你的应用程序使用了未列出的缓存，那么在需要缓存时会在运行时失败，但不会在启动时失败。
这与使用未声明缓存时“真正”缓存提供者的行为类似。

[[io.caching.provider.none]]
=== 无

如果你需要在特定环境中使用无操作缓存而不是自动配置的缓存管理器，请将缓存类型设置为 `none`，如下例所示：

[configprops,yaml]
----
spring:
  cache:
    type: "none"
----
[[io.caching.testing]]
== 测试

在运行测试套件时，通常使用无操作实现是有用的。本节列出了一些对测试有用的策略。

当定义了自定义的 javadoc:org.springframework.cache.CacheManager[] 时，最好的选择是确保缓存配置定义在隔离的 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类中。这样做可以确保切片测试不需要缓存。对于启用完整上下文的测试（例如 javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation]），需要显式配置覆盖常规配置。

如果缓存是自动配置的，则有更多选项可用。测试可以使用 javadoc:org.springframework.boot.test.autoconfigure.core.AutoConfigureCache[format=annotation] 注解，将自动配置的 javadoc:org.springframework.cache.CacheManager[] 替换为无操作实现。

[source,java]
----
import org.springframework.boot.cache.test.autoconfigure.AutoConfigureCache;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
@AutoConfigureCache
public class MyIntegrationTests {

	// Tests use a no-op cache manager

}
----

另一种选择是为自动配置的 javadoc:org.springframework.cache.CacheManager[] 强制使用无操作实现：

[configprops,yaml]
----
spring:
  cache:
    type: "none"
----
