[[using.auto-configuration]]
= 自动配置

Spring Boot 自动配置会根据你添加的 jar 依赖，尝试自动配置你的 Spring 应用程序。
例如，如果 `HSQLDB` 在你的 classpath 上，并且你没有手动配置任何数据库连接 bean，那么 Spring Boot 会自动配置一个内存数据库。

你需要通过将 javadoc:org.springframework.boot.autoconfigure.EnableAutoConfiguration[format=annotation] 或 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 注解添加到你的一个 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类上，来选择启用自动配置。

TIP: 你只应添加一个 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 或 javadoc:org.springframework.boot.autoconfigure.EnableAutoConfiguration[format=annotation] 注解。
我们通常建议你只将其中一个添加到你的主 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类上。



[[using.auto-configuration.replacing]]
== 逐步替换自动配置

自动配置是非侵入式的。
在任何时候，你都可以开始定义自己的配置来替换自动配置的特定部分。
例如，如果你添加了自己的 javadoc:javax.sql.DataSource[] bean，默认的嵌入式数据库支持就会退出。

如果你需要找出当前正在应用哪些自动配置以及原因，可以使用 `--debug` 开关启动应用程序。
这样做会为选定的核心日志记录器启用调试日志，并将条件报告输出到控制台。



[[using.auto-configuration.disabling-specific]]
== 禁用特定的自动配置类

如果你发现某些你不想要的自动配置类正在被应用，可以使用 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 的 exclude 属性来禁用它们，如下例所示：

include-code::MyApplication[]

如果该类不在 classpath 上，你可以使用注解的 `excludeName` 属性并指定完全限定名。
如果你更喜欢使用 javadoc:org.springframework.boot.autoconfigure.EnableAutoConfiguration[format=annotation] 而不是 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]，`exclude` 和 `excludeName` 也可用。
最后，你还可以通过使用 configprop:spring.autoconfigure.exclude[] 属性来控制要排除的自动配置类列表。

TIP: 你可以在注解级别和使用属性两种方式定义排除项。

NOTE: 尽管自动配置类是 `public` 的，但该类被视为公共 API 的唯一方面是其类名，可用于禁用自动配置。
这些类的实际内容，例如嵌套的配置类或 bean 方法，仅供内部使用，我们不建议直接使用它们。



[[using.auto-configuration.packages]]
== 自动配置包

自动配置包是各种自动配置特性在扫描实体和 Spring Data 仓库等内容时默认查找的包。
javadoc:org.springframework.boot.autoconfigure.EnableAutoConfiguration[format=annotation] 注解（直接或通过其在 javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] 上的存在）决定了默认的自动配置包。
可以使用 javadoc:org.springframework.boot.autoconfigure.AutoConfigurationPackage[format=annotation] 注解配置额外的包。
